package view;

import dao.ItensComprasDAO;
import dao.ProdutosDAO;
import model.Produtos;
import utilitarios.LimpaTela;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JComboBox;
import utilitarios.Conexao;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.PreparedStatement;
import java.text.ParseException;
import model.Categoria;
import model.CliFor;
import model.ItensCompras;

/**
 *
 * @author CARLOS
 */
public class Form_Compra extends javax.swing.JDialog {

    private Conexao conexao;
    public DefaultTableModel meus_produtos; // Declare a tabela de produtos
    private List<ItensCompras> itensCompras = new ArrayList<>();
    private List<ItensCompras> listaItensCompra = new ArrayList<>(); // Inicialização da lista

    private static final Locale BR = Locale.of("pt", "BR");
    private static final NumberFormat nf = NumberFormat.getCurrencyInstance(BR);

    CarregarCbx rf = new CarregarCbx(); //Carrega combobox de Fornecedores

    public Form_Compra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setTitle("Cadastro de Compras");
        setLocationRelativeTo(parent);

        // Primeiro inicializa tudo
        meus_produtos = (DefaultTableModel) Carrinho.getModel();
        Date agora = new Date();
        txtData.setText(new SimpleDateFormat("dd/MM/yyyy").format(agora));

        // Depois carrega os fornecedores (com item padrão)
        rf.CarregarCbx("tbclifor", "nomeCliFor", cbxFornecedores);

        // Depois lista produtos
        try {
            listar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar produtos.");
        }
        txtCodigo.requestFocus();
    }

    // Só pra testar direto (opcional)
    public Form_Compra() throws ClassNotFoundException, SQLException {
        this(null, true);
    }

    public void adicionarItem(int produtoId, double qtd, double preco, double qtdAtual, double precoAtual) {
        // Log para verificar o produtoId que está sendo passado
        //System.out.println("Adicionando item com produtoId: " + produtoId);

        // Criação do novo item
        ItensCompras novoItem = new ItensCompras(produtoId, qtd, preco, qtdAtual, precoAtual);

        // Adiciona o item à lista
        itensCompras.add(novoItem);

        // Log para confirmar que o item foi adicionado
        //System.out.println("Item adicionado: " + novoItem);
    }

    public void setMeusProdutos(DefaultTableModel meus_produtos) {
        this.meus_produtos = meus_produtos; // Armazena o modelo de tabela passado
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PainelFornecedor = new javax.swing.JPanel();
        txtData = new javax.swing.JFormattedTextField();
        jLabelData = new javax.swing.JLabel();
        jLabelNomeF = new javax.swing.JLabel();
        jLabelPesqProd = new javax.swing.JLabel();
        txtPesquisaProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        cbxFornecedores = new javax.swing.JComboBox<>();
        jTextFieldid = new javax.swing.JTextField();
        painel_produto = new javax.swing.JPanel();
        jLabelCodProd = new javax.swing.JLabel();
        jLabelProdProd = new javax.swing.JLabel();
        jLabelPrecoProd = new javax.swing.JLabel();
        jLabelEstoqueProd = new javax.swing.JLabel();
        jLabelQtdProd = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtProduto = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        txtEstoque = new javax.swing.JTextField();
        txtQtd = new javax.swing.JTextField();
        jLabelDescProd = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JFormattedTextField();
        btnAdicionar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabelPrecoCompraProd = new javax.swing.JLabel();
        txtPrecoCompra = new javax.swing.JTextField();
        PainelCarrinho = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Carrinho = new javax.swing.JTable();
        painel_compra = new javax.swing.JPanel();
        jLabel1TotalCompra = new javax.swing.JLabel();
        txtTotalCompra = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jButtonFinalizarCompra = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaObs = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Compras");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulário Compras");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Fornecedor"));

        jLabelData.setText("Data :");

        jLabelNomeF.setText("Nome:");

        jLabelPesqProd.setText("Pesquise um produto aqui :");

        txtPesquisaProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaProdutoKeyReleased(evt);
            }
        });

        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "descrição", "preço", "qtd. estoque", "fornecedor"
            }
        ));
        tabelaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProduto);

        cbxFornecedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbxFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFornecedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelFornecedorLayout = new javax.swing.GroupLayout(PainelFornecedor);
        PainelFornecedor.setLayout(PainelFornecedorLayout);
        PainelFornecedorLayout.setHorizontalGroup(
            PainelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelFornecedorLayout.createSequentialGroup()
                        .addComponent(jLabelData)
                        .addGap(18, 18, 18)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PainelFornecedorLayout.createSequentialGroup()
                        .addGroup(PainelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelFornecedorLayout.createSequentialGroup()
                                .addComponent(jLabelPesqProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPesquisaProduto))
                            .addGroup(PainelFornecedorLayout.createSequentialGroup()
                                .addComponent(jLabelNomeF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxFornecedores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );
        PainelFornecedorLayout.setVerticalGroup(
            PainelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeF)
                    .addComponent(cbxFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPesqProd)
                    .addComponent(txtPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
        );

        painel_produto.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));

        jLabelCodProd.setText("Código:");

        jLabelProdProd.setText("Produto:");

        jLabelPrecoProd.setText("Preço:");

        jLabelEstoqueProd.setText("Estoque:");

        jLabelQtdProd.setText("Qtd. :");

        txtCodigo.setEnabled(false);
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        txtProduto.setEnabled(false);

        txtPreco.setEnabled(false);

        txtEstoque.setEnabled(false);

        txtQtd.setText("1");

        jLabelDescProd.setText("Desconto %");

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdicionar.setText("ADD ITEM");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jLabelPrecoCompraProd.setText("Preço de Compra:");

        javax.swing.GroupLayout painel_produtoLayout = new javax.swing.GroupLayout(painel_produto);
        painel_produto.setLayout(painel_produtoLayout);
        painel_produtoLayout.setHorizontalGroup(
            painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_produtoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_produtoLayout.createSequentialGroup()
                        .addComponent(jLabelCodProd)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDescProd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(painel_produtoLayout.createSequentialGroup()
                        .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel_produtoLayout.createSequentialGroup()
                                .addComponent(jLabelProdProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel_produtoLayout.createSequentialGroup()
                                .addComponent(jLabelEstoqueProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesquisar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_produtoLayout.createSequentialGroup()
                        .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painel_produtoLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(btnAdicionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimpar))
                            .addGroup(painel_produtoLayout.createSequentialGroup()
                                .addComponent(jLabelPrecoProd)
                                .addGap(24, 24, 24)
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(jLabelQtdProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPrecoCompraProd)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        painel_produtoLayout.setVerticalGroup(
            painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_produtoLayout.createSequentialGroup()
                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodProd)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDescProd)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelProdProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecoProd)
                    .addComponent(jLabelQtdProd)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrecoCompraProd)
                    .addComponent(txtPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstoqueProd)
                    .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        painel_produtoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdicionar, btnLimpar});

        PainelCarrinho.setBorder(javax.swing.BorderFactory.createTitledBorder("Carrinho de Compras"));

        Carrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Qtd.", "Preço", "Subtotal"
            }
        ));
        jScrollPane3.setViewportView(Carrinho);

        javax.swing.GroupLayout PainelCarrinhoLayout = new javax.swing.GroupLayout(PainelCarrinho);
        PainelCarrinho.setLayout(PainelCarrinhoLayout);
        PainelCarrinhoLayout.setHorizontalGroup(
            PainelCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );
        PainelCarrinhoLayout.setVerticalGroup(
            PainelCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        painel_compra.setBorder(javax.swing.BorderFactory.createTitledBorder("Total da Compra"));

        jLabel1TotalCompra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1TotalCompra.setText("Total da Compra : ");

        txtTotalCompra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTotalCompra.setForeground(new java.awt.Color(240, 0, 0));
        txtTotalCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalCompra.setEnabled(false);
        txtTotalCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalCompraActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setText("CANCELAR COMPRA");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jButtonFinalizarCompra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonFinalizarCompra.setText("FINALIZAR COMPRA");
        jButtonFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarCompraActionPerformed(evt);
            }
        });

        jLabel2.setText("Obs.:");

        jTextAreaObs.setColumns(20);
        jTextAreaObs.setRows(5);
        jScrollPane2.setViewportView(jTextAreaObs);

        javax.swing.GroupLayout painel_compraLayout = new javax.swing.GroupLayout(painel_compra);
        painel_compra.setLayout(painel_compraLayout);
        painel_compraLayout.setHorizontalGroup(
            painel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_compraLayout.createSequentialGroup()
                .addGroup(painel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_compraLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1TotalCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalCompra))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_compraLayout.createSequentialGroup()
                        .addGap(0, 138, Short.MAX_VALUE)
                        .addComponent(jButtonFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(painel_compraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        painel_compraLayout.setVerticalGroup(
            painel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_compraLayout.createSequentialGroup()
                .addGroup(painel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(painel_compraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(painel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1TotalCompra)
                    .addComponent(txtTotalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_compraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFinalizarCompra)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel_produto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelCarrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel_compra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PainelFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PainelCarrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painel_compra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel_produto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void listar() throws SQLException, ClassNotFoundException {
        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.listarTodos();
        DefaultTableModel dados = (DefaultTableModel) tabelaProduto.getModel();
        dados.setNumRows(0);

        // Configura o formato de moeda brasileira
        @SuppressWarnings("deprecation")
        NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));

        for (Produtos p : lista) {

            // Formata o preço
            String precoFormatado = nf.format(p.getPrecoMedioCusto());//getPreco());

            // Exibe a quantidade com 3 casas decimais
            String qtdEstoqueFormatada = String.format("%.3f", p.getQtd_estoque());

            dados.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                precoFormatado, // Exibe o preço médio formatado
                qtdEstoqueFormatada, // Exibe a quantidade formatada
                p.getCliFor().getNomeCliFor()
            });
        }
    }
    CliFor obj = new CliFor();
    double preco, subtotal, total;
    int qtd;
    //DefaultTableModel meus_produtos;

    private void tabelaProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutoMouseClicked
        txtCodigo.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 0).toString());
        txtProduto.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 1).toString());
        txtPreco.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 2).toString());

        // Obtém a quantidade do estoque
        String estoqueStr = tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 3).toString();

        // Remove vírgulas antes da conversão, se necessário
        estoqueStr = estoqueStr.replace(".", ""); // Remove o ponto para milhar (se houver)
        estoqueStr = estoqueStr.replace(",", "."); // Substitui a vírgula por ponto para o formato decimal

        // Converte a string em double
        double estoque = Double.parseDouble(estoqueStr);

        // Formata o valor como double com 3 casas decimais
        String estoqueFormatado = String.format("%.3f", estoque);
        txtEstoque.setText(estoqueFormatado);

        txtCodigo.setEnabled(false);
    }//GEN-LAST:event_tabelaProdutoMouseClicked

    private void txtTotalCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalCompraActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            listar();
            Date agora = new Date();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            String dataFormatada = formato.format(agora);
            txtData.setText(String.valueOf(dataFormatada));
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Form_Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int id = Integer.valueOf(txtCodigo.getText());
            Produtos obj = new Produtos();
            ProdutosDAO dao;
            try {
                dao = new ProdutosDAO();
                obj = dao.buscarPorId(id); //ProdutosCodigo(id);
                if (obj.getId() != 0) {
                    txtCodigo.setText(String.valueOf(obj.getId()));
                    txtProduto.setText(obj.getDescricao());
                    txtPreco.setText(String.valueOf(obj.getPrecoMedioCusto())); //Alterado para pegar Preço Médio

                    // Obtém a quantidade do estoque e formata como double com 3 casas decimais
                    String estoqueFormatado = String.format("%.3f", obj.getQtd_estoque());
                    txtEstoque.setText(estoqueFormatado);

                    txtCodigo.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Código inválido!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Form_Compra.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        LimpaTela util = new LimpaTela();
        util.LimpaTela(painel_produto);
        txtCodigo.setEnabled(true);
        txtCodigo.requestFocus();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        int id = Integer.valueOf(txtCodigo.getText());
        Produtos obj = new Produtos();
        ProdutosDAO dao;
        try {
            dao = new ProdutosDAO();
            obj = dao.buscarPorId(id); //BuscarProdutosCodigo(id);
            if (obj.getId() != 0) {
                txtCodigo.setText(String.valueOf(obj.getId()));
                txtProduto.setText(obj.getDescricao());
                txtPreco.setText(String.valueOf(obj.getPrecoMedioCusto())); //Alterado para pegar preço Médio

                // Formata a quantidade do estoque como double com 3 casas decimais
                String estoqueFormatado = String.format("%.3f", obj.getQtd_estoque());
                txtEstoque.setText(estoqueFormatado);

                txtCodigo.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Código inválido!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Form_Compra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtPesquisaProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaProdutoKeyReleased
        String nome = "%" + txtPesquisaProduto.getText() + "%";
        ProdutosDAO dao;
        try {
            dao = new ProdutosDAO();
            List<Produtos> lista = dao.filtrarPorNome(nome); //filtrar(nome);
            DefaultTableModel dados = (DefaultTableModel) tabelaProduto.getModel();
            dados.setNumRows(0);

            // Define o formato para moeda no padrão brasileiro
            NumberFormat nfPreco = NumberFormat.getCurrencyInstance();

            for (Produtos p : lista) {
                // Formata o preço
                String precoFormatado = nfPreco.format(p.getPrecoMedioCusto());//Alterado para pegar preço Medio

                // Formata a quantidade como double com 3 casas decimais
                String estoqueFormatado = String.format("%.3f", p.getQtd_estoque());

                dados.addRow(new Object[]{
                    p.getId(),
                    p.getDescricao(),
                    precoFormatado, // Preço formatado
                    estoqueFormatado, // Quantidade formatada
                    p.getCliFor().getNomeCliFor()
                });
                txtCodigo.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Form_Produtos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtPesquisaProdutoKeyReleased

    @SuppressWarnings("unchecked")
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        try {
            int produtoId = Integer.parseInt(txtCodigo.getText());
            double qtd = Double.parseDouble(txtQtd.getText().replace(",", "."));
            double precoCompra = Double.parseDouble(txtPrecoCompra.getText().replace("R$", "").replace(".", "").replace(",", ".").trim());

            if (qtd <= 0) {
                JOptionPane.showMessageDialog(this, "Quantidade deve ser maior que zero!");
                return;
            }
            if (precoCompra <= 0) {
                JOptionPane.showMessageDialog(this, "Preço de compra deve ser maior que zero!");
                return;
            }

            ProdutosDAO dao = new ProdutosDAO();
            Produtos p = dao.buscarPorId(produtoId);

            if (p == null) {
                JOptionPane.showMessageDialog(this, "Produto não encontrado!");
                return;
            }

            double subtotal = qtd * precoCompra;
            total += subtotal;

            // adiciona no carrinho
            meus_produtos.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                String.format("%.3f", qtd),
                NumberFormat.getCurrencyInstance(Locale.of("pt", "BR")).format(precoCompra),
                NumberFormat.getCurrencyInstance(Locale.of("pt", "BR")).format(subtotal)
            });

            // guarda na lista de itens
            ItensCompras item = new ItensCompras();
            item.setProdutoId(p.getId());
            item.setDescricao(p.getDescricao());
            item.setQtd(qtd);
            item.setPrecoCompra(precoCompra);
            item.setSubtotal(subtotal);
            itensCompras.add(item);

            txtTotalCompra.setText(NumberFormat.getCurrencyInstance(Locale.of("pt", "BR")).format(total));

            // limpa campos do produto
            txtCodigo.setText("");
            txtProduto.setText("");
            txtPrecoCompra.setText("");
            txtQtd.setText("");
            txtEstoque.setText("");
            txtCodigo.requestFocus();

            JOptionPane.showMessageDialog(this, "Item adicionado ao carrinho!");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Verifique quantidade e preço!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void jButtonFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarCompraActionPerformed
        if (itensCompras.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Adicione pelo menos um item!");
            return;
        }

        String idFornStr = jTextFieldid.getText().trim();
        if (idFornStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecione um fornecedor!");
            return;
        }
        // Garante o formato "0338"
        String codigoFornecedor = String.format("%04d", Integer.parseInt(idFornStr));
        
        //int idFornecedor = Integer.parseInt(idFornStr);
        Connection con = null;
        try {
            con = Conexao.faz_conexao();
            con.setAutoCommit(false); // ? INICIA TRANSAÇÃO

            // 1. SALVA COMPRA
            String sqlCompra = """
            INSERT INTO tb_compras (fornecedor_id, data_compra, total_compra, observacoes) 
            VALUES (?, CURRENT_TIMESTAMP, ?, ?)
            """;
            int idCompra;
            try (PreparedStatement ps = con.prepareStatement(sqlCompra, PreparedStatement.RETURN_GENERATED_KEYS)) {
                //ps.setInt(1, idFornecedor);
                ps.setString(1, codigoFornecedor);
                ps.setDouble(2, total);
                ps.setString(3, jTextAreaObs.getText().isEmpty() ? "Sem obs" : jTextAreaObs.getText());
                ps.executeUpdate();

                try (ResultSet rs = ps.getGeneratedKeys()) {
                    if (!rs.next()) {
                        throw new SQLException("Falha ao obter ID da compra");
                    }
                    idCompra = rs.getInt(1);
                }
            }

            // 2. SALVA ITENS + ESTOQUE
            ItensComprasDAO itensDao = new ItensComprasDAO();
            ProdutosDAO prodDao = new ProdutosDAO();

            for (ItensCompras item : itensCompras) {
                itensDao.salvar(con, item, idCompra); // ? agora passa a conexão!
                double custoTotal = item.getQtd() * item.getPrecoCompra();
                prodDao.entradaEstoque(con, item.getProdutoId(), item.getQtd(), custoTotal);
            }

            // AQUI É O SEGREDO: COMMIT SÓ DEPOIS DE TUDO!!!
            con.commit();
            //System.out.println("TRANSAÇÃO COMMITADA COM SUCESSO! COMPRA Nº " + idCompra);

            JOptionPane.showMessageDialog(this,
                    "COMPRA FINALIZADA COM SUCESSO!\nNº da Compra: " + idCompra + "\nTotal: R$ " + String.format("%.2f", total),
                    "PARABÉNS!", JOptionPane.INFORMATION_MESSAGE);

            // LIMPA TUDO
            itensCompras.clear();
            total = 0;
            meus_produtos.setRowCount(0);
            txtTotalCompra.setText("R$ 0,00");
            jTextAreaObs.setText("");
            new LimpaTela().LimpaTela(painel_produto);
            txtCodigo.requestFocus();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "ERRO: " + e.getMessage(), "Falha", JOptionPane.ERROR_MESSAGE);
            if (con != null) {
                try {
                    con.rollback();
                    //System.out.println("ROLLBACK EXECUTADO");
                } catch (Exception ex) {
                }
            }
        } finally {
            if (con != null) {
                try {
                    con.setAutoCommit(true);
                    con.close();
                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_jButtonFinalizarCompraActionPerformed

    private List<ItensCompras> obterItensCompra() {
        List<ItensCompras> itens = new ArrayList<>();

        try {
            //System.out.println("=== Início da Extração de Itens do Carrinho ===");
            for (int i = 0; i < Carrinho.getRowCount(); i++) {
                try {
                    // Obtendo dados da tabela
                    Object codigoObj = Carrinho.getValueAt(i, 0);
                    Object qtdObj = Carrinho.getValueAt(i, 2);
                    Object precoObj = Carrinho.getValueAt(i, 3);

                    // Verificação de null
                    if (codigoObj == null || qtdObj == null || precoObj == null) {
                        //System.out.println("Linha " + i + " contém valores nulos. Ignorada.");
                        continue;
                    }

                    // Convertendo para String para evitar erros
                    String codigoStr = codigoObj.toString().trim();
                    String qtdStr = qtdObj.toString().trim();
                    String precoStr = precoObj.toString().trim();

                    // Logs dos valores capturados
                    //System.out.println("Linha " + i + " - Código (String): " + codigoStr);
                    //System.out.println("Linha " + i + " - Quantidade (String): " + qtdStr);
                    //System.out.println("Linha " + i + " - Preço (String): " + precoStr);
                    // Conversões para os tipos corretos
                    int produtoId = Integer.parseInt(codigoStr);
                    double quantidade = Double.parseDouble(qtdStr.replace(",", "."));
                    double precoCompra = Double.parseDouble(precoStr.replace(".", "").replace(",", "."));

                    // Validação
                    if (produtoId <= 0 || quantidade <= 0 || precoCompra <= 0) {
                        //System.out.println("Valores inválidos na linha " + i + ". ProdutoID: " + produtoId + ", Quantidade: " + quantidade + ", Preço: " + precoCompra);
                        continue; // Ignora esta linha
                    }

                    // Criando objeto ItensCompras
                    ItensCompras item = new ItensCompras();
                    item.setProdutoId(produtoId);
                    item.setQtd(quantidade);
                    item.setPrecoCompra(precoCompra);

                    // Adiciona à lista
                    itens.add(item);

                    //System.out.println("Linha " + i + " adicionada com sucesso! ProdutoID: " + produtoId + ", Quantidade: " + quantidade + ", Preço: " + precoCompra);
                } catch (NumberFormatException e) {
                    System.out.println("Erro de conversão na linha " + i + ". Valores: Código, Qtd ou Preço podem estar em formato inválido.");
                    e.printStackTrace();
                }
            }
        } catch (Exception e) {
            //System.out.println("Erro inesperado ao obter itens de compra.");
            e.printStackTrace();
        }

        //System.out.println("=== Fim da Extração de Itens do Carrinho ===");
        return itens;
    }


    private void cbxFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFornecedoresActionPerformed
        Object item = cbxFornecedores.getSelectedItem();
        if (item == null || item.toString().contains("Selecione")) {
            jTextFieldid.setText("");
            return;
        }
        try {
            String texto = item.toString();
            String[] partes = texto.split("-");
            if (partes.length >= 2) {
                jTextFieldid.setText(partes[1].trim());
            }
        } catch (Exception e) {
            jTextFieldid.setText("");
        }
    }//GEN-LAST:event_cbxFornecedoresActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        itensCompras.clear();
        total = 0;
        meus_produtos.setRowCount(0);
        txtTotalCompra.setText("");
        jTextAreaObs.setText("");
        new LimpaTela().LimpaTela(PainelFornecedor);
        new LimpaTela().LimpaTela(painel_produto);
        new LimpaTela().LimpaTela(PainelCarrinho);
        txtCodigo.requestFocus();
    }//GEN-LAST:event_btnCancelarActionPerformed

    public String formatarDoubleParaMoeda(double valor) {
        @SuppressWarnings("deprecation")
        NumberFormat nf = NumberFormat.getNumberInstance(new Locale("pt", "BR"));
        nf.setMinimumFractionDigits(2);
        nf.setMaximumFractionDigits(2);
        return nf.format(valor);
    }

    /**
     * @param args the command line arguments
     */
    private static class CarregarCbx {

        public void CarregarCbx(String tabela, String valor, JComboBox<String> combo) {
            combo.removeAllItems();
            combo.addItem("Selecione um fornecedor..."); // ? ITEM PADRÃO

            String sql = "SELECT codclifor, nomeclifor FROM " + tabela + " WHERE tipo = 'FOR' ORDER BY nomeclifor";
            try (Connection con = Conexao.faz_conexao(); PreparedStatement stmt = con.prepareStatement(sql); ResultSet rs = stmt.executeQuery()) {

                while (rs.next()) {
                    String nome = rs.getString("nomeclifor");
                    int id = rs.getInt("codclifor");
                    combo.addItem(nome + " - " + id);
                }

                // Força selecionar o primeiro item (não null)
                if (combo.getItemCount() > 0) {
                    combo.setSelectedIndex(0);
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,
                        "Erro ao carregar fornecedores:\n" + ex.getMessage(),
                        "Erro", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Carrinho;
    private javax.swing.JPanel PainelCarrinho;
    private javax.swing.JPanel PainelFornecedor;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cbxFornecedores;
    private javax.swing.JButton jButtonFinalizarCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1TotalCompra;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCodProd;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDescProd;
    private javax.swing.JLabel jLabelEstoqueProd;
    private javax.swing.JLabel jLabelNomeF;
    private javax.swing.JLabel jLabelPesqProd;
    private javax.swing.JLabel jLabelPrecoCompraProd;
    private javax.swing.JLabel jLabelPrecoProd;
    private javax.swing.JLabel jLabelProdProd;
    private javax.swing.JLabel jLabelQtdProd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaObs;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JPanel painel_compra;
    private javax.swing.JPanel painel_produto;
    private javax.swing.JTable tabelaProduto;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JFormattedTextField txtDesconto;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtPesquisaProduto;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtPrecoCompra;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtTotalCompra;
    // End of variables declaration//GEN-END:variables
}
