package view;

import dao.ItensVendasDAO;
import dao.ProdutosDAO;
import dao.VendasDAO;
import model.ItensVendas;
import model.Vendas;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import model.CliFor;
import utilitarios.Conexao;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author CARLOS
 */
public class Form_Pagamentos extends javax.swing.JDialog {

    public List<ItensVendas> itensVendas = new ArrayList<>();
    public double totalVenda = 0.0;
    public CliFor clientes = new CliFor();
    public boolean vendaFinalizada = false;

    public Form_Pagamentos(java.awt.Component owner, boolean modal) {
        super(JOptionPane.getRootFrame(), modal);  // Usa o Frame principal
        initComponents();
        setTitle("Finalizar Venda - Pagamento");

        // Centraliza em relação ao owner (Form_Vendas)
        if (owner != null) {
            setLocationRelativeTo(owner);
        } else {
            setLocationRelativeTo(null); // centraliza na tela
        }

        // Inicializa campos
        txtDinheiro.setText("0,00");
        txtCartao.setText("0,00");
        txtCheque.setText("0,00");
        txtPix.setText("0,00");
        txtTroco.setText("0,00");
        txtObservacoes.setText("");

        txtDinheiro.requestFocus();
        txtDinheiro.selectAll();
    }

    public Form_Pagamentos() {
        this(null, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDinheiro = new javax.swing.JTextField();
        txtCartao = new javax.swing.JTextField();
        txtCheque = new javax.swing.JTextField();
        txtTroco = new javax.swing.JTextField();
        txtTotalVenda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacoes = new javax.swing.JTextArea();
        btnPagar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaItens = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtPix = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagamentos");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pagamentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setText("Dinheiro");

        jLabel3.setText("Cartão");

        jLabel4.setText("Cheque");

        jLabel5.setText("Trôco");

        jLabel6.setText("Total");

        jLabel7.setText("Observações");

        txtDinheiro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCartao.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCheque.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtTroco.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtTotalVenda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTotalVenda.setEnabled(false);
        txtTotalVenda.setSelectionColor(new java.awt.Color(255, 0, 0));
        txtTotalVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalVendaActionPerformed(evt);
            }
        });

        txtObservacoes.setColumns(20);
        txtObservacoes.setRows(5);
        jScrollPane1.setViewportView(txtObservacoes);

        btnPagar.setText("PAGAR");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        tabelaItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Título 5"
            }
        ));
        jScrollPane2.setViewportView(tabelaItens);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Pix");

        txtPix.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPix)
                    .addComponent(txtCartao)
                    .addComponent(txtDinheiro, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(txtCheque)
                    .addComponent(txtTroco)
                    .addComponent(txtTotalVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCartao, txtCheque, txtDinheiro, txtTroco});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtCartao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPagar)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void carregarDados() {
        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"ID", "Descrição", "Qtd", "Preço Unit.", "Subtotal"}, 0
        );

        NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.of("pt", "BR"));

        for (ItensVendas item : itensVendas) {
            model.addRow(new Object[]{
                item.getProdutos().getId(),
                item.getProdutos().getDescricao(),
                String.format("%.3f", item.getQtd()),
                nf.format(item.getProdutos().getPrecoVenda()), // ? CORRIGIDO AQUI!
                nf.format(item.getSubtotal())
            });
        }

        // Se você tiver uma jTable chamada tabelaItens no Form_Pagamentos:
        tabelaItens.setModel(model);  // ? descomente se tiver

        // Total da venda
        txtTotalVenda.setText(nf.format(totalVenda));
    }


    private void txtTotalVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalVendaActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        try {
            double dinheiro = parseMoeda(txtDinheiro.getText());
            double cartao = parseMoeda(txtCartao.getText());
            double cheque = parseMoeda(txtCheque.getText());
            double pix = parseMoeda(txtPix.getText());
            double totalPago = dinheiro + cartao + cheque + pix;

            if (totalPago < totalVenda) {
                JOptionPane.showMessageDialog(this, "Valor pago insuficiente!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (JOptionPane.showConfirmDialog(this,
                    "Confirmar venda de R$ " + String.format("%,.2f", totalVenda)
                    + "\nTroco: R$ " + String.format("%,.2f", totalPago - totalVenda),
                    "Finalizar?", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
                return;
            }

            try (Connection con = Conexao.faz_conexao()) {
                con.setAutoCommit(false);

                Vendas v = new Vendas();
                v.setClientes(clientes != null ? clientes : new CliFor()); // ? avulso se null
                v.setData_venda(java.sql.Timestamp.valueOf(java.time.LocalDateTime.now()));
                v.setTotal_venda(totalVenda);
                v.setObservacoes(txtObservacoes.getText().isEmpty() ? "Venda PDV" : txtObservacoes.getText());

                VendasDAO daoVenda = new VendasDAO();
                daoVenda.salvar(v, con); // ID já é setado dentro do método

                ItensVendasDAO itemDao = new ItensVendasDAO();
                ProdutosDAO prodDao = new ProdutosDAO();

//                for (ItensVendas item : itensVendas) {
//                    item.getVendas().setId(v.getId());
//                    itemDao.salvar(item, con);
//                    prodDao.baixaEstoque(item.getProdutos().getId(), item.getQtd(), con);
//                }
                for (ItensVendas item : itensVendas) {
                    // ASSOCIA O OBJETO VENDA AO ITEM ANTES DE SALVAR!
                    item.setVendas(v);  // ? ESSA LINHA É OBRIGATÓRIA!

                    itemDao.salvar(item, con);
                    prodDao.baixaEstoque(item.getProdutos().getId(), item.getQtd(), con);
                }

                con.commit();

                JOptionPane.showMessageDialog(this,
                        "VENDA Nº " + v.getId() + " FINALIZADA COM SUCESSO!\n"
                        + "Troco: R$ " + String.format("%,.2f", totalPago - totalVenda),
                        "SUCESSO!", JOptionPane.INFORMATION_MESSAGE);

                vendaFinalizada = true;
                dispose();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "ERRO: " + e.getMessage());
                e.printStackTrace();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    // Método para limpar e converter o valor
    private double limparEConverterValor(String valor) {

        // Limpar espaços em branco
        String valorLimpo = valor.trim();

        // Se a string estiver vazia, retornar 0.0
        if (valorLimpo.isEmpty()) {
            return 0.0;
        }

        // Substituir a vírgula por ponto para o separador decimal
        valorLimpo = valorLimpo.replace(",", ".");

        // Remover pontos que estão antes da última vírgula (se houver)
        if (valorLimpo.indexOf('.') != valorLimpo.lastIndexOf('.')) {
            int lastPointIndex = valorLimpo.lastIndexOf('.');
            valorLimpo = valorLimpo.substring(0, lastPointIndex).replace(".", "") + valorLimpo.substring(lastPointIndex);
        }

        // Debug: imprime o valor limpo
        // System.out.println("Valor limpo após ajuste: " + valorLimpo);
        try {
            // Converter para double
            return Double.parseDouble(valorLimpo);
        } catch (NumberFormatException e) {
            // Se ocorrer um erro na conversão, imprimir mensagem de erro e retornar 0.0
            System.err.println("Erro ao converter valor: " + valor + ". " + e.getMessage());
            return 0.0;
        }
    }

    public String formatarQuantidade(double quantidade) {
        NumberFormat formatador = NumberFormat.getInstance();
        formatador.setMaximumFractionDigits(3); // Permite até 3 casas decimais
        formatador.setGroupingUsed(true); // Usar separadores de milhar
        return formatador.format(quantidade);
    }

    private double parseMoeda(String texto) {
        if (texto == null || texto.trim().isEmpty()) {
            return 0.0;
        }

        // Remove tudo que não for número, vírgula ou ponto
        String limpo = texto.replaceAll("[^0-9,\\.]", "");

        // Troca vírgula por ponto (padrão Brasil ? Java)
        limpo = limpo.replace(",", ".");

        try {
            return Double.parseDouble(limpo);
        } catch (NumberFormatException e) {
            System.out.println("Erro ao converter moeda: " + texto + " ? " + limpo);
            return 0.0;
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaItens;
    private javax.swing.JTextField txtCartao;
    private javax.swing.JTextField txtCheque;
    private javax.swing.JTextField txtDinheiro;
    private javax.swing.JTextArea txtObservacoes;
    private javax.swing.JTextField txtPix;
    public javax.swing.JTextField txtTotalVenda;
    private javax.swing.JTextField txtTroco;
    // End of variables declaration//GEN-END:variables
}
