package view;

import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import dao.ItensVendasDAO;
import dao.VendasDAO;
import java.io.FileOutputStream;
import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.ItensVendas;
import model.Vendas;
import javax.swing.JOptionPane;

/**
 *
 * @author CARLOS
 */
public class Form_DetalheVenda extends javax.swing.JDialog {

    NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.of("pt", "BR"));
    
    /**
     * Creates new form FormularioDetalheVenda
     */
    public Form_DetalheVenda(java.awt.Component owner, boolean modal, int idVenda) {
        super(JOptionPane.getRootFrame(), modal);  // Usa o Frame principal
        
        initComponents();
        setTitle("Detalhes da Venda");
        setLocationRelativeTo(owner);  // centraliza em relação ao dono

        carregarDadosVenda(idVenda);
    }

    // Construtor vazio (opcional)
    public Form_DetalheVenda() {
        this(null, true, 0);
    }

    private void carregarDadosVenda(int idVenda) {
        try {
            VendasDAO dao = new VendasDAO();
            Vendas v = dao.buscarPorId(idVenda);
            if (v != null) {
                txtIdVenda.setText(String.valueOf(v.getId()));
                txtCliente.setText(v.getClientes().getNomeCliFor());
                txtDataVenda.setText(v.getData_venda().toLocalDateTime()
                        .format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")));
                txtTotalVenda.setText(NumberFormat.getCurrencyInstance(Locale.of("pt", "BR"))
                        .format(v.getTotal_venda()));
                txtObs.setText(v.getObservacoes());

                // Carrega itens
                ItensVendasDAO itensDao = new ItensVendasDAO();
                List<ItensVendas> itens = itensDao.listarPorVenda(idVenda);
                DefaultTableModel model = (DefaultTableModel) Carrinho.getModel();
                model.setRowCount(0);

                NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.of("pt", "BR"));
                double acumulado = 0.0;

                for (ItensVendas i : itens) {
                    acumulado += i.getSubtotal();

                    model.addRow(new Object[]{
                        i.getProdutos().getId(),
                        i.getProdutos().getDescricao(),
                        String.format("%.3f", i.getQtd()),
                        nf.format(i.getPrecoVenda()), // Preço unitário da época
                        nf.format(i.getSubtotal()), // Subtotal do item
                        nf.format(acumulado), // ? ACUMULADO (pro cliente no PDF)
                        nf.format(i.getPrecoMedioCusto()) // ? CUSTO MÉDIO (só pra você na tela!)
                    });
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar venda: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdVenda = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        txtDataVenda = new javax.swing.JFormattedTextField();
        txtTotalVenda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        btnCupomPDF = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        Carrinho = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalhe da Venda");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Detalhe da Venda");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel2.setText("Id da Venda");

        jLabel3.setText("Cliente");

        jLabel4.setText("Data da Venda");

        jLabel5.setText("Total de Venda");

        jLabel6.setText("Observações");

        txtIdVenda.setEnabled(false);
        txtIdVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdVendaActionPerformed(evt);
            }
        });

        txtCliente.setEnabled(false);

        try {
            txtDataVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/20##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataVenda.setEnabled(false);

        txtTotalVenda.setEnabled(false);

        txtObs.setColumns(20);
        txtObs.setRows(5);
        txtObs.setEnabled(false);
        jScrollPane1.setViewportView(txtObs);

        btnCupomPDF.setText("Gerar Cupom PDF");
        btnCupomPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCupomPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnCupomPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalVenda)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(txtTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCupomPDF)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Carrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Qtd.", "Preço", "Subtotais", "Acumulado"
            }
        ));
        jScrollPane3.setViewportView(Carrinho);

        jScrollPane2.setViewportView(jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdVendaActionPerformed

    public void gerarCupomPDF() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Salvar Cupom Não Fiscal");
        fileChooser.setFileFilter(new FileNameExtensionFilter("PDF Files", "pdf"));
        int userSelection = fileChooser.showSaveDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String file_name = fileChooser.getSelectedFile().getAbsolutePath();
            if (!file_name.toLowerCase().endsWith(".pdf")) {
                file_name += ".pdf";
            }

            Document document = new Document(PageSize.A4);
            document.setMargins(10f, 10f, 10f, 10f);

            try {
                PdfWriter.getInstance(document, new FileOutputStream(file_name));
                document.open();

                // Cabeçalho do cupom (igual antes)
                document.add(new Paragraph("********************************"));
                document.add(new Paragraph(" Cupom Não Fiscal ", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12)));
                document.add(new Paragraph("********************************"));
                document.add(new Paragraph("ID Venda: " + txtIdVenda.getText()));
                document.add(new Paragraph("Total : " + txtTotalVenda.getText()));
                document.add(new Paragraph("Cliente : " + txtCliente.getText()));
                document.add(new Paragraph("Data : " + txtDataVenda.getText()));
                document.add(new Paragraph("Obs. : " + txtObs.getText()));
                document.add(new Paragraph("\nItens da Venda:"));
                document.add(new Paragraph("--------------------------------------------------------------------------------------------------------------------------------"));

                // Tabela com 6 colunas (sem custo médio pro cliente)
                PdfPTable tabela = new PdfPTable(6);
                tabela.setWidthPercentage(75);
                tabela.setWidths(new float[]{2f, 5f, 2f, 3f, 4f, 5f});

                // Cabeçalho
                tabela.addCell(getCell("Cod", PdfPCell.ALIGN_LEFT));
                tabela.addCell(getCell("Produto", PdfPCell.ALIGN_LEFT));
                tabela.addCell(getCell("Qtd", PdfPCell.ALIGN_CENTER));
                tabela.addCell(getCell("Preço", PdfPCell.ALIGN_RIGHT));
                tabela.addCell(getCell("Subtotal", PdfPCell.ALIGN_RIGHT));
                tabela.addCell(getCell("Acumulado", PdfPCell.ALIGN_RIGHT));

                DefaultTableModel model = (DefaultTableModel) Carrinho.getModel();
                double acumulado = 0.0;
                NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.of("pt", "BR"));

                for (int row = 0; row < model.getRowCount(); row++) {
                    // Colunas normais (já formatadas bonitinhas)
                    tabela.addCell(getCell(model.getValueAt(row, 0).toString(), PdfPCell.ALIGN_LEFT));     // Código
                    tabela.addCell(getCell(model.getValueAt(row, 1).toString(), PdfPCell.ALIGN_LEFT));     // Produto
                    tabela.addCell(getCell(model.getValueAt(row, 2).toString(), PdfPCell.ALIGN_CENTER));   // Qtd
                    tabela.addCell(getCell(model.getValueAt(row, 3).toString(), PdfPCell.ALIGN_RIGHT));    // Preço Unit.
                    tabela.addCell(getCell(model.getValueAt(row, 4).toString(), PdfPCell.ALIGN_RIGHT));    // Subtotal

                    // === CÁLCULO SEGURO DO ACUMULADO ===
                    String subtotalStr = model.getValueAt(row, 4).toString(); // ex: "R$ 71,76"
                    double subtotal = parseCurrencyToDouble(subtotalStr);
                    acumulado += subtotal;

                    // Mostra o acumulado já formatado com R$
                    tabela.addCell(getCell(nf.format(acumulado), PdfPCell.ALIGN_RIGHT));
                }

                document.add(tabela);
                document.add(new Paragraph("========================================================================="));

                JOptionPane.showMessageDialog(null, "PDF gerado com sucesso: " + file_name);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao gerar PDF: " + e.getMessage());
                e.printStackTrace();
            } finally {
                document.close();
            }
        }
    }

    // === FUNÇÃO MÁGICA QUE RESOLVE O PROBLEMA DA MOEDA BRASILEIRA ===
    private double parseCurrencyToDouble(String valor) {
        if (valor == null || valor.trim().isEmpty()) {
            return 0.0;
        }

        String limpo = valor
                .replace("R$", "")
                .replace(" ", "")
                .replace(" ", "") // esse espaço invisível maldito!
                .replace(".", "")
                .replace(",", ".")
                .trim();

        try {
            return Double.parseDouble(limpo);
        } catch (Exception e) {
            System.out.println("Erro ao converter: " + valor);
            return 0.0;
        }
    }

    // Função auxiliar para criar células sem borda
    private PdfPCell getCell(String text, int alignment) {
        PdfPCell cell = new PdfPCell(new Phrase(text));
        cell.setPadding(5);
        cell.setHorizontalAlignment(alignment);
        cell.setBorder(PdfPCell.NO_BORDER);
        return cell;
    }


    private void btnCupomPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCupomPDFActionPerformed
        gerarCupomPDF();
    }//GEN-LAST:event_btnCupomPDFActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Carrinho;
    private javax.swing.JButton btnCupomPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextField txtCliente;
    public javax.swing.JFormattedTextField txtDataVenda;
    public javax.swing.JTextField txtIdVenda;
    public javax.swing.JTextArea txtObs;
    public javax.swing.JTextField txtTotalVenda;
    // End of variables declaration//GEN-END:variables
}
