package view;

import utilitarios.Conexao;
import dao.ProdutosDAO;
import model.Produtos;
import utilitarios.LimpaTela;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JComboBox;
import javax.swing.text.MaskFormatter;
import model.CliFor;
import model.ItensVendas;

/**
 *
 * @author CARLOS
 */
public class Form_Vendas extends javax.swing.JDialog {

    public List<ItensVendas> itensVendas = new ArrayList<>();
    public DefaultTableModel meus_produtos; // Declare a tabela de produtos
    private final NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.of("pt", "BR"));
    public CliFor clientes = new CliFor(); // ? já tem!

    CarregarCbx rf = new CarregarCbx(); //Carrega combobox de Clientes

    public Form_Vendas(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        setTitle("PDV - Ponto de Venda");
        setLocationRelativeTo(null);

        // Modelo da tabela carrinho
        meus_produtos = new DefaultTableModel(
                new Object[]{"ID", "Descrição", "Qtd", "Preço Unit.", "Subtotal"}, 0
        );
        Carrinho.setModel(meus_produtos);

        // Data atual
        txtData.setText(java.time.LocalDate.now().format(
                java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy")
        ));

        // Carrega clientes no combo
        new CarregarCbx().CarregarCbx("tbclifor", "nomeCliFor", cbxClientes);

        // Foco no código
        txtCodigo.requestFocus();
    }

    // Pra testar direto (opcional)
    public Form_Vendas() throws SQLException {
        this(null, true);
    }

    // Use em qualquer lugar assim:
    private String formatarMoeda(double valor) {
        return nf.format(valor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painel_Cliente = new javax.swing.JPanel();
        txtData = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPesquisaProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        cbxClientes = new javax.swing.JComboBox<>();
        jTextFieldid = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        painel_produto = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtProduto = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        txtEstoque = new javax.swing.JTextField();
        txtQtd = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JFormattedTextField();
        btnAdicionar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        painel_Carrinho = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Carrinho = new javax.swing.JTable();
        painel_Venda = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtTotalVenda = new javax.swing.JTextField();
        btnPagamento = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ponto de Vendas");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ponto de Vendas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel_Cliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel2.setText("CPF :");

        jLabel3.setText("Data :");

        jLabel4.setText("Nome:");

        jLabel5.setText("Pesquise um produto aqui :");

        txtPesquisaProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaProdutoKeyReleased(evt);
            }
        });

        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "descrição", "preço_venda", "qtd. estoque", "fornecedor"
            }
        ));
        tabelaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProduto);

        cbxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbxClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_ClienteLayout = new javax.swing.GroupLayout(painel_Cliente);
        painel_Cliente.setLayout(painel_ClienteLayout);
        painel_ClienteLayout.setHorizontalGroup(
            painel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_ClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_ClienteLayout.createSequentialGroup()
                        .addGroup(painel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painel_ClienteLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painel_ClienteLayout.createSequentialGroup()
                                .addGroup(painel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painel_ClienteLayout.createSequentialGroup()
                                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painel_ClienteLayout.createSequentialGroup()
                                        .addComponent(cbxClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(20, 20, 20))))
        );
        painel_ClienteLayout.setVerticalGroup(
            painel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_ClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
        );

        painel_produto.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));

        jLabel6.setText("Código:");

        jLabel7.setText("Produto:");

        jLabel8.setText("Preço:");

        jLabel9.setText("Estoque:");

        jLabel10.setText("Qtd. :");

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        txtProduto.setEnabled(false);

        txtPreco.setEnabled(false);

        txtEstoque.setEnabled(false);

        txtQtd.setText("1");

        jLabel11.setText("Desconto %");

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdicionar.setText("ADD ITEM");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_produtoLayout = new javax.swing.GroupLayout(painel_produto);
        painel_produto.setLayout(painel_produtoLayout);
        painel_produtoLayout.setHorizontalGroup(
            painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_produtoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painel_produtoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_produtoLayout.createSequentialGroup()
                        .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel_produtoLayout.createSequentialGroup()
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtProduto)))
                    .addGroup(painel_produtoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEstoque)
                        .addGap(177, 177, 177)))
                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpar)
                    .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnPesquisar)
                        .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        painel_produtoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdicionar, btnLimpar});

        painel_produtoLayout.setVerticalGroup(
            painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_produtoLayout.createSequentialGroup()
                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProduto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        painel_produtoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdicionar, btnLimpar});

        painel_Carrinho.setBorder(javax.swing.BorderFactory.createTitledBorder("Carrinho de Compras"));

        Carrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Qtd.", "Preço", "Subtotall"
            }
        ));
        jScrollPane3.setViewportView(Carrinho);

        javax.swing.GroupLayout painel_CarrinhoLayout = new javax.swing.GroupLayout(painel_Carrinho);
        painel_Carrinho.setLayout(painel_CarrinhoLayout);
        painel_CarrinhoLayout.setHorizontalGroup(
            painel_CarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );
        painel_CarrinhoLayout.setVerticalGroup(
            painel_CarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_CarrinhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        painel_Venda.setBorder(javax.swing.BorderFactory.createTitledBorder("Total da Venda"));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Total da Venda : ");

        txtTotalVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalVendaActionPerformed(evt);
            }
        });

        btnPagamento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPagamento.setText("PAGAMENTO");
        btnPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagamentoActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setText("CANCELAR VENDA");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_VendaLayout = new javax.swing.GroupLayout(painel_Venda);
        painel_Venda.setLayout(painel_VendaLayout);
        painel_VendaLayout.setHorizontalGroup(
            painel_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_VendaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_VendaLayout.createSequentialGroup()
                        .addComponent(btnPagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addComponent(txtTotalVenda))
                .addContainerGap())
        );

        painel_VendaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelar, btnPagamento});

        painel_VendaLayout.setVerticalGroup(
            painel_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_VendaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painel_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        painel_VendaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelar, btnPagamento});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painel_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel_produto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel_Carrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel_Venda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painel_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painel_Carrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painel_Venda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel_produto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void listar() throws SQLException, ClassNotFoundException {
        try (Connection con = Conexao.faz_conexao()) {
            ProdutosDAO dao = new ProdutosDAO();
            List<Produtos> lista = dao.listarTodos();

            DefaultTableModel model = (DefaultTableModel) tabelaProduto.getModel();
            model.setRowCount(0);

            NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.of("pt", "BR"));

            for (Produtos p : lista) {
                model.addRow(new Object[]{
                    p.getId(),
                    p.getDescricao(),
                    nf.format(p.getPrecoVenda()),
                    //"R$ " + p.getPrecoVenda(),  // ? tira o nf.format pra ver o número bruto
                    String.format("%.3f", p.getQtd_estoque()),
                    p.getCliFor() != null ? p.getCliFor().getNomeCliFor() : ""
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar produtos.");
        }
    }
    CliFor obj = new CliFor();
    double preco, subtotal, total;

    /**
     * Creates new form FormularioVendas
     */
    int qtd;

    /**
     * Creates new form FormularioVendas
     */
    public void setMeusProdutos(DefaultTableModel meus_produtos) {
        this.meus_produtos = meus_produtos; // Armazena o modelo de tabela passado
    }

    private void tabelaProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutoMouseClicked
        txtCodigo.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 0).toString());
        txtProduto.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 1).toString());
        txtPreco.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 2).toString()); // aqui estou pegando o preço de venda da tabelaProduto

        // Obtém a quantidade do estoque
        String estoqueStr = tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 3).toString();

        // Remove vírgulas antes da conversão, se necessário
        estoqueStr = estoqueStr.replace(".", ""); // Remove o ponto para milhar (se houver)
        estoqueStr = estoqueStr.replace(",", "."); // Substitui a vírgula por ponto para o formato decimal

        // Converte a string em double
        double estoque = Double.parseDouble(estoqueStr);

        // Formata o valor como double com 3 casas decimais
        String estoqueFormatado = String.format("%.3f", estoque);
        txtEstoque.setText(estoqueFormatado);

        txtCodigo.setEnabled(false);
    }//GEN-LAST:event_tabelaProdutoMouseClicked

    private void txtTotalVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalVendaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) throws SQLException, ClassNotFoundException {
        listar();
    }

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    }//GEN-LAST:event_formWindowActivated

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buscarProdutoPorCodigo();
        }
    }

    private void buscarProdutoPorCodigo() {
        try {
            int id = Integer.parseInt(txtCodigo.getText());
            ProdutosDAO dao = new ProdutosDAO();
            Produtos p = dao.buscarPorId(id);

            if (p != null && p.getId() != 0) {
                txtProduto.setText(p.getDescricao());
                txtPreco.setText(NumberFormat.getCurrencyInstance(Locale.of("pt", "BR")).format(p.getPrecoVenda()));
                txtEstoque.setText(String.format("%.3f", p.getQtd_estoque()));
                txtQtd.setText("1");
                txtQtd.requestFocus();
                txtQtd.selectAll();
            } else {
                JOptionPane.showMessageDialog(this, "Produto não encontrado!");
                txtCodigo.setText("");
                txtCodigo.requestFocus();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Código inválido!");
        } catch (SQLException ex) {
            Logger.getLogger(Form_Vendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        LimpaTela util = new LimpaTela();
        util.LimpaTela(painel_produto);
        txtCodigo.setEnabled(true);
        txtCodigo.requestFocus();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        int id = Integer.valueOf(txtCodigo.getText());
        Produtos obj = new Produtos();
        ProdutosDAO dao;
        try {
            dao = new ProdutosDAO();
            obj = dao.buscarPorId(id);
            if (obj.getId() != 0) {
                txtCodigo.setText(String.valueOf(obj.getId()));
                txtProduto.setText(obj.getDescricao());
                txtPreco.setText(String.valueOf(obj.getPreco()));

                // Formata a quantidade do estoque como double com 3 casas decimais
                String estoqueFormatado = String.format("%.3f", obj.getQtd_estoque());
                txtEstoque.setText(estoqueFormatado);

                txtCodigo.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Código inválido!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Form_Vendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtPesquisaProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaProdutoKeyReleased
        String nome = "%" + txtPesquisaProduto.getText() + "%";
        ProdutosDAO dao;
        try {
            dao = new ProdutosDAO();
            List<Produtos> lista = dao.filtrarPorNome(nome);
            DefaultTableModel dados = (DefaultTableModel) tabelaProduto.getModel();
            dados.setNumRows(0);

            // Define o formato para moeda no padrão brasileiro
            NumberFormat nfPreco = NumberFormat.getCurrencyInstance();

            for (Produtos p : lista) {
                // Formata o preço
                String precoFormatado = nfPreco.format(p.getPrecoVenda());

                // Formata a quantidade como double com 3 casas decimais
                String estoqueFormatado = String.format("%.3f", p.getQtd_estoque());

                dados.addRow(new Object[]{
                    p.getId(),
                    p.getDescricao(),
                    precoFormatado, // Preço formatado
                    estoqueFormatado, // Quantidade formatada
                    p.getCliFor().getNomeCliFor()
                });
                txtCodigo.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Form_Produtos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtPesquisaProdutoKeyReleased

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        try {
            double qtd = Double.parseDouble(txtQtd.getText().replace(",", "."));
            double estoque = Double.parseDouble(txtEstoque.getText().replace(",", "."));
            double preco = NumberFormat.getCurrencyInstance(Locale.of("pt", "BR"))
                    .parse(txtPreco.getText()).doubleValue();

            if (qtd <= 0) {
                JOptionPane.showMessageDialog(this, "Quantidade deve ser maior que zero!");
                return;
            }
            if (qtd > estoque) {
                JOptionPane.showMessageDialog(this, "Quantidade maior que o estoque!");
                return;
            }

            double subtotal = preco * qtd;
            total += subtotal;

            int id = Integer.parseInt(txtCodigo.getText());

            meus_produtos.addRow(new Object[]{
                id,
                txtProduto.getText(),
                String.format("%.3f", qtd),
                txtPreco.getText(),
                NumberFormat.getCurrencyInstance(Locale.of("pt", "BR")).format(subtotal)
            });

            // Adiciona na lista de itens
            ItensVendas item = new ItensVendas();
            ProdutosDAO dao = new ProdutosDAO();
            Produtos produtoCompleto = dao.buscarPorIdComCusto(id);
            Produtos p = new Produtos();
            p.setId(id);
            p.setDescricao(txtProduto.getText());
            p.setPrecoVenda(preco);
            p.setPrecoMedioCusto(produtoCompleto.getPrecoMedioCusto()); // GRAVA O CUSTO NA VENDA!
            item.setProdutos(p);
            item.setQtd(qtd);
            item.setSubtotal(subtotal);
            item.setPrecoMedioCusto(produtoCompleto.getPrecoMedioCusto()); // AQUI GRAVA O CUSTO!
            itensVendas.add(item);
            txtTotalVenda.setText(NumberFormat.getCurrencyInstance(Locale.of("pt", "BR")).format(total));

            // Limpa campos do produto
            txtCodigo.setText("");
            txtProduto.setText("");
            txtPreco.setText("");
            txtEstoque.setText("");
            txtQtd.setText("1");
            txtCodigo.requestFocus();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar item: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed


    private void btnPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagamentoActionPerformed
        if (itensVendas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Adicione pelo menos um item!");
            return;
        }

        Form_Pagamentos pag = new Form_Pagamentos(this, true);
        pag.itensVendas = this.itensVendas;
        pag.totalVenda = this.total;

        // AQUI ESTÁ A VERDADEIRA MÁGICA:
        pag.clientes = this.clientes; // ? PASSA O CLIENTE QUE VOCÊ JÁ TEM PRONTO!

        pag.carregarDados();
        pag.setVisible(true);

        if (pag.vendaFinalizada) {
            this.dispose();
        }
    }//GEN-LAST:event_btnPagamentoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Limpar dados após finalização
        itensVendas.clear();
        total = 0;
        txtTotalVenda.setText(""); // Limpa o total de compra

        // Limpa os painéis
        new LimpaTela().LimpaTela(painel_Cliente);
        new LimpaTela().LimpaTela(painel_produto);
        new LimpaTela().LimpaTela(painel_Carrinho);
        new LimpaTela().LimpaTela(painel_Venda);

        // Limpar a jTable do carrinho
        DefaultTableModel model = (DefaultTableModel) Carrinho.getModel();
        model.setRowCount(0); // Remove todas as linhas
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbxClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClientesActionPerformed
        Object itemSelecionado = cbxClientes.getSelectedItem();
        if (itemSelecionado == null || itemSelecionado.toString().trim().isEmpty()) {
            limparCamposCliente();
            clientes = null;
            return;
        }

        String texto = itemSelecionado.toString().trim();

        // ACEITA QUALQUER FORMATO COM | (com ou sem espaços)
        String[] partes = texto.split("\\s*\\|\\s*", 3);  // ? A MÁGICA!

        if (partes.length < 3) {
            System.out.println("Formato inválido no combo: " + texto);
            limparCamposCliente();
            clientes = null;
            return;
        }

        String nomeCliente = partes[0].trim();
        String idCliente = partes[1].trim();      // ? "1000"
        String documento = partes[2].trim();

        // Preenche os campos visuais
        jTextFieldid.setText(idCliente);
        txtCpf.setText(documento);

        // Preenche o objeto cliente
        clientes = new CliFor();
        clientes.setCodCliFor(idCliente);
        clientes.setNomeCliFor(nomeCliente);

        System.out.println("Cliente selecionado: " + nomeCliente + " | Código: " + idCliente);
    }

    private static String formatarCpfCnpj(String doc) {
        if (doc == null) {
            return "";
        }
        doc = doc.replaceAll("\\D", ""); // remove tudo que não é número

        if (doc.length() == 11) {
            return doc.replaceAll("(\\d{3})(\\d{3})(\\d{3})(\\d{2})", "$1.$2.$3-$4");
        } else if (doc.length() == 14) {
            return doc.replaceAll("(\\d{2})(\\d{3})(\\d{3})(\\d{4})(\\d{2})", "$1.$2.$3/$4-$5");
        }
        return doc; // retorna como está se não for CPF nem CNPJ
    }

    private void limparCamposCliente() {
        //jTextFieldid.setText("");
        txtCpf.setText("");
        // txtNomeCliente.setText("");
    }//GEN-LAST:event_cbxClientesActionPerformed

    private String formatarCPF(String cpf) {
        try {
            MaskFormatter formatter = new MaskFormatter("###.###.###-##");
            formatter.setValueContainsLiteralCharacters(false);
            return formatter.valueToString(cpf.replaceAll("\\D", "")); // Remove caracteres não numéricos antes de formatar
        } catch (Exception e) {
            e.printStackTrace();
            return cpf; // Retorna o CPF sem formatação em caso de erro
        }
    }

    private double formatarMoedaParaDouble(String valor) {
        try {
            // Exibe o valor original para análise
            //System.out.println("Valor original antes de limpar: " + valor);

            // Remove o símbolo "R$", remove todos os tipos de espaço (incluindo espaços invisíveis), pontos e vírgulas
            String valorLimpo = valor.replace("R$", "").replace("\u00A0", "").trim().replace(".", "").replace(",", ".");

            // Exibe o valor limpo antes de converter
            //System.out.println("Valor limpo: " + valorLimpo);
            return Double.parseDouble(valorLimpo);
        } catch (NumberFormatException e) {
            System.out.println("Erro ao converter o valor: " + valor);
            return 0;
        }
    }

    public String formatarDoubleParaMoeda(double valor) {
        @SuppressWarnings("deprecation")
        NumberFormat nf = NumberFormat.getNumberInstance(new Locale("pt", "BR"));
        nf.setMinimumFractionDigits(2);
        nf.setMaximumFractionDigits(2);
        return nf.format(valor);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Form_Vendas().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Form_Vendas.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    private static class CarregarCbx {

        @SuppressWarnings({"empty-statement", "unchecked", "unchecked"})
        public void CarregarCbx(String tabela, String valor, JComboBox combo) throws SQLException {
            String sql = "Select * FROM " + tabela + " WHERE tipo = 'CLI' ORDER BY nomeclifor";
            // Cria uma instância da classe Conexao
            Conexao conexao = new Conexao();
            try (Connection con = Conexao.faz_conexao(); PreparedStatement stmt = con.prepareStatement(sql); ResultSet rs = stmt.executeQuery()) {

                while (rs.next()) {
                    String nome = rs.getString("nomeclifor");
                    int id = rs.getInt("codclifor");
                    String Ncpf = rs.getString("cpf");
                    combo.addItem(nome + " | " + id + " | " + formatarCpfCnpj(Ncpf));
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,
                        "Erro ao carregar fornecedores:\n" + ex.getMessage(),
                        "Erro", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Carrinho;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPagamento;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cbxClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JPanel painel_Carrinho;
    private javax.swing.JPanel painel_Cliente;
    private javax.swing.JPanel painel_Venda;
    private javax.swing.JPanel painel_produto;
    private javax.swing.JTable tabelaProduto;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JFormattedTextField txtDesconto;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtPesquisaProduto;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtTotalVenda;
    // End of variables declaration//GEN-END:variables
}
