package view;

import utilitarios.Conexao;
import classes.CustomTableCellRenderer;
import classes.ExportToExcel;
import classes.ImprimirJTable;
import classes.PercentualRenderer;
import java.awt.Color;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
//import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Connection;

import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;

import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;

public class Tela_de_Consulta_RD extends javax.swing.JFrame {

    public Tela_de_Consulta_RD() throws SQLException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRegime = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldDataIni = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldDataFim = new javax.swing.JFormattedTextField();
        jPanelRegime = new javax.swing.JPanel();
        rbCaixa = new javax.swing.JRadioButton();
        rbCompetencia = new javax.swing.JRadioButton();
        rbVcto = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonPImprimir = new javax.swing.JButton();
        jButtonPLimpar = new javax.swing.JButton();
        jButtonPFechar = new javax.swing.JButton();
        jButtonGraficoDesp = new javax.swing.JButton();
        jButtonGraficoRec = new javax.swing.JButton();
        jButtonExportar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel2.setText("   PERÍODO DE VENCIMENTOS  de");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        try {
            jFormattedTextFieldDataIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("até");

        try {
            jFormattedTextFieldDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        grupoRegime.add(rbCaixa);
        rbCaixa.setText("Regime de Caixa");

        grupoRegime.add(rbCompetencia);
        rbCompetencia.setText("Regime de Competência");

        grupoRegime.add(rbVcto);
        rbVcto.setText("Vencimento");

        javax.swing.GroupLayout jPanelRegimeLayout = new javax.swing.GroupLayout(jPanelRegime);
        jPanelRegime.setLayout(jPanelRegimeLayout);
        jPanelRegimeLayout.setHorizontalGroup(
            jPanelRegimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbVcto)
                .addGap(35, 35, 35)
                .addComponent(rbCaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(rbCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelRegimeLayout.setVerticalGroup(
            jPanelRegimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegimeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRegimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCompetencia)
                    .addComponent(rbCaixa)
                    .addComponent(rbVcto))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelRegime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(360, 360, 360))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRegime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonPImprimir.setText("Imprimir");
        jButtonPImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPImprimirActionPerformed(evt);
            }
        });

        jButtonPLimpar.setText("Limpar");
        jButtonPLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPLimparActionPerformed(evt);
            }
        });

        jButtonPFechar.setText("Fechar");
        jButtonPFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPFecharActionPerformed(evt);
            }
        });

        jButtonGraficoDesp.setText("Gráfico Despesas");
        jButtonGraficoDesp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGraficoDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGraficoDespActionPerformed(evt);
            }
        });

        jButtonGraficoRec.setText("Gráfico Receitas");
        jButtonGraficoRec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGraficoRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGraficoRecActionPerformed(evt);
            }
        });

        jButtonExportar.setText("Exportar para Excel");
        jButtonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGraficoDesp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGraficoRec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jButtonPImprimir)
                    .addComponent(jButtonPLimpar)
                    .addComponent(jButtonPFechar)
                    .addComponent(jButtonGraficoDesp)
                    .addComponent(jButtonGraficoRec)
                    .addComponent(jButtonExportar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CONSULTA - RECEITAS X DESPESAS");

        jTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRINCIPAL", "GRUPO", "CONTA", "TOTAL CONTA", "ACUMULADO", "PERCENTUAL", "MÉDIA HISTÓRICA(%)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePesquisa.setSelectionBackground(new java.awt.Color(255, 255, 204));
        jTablePesquisa.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jTablePesquisa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPFecharActionPerformed
        try {
            TelaPrincipal exibir;
            exibir = new TelaPrincipal();
            exibir.setVisible(true);
            setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(Tela_de_Consulta_RD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPFecharActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

        if (jFormattedTextFieldDataIni.getText().trim().length() <= 4) {
            JOptionPane.showMessageDialog(null, "Atenção! Favor preencher o campo de data inicial corretamente.");
            return;
        }
        if (jFormattedTextFieldDataFim.getText().trim().length() <= 4) {
            JOptionPane.showMessageDialog(null, "Atenção! Favor preencher o campo de data final corretamente.");
            return;
        }

        // Variáveis para totais do período
        double receitasOperacionais = 0.0;
        double receitasNaoOperacionais = 0.0;
        double despesasOperacionais = 0.0;
        double despesasNaoOperacionais = 0.0;
        double totalReceitas = 0.0;
        double totalDespesas = 0.0;

        SimpleDateFormat formatoEntrada = new SimpleDateFormat("dd/MM/yyyy");
        formatoEntrada.setLenient(false);

        java.util.Date dataIniUtil;
        java.util.Date dataFimUtil;
        try {
            dataIniUtil = formatoEntrada.parse(jFormattedTextFieldDataIni.getText().trim());
            dataFimUtil = formatoEntrada.parse(jFormattedTextFieldDataFim.getText().trim());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Formato de data inválido (use dd/MM/yyyy)");
            Logger.getLogger(Tela_de_Consulta_RD.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }

        // Determina o campo de data
        String campoData;
        if (rbVcto.isSelected()) {
            campoData = "dtvcto";
        } else if (rbCompetencia.isSelected()) {
            campoData = "dtemi";
        } else {
            campoData = "dtapr";
        }

        // ???????????????????????????????????????????????
        // 1. Totais do período atual (para percentuais)
        // ???????????????????????????????????????????????
        try (Connection conTot = Conexao.faz_conexao(); PreparedStatement stmtTot = conTot.prepareStatement(
                "SELECT nome_s, SUM(valor) AS total "
                + "FROM viewmovrd "
                + "WHERE " + campoData + " BETWEEN ? AND ? "
                + "  AND nome_p <> 'NULO' "
                + "  AND classif NOT IN ('3.003.005', '4.008.011') "
                + "GROUP BY nome_s"
        )) {

            stmtTot.setDate(1, new java.sql.Date(dataIniUtil.getTime()));
            stmtTot.setDate(2, new java.sql.Date(dataFimUtil.getTime()));

            try (ResultSet rsTot = stmtTot.executeQuery()) {
                while (rsTot.next()) {
                    String nomeS = rsTot.getString("nome_s");
                    double valor = rsTot.getDouble("total");

                    if ("RECEITAS OPERACIONAIS".equalsIgnoreCase(nomeS)) {
                        receitasOperacionais += valor;
                        totalReceitas += valor;
                    } else if ("RECEITAS NÃO OPERACIONAIS".equalsIgnoreCase(nomeS)
                            || "RECEITAS NAO OPERACIONAIS".equalsIgnoreCase(nomeS)) {
                        receitasNaoOperacionais += valor;
                        totalReceitas += valor;
                    } else if ("DESPESAS OPERACIONAIS".equalsIgnoreCase(nomeS)) {
                        despesasOperacionais += valor;
                        totalDespesas += valor;
                    } else if ("DESPESAS NÃO OPERACIONAIS".equalsIgnoreCase(nomeS)
                            || "DESPESAS NAO OPERACIONAIS".equalsIgnoreCase(nomeS)) {
                        despesasNaoOperacionais += valor;
                        totalDespesas += valor;
                    }
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(Tela_de_Consulta_RD.class.getName()).log(Level.SEVERE, "Erro ao obter totais do período", e);
            JOptionPane.showMessageDialog(null, "Erro ao consultar totais do período.");
            return;
        }

        // ???????????????????????????????????????????????
        // 2. Percentuais históricos (últimos 24 meses)
        // ???????????????????????????????????????????????
        Map<String, Double> mediaHistoricaPorConta = new HashMap<>();
        try (Connection conHist = Conexao.faz_conexao()) {

            LocalDate dataFim = dataFimUtil.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate dataIniHist = dataFim.minusMonths(24);
            Date sqlDataIniHist = Date.valueOf(dataIniHist);

            // Totais históricos gerais
            double totalRecHist = 0.0;
            double totalDespHist = 0.0;

            try (PreparedStatement stmtTotHist = conHist.prepareStatement(
                    "SELECT nome_s, SUM(valor) AS total "
                    + "FROM viewmovrd "
                    + "WHERE nome_p <> 'NULO' "
                    + "  AND " + campoData + " >= ? "
                    + "GROUP BY nome_s")) {

                stmtTotHist.setDate(1, sqlDataIniHist);
                try (ResultSet rs = stmtTotHist.executeQuery()) {
                    while (rs.next()) {
                        String nomeS = rs.getString("nome_s");
                        double tot = rs.getDouble("total");
                        if (nomeS != null) {
                            if (nomeS.toUpperCase().contains("RECEITAS")) {
                                totalRecHist += tot;
                            } else if (nomeS.toUpperCase().contains("DESPESAS")) {
                                totalDespHist += tot;
                            }
                        }
                    }
                }
            }

            // Média histórica por conta
            try (PreparedStatement stmtHist = conHist.prepareStatement(
                    "SELECT nome_c, nome_s, SUM(valor) AS total "
                    + "FROM viewmovrd "
                    + "WHERE nome_p <> 'NULO' "
                    + "  AND " + campoData + " >= ? "
                    + "GROUP BY nome_c, nome_s")) {

                stmtHist.setDate(1, sqlDataIniHist);
                try (ResultSet rsHist = stmtHist.executeQuery()) {
                    while (rsHist.next()) {
                        String nomeC = rsHist.getString("nome_c");
                        double totalConta = rsHist.getDouble("total");
                        double percHist = 0.0;

                        if (totalConta > 0 && totalRecHist != 0) {
                            percHist = (totalConta / totalRecHist) * 100;
                        } else if (totalConta < 0 && totalDespHist != 0) {
                            percHist = (totalConta / totalDespHist) * 100;
                        }

                        mediaHistoricaPorConta.put(nomeC, percHist);
                    }
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(Tela_de_Consulta_RD.class.getName()).log(Level.SEVERE, "Erro ao consultar histórico 24 meses", e);
            // Aqui você pode decidir se continua ou retorna
            // Por enquanto continua, mas com histórico zerado
        }

        // ???????????????????????????????????????????????
        // 3. Consulta principal + preenchimento da tabela
        // ???????????????????????????????????????????????
        try (Connection con = Conexao.faz_conexao(); PreparedStatement stmt = con.prepareStatement(
                "SELECT nome_p, nome_s, nome_c, SUM(valor) AS total "
                + "FROM viewmovrd "
                + "WHERE " + campoData + " BETWEEN ? AND ? "
                + "  AND nome_p <> 'NULO' "
                + "  AND classif NOT IN ('3.003.005','4.008.011') "
                + "GROUP BY nome_p, nome_s, nome_c, classif "
                + "ORDER BY classif"
        )) {

            stmt.setDate(1, new java.sql.Date(dataIniUtil.getTime()));
            stmt.setDate(2, new java.sql.Date(dataFimUtil.getTime()));

            DefaultTableModel modelo = new DefaultTableModel(
                    new Object[]{"PRINCIPAL", "GRUPO", "CONTA", "TOTAL", "ACUMULADO", "PERCENTUAL", "MÉDIA HISTÓRICA (%)"},
                    0
            );
            jTablePesquisa.setModel(modelo);

            try (ResultSet rs = stmt.executeQuery()) {

                jTablePesquisa.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                jTablePesquisa.getColumnModel().getColumn(0).setPreferredWidth(100);
                jTablePesquisa.getColumnModel().getColumn(1).setPreferredWidth(250);
                jTablePesquisa.getColumnModel().getColumn(2).setPreferredWidth(370);
                jTablePesquisa.getColumnModel().getColumn(3).setPreferredWidth(130);
                jTablePesquisa.getColumnModel().getColumn(4).setPreferredWidth(100);
                jTablePesquisa.getColumnModel().getColumn(5).setPreferredWidth(100);
                jTablePesquisa.getColumnModel().getColumn(6).setPreferredWidth(140);

                DefaultTableCellRenderer rightAlign = new DefaultTableCellRenderer();
                rightAlign.setHorizontalAlignment(SwingConstants.RIGHT);

                jTablePesquisa.getColumnModel().getColumn(3).setCellRenderer(rightAlign);
                jTablePesquisa.getColumnModel().getColumn(4).setCellRenderer(rightAlign);

                DecimalFormat df = new DecimalFormat("#,##0.00");
                DecimalFormat dp = new DecimalFormat("0.0000");

                double acumulado = 0.0;
                String ultimoPrin = "";
                String prin = "";
                String grupo = "";

                while (rs.next()) {
                    String nomeP = rs.getString("nome_p");
                    String nomeS = rs.getString("nome_s");
                    String nomeC = rs.getString("nome_c");
                    double valor = rs.getDouble("total");

                    double percentual = 0.0;
                    if (valor > 0 && totalReceitas != 0) {
                        percentual = (valor / totalReceitas) * 100;
                    } else if (valor < 0 && totalDespesas != 0) {
                        percentual = (valor / totalDespesas) * 100;
                    }

                    acumulado += valor;

                    // Linha separadora entre grupos PRINCIPAL
                    if (!ultimoPrin.isEmpty() && !ultimoPrin.equals(nomeP)) {
                        modelo.addRow(new Object[]{"", "", "", "", "", "", ""});
                    }

                    prin = prin.equals(nomeP) ? " " : nomeP;
                    grupo = grupo.equals(nomeS) ? " " : nomeS;

                    double histPerc = mediaHistoricaPorConta.getOrDefault(nomeC, 0.0);

                    modelo.addRow(new Object[]{
                        prin,
                        grupo,
                        nomeC,
                        df.format(valor),
                        df.format(acumulado),
                        dp.format(percentual),
                        dp.format(histPerc)
                    });

                    ultimoPrin = nomeP;
                    prin = nomeP;
                    grupo = nomeS;
                }

                // Linhas de resumo (igual à sua lógica original + MySQL)
                modelo.addRow(new Object[]{"", "", "", "", "", "", ""});
                String taxa = totalReceitas != 0 ? dp.format((-totalDespesas / totalReceitas) * 100) : "?";
                modelo.addRow(new Object[]{"", "", "TAXA DE CONSUMO", "", "", taxa, ""});

                long diasPeriodo = ChronoUnit.DAYS.between(
                        dataIniUtil.toInstant().atZone(ZoneId.systemDefault()).toLocalDate(),
                        dataFimUtil.toInstant().atZone(ZoneId.systemDefault()).toLocalDate()
                ) + 1;

                double recDiaria = totalReceitas != 0 ? totalReceitas / diasPeriodo : 0.0;
                int diasReceita = (int) Math.round(recDiaria);
                double diasConsumidos = recDiaria != 0 ? totalDespesas / recDiaria : 0.0;
                int diasDespesa = (int) Math.round(diasConsumidos);

                modelo.addRow(new Object[]{"", "", "", "", "", "", ""});
                modelo.addRow(new Object[]{"", "", "TOTAL DIAS NO PERÍODO: " + diasPeriodo + " dias", "", "", "", ""});
                modelo.addRow(new Object[]{"", "", "DIAS EQUIVALENTES CONSUMIDOS: " + (-diasDespesa) + " dias", "", "", "", ""});

                // Resumo final das categorias
                modelo.addRow(new Object[]{"", "", "", "", "", "", ""});
                modelo.addRow(new Object[]{"", "", "RECEITAS OPERACIONAIS", "", df.format(receitasOperacionais), "", ""});
                modelo.addRow(new Object[]{"", "", "DESPESAS OPERACIONAIS", "", df.format(despesasOperacionais), "", ""});
                modelo.addRow(new Object[]{"", "", "RESULTADO OPERACIONAL", "", df.format(receitasOperacionais + despesasOperacionais), "", ""});

                modelo.addRow(new Object[]{"", "", "", "", "", "", ""});
                modelo.addRow(new Object[]{"", "", "RECEITAS NÃO OPERACIONAIS", "", df.format(receitasNaoOperacionais), "", ""});
                modelo.addRow(new Object[]{"", "", "DESPESAS NÃO OPERACIONAIS", "", df.format(despesasNaoOperacionais), "", ""});
                modelo.addRow(new Object[]{"", "", "RESULTADO NÃO OPERACIONAL", "", df.format(receitasNaoOperacionais + despesasNaoOperacionais), "", ""});

                modelo.addRow(new Object[]{"", "", "", "", "", "", ""});
                modelo.addRow(new Object[]{"", "", "RESULTADO FINAL DO PERÍODO:", "",
                    df.format(receitasOperacionais + despesasOperacionais + receitasNaoOperacionais + despesasNaoOperacionais),
                    "", ""});

                // Renderers personalizados
                jTablePesquisa.getColumnModel().getColumn(3).setCellRenderer(new CustomTableCellRenderer(3, 11, false));
                jTablePesquisa.getColumnModel().getColumn(4).setCellRenderer(new CustomTableCellRenderer(4, 11, false));

                PercentualRenderer percRenderer = new PercentualRenderer();
                jTablePesquisa.getColumnModel().getColumn(5).setCellRenderer(percRenderer);
                jTablePesquisa.getColumnModel().getColumn(6).setCellRenderer(percRenderer);
            }

        } catch (SQLException e) {
            Logger.getLogger(Tela_de_Consulta_RD.class.getName()).log(Level.SEVERE, "Erro na consulta principal", e);
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados da consulta.");
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonPLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPLimparActionPerformed
        ((DefaultTableModel) jTablePesquisa.getModel()).setRowCount(0);
        jFormattedTextFieldDataIni.setText("");
        jFormattedTextFieldDataFim.setText("");
    }//GEN-LAST:event_jButtonPLimparActionPerformed

    private void jButtonPImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPImprimirActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        
        java.util.Date date = new java.util.Date();
        
        String infDt = dateFormat.format(date);

        // Pegar as datas dos campos
        String dataInicial = jFormattedTextFieldDataIni.getText();
        String dataFinal = jFormattedTextFieldDataFim.getText();

        PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
        set.add(OrientationRequested.LANDSCAPE);

        // Cabeçalho com as datas do período
        MessageFormat cabecalho = new MessageFormat(
                "Receitas X Despesas - Período: " + dataInicial + " a " + dataFinal);

        MessageFormat rodape = new MessageFormat("Página {0,number,integer}" + " - Impressão: " + infDt);

        try {
            jTablePesquisa.print(JTable.PrintMode.FIT_WIDTH, cabecalho, rodape, false, set, false);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Erro ao imprimir!!! %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jButtonPImprimirActionPerformed

    private void jButtonGraficoDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGraficoDespActionPerformed
        try {
            PieChartDesp desp = new PieChartDesp();
        } catch (Exception ex) {
            Logger.getLogger(Tela_de_Consulta_RD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonGraficoDespActionPerformed

    private void jButtonGraficoRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGraficoRecActionPerformed
        // TODO add your handling code here:
        try {
            PieChartRec rec = new PieChartRec();
        } catch (Exception ex) {
            Logger.getLogger(Tela_de_Consulta_RD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonGraficoRecActionPerformed

    private void jButtonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Salvar como...");
        int userSelection = fileChooser.showSaveDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String path = fileChooser.getSelectedFile().getAbsolutePath();
            if (!path.endsWith(".xlsx")) {
                path += ".xlsx";
            }
            try {
                ExportToExcel exporter = new ExportToExcel();
                exporter.exportTable(jTablePesquisa, path);
                JOptionPane.showMessageDialog(null, "Arquivo Excel " + path + " foi gerado com sucesso!");
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao exportar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Consulta_RD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Consulta_RD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Consulta_RD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Consulta_RD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Tela_de_Consulta_RD().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Tela_de_Consulta_RD.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoRegime;
    private javax.swing.JButton jButtonExportar;
    private javax.swing.JButton jButtonGraficoDesp;
    private javax.swing.JButton jButtonGraficoRec;
    private javax.swing.JButton jButtonPFechar;
    private javax.swing.JButton jButtonPImprimir;
    private javax.swing.JButton jButtonPLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataFim;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataIni;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelRegime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisa;
    private javax.swing.JRadioButton rbCaixa;
    private javax.swing.JRadioButton rbCompetencia;
    private javax.swing.JRadioButton rbVcto;
    // End of variables declaration//GEN-END:variables

    public class PieChartDesp extends JFrame {

        JFreeChart chart;

        public PieChartDesp() throws ParseException {
            super("Gráfico Despesas no Período");
            setSize(1000, 800);
            setLayout(null);
            setResizable(false);
            setLocationRelativeTo(null);
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            crearGraficoD();
            ChartPanel panel = new ChartPanel(chart, false);
            panel.setBounds(10, 20, 960, 720);
            add(panel);
            setVisible(true);
        }

        public void crearGraficoD() throws ParseException {
            ArrayList<String> labels = new ArrayList<>();
            DecimalFormat df = new DecimalFormat("#,###.00");
            ArrayList<Double> values = new ArrayList<>();
            for (int i = 0; i < jTablePesquisa.getRowCount(); i++) {
                String value = (String) jTablePesquisa.getValueAt(i, 3);
                if (value != null && !value.trim().isEmpty()) {
                    labels.add((String) jTablePesquisa.getValueAt(i, 2));
                    values.add(df.parse(value).doubleValue() * -1);
                }
            }
            DefaultPieDataset dataset = new DefaultPieDataset();
            for (int i = 0; i < labels.size(); i++) {
                dataset.setValue(labels.get(i), values.get(i));
            }
            chart = ChartFactory.createPieChart(
                    "Gráfico de Despesas por Período", //Titulo do grafico
                    dataset, //data
                    true, //Legenda
                    true,
                    false);
            //pintura
            chart.setBackgroundPaint(Color.ORANGE);//Cor do funde da janela
            chart.getTitle().setPaint(Color.blue); //Dar cor ao titulo
            PiePlot plot = (PiePlot) chart.getPlot();
            plot.setLabelBackgroundPaint(Color.ORANGE);//Cor das etiquetas
            plot.setBackgroundPaint(Color.WHITE); //Cor do fundo do grafico        
            this.dispose();
        }
    }

    public class PieChartRec extends JFrame {

        JFreeChart chart;

        public PieChartRec() throws ParseException {
            super("Gráfico Receitas no Período");
            setSize(1000, 800);
            setLayout(null);
            setResizable(false);
            setLocationRelativeTo(null);
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            crearGraficoR();
            ChartPanel panel = new ChartPanel(chart, false);
            panel.setBounds(10, 20, 960, 720);
            add(panel);
            setVisible(true);
        }

        public void crearGraficoR() throws ParseException {
            ArrayList<String> labels = new ArrayList<>();
            DecimalFormat df = new DecimalFormat("#,###.00");
            ArrayList<Double> values = new ArrayList<>();
            for (int i = 0; i < jTablePesquisa.getRowCount(); i++) {
                String value = (String) jTablePesquisa.getValueAt(i, 3);
                if (value != null && !value.trim().isEmpty()) {
                    labels.add((String) jTablePesquisa.getValueAt(i, 2));
                    values.add(df.parse(value).doubleValue());
                }
            }
            DefaultPieDataset dataset = new DefaultPieDataset();
            for (int i = 0; i < labels.size(); i++) {
                dataset.setValue(labels.get(i), values.get(i));
            }
            chart = ChartFactory.createPieChart(
                    "Gráfico de Receitas por Período", //Título do Gráfico
                    dataset, //data
                    true, //Legenda
                    true,
                    false);
            //pintura
            chart.setBackgroundPaint(Color.ORANGE);//Cor de fundo da janela
            chart.getTitle().setPaint(Color.blue); //Dar cor ao título
            PiePlot plot = (PiePlot) chart.getPlot();
            plot.setLabelBackgroundPaint(Color.ORANGE);//Cor das etiquetas
            plot.setBackgroundPaint(Color.WHITE); //Cor de fundo do gráfico        
            this.dispose();
        }
    }
}
