package view;

import utilitarios.Conexao;
import classes.CustomTableCellRenderer;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class Tela_de_Consulta_Contas extends javax.swing.JFrame {

    CarregarCbx3 r3 = new CarregarCbx3(); //Carrega combobox de ClassificaÃ§Ã£o por Conta        

    public Tela_de_Consulta_Contas() throws SQLException {
        initComponents();
        r3.CarregarCbx3("gpprincipal", "nome_c", cbxClass);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxClass = new javax.swing.JComboBox<>();
        jFormattedTextFieldDataIni = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldDataFim = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSaldoAnterior = new javax.swing.JTextField();
        tfClass = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonPImprimir = new javax.swing.JButton();
        jButtonPLimpar = new javax.swing.JButton();
        jButtonPFechar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setText("Conta para pesquisa:");

        jLabel2.setText("Período de Vcto. à pesquisar");

        cbxClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbxClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClassActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldDataIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("até");

        try {
            jFormattedTextFieldDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reg.", "Recurso", "vRecurso", "Favorecido", "vFavorecido", "Lançto.", "Emissão", "Vencimento", "Documento", "Classif.", "Descrição", "Valor", "Apresent.", "Status", "Prev.", "Saldo"
            }
        ));
        jTablePesquisa.setSelectionBackground(new java.awt.Color(255, 255, 204));
        jTablePesquisa.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTablePesquisa);

        jLabel4.setText("Saldo Anterior:");

        jTextFieldSaldoAnterior.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSaldoAnterior.setEnabled(false);

        tfClass.setEnabled(false);
        tfClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxClass, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSaldoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1214, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbxClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldSaldoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonPImprimir.setText("Imprimir");
        jButtonPImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPImprimirActionPerformed(evt);
            }
        });

        jButtonPLimpar.setText("Limpar");
        jButtonPLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPLimparActionPerformed(evt);
            }
        });

        jButtonPFechar.setText("Fechar");
        jButtonPFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(349, 349, 349))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jButtonPImprimir)
                    .addComponent(jButtonPLimpar)
                    .addComponent(jButtonPFechar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CONSULTA - CLASSIFICAÇÃO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfClassActionPerformed

    private void cbxClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClassActionPerformed
        if (cbxClass.getSelectedIndex() > 0) {
            String selectedValue = cbxClass.getSelectedItem().toString();//.substring(11);
            var texto = selectedValue.length();
            texto = texto - 9;
            selectedValue = cbxClass.getSelectedItem().toString().substring(texto);
            tfClass.setText(selectedValue);
        }
    }//GEN-LAST:event_cbxClassActionPerformed

    private void jButtonPFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPFecharActionPerformed

        try {
            TelaPrincipal exibir;
            exibir = new TelaPrincipal();
            exibir.setVisible(true);
            setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(Tela_de_Consulta_Contas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPFecharActionPerformed

    @SuppressWarnings("unchecked")
    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        if (jFormattedTextFieldDataIni.getText().trim().length() == 4) {
            JOptionPane.showMessageDialog(null, "Atenção! Favor preencher o campo de data inicial.");
        } else if (jFormattedTextFieldDataFim.getText().trim().length() == 4) {
            JOptionPane.showMessageDialog(null, "Atenção! Favor preencher o campo de data final.");
        } else {
            jTextFieldSaldoAnterior.setText("0");
            String ssa = jTextFieldSaldoAnterior.getText();
            double sa = Double.valueOf(ssa).doubleValue();
            DecimalFormat dec = new DecimalFormat("#,##0.00");
            jTextFieldSaldoAnterior.setText(dec.format(sa));
            try {
                SimpleDateFormat formato_data = new SimpleDateFormat("dd/MM/yyyy");
                DecimalFormat df = new DecimalFormat("#,##0.00");
                Connection con;
                con = Conexao.faz_conexao();
                //String sql = "SELECT * FROM tbmovimento WHERE dtVcto BETWEEN ? AND ? AND classif = ? ORDER BY dtVcto";
                String sql = "SELECT * FROM \"tbmovimento\" WHERE \"dtvcto\" BETWEEN ? AND ? AND \"classif\" = ? ORDER BY \"dtvcto\"";
                PreparedStatement stmt = con.prepareStatement(sql);
                java.util.Date data_i = null;
                try {
                    data_i = formato_data.parse(jFormattedTextFieldDataIni.getText());
                } catch (ParseException ex) {
                    System.out.println("Problema ao pegar data inicial: " + ex);
                }
                stmt.setDate(1, new java.sql.Date(data_i.getTime()));
                java.util.Date data_f = null;
                try {
                    data_f = formato_data.parse(jFormattedTextFieldDataFim.getText());
                } catch (ParseException ex) {
                    System.out.println("Problema ao pegar data Final: " + ex);
                }
                stmt.setDate(2, new java.sql.Date(data_f.getTime()));
                stmt.setString(3, tfClass.getText());
                ResultSet rs = stmt.executeQuery();
                DefaultTableModel modelo = (DefaultTableModel) jTablePesquisa.getModel();
                modelo.setNumRows(0);
                //jTablePesquisa.setRowSorter(new TableRowSorter(modelo)); // Organiza tabela clicando no tÃ­tulo da coluna
                jTablePesquisa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(0)).setPreferredWidth(40); //idMov
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(1)).setPreferredWidth(60); //recurso
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(2)).setPreferredWidth(0); //70 vrecurso 
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(3)).setPreferredWidth(50); //50 clifor
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(4)).setPreferredWidth(0); //75 vCliFor
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(5)).setPreferredWidth(75); //dtlancto
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(6)).setPreferredWidth(75); //dtEmi
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(7)).setPreferredWidth(75); //dtVcto
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(8)).setPreferredWidth(110); //documento
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(9)).setPreferredWidth(70);  //classif
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(10)).setPreferredWidth(325); //Descr
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(11)).setPreferredWidth(80);  //Valor
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(12)).setPreferredWidth(100); //dtApr
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(13)).setPreferredWidth(30); //40 statusMov
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(14)).setPreferredWidth(20); //30 Prev
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(15)).setPreferredWidth(80); //Saldo
                DefaultTableCellRenderer tab = new DefaultTableCellRenderer();
                tab.setHorizontalAlignment(SwingConstants.RIGHT);
                jTablePesquisa.getColumnModel().getColumn(11).setCellRenderer(tab);
                jTablePesquisa.getColumnModel().getColumn(15).setCellRenderer(tab);

                jTablePesquisa.getColumnModel().getColumn(2).setMinWidth(0); // Ocultando as colunas
                jTablePesquisa.getColumnModel().getColumn(2).setMaxWidth(0); // Ocultando as colunas

                jTablePesquisa.getColumnModel().getColumn(4).setMinWidth(0); // Ocultando as colunas
                jTablePesquisa.getColumnModel().getColumn(4).setMaxWidth(0); // Ocultando as colunas

                while (rs.next()) {
                    sa = sa + rs.getDouble("valor");
                    Date Apre = rs.getDate("dtapr");
                    String AprFormatada;
                    if (Apre == null && !"".equals(Apre)) {
                        AprFormatada = null;
                    } else if (Apre.equals("  /  /    ")) {
                        AprFormatada = null;
                    } else if (Apre.equals("")) {
                        AprFormatada = null;
                    } else {
                        AprFormatada = formato_data.format(Apre);
                    }
                    modelo.addRow(new Object[]{rs.getString("idmov"),
                        rs.getString("recurso"),
                        rs.getString("vrecurso"),
                        rs.getString("clifor"),
                        rs.getString("vclifor"),
                        formato_data.format(rs.getDate("dtlancto")),
                        formato_data.format(rs.getDate("dtemi")),
                        formato_data.format(rs.getDate("dtvcto")),
                        rs.getString("documento"),
                        rs.getString("classif"),
                        rs.getString("descr"),
                        df.format(rs.getDouble("valor")),
                        AprFormatada,
                        rs.getString("statusmov"),
                        rs.getString("prev"),
                        df.format(sa),});
                }
                
                //Parâmetros Coluna da jTable, Tamanho da Fonte, se é data (true ou false).
                jTablePesquisa.getColumnModel().getColumn(11).setCellRenderer(new CustomTableCellRenderer(11, 11, false));
                jTablePesquisa.getColumnModel().getColumn(15).setCellRenderer(new CustomTableCellRenderer(15, 11, false));
                
                rs.close();
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(Tela_de_Mov.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonPLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPLimparActionPerformed
        ((DefaultTableModel) jTablePesquisa.getModel()).setRowCount(0);
        tfClass.setText("");
        jFormattedTextFieldDataIni.setText("");
        jFormattedTextFieldDataFim.setText("");
        jTextFieldSaldoAnterior.setText("");
        cbxClass.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonPLimparActionPerformed

    private void jButtonPImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPImprimirActionPerformed
        MessageFormat cabecalho = new MessageFormat("Relatório de Consulta - Classificação");
        MessageFormat rodape = new MessageFormat("Página {0,number,integer}");
        try {
            jTablePesquisa.print(JTable.PrintMode.FIT_WIDTH, cabecalho, rodape);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Erro ao imprimir!!! %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jButtonPImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Consulta_Contas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Consulta_Contas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Consulta_Contas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Consulta_Contas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Tela_de_Consulta_Contas().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Tela_de_Consulta_Contas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    /*private void PegaSaldoAnterior() {
        DecimalFormat dec = new DecimalFormat("#,##0.00");
        String sql = "SELECT SUM(Valor) FROM tbmovimento WHERE dtVcto < ? AND classif = ?";
        Connection con;
        try {
            con = Conexao.faz_conexao();
            PreparedStatement stt = con.prepareStatement(sql);
            SimpleDateFormat formato_data = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date data_c = formato_data.parse(jFormattedTextFieldDataIni.getText());
            stt.setDate(1, new java.sql.Date(data_c.getTime()));
            stt.setString(2, tfClass.getText());
            ResultSet rsoma = stt.executeQuery();
            double somaval = 0;
            while (rsoma.next()) {
                somaval = rsoma.getDouble(1);
            }
            jTextFieldSaldoAnterior.setText(String.valueOf(somaval));
            stt.close();
            rsoma.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Tela_de_Consulta_Contas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Tela_de_Consulta_Contas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxClass;
    private javax.swing.JButton jButtonPFechar;
    private javax.swing.JButton jButtonPImprimir;
    private javax.swing.JButton jButtonPLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataFim;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataIni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisa;
    private javax.swing.JTextField jTextFieldSaldoAnterior;
    private javax.swing.JTextField tfClass;
    // End of variables declaration//GEN-END:variables

    private static class CarregarCbx3 {
        @SuppressWarnings({"empty-statement", "unchecked"})
        public void CarregarCbx3(String tabela, String valor, JComboBox combo) throws SQLException {
            //String sql = "Select * FROM " + tabela + " WHERE nome_C <> '-' ";
            String sql = "SELECT \"cod_geral\", \"nome_p\", \"nome_s\", \"nome_c\" FROM \"" + tabela + "\" WHERE \"nome_c\" <> '-' ORDER BY \"nome_c\"";
            Connection con = Conexao.faz_conexao();
            try {
                PreparedStatement stmt = con.prepareStatement(sql);
                ResultSet rs = stmt.executeQuery();
                while (rs.next()) {
                    combo.addItem(rs.getString(valor) + "-" + (rs.getString("cod_geral")));
                }
                rs.close();
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(Tela_de_Mov.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
