package view;

import utilitarios.Conexao;
import classes.ExportToExcel;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import static javax.swing.SwingConstants.RIGHT;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.labels.StandardXYToolTipGenerator;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

public class Tela_de_Consulta_RC extends javax.swing.JFrame {

    // Arrays para armazenar os totais de receitas, despesas e resultados
    private double[] receitasMensais = new double[12];
    private double[] despesasMensais = new double[12];
    private double[] resultadosMensais = new double[12];
    private double[] saldoFinalMensal = new double[12];

    // === VARIÁVEIS GLOBAIS PARA TRANSPORTE E GRÁFICO ===
    private static String ultimoPeriodoFim = "";
    private static double saldoTransportado = 0.0;

    private double saldoInicialEmprestimo = 0.0;
    private double saldoTransportadoEmprestimo = 0.0;

    public Tela_de_Consulta_RC() throws SQLException {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupStatus = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldDataIni = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldDataFim = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButtonAnual = new javax.swing.JButton();
        jPanelStatus = new javax.swing.JPanel();
        jRadioButtonTodos = new javax.swing.JRadioButton();
        jRadioButtonConf = new javax.swing.JRadioButton();
        jRadioButtonPrev = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonPImprimir = new javax.swing.JButton();
        jButtonPLimpar = new javax.swing.JButton();
        jButtonPFechar = new javax.swing.JButton();
        jButtonGrafico = new javax.swing.JButton();
        jButtonExportar = new javax.swing.JButton();
        jButtonSalvaprev = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel2.setText("   PERÍODO DE VENCIMENTOS     de");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        try {
            jFormattedTextFieldDataIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("até");

        try {
            jFormattedTextFieldDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CONSULTA - REFERÊNCIA CRUZADA");

        jTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contas", "janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro", "Total"
            }
        ));
        jTablePesquisa.setSelectionBackground(new java.awt.Color(255, 255, 204));
        jTablePesquisa.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jTablePesquisa);

        jLabel4.setText("ou");

        jButtonAnual.setText("Anual");
        jButtonAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnualActionPerformed(evt);
            }
        });

        buttonGroupStatus.add(jRadioButtonTodos);
        jRadioButtonTodos.setText("Todos");

        buttonGroupStatus.add(jRadioButtonConf);
        jRadioButtonConf.setText("Confirmados");

        buttonGroupStatus.add(jRadioButtonPrev);
        jRadioButtonPrev.setText("Previstos");

        javax.swing.GroupLayout jPanelStatusLayout = new javax.swing.GroupLayout(jPanelStatus);
        jPanelStatus.setLayout(jPanelStatusLayout);
        jPanelStatusLayout.setHorizontalGroup(
            jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonTodos)
                .addGap(26, 26, 26)
                .addComponent(jRadioButtonConf)
                .addGap(28, 28, 28)
                .addComponent(jRadioButtonPrev)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelStatusLayout.setVerticalGroup(
            jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonTodos)
                    .addComponent(jRadioButtonConf)
                    .addComponent(jRadioButtonPrev))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAnual)
                                .addGap(136, 136, 136)
                                .addComponent(jPanelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAnual)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jPanelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonPImprimir.setText("Imprimir");
        jButtonPImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonPImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPImprimirActionPerformed(evt);
            }
        });

        jButtonPLimpar.setText("Limpar");
        jButtonPLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonPLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPLimparActionPerformed(evt);
            }
        });

        jButtonPFechar.setText("Fechar");
        jButtonPFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonPFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPFecharActionPerformed(evt);
            }
        });

        jButtonGrafico.setText("Gráfico");
        jButtonGrafico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGraficoActionPerformed(evt);
            }
        });

        jButtonExportar.setText("Exportar para Excel");
        jButtonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportarActionPerformed(evt);
            }
        });

        jButtonSalvaprev.setText("Salva Previstos");
        jButtonSalvaprev.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSalvaprev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvaprevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalvaprev, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPImprimir)
                    .addComponent(jButtonPLimpar)
                    .addComponent(jButtonPFechar)
                    .addComponent(jButtonGrafico)
                    .addComponent(jButtonExportar)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jButtonSalvaprev)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonPFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPFecharActionPerformed
        try {
            TelaPrincipal exibir;
            exibir = new TelaPrincipal();
            exibir.setVisible(true);
            setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(Tela_de_Consulta_RC.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPFecharActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

        // === VALIDAÇÃO DOS CAMPOS DE DATA ===
        if (jFormattedTextFieldDataIni.getText().trim().length() == 4) {
            JOptionPane.showMessageDialog(null, "Atenção! Favor preencher o campo de data inicial.");
            return;
        }
        if (jFormattedTextFieldDataFim.getText().trim().length() == 4) {
            JOptionPane.showMessageDialog(null, "Atenção! Favor preencher o campo de data final.");
            return;
        }

        double saldoInicialPeriodo = 0;
        double pegaSaldoFinal = 0;

        // === DECLARAÇÕES FORA DO TRY ===
        Connection con = null;
        PreparedStatement stmt = null, stmtReceitas = null, stmtDespesas = null;
        PreparedStatement stmtEmprestimosObtidos = null, stmtEmprestimosPagos = null;
        PreparedStatement stmtSaldo = null;
        ResultSet rs = null, rsReceitas = null, rsDespesas = null;
        ResultSet rsEmprestimosObtidos = null, rsEmprestimosPagos = null;
        ResultSet rsSaldo = null;

        try {
            // === FORMATAR DATAS ===
            SimpleDateFormat formatoEntrada = new SimpleDateFormat("dd/MM/yyyy");
            String dataIniStr = jFormattedTextFieldDataIni.getText().trim();
            String dataFimStr = jFormattedTextFieldDataFim.getText().trim();

            // Datas em formato java.util.Date para lógica de calendário
            Date dataIni = formatoEntrada.parse(dataIniStr);
            Date dataFim = formatoEntrada.parse(dataFimStr);
            Date dataHoje = new Date();

            // Datas em formato java.sql.Date para o JDBC (PostgreSQL)
            java.sql.Date sqlDataIni = new java.sql.Date(dataIni.getTime());
            java.sql.Date sqlDataFim = new java.sql.Date(dataFim.getTime());
            java.sql.Date sqlDataHoje = new java.sql.Date(dataHoje.getTime());

            // === FORMATADOR DE MOEDA ===
            DecimalFormatSymbols symbols = new DecimalFormatSymbols();
            symbols.setDecimalSeparator(',');
            symbols.setGroupingSeparator('.');
            DecimalFormat dfCurrency = new DecimalFormat("#,##0.00", symbols);

            
            // === DEFINIÇÃO DINÂMICA DO FILTRO DE STATUS ===
            String filtroStatus = "";
            if (jRadioButtonConf.isSelected()) {
                filtroStatus = " AND prev = 'V' ";
            } else if (jRadioButtonPrev.isSelected()) {
                filtroStatus = " AND prev = 'F' ";
            }
            
            // === ABRIR CONEXÃO ===
            con = Conexao.faz_conexao();

            // === 1. BUSCAR SALDO ANTERIOR (ATÉ O DIA ANTES DO PERÍODO) ===
            Calendar cal = Calendar.getInstance();
            cal.setTime(dataIni);
            cal.add(Calendar.DAY_OF_MONTH, -1);

            // Data do dia anterior para o banco
            java.sql.Date sqlDataDiaAnterior = new java.sql.Date(cal.getTimeInMillis());

            double saldoCaixaBancoAnterior = 0.0;
            double saldoEmprestimoAnterior = 0.0;

            // === DECISÃO: Período já passou ou é futuro? ===
            boolean periodoNoPassado = cal.getTime().before(dataHoje);

            if (periodoNoPassado) {
                // === PERÍODO NO PASSADO ===
                String sqlSaldoCaixa = "SELECT COALESCE(SUM(valor), 0) AS saldo "
                        + "FROM tbmovimento "
                        + "WHERE dtlancto <= ? "
                        + "  AND vrecurso IN ('1.001.001', '1.001.002', '1.003.001', '2.001.004') "
                        + "  AND recurso NOT IN ('0079', '0022') "
                        + "  AND dtApr IS NOT NULL;";

                String sqlSaldoEmprestimo = "SELECT COALESCE(SUM(valor), 0) AS saldo "
                        + "FROM tbmovimento WHERE recurso = '0080' AND dtlancto <= ?;";

                // Executa Saldo Caixa
                stmtSaldo = con.prepareStatement(sqlSaldoCaixa);
                stmtSaldo.setDate(1, sqlDataDiaAnterior);
                rsSaldo = stmtSaldo.executeQuery();
                if (rsSaldo.next()) {
                    saldoCaixaBancoAnterior = rsSaldo.getDouble("saldo");
                }
                rsSaldo.close();
                stmtSaldo.close();

                // Executa Saldo Empréstimo
                stmtSaldo = con.prepareStatement(sqlSaldoEmprestimo);
                stmtSaldo.setDate(1, sqlDataDiaAnterior);
                rsSaldo = stmtSaldo.executeQuery();
                if (rsSaldo.next()) {
                    saldoEmprestimoAnterior = rsSaldo.getDouble("saldo");
                }
                rsSaldo.close();
                stmtSaldo.close();

            } else {
                // === PERÍODO ATUAL OU FUTURO ===
                // C1 - Saldo efetivo consolidado até hoje
                String sqlC1 = "SELECT COALESCE(SUM(valor), 0) AS saldo "
                        + "FROM tbmovimento "
                        + "WHERE vrecurso IN ('1.001.001','1.001.002','1.003.001','2.001.004') "
                        + "  AND dtlancto <= ? "
                        + "  AND dtApr IS NOT NULL "
                        + "  AND recurso NOT IN ('0079','0022','0080');";

                // C2 - Projeções confirmadas até dia anterior
                String sqlC2 = "SELECT COALESCE(SUM(valor), 0) AS saldo "
                        + "FROM tbmovimento "
                        + "WHERE vrecurso IN ('1.002.001','2.001.002','2.001.003') "
                        + "  AND dtvcto <= ? "
                        + "  AND (statusmov IS NULL OR statusmov = '');";

                // C4 - Empréstimos obtidos até dia anterior
                String sqlC4 = "SELECT COALESCE(SUM(valor), 0) AS saldo "
                        + "FROM tbmovimento WHERE recurso = '0080' AND dtlancto <= ?;";

                // Executa C1 (até hoje)
                stmtSaldo = con.prepareStatement(sqlC1);
                stmtSaldo.setDate(1, sqlDataHoje);
                rsSaldo = stmtSaldo.executeQuery();
                if (rsSaldo.next()) {
                    saldoCaixaBancoAnterior += rsSaldo.getDouble("saldo");
                }
                rsSaldo.close();
                stmtSaldo.close();

                // Executa C2 (até dia anterior)
                stmtSaldo = con.prepareStatement(sqlC2);
                stmtSaldo.setDate(1, sqlDataDiaAnterior);
                rsSaldo = stmtSaldo.executeQuery();
                if (rsSaldo.next()) {
                    saldoCaixaBancoAnterior += rsSaldo.getDouble("saldo");
                }
                rsSaldo.close();
                stmtSaldo.close();

                // Executa C4 (Empréstimos até dia anterior)
                stmtSaldo = con.prepareStatement(sqlC4);
                stmtSaldo.setDate(1, sqlDataDiaAnterior);
                rsSaldo = stmtSaldo.executeQuery();
                if (rsSaldo.next()) {
                    double valorEmp = rsSaldo.getDouble("saldo");
                    saldoEmprestimoAnterior = valorEmp * -1; // Ajuste de sinal conforme sua lógica
                    saldoCaixaBancoAnterior += valorEmp;
                }
                rsSaldo.close();
                stmtSaldo.close();
            }

            // === ATRIBUIÇÃO FINAL ===
            saldoInicialPeriodo = saldoCaixaBancoAnterior;
            saldoInicialEmprestimo = saldoEmprestimoAnterior;

            // Atualiza também o transporte (caso esteja abrindo o mesmo período novamente)
            // === 2. CONSULTA PRINCIPAL (CONTAS) ===
            String sql = "SELECT nome_c AS \"Contas\", "
                    + "SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 1 THEN valor ELSE 0 END) AS \"janeiro\", "
                    + "SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 2 THEN valor ELSE 0 END) AS \"fevereiro\", "
                    + "SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 3 THEN valor ELSE 0 END) AS \"março\", "
                    + "SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 4 THEN valor ELSE 0 END) AS \"abril\", "
                    + "SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 5 THEN valor ELSE 0 END) AS \"maio\", "
                    + "SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 6 THEN valor ELSE 0 END) AS \"junho\", "
                    + "SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 7 THEN valor ELSE 0 END) AS \"julho\", "
                    + "SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 8 THEN valor ELSE 0 END) AS \"agosto\", "
                    + "SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 9 THEN valor ELSE 0 END) AS \"setembro\", "
                    + "SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 10 THEN valor ELSE 0 END) AS \"outubro\", "
                    + "SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 11 THEN valor ELSE 0 END) AS \"novembro\", "
                    + "SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 12 THEN valor ELSE 0 END) AS \"dezembro\", "
                    + "SUM(valor) AS \"total\" "
                    + "FROM viewmovrd "
                    + "WHERE dtvcto BETWEEN ? AND ? " + filtroStatus
                    + "  AND nome_p <> 'NULO' "
                    + "  AND (classif NOT IN ('3.003.005', '4.008.011') "
                    + "       OR (classif = '4.008.011' AND dtapr IS NULL)) "
                    + "GROUP BY nome_c "
                    + "ORDER BY nome_c;";

            stmt = con.prepareStatement(sql);
            stmt.setDate(1, sqlDataIni);
            stmt.setDate(2, sqlDataFim);
            rs = stmt.executeQuery();

            // === LIMPAR E CONFIGURAR TABELA ===
            DefaultTableModel modelo = (DefaultTableModel) jTablePesquisa.getModel();
            modelo.setNumRows(0);
            jTablePesquisa.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(0)).setPreferredWidth(320);
            for (int i = 1; i <= 12; i++) {
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(i)).setPreferredWidth(70);
            }
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(13)).setPreferredWidth(90);

            DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
            rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
            for (int i = 1; i < jTablePesquisa.getColumnCount(); i++) {
                jTablePesquisa.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
            }

            // === 5. CONSULTAS DE RECEITAS, DESPESAS E EMPRÉSTIMOS ===
            // === QUERY RECEITAS ===
            String queryReceitas = "SELECT "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 1 AND valor > 0 AND classif LIKE '3.%' AND classif != '3.003.005' THEN valor ELSE 0 END), 0)::numeric, 2) AS janeiro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 2 AND valor > 0 AND classif LIKE '3.%' AND classif != '3.003.005' THEN valor ELSE 0 END), 0)::numeric, 2) AS fevereiro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 3 AND valor > 0 AND classif LIKE '3.%' AND classif != '3.003.005' THEN valor ELSE 0 END), 0)::numeric, 2) AS março, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 4 AND valor > 0 AND classif LIKE '3.%' AND classif != '3.003.005' THEN valor ELSE 0 END), 0)::numeric, 2) AS abril, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 5 AND valor > 0 AND classif LIKE '3.%' AND classif != '3.003.005' THEN valor ELSE 0 END), 0)::numeric, 2) AS maio, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 6 AND valor > 0 AND classif LIKE '3.%' AND classif != '3.003.005' THEN valor ELSE 0 END), 0)::numeric, 2) AS junho, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 7 AND valor > 0 AND classif LIKE '3.%' AND classif != '3.003.005' THEN valor ELSE 0 END), 0)::numeric, 2) AS julho, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 8 AND valor > 0 AND classif LIKE '3.%' AND classif != '3.003.005' THEN valor ELSE 0 END), 0)::numeric, 2) AS agosto, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 9 AND valor > 0 AND classif LIKE '3.%' AND classif != '3.003.005' THEN valor ELSE 0 END), 0)::numeric, 2) AS setembro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 10 AND valor > 0 AND classif LIKE '3.%' AND classif != '3.003.005' THEN valor ELSE 0 END), 0)::numeric, 2) AS outubro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 11 AND valor > 0 AND classif LIKE '3.%' AND classif != '3.003.005' THEN valor ELSE 0 END), 0)::numeric, 2) AS novembro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 12 AND valor > 0 AND classif LIKE '3.%' AND classif != '3.003.005' THEN valor ELSE 0 END), 0)::numeric, 2) AS dezembro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN valor > 0 AND classif LIKE '3.%' AND classif != '3.003.005' THEN valor ELSE 0 END), 0)::numeric, 2) AS total "
                    + "FROM viewmovrd "
                    + "WHERE dtvcto BETWEEN ? AND ? AND nome_p <> 'NULO' " + filtroStatus + ";";

            stmtReceitas = con.prepareStatement(queryReceitas);
            stmtReceitas.setDate(1, sqlDataIni);
            stmtReceitas.setDate(2, sqlDataFim);
            rsReceitas = stmtReceitas.executeQuery();

            // === QUERY DESPESAS ===
            String queryDespesas = "SELECT "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 1 AND valor < 0 AND classif LIKE '4.%' AND classif != '4.008.011' THEN valor ELSE 0 END), 0)::numeric, 2) AS janeiro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 2 AND valor < 0 AND classif LIKE '4.%' AND classif != '4.008.011' THEN valor ELSE 0 END), 0)::numeric, 2) AS fevereiro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 3 AND valor < 0 AND classif LIKE '4.%' AND classif != '4.008.011' THEN valor ELSE 0 END), 0)::numeric, 2) AS março, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 4 AND valor < 0 AND classif LIKE '4.%' AND classif != '4.008.011' THEN valor ELSE 0 END), 0)::numeric, 2) AS abril, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 5 AND valor < 0 AND classif LIKE '4.%' AND classif != '4.008.011' THEN valor ELSE 0 END), 0)::numeric, 2) AS maio, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 6 AND valor < 0 AND classif LIKE '4.%' AND classif != '4.008.011' THEN valor ELSE 0 END), 0)::numeric, 2) AS junho, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 7 AND valor < 0 AND classif LIKE '4.%' AND classif != '4.008.011' THEN valor ELSE 0 END), 0)::numeric, 2) AS julho, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 8 AND valor < 0 AND classif LIKE '4.%' AND classif != '4.008.011' THEN valor ELSE 0 END), 0)::numeric, 2) AS agosto, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 9 AND valor < 0 AND classif LIKE '4.%' AND classif != '4.008.011' THEN valor ELSE 0 END), 0)::numeric, 2) AS setembro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 10 AND valor < 0 AND classif LIKE '4.%' AND classif != '4.008.011' THEN valor ELSE 0 END), 0)::numeric, 2) AS outubro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 11 AND valor < 0 AND classif LIKE '4.%' AND classif != '4.008.011' THEN valor ELSE 0 END), 0)::numeric, 2) AS novembro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 12 AND valor < 0 AND classif LIKE '4.%' AND classif != '4.008.011' THEN valor ELSE 0 END), 0)::numeric, 2) AS dezembro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN valor < 0 AND classif LIKE '4.%' AND classif != '4.008.011' THEN valor ELSE 0 END), 0)::numeric, 2) AS total_despesas "
                    + "FROM viewmovrd WHERE dtvcto BETWEEN ? AND ? AND nome_p <> 'NULO' " + filtroStatus + ";";

            stmtDespesas = con.prepareStatement(queryDespesas);
            stmtDespesas.setDate(1, sqlDataIni);
            stmtDespesas.setDate(2, sqlDataFim);
            rsDespesas = stmtDespesas.executeQuery();

            // === QUERY EMPRÉSTIMOS OBTIDOS ===
            String queryEmprestimosObtidos = "SELECT "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 1 AND classif = '3.003.005' THEN ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS janeiro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 2 AND classif = '3.003.005' THEN ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS fevereiro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 3 AND classif = '3.003.005' THEN ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS março, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 4 AND classif = '3.003.005' THEN ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS abril, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 5 AND classif = '3.003.005' THEN ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS maio, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 6 AND classif = '3.003.005' THEN ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS junho, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 7 AND classif = '3.003.005' THEN ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS julho, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 8 AND classif = '3.003.005' THEN ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS agosto, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 9 AND classif = '3.003.005' THEN ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS setembro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 10 AND classif = '3.003.005' THEN ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS outubro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 11 AND classif = '3.003.005' THEN ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS novembro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 12 AND classif = '3.003.005' THEN ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS dezembro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN classif = '3.003.005' THEN ABS(valor) ELSE 0 END), 0)::numeric, 2) AS total_emprestimos_obtidos "
                    + "FROM tbmovimento WHERE dtvcto BETWEEN ? AND ? AND dtapr IS NOT NULL" + filtroStatus + ";";

            stmtEmprestimosObtidos = con.prepareStatement(queryEmprestimosObtidos);
            stmtEmprestimosObtidos.setDate(1, sqlDataIni);
            stmtEmprestimosObtidos.setDate(2, sqlDataFim);
            rsEmprestimosObtidos = stmtEmprestimosObtidos.executeQuery();

            // === QUERY EMPRÉSTIMOS PAGOS ===
            String queryEmprestimosPagos = "SELECT "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 1 AND classif = '4.008.011' THEN -ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS janeiro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 2 AND classif = '4.008.011' THEN -ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS fevereiro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 3 AND classif = '4.008.011' THEN -ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS março, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 4 AND classif = '4.008.011' THEN -ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS abril, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 5 AND classif = '4.008.011' THEN -ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS maio, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 6 AND classif = '4.008.011' THEN -ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS junho, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 7 AND classif = '4.008.011' THEN -ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS julho, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 8 AND classif = '4.008.011' THEN -ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS agosto, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 9 AND classif = '4.008.011' THEN -ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS setembro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 10 AND classif = '4.008.011' THEN -ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS outubro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 11 AND classif = '4.008.011' THEN -ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS novembro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN EXTRACT(MONTH FROM dtvcto) = 12 AND classif = '4.008.011' THEN -ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS dezembro, "
                    + "ROUND(COALESCE(SUM(CASE WHEN classif = '4.008.011' THEN -ABS(Valor) ELSE 0 END), 0)::numeric, 2) AS total_emprestimos_pagos "
                    + "FROM tbmovimento WHERE dtvcto BETWEEN ? AND ? AND dtapr IS NOT NULL" + filtroStatus + ";";

            stmtEmprestimosPagos = con.prepareStatement(queryEmprestimosPagos);
            stmtEmprestimosPagos.setDate(1, sqlDataIni);
            stmtEmprestimosPagos.setDate(2, sqlDataFim);
            rsEmprestimosPagos = stmtEmprestimosPagos.executeQuery();

            // === LEITURA DOS DADOS ===
            double[] totaisReceitas = new double[12];
            double[] totaisDespesas = new double[12];
            double[] totaisEmprestimosObtidos = new double[12];
            double[] totaisEmprestimosPagos = new double[12];
            double totalReceitas = 0, totalDespesas = 0, totalEmprestimosObtidos = 0, totalEmprestimosPagos = 0;

            if (rsReceitas.next()) {
                for (int i = 0; i < 12; i++) {
                    totaisReceitas[i] = rsReceitas.getDouble(i + 1);
                    totalReceitas += totaisReceitas[i];
                }
            }
            if (rsDespesas.next()) {
                for (int i = 0; i < 12; i++) {
                    totaisDespesas[i] = rsDespesas.getDouble(i + 1);
                    totalDespesas += totaisDespesas[i];
                }
            }
            if (rsEmprestimosObtidos.next()) {
                for (int i = 0; i < 12; i++) {
                    totaisEmprestimosObtidos[i] = rsEmprestimosObtidos.getDouble(i + 1);
                    totalEmprestimosObtidos += totaisEmprestimosObtidos[i];
                }
            }
            if (rsEmprestimosPagos.next()) {
                for (int i = 0; i < 12; i++) {
                    totaisEmprestimosPagos[i] = rsEmprestimosPagos.getDouble(i + 1);
                    totalEmprestimosPagos += totaisEmprestimosPagos[i];
                }
            }

            // === PREENCHER ARRAYS PARA O GRÁFICO ===
            for (int i = 0; i < 12; i++) {
                receitasMensais[i] = totaisReceitas[i];
                despesasMensais[i] = totaisDespesas[i];
                resultadosMensais[i] = totaisReceitas[i] + totaisDespesas[i];
            }

            // === CÁLCULO ACUMULATIVO ===
            // Usamos o Calendar para extrair os meses de forma segura e numérica
            Calendar calAux = Calendar.getInstance();

            // Extrair mês de Início
            calAux.setTime(dataIni);
            int mesInicio = calAux.get(Calendar.MONTH) + 1; // +1 porque no Java Janeiro é 0

            // Extrair mês de Fim
            calAux.setTime(dataFim);
            int mesFim = calAux.get(Calendar.MONTH) + 1;

            // Opcional: Se precisar do ano para validações de períodos que viram o ano
            int anoInicio = calAux.get(Calendar.YEAR);

            // Base limpa para a linha "Saldo Anterior" (Caixa/Banco)
            double saldoInicialCaixaBanco = saldoInicialPeriodo; // ? Usa o Saldo Limpo Transportado

            double[] saldoAcumuladoEmprestimo = new double[12];
            double totalResultadoFinal = 0;
            // Define o passivo inicial de empréstimo (Ex: -600.00)
            // Este é o valor vindo do período anterior, que será usado UMA VEZ no primeiro mês.
            double saldoBaseEmprestimo = saldoInicialEmprestimo; // ? Usa o Saldo de Empréstimo Transportado

            double[] saldosIniciais = new double[12];
            double[] saldosFinais = new double[12];
            double[] resultadoFinalPeriodo = new double[12];

            for (int i = 0; i < 12; i++) {
                int mesAtual = i + 1;
                if (mesAtual >= mesInicio && mesAtual <= mesFim) {

                    // CÁLCULO SALDO DE CAIXA/BANCO (Onde o Saldo Anterior aparece)
                    saldosIniciais[i] = (mesAtual == mesInicio) ? saldoInicialCaixaBanco : saldosFinais[i - 1]; // Inicia com R$ 208,53

                    double resultadoMes = totaisReceitas[i] + totaisDespesas[i]; // Fluxo de Caixa Mês
                    saldosFinais[i] = saldosIniciais[i] + resultadoMes; // SOMA APENAS COM RESULTADO DE CAIXA/BANCO

                    // ?? CÁLCULO DO SALDO DE EMPRÉSTIMO ACUMULADO
                    double emprestimoMes = (totaisEmprestimosObtidos[i]) + totaisEmprestimosPagos[i];

                    // CALCULA EMPRÉSTIMO ACUMULADO
                    if (i == 0) {
                        saldoAcumuladoEmprestimo[i] = saldoBaseEmprestimo + emprestimoMes; // Inicia com -R$ 600,00
                    } else {
                        // Transporta o saldo final do mês anterior de empréstimo
                        saldoAcumuladoEmprestimo[i] = saldoAcumuladoEmprestimo[i - 1] + emprestimoMes;
                    }

                    // FIM DOS CÁLCULOS
                    saldoFinalMensal[i] = saldosFinais[i]; // Mantém o Saldo de Caixa/Banco

                } else {
                    saldosIniciais[i] = saldosFinais[i] = 0.0;
                    saldoAcumuladoEmprestimo[i] = 0.0;
                }
            }

            double totalSaldoFinal = (mesFim >= mesInicio) ? saldosFinais[mesFim - 1] : saldoInicialPeriodo;

            // =================================================================
            // BLOCO DE TRANSPORTE FINAL (PONTO 3 CORRIGIDO)
            // =================================================================
            if (mesFim >= mesInicio) {
                int indiceFinal = mesFim - 1;

                // 1. Transporta o Saldo Limpo
                saldoTransportado = saldosFinais[indiceFinal]; // ? ATRIBUIÇÃO CORRETA (R$ 233,40)

                // 2. Transporta o Empréstimo Passivo
                saldoTransportadoEmprestimo = saldoAcumuladoEmprestimo[indiceFinal];

            } else {
                // 1. Transporta o Saldo Limpo (Fallback)
                saldoTransportado = saldoInicialPeriodo;

                // 2. Transporta o Empréstimo Passivo (Fallback)
                saldoTransportadoEmprestimo = saldoInicialEmprestimo;
            }
            // =================================================================

            // === SALDO ANTERIOR CORRETO (com efeito dos empréstimos) ===
            Object[] linhaSaldoAnt = new Object[14];
            linhaSaldoAnt[0] = "Saldo Anterior(Cx/Bcos/Poup)S/Empr.";

            double saldoAnteriorTotal = saldoInicialPeriodo;

            for (int i = 0; i < 12; i++) {
                int mesAtual = i + 1;
                if (mesAtual >= mesInicio && mesAtual <= mesFim) {
                    if (mesAtual == mesInicio) {
                        linhaSaldoAnt[i + 1] = dfCurrency.format(saldoAnteriorTotal);
                    } else {
                        // Mostra o acumulado até o mês anterior (limpo + dívida)
                        linhaSaldoAnt[i + 1] = dfCurrency.format(saldosFinais[i - 1] + saldoAcumuladoEmprestimo[i - 1]);

                    }
                } else {
                    linhaSaldoAnt[i + 1] = "";
                }
            }

            // Coluna TOTAL = mesmo valor do primeiro mês (ou do último mês anterior)
            linhaSaldoAnt[13] = dfCurrency.format(saldoAnteriorTotal);

            modelo.addRow(linhaSaldoAnt);
            modelo.addRow(new Object[14]); // linha em branco

            // === PREENCHER CONTAS ===
            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString("Contas"),
                    dfCurrency.format(rs.getDouble("janeiro")),
                    dfCurrency.format(rs.getDouble("fevereiro")),
                    dfCurrency.format(rs.getDouble("março")),
                    dfCurrency.format(rs.getDouble("abril")),
                    dfCurrency.format(rs.getDouble("maio")),
                    dfCurrency.format(rs.getDouble("junho")),
                    dfCurrency.format(rs.getDouble("julho")),
                    dfCurrency.format(rs.getDouble("agosto")),
                    dfCurrency.format(rs.getDouble("setembro")),
                    dfCurrency.format(rs.getDouble("outubro")),
                    dfCurrency.format(rs.getDouble("novembro")),
                    dfCurrency.format(rs.getDouble("dezembro")),
                    dfCurrency.format(rs.getDouble("total"))
                });
            }
            modelo.addRow(new Object[14]); // linha em branco

            // === ADICIONAR RECEITAS, DESPESAS, RESULTADO, EMPRÉSTIMOS ===
            modelo.addRow(new Object[]{
                "Receitas",
                dfCurrency.format(totaisReceitas[0]), dfCurrency.format(totaisReceitas[1]), dfCurrency.format(totaisReceitas[2]),
                dfCurrency.format(totaisReceitas[3]), dfCurrency.format(totaisReceitas[4]), dfCurrency.format(totaisReceitas[5]),
                dfCurrency.format(totaisReceitas[6]), dfCurrency.format(totaisReceitas[7]), dfCurrency.format(totaisReceitas[8]),
                dfCurrency.format(totaisReceitas[9]), dfCurrency.format(totaisReceitas[10]), dfCurrency.format(totaisReceitas[11]),
                dfCurrency.format(totalReceitas)
            });
            modelo.addRow(new Object[]{
                "Despesas",
                dfCurrency.format(totaisDespesas[0]), dfCurrency.format(totaisDespesas[1]), dfCurrency.format(totaisDespesas[2]),
                dfCurrency.format(totaisDespesas[3]), dfCurrency.format(totaisDespesas[4]), dfCurrency.format(totaisDespesas[5]),
                dfCurrency.format(totaisDespesas[6]), dfCurrency.format(totaisDespesas[7]), dfCurrency.format(totaisDespesas[8]),
                dfCurrency.format(totaisDespesas[9]), dfCurrency.format(totaisDespesas[10]), dfCurrency.format(totaisDespesas[11]),
                dfCurrency.format(totalDespesas)
            });
            modelo.addRow(new Object[]{
                "Resultado",
                dfCurrency.format(totaisReceitas[0] + totaisDespesas[0]),
                dfCurrency.format(totaisReceitas[1] + totaisDespesas[1]),
                dfCurrency.format(totaisReceitas[2] + totaisDespesas[2]),
                dfCurrency.format(totaisReceitas[3] + totaisDespesas[3]),
                dfCurrency.format(totaisReceitas[4] + totaisDespesas[4]),
                dfCurrency.format(totaisReceitas[5] + totaisDespesas[5]),
                dfCurrency.format(totaisReceitas[6] + totaisDespesas[6]),
                dfCurrency.format(totaisReceitas[7] + totaisDespesas[7]),
                dfCurrency.format(totaisReceitas[8] + totaisDespesas[8]),
                dfCurrency.format(totaisReceitas[9] + totaisDespesas[9]),
                dfCurrency.format(totaisReceitas[10] + totaisDespesas[10]),
                dfCurrency.format(totaisReceitas[11] + totaisDespesas[11]),
                dfCurrency.format(totalReceitas + totalDespesas)
            });
            modelo.addRow(new Object[14]); // linha em branco

            // === ADICIONAR LINHA DE SALDO INICIAL DE EMPRÉSTIMO ===
            Object[] linhaSaldoEmprestimo = new Object[14];
            linhaSaldoEmprestimo[0] = "Saldo Inicial Empréstimo";

            for (int i = 0; i < 12; i++) {
                int mesAtual = i + 1;
                if (mesAtual == mesInicio) {
                    // Força aparecer negativo (mesmo que o valor já seja negativo)
                    double valorExibir = saldoInicialEmprestimo <= 0 ? saldoInicialEmprestimo : -saldoInicialEmprestimo;
                    linhaSaldoEmprestimo[i + 1] = dfCurrency.format(valorExibir);
                } else {
                    linhaSaldoEmprestimo[i + 1] = "";
                }
            }
            linhaSaldoEmprestimo[13] = dfCurrency.format(saldoInicialEmprestimo <= 0 ? saldoInicialEmprestimo : -saldoInicialEmprestimo);
            modelo.addRow(linhaSaldoEmprestimo);

            // === EMPRÉSTIMOS RECEBIDOS (apresentar como negativo) ===
            modelo.addRow(new Object[]{
                "Emprést.Obt.C.Prazo-Recebidos",
                formatarEmprestimoVisual(totaisEmprestimosObtidos[0], true),
                formatarEmprestimoVisual(totaisEmprestimosObtidos[1], true),
                formatarEmprestimoVisual(totaisEmprestimosObtidos[2], true),
                formatarEmprestimoVisual(totaisEmprestimosObtidos[3], true),
                formatarEmprestimoVisual(totaisEmprestimosObtidos[4], true),
                formatarEmprestimoVisual(totaisEmprestimosObtidos[5], true),
                formatarEmprestimoVisual(totaisEmprestimosObtidos[6], true),
                formatarEmprestimoVisual(totaisEmprestimosObtidos[7], true),
                formatarEmprestimoVisual(totaisEmprestimosObtidos[8], true),
                formatarEmprestimoVisual(totaisEmprestimosObtidos[9], true),
                formatarEmprestimoVisual(totaisEmprestimosObtidos[10], true),
                formatarEmprestimoVisual(totaisEmprestimosObtidos[11], true),
                formatarEmprestimoVisual(totalEmprestimosObtidos, true)
            });
            // === EMPRÉSTIMOS PAGOS (apresentar como positivo) ===
            modelo.addRow(new Object[]{
                "Emprést.Obt.C.Prazo-Pagos",
                formatarEmprestimoVisual(totaisEmprestimosPagos[0], true), // true = inverte o sinal (de negativo vira positivo)
                formatarEmprestimoVisual(totaisEmprestimosPagos[1], true),
                formatarEmprestimoVisual(totaisEmprestimosPagos[2], true),
                formatarEmprestimoVisual(totaisEmprestimosPagos[3], true),
                formatarEmprestimoVisual(totaisEmprestimosPagos[4], true),
                formatarEmprestimoVisual(totaisEmprestimosPagos[5], true),
                formatarEmprestimoVisual(totaisEmprestimosPagos[6], true),
                formatarEmprestimoVisual(totaisEmprestimosPagos[7], true),
                formatarEmprestimoVisual(totaisEmprestimosPagos[8], true),
                formatarEmprestimoVisual(totaisEmprestimosPagos[9], true),
                formatarEmprestimoVisual(totaisEmprestimosPagos[10], true),
                formatarEmprestimoVisual(totaisEmprestimosPagos[11], true),
                formatarEmprestimoVisual(totalEmprestimosPagos, true)
            });
            modelo.addRow(new Object[]{
                "Saldo Empréstimos C.Prazo",
                formatarNegativo(saldoAcumuladoEmprestimo[0]),
                formatarNegativo(saldoAcumuladoEmprestimo[1]),
                formatarNegativo(saldoAcumuladoEmprestimo[2]),
                formatarNegativo(saldoAcumuladoEmprestimo[3]),
                formatarNegativo(saldoAcumuladoEmprestimo[4]),
                formatarNegativo(saldoAcumuladoEmprestimo[5]),
                formatarNegativo(saldoAcumuladoEmprestimo[6]),
                formatarNegativo(saldoAcumuladoEmprestimo[7]),
                formatarNegativo(saldoAcumuladoEmprestimo[8]),
                formatarNegativo(saldoAcumuladoEmprestimo[9]),
                formatarNegativo(saldoAcumuladoEmprestimo[10]),
                formatarNegativo(saldoAcumuladoEmprestimo[11]),
                formatarNegativo(saldoAcumuladoEmprestimo[mesFim - 1])
            });
            modelo.addRow(new Object[14]); // linha em branco

            // === SALDO FINAL DO PERÍODO SEM EMPRÉSTIMO (CAIXA/BANCO) ===
            Object[] linhaSaldoFinal = new Object[14];
            // ATENÇÃO: Mudando o nome da linha para refletir a variável 'saldosFinais' (sem empréstimo)
            linhaSaldoFinal[0] = "Saldo Final (Cx/Bcos/Poup)S/Empréstimos";
            double saldoFinalTotalComEmprestimo = 0.0; // Variável para guardar o saldo TOTAL do último mês

            for (int i = 0; i < 12; i++) {
                int mesAtual = i + 1;
                if ((i + 1) >= mesInicio && (i + 1) <= mesFim) {

                    // 1. Linha do Saldo Limpo (Caixa/Banco)
                    linhaSaldoFinal[i + 1] = dfCurrency.format(saldosFinais[i]); // ? Usa o array de Saldo Limpo

                    // 2. Cálculo do Saldo TOTAL (Caixa/Banco Limpo + Empréstimo Acumulado)
                    // O saldo final total de cada mês é a soma dos dois acumulados:
                    //saldoFinalTotalComEmprestimo = saldosFinais[i] + saldoAcumuladoEmprestimo[i];
                    // 3. TRANSPORTE: O valor FINAL que será transportado é o TOTAL (com empréstimo)
                    // Isso deve ser feito APENAS para o último mês do loop, mas vamos calcular 
                    // em cada iteração e o último valor prevalecerá.
                    //pegaSaldoFinal = saldoFinalTotalComEmprestimo;
                    //saldoTransportado = pegaSaldoFinal;
                } else {
                    linhaSaldoFinal[i + 1] = "";
                }
            }

            // O total é o Saldo Final Total LIMPO do último mês do período calculado
            linhaSaldoFinal[13] = dfCurrency.format(saldosFinais[mesFim - 1]);
            modelo.addRow(linhaSaldoFinal);

            // === SALDO TOTAL DISPONÍVEL (com efeito dos empréstimos) ===
            Object[] linhaSaldoTotal = new Object[14];
            linhaSaldoTotal[0] = "Saldo Total Disponível(C/Empréstimos)";

            for (int i = 0; i < 12; i++) {
                int mesAtual = i + 1;
                if (mesAtual >= mesInicio && mesAtual <= mesFim) {
                    double saldoLimpo = saldosFinais[i] + saldoAcumuladoEmprestimo[i];
                    linhaSaldoTotal[i + 1] = dfCurrency.format(saldoLimpo);
                } else {
                    linhaSaldoTotal[i + 1] = "";
                }
            }
            linhaSaldoTotal[13] = dfCurrency.format(saldosFinais[mesFim - 1] + saldoAcumuladoEmprestimo[mesFim - 1]);
            modelo.addRow(linhaSaldoTotal);

            // TRANSPORTE CORRETO PARA O PRÓXIMO PERÍODO
            double saldoTotalFinal = saldosFinais[mesFim - 1] + saldoAcumuladoEmprestimo[mesFim - 1];

            // === TRANSPORTE CORRETO (APENAS O SALDO PRÓPRIO) ===
            saldoTransportado = saldosFinais[mesFim - 1];                    // ? 233,40  (só o que é realmente seu)
            saldoTransportadoEmprestimo = saldoAcumuladoEmprestimo[mesFim - 1]; // ? ?600,00 (só para mostrar na tela)

            // === CORES NA TABELA ===
            ColorearTabla colorearTabla = new ColorearTabla();
            for (int i = 1; i < jTablePesquisa.getColumnCount(); i++) {
                jTablePesquisa.getColumnModel().getColumn(i).setCellRenderer(colorearTabla);
            }

        } catch (SQLException | ParseException ex) {
            Logger.getLogger(Tela_de_Consulta_RC.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao consultar dados: " + ex.getMessage());
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (stmt != null) {
                    stmt.close();
                }
                if (rsReceitas != null) {
                    rsReceitas.close();
                }
                if (stmtReceitas != null) {
                    stmtReceitas.close();
                }
                if (rsDespesas != null) {
                    rsDespesas.close();
                }
                if (stmtDespesas != null) {
                    stmtDespesas.close();
                }
                if (rsEmprestimosObtidos != null) {
                    rsEmprestimosObtidos.close();
                }
                if (stmtEmprestimosObtidos != null) {
                    stmtEmprestimosObtidos.close();
                }
                if (rsEmprestimosPagos != null) {
                    rsEmprestimosPagos.close();
                }
                if (stmtEmprestimosPagos != null) {
                    stmtEmprestimosPagos.close();
                }
                if (rsSaldo != null) {
                    rsSaldo.close();
                }
                if (stmtSaldo != null) {
                    stmtSaldo.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException e) {
                Logger.getLogger(Tela_de_Consulta_RC.class.getName()).log(Level.SEVERE, null, e);
            }
            try {
                if (con != null) {
                    con.close();
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private String formatarNegativo(double valor) {
        // === FORMATADOR DE MOEDA ===
        DecimalFormatSymbols symbols = new DecimalFormatSymbols();
        symbols.setDecimalSeparator(',');
        symbols.setGroupingSeparator('.');
        DecimalFormat dfCurrency = new DecimalFormat("#,##0.00", symbols);

        double valorExibir = (valor <= 0) ? valor : -valor;  // força negativo

        String formatado = dfCurrency.format(valorExibir);
        // Se quiser em vermelho (funciona com JTable + HTML)
        //return "<html><font color=" + (valorExibir < 0 ? "red" : "green") + ">" + formatado + "</font></html>";
        // Ou sem cor (só negativo):
        return dfCurrency.format(valorExibir);
    }

    // Só para deixar os empréstimos com sinal invertido na tela
    private String formatarEmprestimoVisual(double valor, boolean inverterSinal) {

        // === FORMATADOR DE MOEDA ===
        DecimalFormatSymbols symbols = new DecimalFormatSymbols();
        DecimalFormatSymbols br = new DecimalFormatSymbols(new Locale.Builder().setLanguage("pt").setRegion("BR").build());
        br.setDecimalSeparator(',');
        br.setGroupingSeparator('.');
        symbols.setDecimalSeparator(',');
        symbols.setGroupingSeparator('.');
        DecimalFormat dfCurrency = new DecimalFormat("#,##0.00", symbols);
        DecimalFormat dfNumero = new DecimalFormat("#,##0.00", br);
        double valorExibir = inverterSinal ? -valor : valor;
        return dfNumero.format(valorExibir);  // ? só retorna " -1.300,00 " ou " 700,00 "
    }


    private void jButtonPLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPLimparActionPerformed
        ((DefaultTableModel) jTablePesquisa.getModel()).setRowCount(0);
        jFormattedTextFieldDataIni.setText("");
        jFormattedTextFieldDataFim.setText("");
    }//GEN-LAST:event_jButtonPLimparActionPerformed

    private void jButtonPImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPImprimirActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        Date date = new Date();
        String infDt = dateFormat.format(date);

        // Pegar as datas dos campos
        String dataInicial = jFormattedTextFieldDataIni.getText();
        String dataFinal = jFormattedTextFieldDataFim.getText();

        PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
        set.add(OrientationRequested.LANDSCAPE);
        //MessageFormat cabecalho = new MessageFormat("Referência Cruzada - " + infDt);

        // Cabeçalho com as datas do período
        MessageFormat cabecalho = new MessageFormat(
                "Referência Cruzada - Período: " + dataInicial + " a " + dataFinal);

        MessageFormat rodape = new MessageFormat(
                "Página {0,number,integer}" + " - Impressão: " + infDt);

        try {
            jTablePesquisa.print(JTable.PrintMode.FIT_WIDTH, cabecalho, rodape, false, set, false);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Erro ao imprimir!!! %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jButtonPImprimirActionPerformed


    private void jButtonGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGraficoActionPerformed
        try {
            // Verifica se há dados
            boolean temDados = false;
            for (int i = 0; i < 12; i++) {
                if (receitasMensais[i] != 0 || despesasMensais[i] != 0 || saldoFinalMensal[i] != 0) {
                    temDados = true;
                    break;
                }
            }

            if (temDados) {
                XYLineChart graf = new XYLineChart(receitasMensais, despesasMensais, resultadosMensais);
            } else {
                JOptionPane.showMessageDialog(this, "Não há dados para exibir no gráfico.");
            }
        } catch (Exception ex) {
            Logger.getLogger(Tela_de_Consulta_RC.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro ao gerar gráfico: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonGraficoActionPerformed

    private void jButtonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportarActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Salvar como...");
        int userSelection = fileChooser.showSaveDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String path = fileChooser.getSelectedFile().getAbsolutePath();
            if (!path.endsWith(".xlsx")) {
                path += ".xlsx";
            }
            try {
                ExportToExcel exporter = new ExportToExcel();
                exporter.exportTable(jTablePesquisa, path);
                JOptionPane.showMessageDialog(null, "Arquivo Excel " + path + " foi gerado com sucesso!");
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao exportar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonExportarActionPerformed

    private void jButtonAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnualActionPerformed
        // Obtém o ano atual
        int anoCorrente = java.time.Year.now().getValue();

        // Define as datas de início e fim do ano
        String dataInicial = "01/01/" + anoCorrente;
        String dataFinal = "31/12/" + anoCorrente;

        // Preenche os campos de data
        jFormattedTextFieldDataIni.setText(dataInicial);
        jFormattedTextFieldDataFim.setText(dataFinal);
    }//GEN-LAST:event_jButtonAnualActionPerformed

    private void jButtonSalvaprevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvaprevActionPerformed

        jRadioButtonPrev.setSelected(true);
        jButtonPesquisarActionPerformed(null);

        String inflacaoStr = JOptionPane.showInputDialog(this, "Expectativa de Inflação/Reajuste (%) considerada:");
        if (inflacaoStr == null) {
            return;
        }

        // 1. Primeiro, geramos o PDF como você já faz
        gerarPDFSnapshot(inflacaoStr);

        // 2. Agora, vamos salvar os dados na tb_plano_diretor
        double inflacao = Double.parseDouble(inflacaoStr.replace(",", "."));
        int anoAtual = java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
        
        
        Connection conn = null;
        PreparedStatement pst = null;

        try {
            
            try {
                // === ABRIR CONEXÃO ===
                conn = Conexao.faz_conexao();
                String sql = "INSERT INTO tb_plano_diretor (ano_referencia, mes, conta, valor_planejado, inflacao_premissa) VALUES (?, ?, ?, ?, ?)";
                pst = conn.prepareStatement(sql);

                for (int i = 0; i < jTablePesquisa.getRowCount(); i++) {
                    // Captura o nome da conta com segurança
                    Object objConta = jTablePesquisa.getValueAt(i, 0);
                    if (objConta == null) {
                        continue; // Pula se a linha estiver totalmente vazia
                    }
                    String nomeConta = objConta.toString();

                    // FILTRO DE SEGURANÇA: Só deixa passar o que não for Saldo/Resultado/Totais
                    if (nomeConta.startsWith("Saldo")
                            || nomeConta.startsWith("Resultado")
                            || nomeConta.startsWith("Receitas")
                            || nomeConta.startsWith("Despesas")) {
                        continue; // Pula para a próxima linha da tabela sem salvar essa
                    }

                    for (int mes = 1; mes <= 12; mes++) {
                        Object valorObj = jTablePesquisa.getValueAt(i, mes);

                        // Verifica se a célula não está nula antes de processar
                        if (valorObj != null && !valorObj.toString().trim().isEmpty()) {
                            String valorStr = valorObj.toString();

                            // Limpeza para evitar o erro de "multiple points"
                            valorStr = valorStr.replace(".", "").replace(",", ".");

                            try {
                                double valor = Double.parseDouble(valorStr);

                                if (valor != 0) {
                                    pst.setInt(1, anoAtual);
                                    pst.setInt(2, mes);
                                    pst.setString(3, nomeConta);
                                    pst.setDouble(4, valor);
                                    pst.setDouble(5, inflacao);
                                    pst.addBatch();
                                }
                            } catch (NumberFormatException nfe) {
                                // Ignora valores que não sejam números (ex: strings acidentais)
                                continue;
                            }
                        }
                    }
                }

                pst.executeBatch();
                JOptionPane.showMessageDialog(null, "Snapshot salvo com sucesso para análise da Lia!");

            } catch (Exception e) {
                e.printStackTrace(); // Mostra o erro detalhado no console do NetBeans
                JOptionPane.showMessageDialog(null, "Erro ao salvar no banco: " + e.getMessage());
            }

            pst.executeBatch(); // Executa tudo de uma vez
            JOptionPane.showMessageDialog(null, "Snapshot salvo com sucesso no banco de dados para análise da Lia!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar snapshot no banco: " + e.getMessage());
        } finally {
            // Fechar conexões (ajuste conforme seus métodos de fechar)
            try {
                if (conn != null) {
                    conn.close();
                }
                if (pst != null) {
                    pst.close();
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButtonSalvaprevActionPerformed

    private void gerarPDFSnapshot(String inflacao) {
        String dataHoraAtual = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
        String nomeArquivo = "previsoes_" + dataHoraAtual + ".pdf";

        File dir = new File("snapshots");
        if (!dir.exists()) {
            dir.mkdirs();
        }
        String caminho = "snapshots/" + nomeArquivo;

        Document documento = new Document(PageSize.A4.rotate(), 30, 30, 40, 40);
        try {
            PdfWriter.getInstance(documento, new FileOutputStream(caminho));
            documento.open();

            com.itextpdf.text.Font tituloFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, BaseColor.BLACK);
            com.itextpdf.text.Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 10, BaseColor.BLACK);
            com.itextpdf.text.Font negritoFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, BaseColor.BLACK);

            documento.add(new Paragraph("SNAPSHOT DE PLANEJAMENTO - PREVISÕES", tituloFont));
            documento.add(new Paragraph("Data da Exportação: " + new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(new Date()), normalFont));
            documento.add(new Paragraph("Expectativa de Inflação/Reajuste: " + inflacao + "%", normalFont));
            documento.add(new Paragraph(" ", normalFont));

            PdfPTable pdfTable = new PdfPTable(jTablePesquisa.getColumnCount());
            pdfTable.setWidthPercentage(100);

            for (int i = 0; i < jTablePesquisa.getColumnCount(); i++) {
                PdfPCell cell = new PdfPCell(new Phrase(jTablePesquisa.getColumnName(i), negritoFont));
                cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                pdfTable.addCell(cell);
            }

            for (int rows = 0; rows < jTablePesquisa.getRowCount(); rows++) {
                for (int cols = 0; cols < jTablePesquisa.getColumnCount(); cols++) {
                    Object val = jTablePesquisa.getModel().getValueAt(rows, cols);
                    String text = (val == null) ? "" : val.toString();
                    PdfPCell cell = new PdfPCell(new Phrase(text, normalFont));

                    if (cols > 0) {
                        cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
                    }

                    pdfTable.addCell(cell);
                }
            }

            documento.add(pdfTable);
            documento.close();

            JOptionPane.showMessageDialog(this, "Snapshot salvo com sucesso:\n" + new File(caminho).getAbsolutePath());

            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(new File(caminho));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao gerar PDF: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Consulta_RC.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Consulta_RC.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Consulta_RC.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Consulta_RC.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Tela_de_Consulta_RC().setVisible(true);

                } catch (SQLException ex) {
                    Logger.getLogger(Tela_de_Consulta_RC.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupStatus;
    private javax.swing.JButton jButtonAnual;
    private javax.swing.JButton jButtonExportar;
    private javax.swing.JButton jButtonGrafico;
    private javax.swing.JButton jButtonPFechar;
    private javax.swing.JButton jButtonPImprimir;
    private javax.swing.JButton jButtonPLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvaprev;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataFim;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataIni;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelStatus;
    private javax.swing.JRadioButton jRadioButtonConf;
    private javax.swing.JRadioButton jRadioButtonPrev;
    private javax.swing.JRadioButton jRadioButtonTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisa;
    // End of variables declaration//GEN-END:variables

    public class XYLineChart extends JFrame {

        JFreeChart chart;
        double[] receitasMensais;
        double[] despesasMensais;
        double[] resultadosMensais;

        public XYLineChart(double[] receitasMensais, double[] despesasMensais, double[] resultadosMensais) throws ParseException, SQLException {
            super("Gráfico de Resultados");
            setSize(800, 600);
            setLayout(null);
            setResizable(false);
            setLocationRelativeTo(null);
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);

            this.receitasMensais = receitasMensais;
            this.despesasMensais = despesasMensais;
            this.resultadosMensais = resultadosMensais;

            crearGrafico();
            ChartPanel panel = new ChartPanel(chart, false);
            panel.setBounds(10, 20, 760, 520);
            add(panel);
            setVisible(true);
        }

        public void crearGrafico() throws ParseException, SQLException {
            XYSeries seriesReceitas = new XYSeries("Receitas");
            XYSeries seriesDespesas = new XYSeries("Despesas");
            XYSeries seriesResultados = new XYSeries("Resultados");
            XYSeries seriesSaldoFinal = new XYSeries("Saldo Final");

            DecimalFormatSymbols otherSymbols = new DecimalFormatSymbols(Locale.getDefault());
            otherSymbols.setDecimalSeparator('.');

            // Suponha que os meses sejam representados por números inteiros de 1 a 12
            for (int i = 0; i < 12; i++) {
                int mes = i + 1; // Adicionando 1 para representar os meses de 1 a 12
                // Adicionar o ponto (mês, valor formatado da receita) à série
                seriesReceitas.add(mes, receitasMensais[i]);
                seriesDespesas.add(mes, despesasMensais[i] * -1);
                seriesResultados.add(mes, resultadosMensais[i]);
                seriesSaldoFinal.add(mes, saldoFinalMensal[i]);
            }

            XYSeriesCollection dataset = new XYSeriesCollection();
            dataset.addSeries(seriesReceitas);
            dataset.addSeries(seriesDespesas);
            dataset.addSeries(seriesResultados);
            dataset.addSeries(seriesSaldoFinal);

            chart = ChartFactory.createXYLineChart(
                    "Receitas x Despesas x Resultado x Saldo Final",
                    "Meses",
                    "Valores",
                    dataset,
                    PlotOrientation.VERTICAL,
                    true, true, false
            );

            XYPlot plot = (XYPlot) chart.getPlot();
            XYLineAndShapeRenderer renderer = new XYLineAndShapeRenderer();

            // Define a cor das linhas
            renderer.setSeriesPaint(0, Color.BLUE); // Receitas
            renderer.setSeriesPaint(1, Color.RED);  // Despesas
            renderer.setSeriesPaint(2, Color.GREEN); // Resultados
            renderer.setSeriesPaint(3, new Color(255, 140, 0)); // Saldo Final (laranja)

            // Adiciona o gerador de dicas de ferramenta
            renderer.setBaseToolTipGenerator(new StandardXYToolTipGenerator(
                    StandardXYToolTipGenerator.DEFAULT_TOOL_TIP_FORMAT,
                    new DecimalFormat("0"), new DecimalFormat("0.00")));

            // Ajusta o renderer para o plot
            plot.setRenderer(renderer);

            // Ajusta o formato dos números no eixo vertical (valores)
            NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
            rangeAxis.setNumberFormatOverride(new DecimalFormat("#,##0.00"));
        }
    }

    public class ColorearTabla extends DefaultTableCellRenderer {

        private Component componente;

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            componente = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            Font font = new Font("Tahoma", Font.PLAIN, 11);

            // Verifica se o valor é uma string vazia
            if (value != null && !value.toString().isEmpty()) {
                String confere = value.toString().replaceAll(",", "");
                Double muda = Double.valueOf(confere);
                if (muda >= 0) {
                    this.setForeground(Color.black);
                    this.setHorizontalAlignment(RIGHT);
                    componente.setFont(font);
                } else {
                    this.setForeground(Color.RED);
                    this.setHorizontalAlignment(RIGHT);
                }
            } else {
                // Se o valor for uma string vazia, mantenha a cor padrão e a formatação
                this.setForeground(table.getForeground());
                this.setHorizontalAlignment(RIGHT);
            }

            return this;
        }
    }
}
