package view;


import utilitarios.Conexao;

import utilitarios.CustomTableCellRendererFat;

import com.itextpdf.text.Chunk;

import dao.ItensVendasDAO;

import dao.VendasDAO;

import model.ItensVendas;

import model.Vendas;

import java.sql.SQLException;

import java.text.NumberFormat;

import java.time.format.DateTimeParseException;

import java.util.Locale;

import java.util.logging.Level;

import java.util.logging.Logger;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

import com.itextpdf.text.Document;

import com.itextpdf.text.DocumentException;

import com.itextpdf.text.Element;

import com.itextpdf.text.Font;

import com.itextpdf.text.FontFactory;

import com.itextpdf.text.Image;

import com.itextpdf.text.Paragraph;

import com.itextpdf.text.Phrase;

import com.itextpdf.text.pdf.ColumnText;

import com.itextpdf.text.pdf.PdfPCell;

import com.itextpdf.text.pdf.PdfPTable;

import com.itextpdf.text.pdf.PdfPageEventHelper;

import com.itextpdf.text.pdf.PdfWriter;

import java.awt.Desktop;

import java.io.File;

import java.io.FileOutputStream;

import java.io.FileNotFoundException;

import java.io.IOException;

import java.sql.Connection;

import java.sql.PreparedStatement;

import java.sql.ResultSet;

import java.text.ParseException;

import java.text.SimpleDateFormat;

import java.time.LocalDate;

import java.time.format.DateTimeFormatter;

import java.util.Date;

import java.util.List;

import javax.swing.JFileChooser;



/**

 *

 * @author CARLOS

 */

public class Form_HistoricoVendas extends javax.swing.JFrame {



    // Declarações no início da classe

    Conexao conexao = new Conexao();

    private VendasDAO vendasDAO;



    /**

     * Creates new form FormularioHistorico

     */

    public Form_HistoricoVendas() {

        initComponents();

        vendasDAO = new VendasDAO();

    }



    /**

     * This method is called from within the constructor to initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is always

     * regenerated by the Form Editor.

     */

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtInicio = new javax.swing.JFormattedTextField();
        txtFim = new javax.swing.JFormattedTextField();
        btnPesquisarVenda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnGerarRelatorio = new javax.swing.JButton();
        btnApurarLucro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Histórico de Vendas");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Histórico de Vendas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta por data"));

        jLabel2.setText("Data Inicial");

        jLabel3.setText("Data Final");

        try {
            txtInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/20##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/20##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnPesquisarVenda.setText("Pesquisar");
        btnPesquisarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtFim, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btnPesquisarVenda)
                .addGap(61, 61, 61))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtFim, txtInicio});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarVenda))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cliente", "Data da Venda", "Total da Venda", "Total Acumulado", "Observações"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        btnGerarRelatorio.setText("Gerar Relatório de Faturamento");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        btnApurarLucro.setText("Apurar Lucro no Período");
        btnApurarLucro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApurarLucroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnApurarLucro)
                .addGap(54, 54, 54)
                .addComponent(btnGerarRelatorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGerarRelatorio)
                    .addComponent(btnApurarLucro)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    private void btnPesquisarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarVendaActionPerformed

        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        try {

            // Parse das datas de início e fim

            LocalDate data_inicio = LocalDate.parse(txtInicio.getText(), formato);

            LocalDate data_fim = LocalDate.parse(txtFim.getText(), formato);



            // Instanciar o DAO e fazer a consulta

            VendasDAO vd = new VendasDAO();

            List<Vendas> lista = vd.historicoVendas(data_inicio, data_fim); // Agora reconhece SQLException



            // Atualizar a tabela

            DefaultTableModel historico = (DefaultTableModel) tabela.getModel();

            historico.setNumRows(0); // Limpar tabela anterior



            // Define o formato para moeda no padrão brasileiro

            NumberFormat nf = NumberFormat.getCurrencyInstance();

            double faturamentoAcumulado = 0.0;



            for (Vendas v : lista) {

                // Formata o preço de Total da Venda

                String Total_vendaFormatado = nf.format(v.getTotal_venda());



                // Atualiza o Faturamento Acumulado

                faturamentoAcumulado += v.getTotal_venda();

                String FaturamentoAcumuladoFormatado = nf.format(faturamentoAcumulado);



                // Adiciona a nova linha com a coluna Faturamento Acumulado

                historico.addRow(new Object[]{

                    v.getId(),

                    v.getClientes().getNomeCliFor(),

                    v.getData_venda(),

                    Total_vendaFormatado,

                    FaturamentoAcumuladoFormatado, // Nova coluna com o Faturamento Acumulado

                    v.getObservacoes()

                });

            }

        } catch (DateTimeParseException ex) {

            Logger.getLogger(Form_HistoricoVendas.class.getName()).log(Level.SEVERE, "Erro ao parsear as datas!", ex);

            JOptionPane.showMessageDialog(null, "Formato de data inválido! Use dd/MM/yyyy.");

        } catch (SQLException ex) {

            Logger.getLogger(Form_HistoricoVendas.class.getName()).log(Level.SEVERE, "Erro ao consultar as vendas!", ex);

            JOptionPane.showMessageDialog(null, "Erro ao consultar as vendas: " + ex.getMessage());

        }

    }//GEN-LAST:event_btnPesquisarVendaActionPerformed



    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked

        Form_DetalheVenda fdv = new Form_DetalheVenda();

        fdv.txtIdVenda.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());

        fdv.txtCliente.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());

        fdv.txtDataVenda.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());

        fdv.txtTotalVenda.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());

        fdv.txtObs.setText(tabela.getValueAt(tabela.getSelectedRow(), 5).toString());

        int venda_id = Integer.valueOf(fdv.txtIdVenda.getText());

        ItensVendasDAO dao;



        // Formatador de números para moeda (sem números)

        @SuppressWarnings("deprecation")

        NumberFormat nf = NumberFormat.getNumberInstance(new Locale("pt", "BR"));

        nf.setMinimumFractionDigits(2);

        nf.setMaximumFractionDigits(2);



        try {

            dao = new ItensVendasDAO();

            List<ItensVendas> lista = dao.listaItens(venda_id);

            DefaultTableModel dados = (DefaultTableModel) fdv.Carrinho.getModel();

            dados.setNumRows(0); // Limpar dados anteriores



            double faturamentoAcumulado = 0.0;



            for (ItensVendas i : lista) {

                // Formata o preço e o subtotal

                String precoFormatado = nf.format(i.getProdutos().getPreco());

                String subtotalFormatado = nf.format(i.getSubtotal());

                String quantidadeFormatada = nf.format(i.getQtd()); // Formata a quantidade como double



                // Atualiza o Faturamento Acumulado

                faturamentoAcumulado += i.getSubtotal();



                // Formata o Faturamento Acumulado

                String faturamentoFormatado = nf.format(faturamentoAcumulado);



                dados.addRow(new Object[]{

                    i.getProdutos().getId(),

                    i.getProdutos().getDescricao(),

                    quantidadeFormatada, // Exibe a quantidade formatada

                    precoFormatado,

                    subtotalFormatado,

                    faturamentoFormatado // Exibe o faturamento acumulado formatado

                });

            }



            fdv.setVisible(true);



        } catch (SQLException | ClassNotFoundException ex) {

            Logger.getLogger(Form_HistoricoVendas.class.getName()).log(Level.SEVERE, null, ex);

            JOptionPane.showMessageDialog(null, "Erro ao carregar os detalhes da venda: " + ex.getMessage());

        }

    }//GEN-LAST:event_tabelaMouseClicked



    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed

        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        try {

            if (txtInicio.getText().trim().isEmpty() || txtFim.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Por favor, preencha ambas as datas.");

                return;

            }



            // Parse das datas de início e fim

            LocalDate data_inicio = LocalDate.parse(txtInicio.getText(), formato);

            LocalDate data_fim = LocalDate.parse(txtFim.getText(), formato);



            // Instanciar o DAO e fazer a consulta

            VendasDAO vd = new VendasDAO();

            List<Vendas> lista = vd.historicoVendas(data_inicio, data_fim); // Agora reconhece SQLException



            // Atualizar a tabela

            DefaultTableModel historico = (DefaultTableModel) tabela.getModel();

            historico.setNumRows(0); // Limpar tabela anterior



            @SuppressWarnings("deprecation")

            NumberFormat nf = NumberFormat.getNumberInstance(new Locale("pt", "BR"));

            nf.setMaximumFractionDigits(2);

            nf.setMinimumFractionDigits(2); // Para garantir 2 casas decimais sempre

            nf.setGroupingUsed(true); // Para habilitar separadores de milhar

            double faturamentoAcumulado = 0.0;



            for (Vendas v : lista) {

                //System.out.println("Total Venda: " + v.getTotal_venda()); // Log do valor bruto

                String Total_vendaFormatado = nf.format(v.getTotal_venda());

                faturamentoAcumulado += v.getTotal_venda();

                String FaturamentoAcumuladoFormatado = nf.format(faturamentoAcumulado);



                //System.out.println("Total Venda Formatado: " + Total_vendaFormatado); // Log do valor formatado

                //System.out.println("Faturamento Acumulado: " + FaturamentoAcumuladoFormatado);

                historico.addRow(new Object[]{

                    v.getId(),

                    v.getClientes().getNomeCliFor(),

                    v.getData_venda(),

                    Total_vendaFormatado,

                    FaturamentoAcumuladoFormatado,

                    v.getObservacoes()

                });

            }

            // Reaplicar renderização personalizada

            tabela.setDefaultRenderer(Object.class, new CustomTableCellRendererFat());



            // Gerar o PDF com o título e rodapé

            gerarRelatorioPDF(lista, nf, data_inicio, data_fim);



        } catch (DateTimeParseException ex) {

            Logger.getLogger(Form_HistoricoVendas.class.getName()).log(Level.SEVERE, "Erro ao parsear as datas!", ex);

            JOptionPane.showMessageDialog(null, "Formato de data inválido! Use dd/MM/yyyy.");

        } catch (SQLException ex) {

            Logger.getLogger(Form_HistoricoVendas.class.getName()).log(Level.SEVERE, "Erro ao consultar as vendas!", ex);

            JOptionPane.showMessageDialog(null, "Erro ao consultar as vendas: " + ex.getMessage());

        } catch (FileNotFoundException ex) {

            Logger.getLogger(Form_HistoricoVendas.class.getName()).log(Level.SEVERE, null, ex);

        } catch (DocumentException | IOException ex) {

            Logger.getLogger(Form_HistoricoVendas.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_btnGerarRelatorioActionPerformed



    private void btnApurarLucroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApurarLucroActionPerformed

        try {

            // Formato das datas de entrada (usuário)

            SimpleDateFormat inputFormat = new SimpleDateFormat("dd/MM/yyyy");

            SimpleDateFormat sqlFormat = new SimpleDateFormat("yyyy-MM-dd");



            // Converter as datas de entrada para o formato do banco

            Date inicio = inputFormat.parse(txtInicio.getText().trim());

            Date fim = inputFormat.parse(txtFim.getText().trim());

            String dataInicio = sqlFormat.format(inicio);

            String dataFim = sqlFormat.format(fim);



            conexao.abrirConexao(); // Abre a conexão

            Connection con = conexao.getConexao(); // Obtém a conexão



            // Consulta SQL ajustada para considerar a coluna subtotal e calcular corretamente o lucro

            PreparedStatement stmt = con.prepareStatement(

                    "SELECT DATE(v.data_venda) AS data, iv.subtotal, iv.precoMedioCusto, iv.qtd, "

                    + "(iv.subtotal / iv.qtd) - iv.precoMedioCusto AS lucro "

                    + "FROM tb_vendas v "

                    + "INNER JOIN tb_itensvendas iv ON v.id = iv.venda_id "

                    + "WHERE DATE(v.data_venda) BETWEEN ? AND ? "

                    + "ORDER BY DATE(v.data_venda)"

            );



            // Passar os parâmetros no formato correto

            stmt.setString(1, dataInicio);

            stmt.setString(2, dataFim);



            ResultSet rs = stmt.executeQuery();

            

            // Obtém o caminho para a área de Trabalho

            String desktopPath = javax.swing.filechooser.FileSystemView.getFileSystemView().getHomeDirectory().getAbsolutePath();



            // Configuração do JFileChooser

            JFileChooser fileChooser = new JFileChooser();

            fileChooser.setDialogTitle("Salvar Relatório");

            fileChooser.setCurrentDirectory(new File(desktopPath)); // Define a área de Trabalho como diretório inicial



            // Exibe a janela para o usuário escolher o local e nome do arquivo

            int escolha = fileChooser.showSaveDialog(null);

            if (escolha != JFileChooser.APPROVE_OPTION) {

                return; // Sai do método se o usuário cancelar a operação

            }



            // Recupera o arquivo selecionado e garante a extensão .pdf

            File arquivo = fileChooser.getSelectedFile();

            if (!arquivo.getName().endsWith(".pdf")) {

                arquivo = new File(arquivo.getAbsolutePath() + ".pdf");

            }



            // Criação do documento PDF

            Document document = new Document();

            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(arquivo));

            document.open();



            // Adiciona a imagem

            Image imagem = null;

            try {

                imagem = Image.getInstance("src/Imagens/Home.png"); // Certifique-se do caminho da imagem

                imagem.scaleAbsolute(45f, 50f);

                imagem.setAlignment(Element.ALIGN_LEFT);

                document.add(imagem);

            } catch (DocumentException | IOException e) {

                JOptionPane.showMessageDialog(null, "Imagem não encontrada: " + e.getMessage());

            }



            // Adiciona o título

            Paragraph titulo = new Paragraph(

                    "Apuração de resultados - referente ao período de: " + inputFormat.format(inicio) + " até " + inputFormat.format(fim),

                    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14)

            );

            titulo.setAlignment(Element.ALIGN_CENTER);

            titulo.setSpacingAfter(10f); // Adiciona espaçamento abaixo do título

            document.add(titulo);



            // Criação da tabela no PDF (com 4 colunas)

            PdfPTable table = new PdfPTable(4);

            table.setWidthPercentage(100);

            table.setWidths(new float[]{2, 2, 2, 2}); // Define as larguras das colunas



            // Cabeçalhos da tabela

            table.addCell("Data");

            table.addCell("Faturado");

            table.addCell("Custo Médio");

            table.addCell("Lucro");



            // Variáveis para os totais

            double totalFaturado = 0;

            double totalLucro = 0;



            // Gerar conteúdo da tabela no PDF

            while (rs.next()) {

                // Obtenção da data

                String data = rs.getString("data");



                // Formatar a data para o formato 'dd/MM/yyyy'

                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

                Date date = java.sql.Date.valueOf(data); // Convertendo para tipo Date

                String formattedData = dateFormat.format(date); // Formatação



                double subtotal = rs.getDouble("subtotal");

                double precoMedioCusto = rs.getDouble("precoMedioCusto");

                double qtd = rs.getDouble("qtd");

                double lucro = rs.getDouble("lucro");



                // Formatação para valores monetários

                String formattedSubtotal = String.format("%.2f", subtotal).replace('.', ',');

                String formattedPrecoMedioCusto = String.format("%.2f", precoMedioCusto).replace('.', ',');

                String formattedLucro = String.format("%.2f", lucro).replace('.', ',');



                // Adiciona as células da tabela

                table.addCell(formattedData); // Aqui está a data formatada

                table.addCell(formattedSubtotal);

                table.addCell(formattedPrecoMedioCusto);

                table.addCell(formattedLucro);



                // Calcula os totais

                totalFaturado += subtotal;

                totalLucro += lucro;

            }



            // Adicionar linha de totais

            table.addCell("Totais:");

            table.addCell(String.format("%.2f", totalFaturado).replace('.', ','));

            table.addCell("");

            table.addCell(String.format("%.2f", totalLucro).replace('.', ','));

            table.addCell("");

            

            // Adiciona rodapé no PDF

            writer.setPageEvent(new PdfPageEventHelper() {

                @Override

                public void onEndPage(PdfWriter writer, Document document) {

                    String footerText = "Gerado em " + LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))

                            + " - Pág. " + writer.getPageNumber();

                    ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_RIGHT, new Phrase(footerText),

                            document.right() - 30, document.bottom() - 10, 0); // Ajusta o rodapé à direita

                }

            });

            

            // Adiciona a tabela ao documento PDF

            document.add(table);

            

            // Fecha o documento

            document.close();

            JOptionPane.showMessageDialog(null, "Relatório gerado com sucesso em: " + arquivo.getAbsolutePath());

            

            // Abre o PDF para visualização

            Desktop.getDesktop().open(arquivo);



            rs.close();

            stmt.close();

            con.close();

            //JOptionPane.showMessageDialog(null, "Relatório gerado com sucesso!");

        } catch (ParseException e) {

            JOptionPane.showMessageDialog(null, "Erro: Insira as datas no formato dd/MM/yyyy.");

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Erro ao buscar os dados no banco: " + e.getMessage());

        } catch (Exception ex) {

            Logger.getLogger(Form_HistoricoVendas.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_btnApurarLucroActionPerformed



    private void gerarRelatorioPDF(List<Vendas> lista, NumberFormat nf, LocalDate data_inicio, LocalDate data_fim) throws FileNotFoundException, DocumentException, IOException {



        // Obtém o caminho para a área de Trabalho

        String desktopPath = javax.swing.filechooser.FileSystemView.getFileSystemView().getHomeDirectory().getAbsolutePath();



        // Configuração do JFileChooser

        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setDialogTitle("Salvar Relatório");

        fileChooser.setCurrentDirectory(new File(desktopPath)); // Define a área de Trabalho como diretório inicial



        // Exibe a janela para o usuário escolher o local e nome do arquivo

        int escolha = fileChooser.showSaveDialog(null);

        if (escolha != JFileChooser.APPROVE_OPTION) {

            return; // Sai do método se o usuário cancelar a operação

        }



        // Recupera o arquivo selecionado e garante a extensão .pdf

        File arquivo = fileChooser.getSelectedFile();

        if (!arquivo.getName().endsWith(".pdf")) {

            arquivo = new File(arquivo.getAbsolutePath() + ".pdf");

        }



        // Criação do documento PDF

        Document document = new Document();

        PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(arquivo));

        document.open();



        // Adiciona a imagem

        Image imagem = null;

        try {

            imagem = Image.getInstance("src/Imagens/Home.png"); // Certifique-se do caminho da imagem

            imagem.scaleAbsolute(45f, 50f);

            imagem.setAlignment(Element.ALIGN_LEFT);

            document.add(imagem);

        } catch (DocumentException | IOException e) {

            JOptionPane.showMessageDialog(null, "Imagem não encontrada: " + e.getMessage());

        }



        // Adiciona título com a data

        String titulo = "Faturamento referente ao período de: " + data_inicio.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))

                + " até " + data_fim.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));

        Paragraph pTitulo = new Paragraph(titulo, new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD));

        pTitulo.setAlignment(Element.ALIGN_CENTER);

        document.add(pTitulo);

        document.add(new Chunk("\n")); // Espaço entre o título e a tabela



        // Criação da tabela no PDF

        PdfPTable tabelaPDF = new PdfPTable(6);

        tabelaPDF.setWidths(new float[]{1, 3, 2, 2, 2, 3}); // Ajuste das larguras das colunas

        tabelaPDF.addCell("ID Venda");

        tabelaPDF.addCell("Nome Cliente");

        tabelaPDF.addCell("Data Venda");

        tabelaPDF.addCell("Total Venda");

        tabelaPDF.addCell("Fat.Acum.");

        tabelaPDF.addCell("Obs.");



        double faturamentoAcumulado = 0.0;

        for (Vendas v : lista) {

            tabelaPDF.addCell(new PdfPCell(new Phrase(String.valueOf(v.getId())))); // ID Cliente

            tabelaPDF.addCell(new PdfPCell(new Phrase(v.getClientes().getNomeCliFor()))); // Nome Cliente



            // Formata a data

            try {

                if (v.getData_venda() != null && !v.getData_venda().isEmpty()) {

                    LocalDate dataVenda = LocalDate.parse(v.getData_venda(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));

                    tabelaPDF.addCell(new PdfPCell(new Phrase(dataVenda.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")))));

                } else {

                    tabelaPDF.addCell(new PdfPCell(new Phrase("Data Inválida")));

                }

            } catch (DateTimeParseException e) {

                System.err.println("Erro ao parsear a data: " + v.getData_venda());

                tabelaPDF.addCell(new PdfPCell(new Phrase("Data Inválida")));

            }



            // Formata o total da venda

            String totalVendaFormatado = nf.format(v.getTotal_venda());

            tabelaPDF.addCell(new PdfPCell(new Phrase(totalVendaFormatado)));



            // Calcula e formata o faturamento acumulado

            faturamentoAcumulado += v.getTotal_venda();

            String faturamentoAcumuladoFormatado = nf.format(faturamentoAcumulado);

            tabelaPDF.addCell(new PdfPCell(new Phrase(faturamentoAcumuladoFormatado)));



            // Observações

            tabelaPDF.addCell(new PdfPCell(new Phrase(v.getObservacoes() != null ? v.getObservacoes() : "")));

        }

        // Adiciona rodapé no PDF

        writer.setPageEvent(new PdfPageEventHelper() {

            @Override

            public void onEndPage(PdfWriter writer, Document document) {

                String footerText = "Gerado em " + LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))

                        + " - Pág. " + writer.getPageNumber();

                ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_RIGHT, new Phrase(footerText),

                        document.right() - 30, document.bottom() - 10, 0); // Ajusta o rodapé à direita

            }

        });



        document.add(tabelaPDF);

        document.close();

        

        JOptionPane.showMessageDialog(null, "Relatório gerado com sucesso em: " + arquivo.getAbsolutePath());



        // Abre o PDF para visualização

        Desktop.getDesktop().open(arquivo);

    }



    /**

     * @param args the command line arguments

     */

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 

         */

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Windows".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;

                }

            }

        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(Form_HistoricoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(Form_HistoricoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(Form_HistoricoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(Form_HistoricoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>



        /* Create and display the form */

        java.awt.EventQueue.invokeLater(() -> {

            new Form_HistoricoVendas().setVisible(true);

        });

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApurarLucro;
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JButton btnPesquisarVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JFormattedTextField txtFim;
    private javax.swing.JFormattedTextField txtInicio;
    // End of variables declaration//GEN-END:variables

}

