package view;


import utilitarios.Conexao;

import dao.CliForDAO;

import dao.ProdutosDAO;

import java.awt.HeadlessException;

import model.Produtos;

import utilitarios.LimpaTela;

import java.awt.event.KeyEvent;

import java.sql.Connection;

import java.sql.PreparedStatement;

import java.sql.ResultSet;

import java.sql.SQLException;

import java.text.SimpleDateFormat;

import java.util.Date;

import java.util.List;

import java.util.logging.Level;

import java.util.logging.Logger;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

import java.text.NumberFormat;

import java.text.ParseException;

import java.util.ArrayList;

import java.util.Locale;

import javax.swing.JComboBox;

import javax.swing.text.MaskFormatter;

import model.CliFor;

import model.ItensVendas;



/**

 *

 * @author CARLOS

 */

public class Form_Vendas extends javax.swing.JFrame {



    public List<ItensVendas> itensVendas = new ArrayList<>();

    public DefaultTableModel meus_produtos; // Declare a tabela de produtos

    CarregarCbx rf = new CarregarCbx(); //Carrega combobox de Clientes



    public Form_Vendas() throws SQLException {

        initComponents();



        rf.CarregarCbx("tbclifor", "nomeCliFor", cbxClientes);



        // Inicializa o modelo da tabela e associa à jTable

        meus_produtos = new DefaultTableModel(new Object[]{"ID", "Descrição", "Quantidade", "Preço", "Subtotal"}, 0);

        Carrinho.setModel(meus_produtos); // Associa o modelo ao jTable

    }



    /**

     * This method is called from within the constructor to initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is always

     * regenerated by the Form Editor.

     */

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painel_Cliente = new javax.swing.JPanel();
        txtData = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPesquisaProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        cbxClientes = new javax.swing.JComboBox<>();
        jTextFieldid = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        painel_produto = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtProduto = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        txtEstoque = new javax.swing.JTextField();
        txtQtd = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JFormattedTextField();
        btnAdicionar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        painel_Carrinho = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Carrinho = new javax.swing.JTable();
        painel_Venda = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtTotalVenda = new javax.swing.JTextField();
        btnPagamento = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ponto de Vendas");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-Ponto de Vendas-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel_Cliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel2.setText("CPF :");

        jLabel3.setText("Data :");

        jLabel4.setText("Nome:");

        jLabel5.setText("Pesquise um produto aqui :");

        txtPesquisaProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaProdutoKeyReleased(evt);
            }
        });

        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "descrição", "preço", "qtd. estoque", "fornecedor"
            }
        ));
        tabelaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProduto);

        cbxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbxClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_ClienteLayout = new javax.swing.GroupLayout(painel_Cliente);
        painel_Cliente.setLayout(painel_ClienteLayout);
        painel_ClienteLayout.setHorizontalGroup(
            painel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_ClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_ClienteLayout.createSequentialGroup()
                        .addGroup(painel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painel_ClienteLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painel_ClienteLayout.createSequentialGroup()
                                .addGroup(painel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painel_ClienteLayout.createSequentialGroup()
                                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painel_ClienteLayout.createSequentialGroup()
                                        .addComponent(cbxClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(20, 20, 20))))
        );
        painel_ClienteLayout.setVerticalGroup(
            painel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_ClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
        );

        painel_produto.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));

        jLabel6.setText("Código:");

        jLabel7.setText("Produto:");

        jLabel8.setText("Preço:");

        jLabel9.setText("Estoque:");

        jLabel10.setText("Qtd. :");

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        txtProduto.setEnabled(false);

        txtPreco.setEnabled(false);

        txtEstoque.setEnabled(false);

        txtQtd.setText("1");

        jLabel11.setText("Desconto %");

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdicionar.setText("ADD ITEM");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_produtoLayout = new javax.swing.GroupLayout(painel_produto);
        painel_produto.setLayout(painel_produtoLayout);
        painel_produtoLayout.setHorizontalGroup(
            painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_produtoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painel_produtoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_produtoLayout.createSequentialGroup()
                        .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel_produtoLayout.createSequentialGroup()
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtProduto)))
                    .addGroup(painel_produtoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEstoque)
                        .addGap(177, 177, 177)))
                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpar)
                    .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnPesquisar)
                        .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        painel_produtoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdicionar, btnLimpar});

        painel_produtoLayout.setVerticalGroup(
            painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_produtoLayout.createSequentialGroup()
                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProduto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painel_produtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        painel_produtoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdicionar, btnLimpar});

        painel_Carrinho.setBorder(javax.swing.BorderFactory.createTitledBorder("Carrinho de Compras"));

        Carrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Qtd.", "Preço", "Subtotall"
            }
        ));
        jScrollPane3.setViewportView(Carrinho);

        javax.swing.GroupLayout painel_CarrinhoLayout = new javax.swing.GroupLayout(painel_Carrinho);
        painel_Carrinho.setLayout(painel_CarrinhoLayout);
        painel_CarrinhoLayout.setHorizontalGroup(
            painel_CarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );
        painel_CarrinhoLayout.setVerticalGroup(
            painel_CarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_CarrinhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        painel_Venda.setBorder(javax.swing.BorderFactory.createTitledBorder("Total da Venda"));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Total da Venda : ");

        txtTotalVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalVendaActionPerformed(evt);
            }
        });

        btnPagamento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPagamento.setText("PAGAMENTO");
        btnPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagamentoActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setText("CANCELAR VENDA");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_VendaLayout = new javax.swing.GroupLayout(painel_Venda);
        painel_Venda.setLayout(painel_VendaLayout);
        painel_VendaLayout.setHorizontalGroup(
            painel_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_VendaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_VendaLayout.createSequentialGroup()
                        .addComponent(btnPagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addComponent(txtTotalVenda))
                .addContainerGap())
        );

        painel_VendaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelar, btnPagamento});

        painel_VendaLayout.setVerticalGroup(
            painel_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_VendaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painel_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        painel_VendaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelar, btnPagamento});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painel_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel_produto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel_Carrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel_Venda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painel_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painel_Carrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painel_Venda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painel_produto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void listar() throws SQLException, ClassNotFoundException {

        ProdutosDAO dao = new ProdutosDAO();

        List<Produtos> lista = dao.Listar();

        DefaultTableModel dados = (DefaultTableModel) tabelaProduto.getModel();

        dados.setNumRows(0);



        // Define o formato para moeda no padrão brasileiro

        NumberFormat nf = NumberFormat.getCurrencyInstance(); // ou ajuste para seu formato desejado



        for (Produtos p : lista) {

            String precoVendaFormatado = nf.format(p.getPrecoVenda());

            String qtdEstoqueFormatada = String.format("%.3f", p.getQtd_estoque());



            dados.addRow(new Object[]{

                p.getId(),

                p.getDescricao(),

                precoVendaFormatado, // Exibe o preço de venda formatado

                qtdEstoqueFormatada, // Exibe a quantidade formatada

                p.getCliFor().getNomeCliFor()

            });

        }

    }

    CliFor obj = new CliFor();

    double preco, subtotal, total;



    /**

     * Creates new form FormularioVendas

     */

    int qtd;



    /**

     * Creates new form FormularioVendas

     */

    public void setMeusProdutos(DefaultTableModel meus_produtos) {

        this.meus_produtos = meus_produtos; // Armazena o modelo de tabela passado

    }



    private void tabelaProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutoMouseClicked

        txtCodigo.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 0).toString());

        txtProduto.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 1).toString());

        txtPreco.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 2).toString()); // aqui estou pegando o preço de venda da tabelaProduto



        // Obtém a quantidade do estoque

        String estoqueStr = tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 3).toString();



        // Remove vírgulas antes da conversão, se necessário

        estoqueStr = estoqueStr.replace(".", ""); // Remove o ponto para milhar (se houver)

        estoqueStr = estoqueStr.replace(",", "."); // Substitui a vírgula por ponto para o formato decimal



        // Converte a string em double

        double estoque = Double.parseDouble(estoqueStr);



        // Formata o valor como double com 3 casas decimais

        String estoqueFormatado = String.format("%.3f", estoque);

        txtEstoque.setText(estoqueFormatado);



        txtCodigo.setEnabled(false);

    }//GEN-LAST:event_tabelaProdutoMouseClicked



    private void txtTotalVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalVendaActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_txtTotalVendaActionPerformed



    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        try {

            listar();

            Date agora = new Date();

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

            String dataFormatada = formato.format(agora);

            txtData.setText(String.valueOf(dataFormatada));

        } catch (SQLException | ClassNotFoundException ex) {

            Logger.getLogger(Form_Vendas.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_formWindowActivated



    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            int id = Integer.valueOf(txtCodigo.getText());

            Produtos obj = new Produtos();

            ProdutosDAO dao;

            try {

                dao = new ProdutosDAO();

                obj = dao.BuscarProdutosCodigo(id);

                if (obj.getId() != 0) {

                    txtCodigo.setText(String.valueOf(obj.getId()));

                    txtProduto.setText(obj.getDescricao());

                    txtPreco.setText(String.valueOf(obj.getPreco()));



                    // Obtém a quantidade do estoque e formata como double com 3 casas decimais

                    String estoqueFormatado = String.format("%.3f", obj.getQtd_estoque());

                    txtEstoque.setText(estoqueFormatado);



                    txtCodigo.setEnabled(false);

                } else {

                    JOptionPane.showMessageDialog(null, "Código inválido!");

                }

            } catch (SQLException | ClassNotFoundException ex) {

                Logger.getLogger(Form_Vendas.class.getName()).log(Level.SEVERE, null, ex);

            }

        }

    }//GEN-LAST:event_txtCodigoKeyPressed



    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        LimpaTela util = new LimpaTela();

        util.LimpaTela(painel_produto);

        txtCodigo.setEnabled(true);

        txtCodigo.requestFocus();

    }//GEN-LAST:event_btnLimparActionPerformed



    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed



        int id = Integer.valueOf(txtCodigo.getText());

        Produtos obj = new Produtos();

        ProdutosDAO dao;

        try {

            dao = new ProdutosDAO();

            obj = dao.BuscarProdutosCodigo(id);

            if (obj.getId() != 0) {

                txtCodigo.setText(String.valueOf(obj.getId()));

                txtProduto.setText(obj.getDescricao());

                txtPreco.setText(String.valueOf(obj.getPreco()));



                // Formata a quantidade do estoque como double com 3 casas decimais

                String estoqueFormatado = String.format("%.3f", obj.getQtd_estoque());

                txtEstoque.setText(estoqueFormatado);



                txtCodigo.setEnabled(false);

            } else {

                JOptionPane.showMessageDialog(null, "Código inválido!");

            }

        } catch (SQLException | ClassNotFoundException ex) {

            Logger.getLogger(Form_Vendas.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_btnPesquisarActionPerformed



    private void txtPesquisaProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaProdutoKeyReleased

        String nome = "%" + txtPesquisaProduto.getText() + "%";

        ProdutosDAO dao;

        try {

            dao = new ProdutosDAO();

            List<Produtos> lista = dao.Filtrar(nome);

            DefaultTableModel dados = (DefaultTableModel) tabelaProduto.getModel();

            dados.setNumRows(0);



            // Define o formato para moeda no padrão brasileiro

            NumberFormat nfPreco = NumberFormat.getCurrencyInstance();



            for (Produtos p : lista) {

                // Formata o preço

                String precoFormatado = nfPreco.format(p.getPreco());



                // Formata a quantidade como double com 3 casas decimais

                String estoqueFormatado = String.format("%.3f", p.getQtd_estoque());



                dados.addRow(new Object[]{

                    p.getId(),

                    p.getDescricao(),

                    precoFormatado, // Preço formatado

                    estoqueFormatado, // Quantidade formatada

                    p.getCliFor().getNomeCliFor()

                });

                txtCodigo.setEnabled(false);

            }

        } catch (SQLException | ClassNotFoundException ex) {

            Logger.getLogger(Form_Produtos.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_txtPesquisaProdutoKeyReleased



    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        String nome = txtProduto.getText();

        try {

            double estoque = Double.valueOf(txtEstoque.getText().replace(".", "").replace(",", "."));

            double quantidade = Double.valueOf(txtQtd.getText().replace(".", "").replace(",", "."));



            String precoText = txtPreco.getText();

            //System.out.println("Preço no campo txtPreco: " + precoText);



            // Utiliza NumberFormat para parsear a string de moeda

            @SuppressWarnings("deprecation")

            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));

            Number number = nf.parse(precoText);

            double preco = number.doubleValue();

            //System.out.println("Preço após parse: " + preco);



            double subtotal = preco * quantidade;

            total += subtotal; // Acumula o total da venda



            // Verifica se a quantidade é maior que o estoque

            if (estoque >= quantidade) {

                txtTotalVenda.setText(formatarDoubleParaMoeda(total)); // Formata o total em moeda



                // Recupera o ID do produto com base no nome

                ProdutosDAO produtosDAO = new ProdutosDAO();

                Produtos obj = produtosDAO.buscarPorNome(nome); // Método que retorna o produto pelo nome

                if (obj == null) {

                    JOptionPane.showMessageDialog(this, "Produto não encontrado no sistema!");

                    return;

                }



                // Adiciona o produto na tabela

                meus_produtos.addRow(new Object[]{

                    obj.getId(), // Adiciona o ID do produto

                    obj.getDescricao(),

                    String.format("%.3f", quantidade).replace(".", ","), // Formata a quantidade

                    formatarDoubleParaMoeda(preco), // Formata o preço em moeda

                    formatarDoubleParaMoeda(subtotal) // Formata o subtotal em moeda

                });



                // Cria um objeto ItensVendas e adiciona na lista

                ItensVendas itemVenda = new ItensVendas();

                itemVenda.setProdutos(obj); // Associa o produto completo

                itemVenda.setQtd(quantidade);

                itemVenda.setSubtotal(subtotal);

                itensVendas.add(itemVenda); // Armazena na lista de itens da venda

            } else {

                JOptionPane.showMessageDialog(null, "Quantidade é maior que o seu estoque!!!");

            }

        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(null, "Verifique os valores inseridos! Eles devem ser válidos.");

        } catch (HeadlessException | ClassNotFoundException | SQLException | ParseException ex) {

            Logger.getLogger(Form_Vendas.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_btnAdicionarActionPerformed





    private void btnPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagamentoActionPerformed

        String nome = "";

        if (cbxClientes.getSelectedItem() != null) {

            nome = cbxClientes.getSelectedItem().toString();

        } else {

            JOptionPane.showMessageDialog(this, "Nenhum cliente selecionado!");

            return; // Sai do método caso não tenha cliente selecionado

        }

        String cpf = txtCpf.getText();

        CliFor obj = new CliFor();

        CliForDAO daoc;

        try {

            daoc = new CliForDAO();

            obj = daoc.BuscarCliente(nome);

            obj = daoc.BuscarClienteCPF(cpf);

            if (obj.getNomeCliFor()!= null && obj.getCpf() != null) {

                Form_Pagamentos telaPag = new Form_Pagamentos();

                telaPag.clientes = obj;



                // Passar o modelo de tabela para o FormularioPagamentos

                telaPag.setMeusProdutos(meus_produtos);



                // Crie uma lista de ItensVendas e preencha com os produtos selecionados

                List<ItensVendas> itensVendas = new ArrayList<>();

                for (int i = 0; i < meus_produtos.getRowCount(); i++) {

                    ItensVendas item = new ItensVendas();

                    Produtos p = new Produtos();



                    // Verificar se o valor do ID não é nulo antes de converter

                    Object idValue = meus_produtos.getValueAt(i, 0);

                    if (idValue == null) {

                        JOptionPane.showMessageDialog(this, "Erro: Produto sem ID na linha " + (i + 1));

                        continue; // Pule esta iteração do loop

                    }



                    p.setId(Integer.valueOf(idValue.toString()));  // Id do produto



                    // Verificar se a quantidade não é nula

                    Object qtdValue = meus_produtos.getValueAt(i, 2);

                    if (qtdValue == null) {

                        JOptionPane.showMessageDialog(this, "Erro: Produto sem quantidade na linha " + (i + 1));

                        continue;

                    }

                    item.setQtd(Double.valueOf(qtdValue.toString().replace(".", "").replace(",", ".")));  // Quantidade



                    // Verificar se o subtotal não é nulo

                    Object subtotalValue = meus_produtos.getValueAt(i, 4);

                    if (subtotalValue == null) {

                        JOptionPane.showMessageDialog(this, "Erro: Produto sem subtotal na linha " + (i + 1));

                        continue;

                    }

                    double subtotal = formatarMoedaParaDouble(subtotalValue.toString());

                    item.setSubtotal(subtotal);



                    item.setProdutos(p);

                    itensVendas.add(item);

                }



                // Passa a lista de itens de venda para o FormularioPagamentos

                telaPag.itensVendas = itensVendas;



                // Formata diretamente o valor total para moeda e exibe no campo txtTotalVenda

                telaPag.txtTotalVenda.setText(formatarDoubleParaMoeda(total));



                // Exibe o formulário de pagamento

                telaPag.setVisible(true);

                this.dispose();

            } else {

                JOptionPane.showMessageDialog(null, "Verifique se esqueceu alguma informação(NOME e/ou CPF)!");

            }



        } catch (SQLException | ClassNotFoundException ex) {

            Logger.getLogger(Form_Vendas.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_btnPagamentoActionPerformed



    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        // Limpar dados após finalização

        itensVendas.clear();

        total = 0;

        txtTotalVenda.setText(""); // Limpa o total de compra



        // Limpa os painéis

        new LimpaTela().LimpaTela(painel_Cliente);

        new LimpaTela().LimpaTela(painel_produto);

        new LimpaTela().LimpaTela(painel_Carrinho);

        new LimpaTela().LimpaTela(painel_Venda);



        // Limpar a jTable do carrinho

        DefaultTableModel model = (DefaultTableModel) Carrinho.getModel();

        model.setRowCount(0); // Remove todas as linhas

    }//GEN-LAST:event_btnCancelarActionPerformed



    private void cbxClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClientesActionPerformed



        // Obtém o valor selecionado

        String selectedValue = cbxClientes.getSelectedItem().toString().trim();

        //System.out.println("Selected Value: " + selectedValue);



        // Localiza o primeiro traço no valor selecionado

        int indexDoTraco = selectedValue.indexOf("-");

        if (indexDoTraco != -1) {

            // Pega tudo que vem após o traço

            String documentoCompleto = selectedValue.substring(indexDoTraco + 1).trim(); // Remove espaços adicionais



            //System.out.println("Documento extraído: " + documentoCompleto);



            // Verifica o tamanho do documento para identificar CPF ou CNPJ

            if (documentoCompleto.length() == 14) {

                txtCpf.setText(documentoCompleto); // Preenche como CPF

                //System.out.println("Documento identificado como CPF: " + documentoCompleto);

            } else if (documentoCompleto.length() == 18) {

                txtCpf.setText(documentoCompleto); // Preenche como CNPJ

                //System.out.println("Documento identificado como CNPJ: " + documentoCompleto);

            } else {

                JOptionPane.showMessageDialog(this, "Documento inválido! Verifique o formato.");

            }

        } else {

            JOptionPane.showMessageDialog(this, "Formato inválido: cliente selecionado não contém um CPF ou CNPJ!");

        }

    }//GEN-LAST:event_cbxClientesActionPerformed



    private String formatarCPF(String cpf) {

        try {

            MaskFormatter formatter = new MaskFormatter("###.###.###-##");

            formatter.setValueContainsLiteralCharacters(false);

            return formatter.valueToString(cpf.replaceAll("\\D", "")); // Remove caracteres não numéricos antes de formatar

        } catch (Exception e) {

            e.printStackTrace();

            return cpf; // Retorna o CPF sem formatação em caso de erro

        }

    }



    private double formatarMoedaParaDouble(String valor) {

        try {

            // Exibe o valor original para análise

            //System.out.println("Valor original antes de limpar: " + valor);



            // Remove o números "R$", remove todos os tipos de espaço (incluindo espaços invisíveis), pontos e vírgulas

            String valorLimpo = valor.replace("R$", "").replace("\u00A0", "").trim().replace(".", "").replace(",", ".");



            // Exibe o valor limpo antes de converter

            //System.out.println("Valor limpo: " + valorLimpo);

            return Double.parseDouble(valorLimpo);

        } catch (NumberFormatException e) {

            System.out.println("Erro ao converter o valor: " + valor);

            return 0;

        }

    }



    public String formatarDoubleParaMoeda(double valor) {

        @SuppressWarnings("deprecation")

        NumberFormat nf = NumberFormat.getNumberInstance(new Locale("pt", "BR"));

        nf.setMinimumFractionDigits(2);

        nf.setMaximumFractionDigits(2);

        return nf.format(valor);

    }



    /**

     * @param args the command line arguments

     */

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 

         */

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Windows".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;

                }

            }

        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(Form_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(Form_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(Form_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(Form_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>



        /* Create and display the form */

        java.awt.EventQueue.invokeLater(() -> {

            try {

                new Form_Vendas().setVisible(true);

            } catch (SQLException ex) {

                Logger.getLogger(Form_Vendas.class.getName()).log(Level.SEVERE, null, ex);

            }

        });

    }



    private static class CarregarCbx {



        @SuppressWarnings({"empty-statement", "unchecked"})

        public void CarregarCbx(String tabela, String valor, JComboBox combo) throws SQLException {

            String sql = "Select * FROM " + tabela + " WHERE Tipo = 'CLI' ORDER BY nomeCliFor";

            // Cria uma instância da classe Conexao

            Conexao conexao = new Conexao();

            try {

                // Abre a conexão

                conexao.abrirConexao();



                // Obtém a conexão

                Connection con = conexao.getConexao();

                PreparedStatement stmt = con.prepareStatement(sql);

                ResultSet rs = stmt.executeQuery();

                while (rs.next()) {

                    combo.addItem(rs.getString(valor) + "-" + (rs.getString("cpf")));

                }

                rs.close();

                con.close();

            } catch (SQLException ex) {

                Logger.getLogger(Tela_Mov.class

                        .getName()).log(Level.SEVERE, null, ex);

            } finally {

                // Fecha a conexão no final

                conexao.fecharConexao();

            }

        }

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Carrinho;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPagamento;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cbxClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JPanel painel_Carrinho;
    private javax.swing.JPanel painel_Cliente;
    private javax.swing.JPanel painel_Venda;
    private javax.swing.JPanel painel_produto;
    private javax.swing.JTable tabelaProduto;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JFormattedTextField txtDesconto;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtPesquisaProduto;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtTotalVenda;
    // End of variables declaration//GEN-END:variables

}

