package view;



import dao.ProdutosDAO;

import model.Produtos;

import utilitarios.LimpaTela;

import java.awt.event.KeyEvent;

import java.math.BigDecimal;

import java.math.RoundingMode;

import java.sql.Connection;

import java.sql.SQLException;

import java.text.NumberFormat;

import java.text.ParseException;

import java.util.List;

import java.util.Locale;

import java.util.logging.Level;

import java.util.logging.Logger;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

import utilitarios.Conexao;

import dao.CliForDAO;

import model.CliFor;



public class Form_Estoque extends javax.swing.JDialog {



    private Conexao conexao;



    private CliFor fornecedorSelecionado; // Atributo para armazenar o fornecedor selecionado

    int idProduto, qtd_atualizada;



    /**

     * Creates new form FormularioClientes

     *

     * @throws java.sql.SQLException

     * @throws java.lang.ClassNotFoundException

     */

    public void listar() throws SQLException, ClassNotFoundException {



        ProdutosDAO dao = new ProdutosDAO();

        List<Produtos> lista = dao.Listar();

        DefaultTableModel dados = (DefaultTableModel) tabela.getModel();

        dados.setNumRows(0);



        // Configura o formato de moeda brasileira

        @SuppressWarnings("deprecation")

        NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));



        for (Produtos p : lista) {

            // Formata o preço do produto

            String precoFormatado = nf.format(p.getPrecoMedioCusto());



            // Formata a quantidade com 3 casas decimais

            String qtdEstoqueFormatada = String.format("%.3f", p.getQtd_estoque());

            String qtdEstoqueFormatadaMinima = String.format("%.3f", p.getQtd_estoqueMinimo());

            String qtdEstoqueFormatadaMaxima = String.format("%.3f", p.getQtd_estoqueMaximo());



            // Adiciona a linha na tabela com o preço e quantidade formatados

            dados.addRow(new Object[]{

                p.getId(),

                p.getDescricao(),

                precoFormatado, // Preço formatado como moeda

                qtdEstoqueFormatada, // Quantidade formatada com 3 casas decimais

                qtdEstoqueFormatadaMinima, // Quantidade formatada com 3 casas decimais

                qtdEstoqueFormatadaMaxima, // Quantidade formatada com 3 casas decimais

                p.getCliFor().getNomeCliFor()

            });

        }

    }



    public Form_Estoque(java.awt.Frame parent, boolean modal) {

        super(parent, modal);

        initComponents();



        //Instanciando a classe

        conexao = new Conexao();

    }



    /**

     * This method is called from within the constructor to initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is always

     * regenerated by the Form Editor.

     */

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painel_guias = new javax.swing.JTabbedPane();
        painel_estoque = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtQtdAtual = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQtd_Nova = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtEstoqueMaximo = new javax.swing.JTextField();
        txtPrecoAtual = new javax.swing.JTextField();
        txtPrecoNovo = new javax.swing.JTextField();
        txtEstoqueMinimo = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Estoque");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estoque");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel_guias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel2.setText("Código");

        jLabel3.setText("Descrição");

        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyReleased(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade Atual");

        jLabel9.setText("Quantidade");

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        jLabel5.setText("Estoque Mínimo");

        jLabel6.setText("Estoque Máximo");

        jLabel7.setText("Preço Atual");

        jLabel8.setText("Preço Novo");

        javax.swing.GroupLayout painel_estoqueLayout = new javax.swing.GroupLayout(painel_estoque);
        painel_estoque.setLayout(painel_estoqueLayout);
        painel_estoqueLayout.setHorizontalGroup(
            painel_estoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_estoqueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_estoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_estoqueLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(painel_estoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painel_estoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painel_estoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdicionar)
                            .addComponent(btnPesquisar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painel_estoqueLayout.createSequentialGroup()
                        .addGroup(painel_estoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel_estoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4))
                            .addComponent(jLabel6))
                        .addGap(12, 12, 12)
                        .addGroup(painel_estoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQtdAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(txtEstoqueMaximo)
                            .addComponent(txtEstoqueMinimo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painel_estoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painel_estoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQtd_Nova, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecoAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(txtPrecoNovo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        painel_estoqueLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtEstoqueMaximo, txtQtdAtual, txtQtd_Nova});

        painel_estoqueLayout.setVerticalGroup(
            painel_estoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_estoqueLayout.createSequentialGroup()
                .addGroup(painel_estoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_estoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_estoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQtdAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtQtd_Nova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_estoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(txtPrecoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_estoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(txtEstoqueMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        painel_estoqueLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtEstoqueMaximo, txtQtdAtual});

        painel_guias.addTab("Dados do produto", painel_estoque);

        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("ALTERAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnImprimir.setText("IMPRIMIR");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "descrição", "preço", "qtd. estoque", "qtd.Mínima", "qtd.Máxima", "fornecedor"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painel_guias)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImprimir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel_guias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnImprimir)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        Produtos obj = new Produtos();

        obj.setDescricao(txtDescricao.getText());



        // Obtém o preço a partir do campo txtPreco, já que você formatou como moeda

        //String precoTexto = txtPreco.getText().replace("R$", "").replace(".", "").replace(",", ".");

        //obj.setPreco(Double.valueOf(precoTexto)); // Converte o texto formatado para double

        obj.setPreco(Double.valueOf(txtQtdAtual.getText()));



        // Obtém a quantidade de estoque com 3 casas decimais

        String qtdEstoqueTexto = txtQtd_Nova.getText().replace(".", "").replace(",", "."); // Formata para o padrão de double

        obj.setQtd_estoque(Double.valueOf(qtdEstoqueTexto)); // Converte o texto para double



        try {

            ProdutosDAO dao = new ProdutosDAO();

            dao.Salvar(obj);

            LimpaTela util = new LimpaTela();

            util.LimpaTela(painel_estoque);

        } catch (SQLException | ClassNotFoundException ex) {

            Logger.getLogger(Form_Estoque.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_btnSalvarActionPerformed



    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        try {

            String nome = txtDescricao.getText();

            Produtos obj = new Produtos();

            ProdutosDAO dao = new ProdutosDAO();

            CliFor f = new CliFor();

            CliForDAO daof = new CliForDAO();



            obj = dao.BuscarProdutos(nome);

            if (obj.getDescricao() != null) {

                txtCodigo.setText(String.valueOf(obj.getId()));

                txtDescricao.setText(obj.getDescricao());

                txtQtdAtual.setText(String.valueOf(obj.getQtd_estoque()));

                txtQtd_Nova.setText(""); // Limpa a quantidade nova

                f = daof.BuscarFornecedor(obj.getCliFor().getNomeCliFor());

                // Você pode adicionar lógica aqui para selecionar o fornecedor na ComboBox, se necessário

            } else {

                JOptionPane.showMessageDialog(null, "Produto não encontrado!");

            }

        } catch (SQLException | ClassNotFoundException ex) {

            Logger.getLogger(Form_Estoque.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_btnPesquisarActionPerformed



    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        LimpaTela util = new LimpaTela();

        util.LimpaTela(painel_estoque);

    }//GEN-LAST:event_btnNovoActionPerformed



    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        try {

            listar();

        } catch (SQLException | ClassNotFoundException ex) {

            Logger.getLogger(Form_Estoque.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_formWindowActivated



    private void txtDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyReleased



    }//GEN-LAST:event_txtDescricaoKeyReleased



    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        Produtos obj = new Produtos();

        obj.setId(Integer.parseInt(txtCodigo.getText()));

        obj.setDescricao(txtDescricao.getText());



        // Obtenha o preço do txtQtdAtual como um valor double

        double preco = Double.parseDouble(txtQtdAtual.getText().replace("R$", "").replace(".", "").replace(",", "."));

        obj.setPreco(preco);



        obj.setQtd_estoque(Integer.parseInt(txtQtd_Nova.getText()));



        try {

            if (fornecedorSelecionado != null) {

                obj.setCliFor(fornecedorSelecionado); // Usa o fornecedor armazenado

            }



            ProdutosDAO daop = new ProdutosDAO();

            daop.Editar(obj);

            LimpaTela util = new LimpaTela();

            util.LimpaTela(painel_estoque);

        } catch (SQLException | ClassNotFoundException ex) {

            Logger.getLogger(Form_Estoque.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_btnEditarActionPerformed



    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        Produtos obj = new Produtos();

        obj.setId(Integer.valueOf(txtCodigo.getText()));

        ProdutosDAO daop;

        try {

            daop = new ProdutosDAO();

            daop.Excluir(obj);

            LimpaTela util = new LimpaTela();

            util.LimpaTela(painel_estoque);

        } catch (SQLException | ClassNotFoundException ex) {

            Logger.getLogger(Form_Estoque.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_btnExcluirActionPerformed



    private void txtDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyPressed



        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String nome = txtDescricao.getText();

            Produtos obj = new Produtos();

            ProdutosDAO dao;

            try {

                dao = new ProdutosDAO();

                CliForDAO daof = new CliForDAO();

                obj = dao.BuscarProdutos(nome);



                if (obj != null) {

                    if (obj.getDescricao() != null) {

                        // Formata o preço do produto

                        @SuppressWarnings("deprecation")

                        NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));

                        String precoFormatado = nf.format(obj.getPreco());



                        txtCodigo.setText(String.valueOf(obj.getId()));

                        txtDescricao.setText(obj.getDescricao());

                        txtQtdAtual.setText(precoFormatado);

                        txtQtd_Nova.setText(String.valueOf(obj.getQtd_estoque()));



                        // Armazena o fornecedor selecionado

                        if (obj.getCliFor() != null) {

                            fornecedorSelecionado = obj.getCliFor(); // Armazena o fornecedor

                        } else {

                            System.out.println("Fornecedor não encontrado para este produto.");

                        }

                    }

                } else {

                    System.out.println("Produto não encontrado.");

                }

            } catch (SQLException | ClassNotFoundException ex) {

                Logger.getLogger(Form_Estoque.class.getName()).log(Level.SEVERE, null, ex);

            }

        }

    }//GEN-LAST:event_txtDescricaoKeyPressed



    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked

        idProduto = Integer.parseInt(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());

        txtCodigo.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());

        txtDescricao.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());

        txtPrecoAtual.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());

        txtQtdAtual.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());

        txtEstoqueMinimo.setText(tabela.getValueAt(tabela.getSelectedRow(), 4).toString());

        txtEstoqueMaximo.setText(tabela.getValueAt(tabela.getSelectedRow(), 5).toString());

    }//GEN-LAST:event_tabelaMouseClicked



    private String sanitizeString(String input) {

        if (input == null) {

            return null;

        }

        // Remove todos os caracteres não numéricos, exceto a vírgula

        return input.replaceAll("[^\\d,]", "").replace(",", ".").trim();

    }



    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        Connection conn = null; // Declara a conexão

        try {

            conexao.abrirConexao(); // Abre a conexão

            conn = conexao.getConexao(); // Obtém a conexão

            // Leitura e conversão das quantidades

            String qtdAtualStr = txtQtdAtual.getText().trim();

            String qtdNovaStr = txtQtd_Nova.getText().trim();



            String estoqueMinimoStr = sanitizeString(txtEstoqueMinimo.getText());

            String estoqueMaximoStr = sanitizeString(txtEstoqueMaximo.getText());

            String precoAtualStr = sanitizeString(txtPrecoAtual.getText());

            String precoNovoStr = sanitizeString(txtPrecoNovo.getText());



            // Conversão para double

            double qtdAtual = Double.parseDouble(qtdAtualStr.replace(",", "."));

            double qtdNova = Double.parseDouble(qtdNovaStr.replace(",", "."));

            double estoqueMinimo = Double.parseDouble(estoqueMinimoStr);

            double estoqueMaximo = Double.parseDouble(estoqueMaximoStr);

            double precoAtual = Double.parseDouble(precoAtualStr.replace(".", "").replace(",", "."));

            double precoNovo = Double.parseDouble(precoNovoStr.replace(".", "").replace(",", "."));



            // Cálculo da quantidade atualizada

            double qtdAtualizada = qtdAtual + qtdNova;

            //double qtdAtualizada = qtdAtual + estoqueAtualizado;



            // Logs para depuração

//            System.out.println("Quantidade Atual: " + qtdAtual);

//            System.out.println("Quantidade Nova: " + qtdNova);

//            System.out.println("Quantidade Atualizada: " + qtdAtualizada);

//            System.out.println("Chamando adicionarEstoque com ID: " + idProduto); // ID do produto

            if (qtdAtualizada > estoqueMaximo) {

                JOptionPane.showMessageDialog(null, "Estoque máximo ultrapassado!");

                return;

            }



            if (qtdAtualizada < estoqueMinimo) {

                JOptionPane.showMessageDialog(null, "Estoque abaixo do mínimo, é necessário efetuar uma nova compra.");

            }



            //Logs para depuração

            //System.out.println("Qtd Atual: " + qtdAtual + ", Preço Atual: " + precoAtual);

            //System.out.println("Qtd Nova: " + qtdNova + ", Preço Novo: " + precoNovo);

            // Calcular preço médio de custo

            double precoMedioCusto = (((qtdAtual * precoAtual) + (qtdNova * precoNovo)) / (qtdAtual + qtdNova)) / 100;

            BigDecimal precoMedioArredondado = new BigDecimal(precoMedioCusto).setScale(2, RoundingMode.HALF_UP);



            // Chamada ao método para adicionar estoque

            ProdutosDAO daop = new ProdutosDAO();

            daop.adicionarEstoque(conn, idProduto, qtdNova, precoMedioArredondado.doubleValue());



            // Limpa os campos do formulário

            new LimpaTela().LimpaTela(painel_estoque);



            JOptionPane.showMessageDialog(null, "Estoque Atualizado: ");



        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(null, "Erro de conversão de número: " + ex.getMessage());

        } catch (SQLException | ClassNotFoundException ex) {

            JOptionPane.showMessageDialog(null, "Erro ao adicionar: " + ex.getMessage());

        } finally {

            if (conn != null) {

                try {

                    conn.close(); // Fecha a conexão no final

                } catch (SQLException e) {

                    e.printStackTrace();

                }

            }

        }

    }//GEN-LAST:event_btnAdicionarActionPerformed



    public static double parseStringToDouble(String valor) throws ParseException {

        // Remove o símbolo de moeda e espaços

        String valorLimpo = valor.replace("R$", "").replace("\u00A0", "").trim();



        // Substitui a vírgula decimal por ponto e remove separadores de milhar

        valorLimpo = valorLimpo.replace(".", "").replace(",", ".");



        // Converte para double

        return Double.parseDouble(valorLimpo);

    }



    /**

     * @param args the command line arguments

     */

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 

         */

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Windows".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;

                }

            }

        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(Form_Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(Form_Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(Form_Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(Form_Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>



        /* Create and display the form */

        java.awt.EventQueue.invokeLater(() -> {

            //new FormularioEstoque().setVisible(true);

        });

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel painel_estoque;
    private javax.swing.JTabbedPane painel_guias;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEstoqueMaximo;
    private javax.swing.JTextField txtEstoqueMinimo;
    private javax.swing.JTextField txtPrecoAtual;
    private javax.swing.JTextField txtPrecoNovo;
    private javax.swing.JTextField txtQtdAtual;
    private javax.swing.JTextField txtQtd_Nova;
    // End of variables declaration//GEN-END:variables

}

