package view;


import dao.PlaconDAO;

import java.io.IOException;

import java.sql.SQLException;

import java.util.List;

import java.util.logging.Level;

import java.util.logging.Logger;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

import model.Placon;

import relatorios.RelPlano;

import utilitarios.LimpaTela;



public class Tela_CadPlaCon extends javax.swing.JFrame {



    /**

     * Creates new form Tela_CadPlaCon

     *

     * @throws java.sql.SQLException

     * @throws java.lang.ClassNotFoundException

     */

    public void listar() throws SQLException, ClassNotFoundException {

        PlaconDAO dao = new PlaconDAO();

        List<Placon> lista = dao.Listar();

        DefaultTableModel dados = (DefaultTableModel) tbPlaCon.getModel();

        tbPlaCon.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        tbPlaCon.getColumn(tbPlaCon.getColumnName(0)).setPreferredWidth(70);

        tbPlaCon.getColumn(tbPlaCon.getColumnName(1)).setPreferredWidth(90);

        tbPlaCon.getColumn(tbPlaCon.getColumnName(2)).setPreferredWidth(200);

        tbPlaCon.getColumn(tbPlaCon.getColumnName(3)).setPreferredWidth(300);

        dados.setNumRows(0);

        for (Placon c : lista) {

            dados.addRow(new Object[]{

                c.getCod_Geral(),

                c.getNome_P(),

                c.getNome_S(),

                c.getNome_C()

            });

        }

    }



    public Tela_CadPlaCon() {

        initComponents();

    }



    /**

     * This method is called from within the constructor to initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is always

     * regenerated by the Form Editor.

     */

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tfBusca = new javax.swing.JTextField();
        btAbrir = new javax.swing.JButton();
        btnListarDados = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelPlaCon = new javax.swing.JPanel();
        tfCodPrin = new javax.swing.JTextField();
        tfContaPrincipal = new javax.swing.JTextField();
        tfContaSecundaria = new javax.swing.JTextField();
        tfContaMovimento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPlaCon = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("       Cadastro de Plano de Contas");
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        btSalvar.setText("Salvar");
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(btSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnExcluir)
                    .addComponent(btnFechar)
                    .addComponent(jButtonImprimir))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Abrir Dados"));

        btAbrir.setText("Abrir");
        btAbrir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirActionPerformed(evt);
            }
        });

        btnListarDados.setText("Listar Dados");
        btnListarDados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnListarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAbrir)
                    .addComponent(btnListarDados))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO - PLANO DE CONTAS");

        jLabel5.setText("Conta Movimento");

        jLabel4.setText("Conta Secundária");

        jLabel3.setText("Conta Principal");

        jLabel2.setText("Código Geral");

        javax.swing.GroupLayout jPanelPlaConLayout = new javax.swing.GroupLayout(jPanelPlaCon);
        jPanelPlaCon.setLayout(jPanelPlaConLayout);
        jPanelPlaConLayout.setHorizontalGroup(
            jPanelPlaConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlaConLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelPlaConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPlaConLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfContaSecundaria))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPlaConLayout.createSequentialGroup()
                        .addGroup(jPanelPlaConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(jPanelPlaConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfContaPrincipal)
                            .addGroup(jPanelPlaConLayout.createSequentialGroup()
                                .addComponent(tfCodPrin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanelPlaConLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfContaMovimento)))
                .addGap(169, 169, 169))
        );
        jPanelPlaConLayout.setVerticalGroup(
            jPanelPlaConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlaConLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPlaConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfCodPrin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPlaConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfContaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPlaConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfContaSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPlaConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfContaMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(328, 328, 328))
        );

        jPanelPlaConLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfContaMovimento, tfContaSecundaria});

        tbPlaCon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.Geral", "Geral", "Secundária", "Movimento"
            }
        ));
        tbPlaCon.setSelectionBackground(new java.awt.Color(255, 255, 204));
        tbPlaCon.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(tbPlaCon);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelPlaCon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelPlaCon, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        if (tfCodPrin.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Conta em branco!");

        } else {

            Placon obj = new Placon();

            obj.setCod_Geral(tfCodPrin.getText());

            obj.setNome_P(tfContaPrincipal.getText());

            obj.setNome_S(tfContaSecundaria.getText());

            obj.setNome_C(tfContaMovimento.getText());

            try {

                PlaconDAO dao = new PlaconDAO();

                dao.Salvar(obj);

                LimpaTela util = new LimpaTela();

                util.LimpaTela(jPanelPlaCon);



            } catch (SQLException | ClassNotFoundException ex) {

                Logger.getLogger(Tela_CadPlaCon.class.getName()).log(Level.SEVERE, null, ex);

            }

        }

    }//GEN-LAST:event_btSalvarActionPerformed



    private void btAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirActionPerformed

        try {

            String nome = tfBusca.getText();

            Placon obj = new Placon();

            PlaconDAO dao;

            dao = new PlaconDAO();

            obj = dao.BuscarConta(nome);

            if (obj.getCod_Geral() != null) {

                tfCodPrin.setText(obj.getCod_Geral());

                tfContaPrincipal.setText(obj.getNome_P());

                tfContaSecundaria.setText(obj.getNome_S());

                tfContaMovimento.setText(obj.getNome_C());

            } else {

                JOptionPane.showMessageDialog(null, "Conta não encontrada!");

            }



        } catch (SQLException | ClassNotFoundException ex) {

            Logger.getLogger(Tela_CadPlaCon.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_btAbrirActionPerformed



    private void btnListarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarDadosActionPerformed

        try {

            PlaconDAO dao = new PlaconDAO();

            List<Placon> lista = dao.Listar();

            DefaultTableModel dados = (DefaultTableModel) tbPlaCon.getModel();

            dados.setNumRows(0);

            tbPlaCon.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

            tbPlaCon.getColumn(tbPlaCon.getColumnName(0)).setPreferredWidth(70);

            tbPlaCon.getColumn(tbPlaCon.getColumnName(1)).setPreferredWidth(90);

            tbPlaCon.getColumn(tbPlaCon.getColumnName(2)).setPreferredWidth(200);

            tbPlaCon.getColumn(tbPlaCon.getColumnName(3)).setPreferredWidth(300);



            for (Placon c : lista) {

                dados.addRow(new Object[]{

                    c.getCod_Geral(),

                    c.getNome_P(),

                    c.getNome_S(),

                    c.getNome_C()

                });

            }

        } catch (ClassNotFoundException | SQLException e) {

            Logger.getLogger(Tela_CadPlaCon.class.getName()).log(Level.SEVERE, null, e);

        }

    }//GEN-LAST:event_btnListarDadosActionPerformed



    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

        if (tfBusca.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Informe a Conta");

        } else {

            try {

                Placon obj = new Placon();

                obj.setNome_P(tfContaPrincipal.getText());

                obj.setNome_S(tfContaSecundaria.getText());

                obj.setNome_C(tfContaMovimento.getText());

                obj.setCod_Geral(tfCodPrin.getText());

                try {

                    PlaconDAO dao = new PlaconDAO();

                    dao.Editar(obj);

                    LimpaTela util = new LimpaTela();

                    util.LimpaTela(jPanelPlaCon);

                } catch (SQLException | ClassNotFoundException ex) {

                    Logger.getLogger(Tela_CadPlaCon.class.getName()).log(Level.SEVERE, null, ex);

                }

            } catch (NumberFormatException ex) {

                Logger.getLogger(Tela_CadPlaCon.class.getName()).log(Level.SEVERE, null, ex);

            }

        }

    }//GEN-LAST:event_btnAtualizarActionPerformed



    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        if (tfCodPrin.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Informe a Conta à ser excluída.");

        } else {

            Placon obj = new Placon();

            obj.setCod_Geral(tfCodPrin.getText());

            PlaconDAO dao;

            try {

                dao = new PlaconDAO();

                dao.Excluir(obj);

                LimpaTela util = new LimpaTela();

                util.LimpaTela(jPanelPlaCon);

            } catch (SQLException | ClassNotFoundException ex) {

                Logger.getLogger(Tela_CadPlaCon.class.getName()).log(Level.SEVERE, null, ex);

            }

        }

    }//GEN-LAST:event_btnExcluirActionPerformed



    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed

        // TODO add your handling code here:

        try {

            Tela_Principal exibir;

            exibir = new Tela_Principal();

            exibir.setVisible(true);

            setVisible(false);

        } catch (IOException ex) {

            Logger.getLogger(Tela_CadPlaCon.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_btnFecharActionPerformed



    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        try {

            listar();

        } catch (SQLException | ClassNotFoundException ex) {

            Logger.getLogger(Tela_CadPlaCon.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_formWindowActivated



    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed

        RelPlano gen = new RelPlano();

        JOptionPane.showMessageDialog(null, "Relatório Plano de Contas gerado com sucesso!");

        dispose();

        new Tela_CadPlaCon().setVisible(true);

    }//GEN-LAST:event_jButtonImprimirActionPerformed



    /**

     * @param args the command line arguments

     */

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 

         */

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;

                }

            }

        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(Tela_CadPlaCon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(Tela_CadPlaCon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(Tela_CadPlaCon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(Tela_CadPlaCon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>



        /* Create and display the form */

        java.awt.EventQueue.invokeLater(() -> {

            new Tela_CadPlaCon().setVisible(true);

        });

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnListarDados;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelPlaCon;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbPlaCon;
    private javax.swing.JTextField tfBusca;
    private javax.swing.JTextField tfCodPrin;
    private javax.swing.JTextField tfContaMovimento;
    private javax.swing.JTextField tfContaPrincipal;
    private javax.swing.JTextField tfContaSecundaria;
    // End of variables declaration//GEN-END:variables

}

