package view;


import utilitarios.Conexao;

import java.sql.Connection;

import java.sql.PreparedStatement;

import java.sql.ResultSet;

import java.sql.SQLException;

import java.text.ParseException;

import java.text.SimpleDateFormat;

import java.util.logging.Level;

import java.util.logging.Logger;

import javax.swing.JComboBox;

import javax.swing.JOptionPane;



public class Tela_Receber extends javax.swing.JFrame {



    /**

     * Creates new form Tela_Receber

     */

    Conexao conexao = new Conexao();



    //Carrega combobox de Favorecidos

    CarregarCbx re = new CarregarCbx();



    public Tela_Receber() throws SQLException {



        initComponents();

        //Image icon = new ImageIcon(this.getClass().getResource("/IHome.jpg")).getImage();

        //this.setIconImage(icon);



        re.CarregarCbx("tbrecursos", "nomebco", jComboBoxOrigem);

        this.setLocationRelativeTo(null);

        Tela_Mov Lanc = new Tela_Mov();

        jLabelNr.setText(Lanc.textoidMov);

        tfPLanc.setText(Lanc.textoLancto);

        tfPEmissao.setText(Lanc.textoEmissao);

        tfPVencimento.setText(Lanc.textoVencimento);

        tfPPagamento.setText(Lanc.textoApresentacao);

        tfPDocumento.setText(Lanc.textoDocumento);

        tfPDescricao.setText(Lanc.textoDescricao);

        jComboBoxOrigem.setSelectedItem(0);

        tfPDestino.setText(Lanc.textoClass);

        tfPVrPago.setText(Lanc.textoVrPg);

        tfPDesconto.setText("0");

        tfPJuros.setText("0");

        tfPFav.setText(Lanc.textoFav);

        tfPNrFav.setText(Lanc.textoNrFav);

        tfPNrRecurso.setText(Lanc.textoNrRecurso);

    }



    /**

     * This method is called from within the constructor to initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is always

     * regenerated by the Form Editor.

     */

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButtonFechaTelaPagto = new javax.swing.JButton();
        jButtonLancaPgto = new javax.swing.JButton();
        tfPDocumento = new javax.swing.JTextField();
        tfPDescricao = new javax.swing.JTextField();
        tfPDestino = new javax.swing.JTextField();
        jComboBoxOrigem = new javax.swing.JComboBox<>();
        tfPVrPago = new javax.swing.JTextField();
        tfPDesconto = new javax.swing.JTextField();
        tfPJuros = new javax.swing.JTextField();
        tfPEmissao = new javax.swing.JFormattedTextField();
        tfPLanc = new javax.swing.JFormattedTextField();
        tfPPagamento = new javax.swing.JFormattedTextField();
        tfPVencimento = new javax.swing.JFormattedTextField();
        jLabelNr = new javax.swing.JLabel();
        tfPFav = new javax.swing.JTextField();
        tfPNrFav = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfPNrRec = new javax.swing.JTextField();
        tfPRec = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfPNrRecurso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Pagamentos");
        setUndecorated(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Home.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RECEBIMENTOS");

        jLabel3.setText("Lançamento");

        jLabel4.setText("Emissão");

        jLabel5.setText("Vencimento");

        jLabel6.setText("Recebimento");

        jLabel7.setText("Documento");

        jLabel8.setText("Descrição");

        jLabel9.setText("Destino do Recurso");

        jLabel10.setText("Classificação");

        jLabel11.setText("Valor Recebido");

        jLabel12.setText("Descto. Concedido");

        jLabel13.setText("Juros Recebidos");

        jButtonFechaTelaPagto.setText("Cancelar");
        jButtonFechaTelaPagto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonFechaTelaPagto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFechaTelaPagtoActionPerformed(evt);
            }
        });

        jButtonLancaPgto.setBackground(new java.awt.Color(0, 204, 0));
        jButtonLancaPgto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonLancaPgto.setText("Lançar");
        jButtonLancaPgto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonLancaPgto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLancaPgtoActionPerformed(evt);
            }
        });

        tfPDocumento.setEnabled(false);

        tfPDescricao.setEnabled(false);

        tfPDestino.setEnabled(false);
        tfPDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPDestinoActionPerformed(evt);
            }
        });

        jComboBoxOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOrigemActionPerformed(evt);
            }
        });

        tfPVrPago.setEnabled(false);

        tfPEmissao.setEnabled(false);

        tfPLanc.setEnabled(false);

        tfPPagamento.setEnabled(false);

        tfPVencimento.setEnabled(false);

        tfPFav.setEnabled(false);

        tfPNrFav.setEnabled(false);

        jLabel14.setText("Registro");

        tfPNrRec.setEnabled(false);

        tfPRec.setEnabled(false);

        jLabel15.setText("Cliente");

        jLabel16.setText("V.Cliente");

        jLabel17.setText("  Baixar");

        tfPNrRecurso.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabelNr, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPLanc, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel4)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(tfPVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addGap(48, 48, 48)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(19, 19, 19))))
                            .addComponent(tfPDocumento)
                            .addComponent(tfPDescricao)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfPNrRec, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfPRec, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(tfPNrRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPNrFav, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(tfPFav, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(tfPDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPVrPago, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfPDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLancaPgto)
                .addGap(128, 128, 128)
                .addComponent(jButtonFechaTelaPagto)
                .addGap(179, 179, 179))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(7, 7, 7)
                                .addComponent(jLabelNr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(7, 7, 7)
                                .addComponent(tfPLanc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)
                        .addComponent(tfPPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(tfPVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPNrRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfPDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfPVrPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfPDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfPFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfPNrFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfPNrRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel16)
                                .addComponent(jLabel15)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addGap(24, 24, 24))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFechaTelaPagto)
                    .addComponent(jButtonLancaPgto))
                .addGap(49, 49, 49))
        );

        jButtonLancaPgto.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void jButtonFechaTelaPagtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFechaTelaPagtoActionPerformed

        Tela_Mov exibir = null;

        try {

            exibir = new Tela_Mov();

        } catch (SQLException ex) {

            Logger.getLogger(Tela_Receber.class.getName()).log(Level.SEVERE, null, ex);

        }

        exibir.setVisible(true);

        setVisible(false);

    }//GEN-LAST:event_jButtonFechaTelaPagtoActionPerformed



    private void jComboBoxOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOrigemActionPerformed



        String selectedValue = jComboBoxOrigem.getSelectedItem().toString();//.substring(11);

        var texto = selectedValue.length();

        selectedValue = jComboBoxOrigem.getSelectedItem().toString().substring(texto - 14);

        if (!selectedValue.isEmpty()) {

            selectedValue = jComboBoxOrigem.getSelectedItem().toString().substring(texto - 14);

            String frase1 = selectedValue.substring(0, 4);

            tfPNrRec.setText(frase1);

            String frase2 = selectedValue.substring(5);

            tfPRec.setText(frase2);

        }

    }//GEN-LAST:event_jComboBoxOrigemActionPerformed



    private void jButtonLancaPgtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLancaPgtoActionPerformed

        Object[] options = {"Sim", "Não"};

        int i = JOptionPane.showOptionDialog(null, "O Recebimento é parcial?", "Forma de Recebimento", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (i == JOptionPane.YES_OPTION) { //op\\u00e7ao SIM selecionada !!}

            try {

                RcParcial();

            } catch (ParseException ex) {

                Logger.getLogger(Tela_Receber.class.getName()).log(Level.SEVERE, null, ex);

            } catch (SQLException ex) {

                Logger.getLogger(Tela_Receber.class.getName()).log(Level.SEVERE, null, ex);

            }

        } else {

            Double t = Double.parseDouble(tfPDesconto.getText().replaceAll(",", "."));

            Double j = Double.parseDouble(tfPJuros.getText().replaceAll(",", "."));

            try {

                conexao.abrirConexao(); // Abre a conexão

                Connection con = conexao.getConexao(); // Obtém a conexão

                String sql = "INSERT INTO tbmovimento(recurso,vrecurso,clifor,vCliFor,dtlancto,dtEmi,dtVcto,documento,classif,Descr,valor,dtApr,statusMov,Prev) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

                SimpleDateFormat formato_data = new SimpleDateFormat("dd/MM/yyyy");



                // Remover todos os pontos, exceto o decimal

                String valorTextos = tfPVrPago.getText().replaceAll("\\.", "");

                // Substituir a vírgula decimal por ponto decimal

                valorTextos = valorTextos.replaceAll(",", ".");

                Double Lq = Double.parseDouble(valorTextos) + t - j;



                //Double Lq = Double.parseDouble(tfPVrPago.getText().substring(1).replaceAll(",", ".")) + t - j;

                // Início do Lançamento de Pagamento +Entrada+ (Clientes)

                try (PreparedStatement stmt = con.prepareStatement(sql)) {

                    stmt.setString(1, tfPNrRecurso.getText());

                    //stmt.setString(2, tfPRec.getText());

                    stmt.setString(2, "1.002.001");

                    stmt.setString(3, tfPNrFav.getText());

                    stmt.setString(4, tfPFav.getText());



                    // Formato para parsear as datas de entrada

                    SimpleDateFormat formato_data_entrada = new SimpleDateFormat("dd/MM/yyyy");



                    // Parse da data de pagamento

                    java.util.Date data_l = formato_data_entrada.parse(tfPPagamento.getText());

                    // Conversão para java.sql.Date e formatação para string no formato yyyy-MM-dd

                    java.sql.Date sqlData_l = new java.sql.Date(data_l.getTime());

                    stmt.setString(5, sqlData_l.toString());



                    java.util.Date data_e = formato_data_entrada.parse(tfPEmissao.getText());

                    java.sql.Date sqlData_e = new java.sql.Date(data_e.getTime());

                    stmt.setString(6, sqlData_e.toString());



                    java.util.Date data_v = formato_data_entrada.parse(tfPVencimento.getText());

                    java.sql.Date sqlData_v = new java.sql.Date(data_v.getTime());

                    stmt.setString(7, sqlData_v.toString());



                    stmt.setString(8, tfPDocumento.getText());

                    stmt.setString(9, "9.001.003");

                    //stmt.setString(9, tfPDestino.getText());

                    tfPDescricao.setText(tfPDescricao.getText() + " -RC- " + jLabelNr.getText());

                    stmt.setString(10, (tfPDescricao.getText()));



                    //stmt.setDouble(11, Double.parseDouble("-" + tfPVrPago.getText().replaceAll(",", ".")));

                    // Remover todos os pontos, exceto o decimal

                    String valorTexto = tfPVrPago.getText().replaceAll("\\.", "");

                    // Substituir a vírgula decimal por ponto decimal

                    valorTexto = valorTexto.replaceAll(",", ".");

                    // Parse para Double

                    stmt.setDouble(11, Double.parseDouble("-" + valorTexto));



                    stmt.setString(12, sqlData_l.toString());



                    stmt.setString(13, "RC");

                    stmt.setString(14, "V");

                    stmt.execute();

                    stmt.close();

                    con.close();

                } catch (SQLException ex) {

                    Logger.getLogger(Tela_Receber.class.getName()).log(Level.SEVERE, null, ex);

                } catch (ParseException ex) {

                    Logger.getLogger(Tela_Receber.class.getName()).log(Level.SEVERE, null, ex);

                } finally {

                    conexao.fecharConexao(); // Fecha a conexão no final

                }

            } catch (SQLException ex) {

                Logger.getLogger(Tela_Receber.class.getName()).log(Level.SEVERE, null, ex);

            }

            //fim recebimento - lançamento 1



            //Inicio recebimento 2 - lançamento 2 - Saída -

            try {

                conexao.abrirConexao(); // Abre a conexão

                Connection con2 = conexao.getConexao(); // Obtém a conexão

                String sql2 = "INSERT INTO tbmovimento(recurso,vrecurso,clifor,vCliFor,dtlancto,dtEmi,dtVcto,documento,classif,Descr,valor,dtApr,statusMov,Prev) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

                try (PreparedStatement stmt2 = con2.prepareStatement(sql2)) {

                    stmt2.setString(1, tfPNrRec.getText());

                    stmt2.setString(2, tfPRec.getText());

                    stmt2.setString(3, tfPNrFav.getText());

                    stmt2.setString(4, tfPFav.getText());

                    // Formato para parsear as datas de entrada

                    SimpleDateFormat formato_data_entrada = new SimpleDateFormat("dd/MM/yyyy");

                    java.util.Date data_l = formato_data_entrada.parse(tfPPagamento.getText());

                    java.sql.Date sqlData_l = new java.sql.Date(data_l.getTime());

                    stmt2.setString(5, sqlData_l.toString());

                    java.util.Date data_e = formato_data_entrada.parse(tfPEmissao.getText());

                    java.sql.Date sqlData_e = new java.sql.Date(data_e.getTime());

                    stmt2.setString(6, sqlData_e.toString());

                    java.util.Date data_v = formato_data_entrada.parse(tfPVencimento.getText());

                    java.sql.Date sqlData_v = new java.sql.Date(data_v.getTime());

                    stmt2.setString(7, sqlData_v.toString());

                    stmt2.setString(8, tfPDocumento.getText());

                    stmt2.setString(9, "9.001.003");

                    stmt2.setString(10, tfPDescricao.getText());

                    // Remover todos os pontos, exceto o decimal

                    String valorTexto = tfPVrPago.getText().replaceAll("\\.", "");

                    // Substituir a vírgula decimal por ponto decimal

                    valorTexto = valorTexto.replaceAll(",", ".");

                    // Parse para Double

                    stmt2.setDouble(11, Double.parseDouble(valorTexto));

                    stmt2.setString(12, sqlData_l.toString());// Usando a mesma data de recebimento para dtApr

                    stmt2.setString(13, "RC");

                    stmt2.setString(14, "V");

                    stmt2.execute();

                    stmt2.close();

                    con2.close();

                } catch (SQLException | ParseException ex) {

                    Logger.getLogger(Tela_Receber.class.getName()).log(Level.SEVERE, null, ex);

                } finally {

                    conexao.fecharConexao(); // Fecha a conexão no final

                }

                //fim recebimento 2 - lançamento 2



                //Inicio de Lançamento de Desconto Concedido - tfPDesconto

                if (t > 0) {

                    try {

                        conexao.abrirConexao(); // Abre a conexão

                        Connection con3 = conexao.getConexao(); // Obtém a conexão

                        String sql3 = "INSERT INTO tbmovimento(recurso,vrecurso,clifor,vCliFor,dtlancto,dtEmi,dtVcto,documento,classif,Descr,valor,dtApr,statusMov,Prev) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

                        PreparedStatement stmt3 = con3.prepareStatement(sql3);

                        stmt3.setString(1, tfPNrRec.getText()); //Banco de Destino do Recurso

                        stmt3.setString(2, tfPRec.getText()); // Vinculo da Destino Recurso

                        stmt3.setString(3, tfPNrFav.getText()); //Numero do Favorecido

                        stmt3.setString(4, tfPFav.getText()); // Vinculo do Favorecido

                        // Formato para parsear as datas de entrada

                        SimpleDateFormat formato_data_entrada = new SimpleDateFormat("dd/MM/yyyy");

                        java.util.Date data_l = formato_data_entrada.parse(tfPPagamento.getText());

                        java.sql.Date sqlData_l = new java.sql.Date(data_l.getTime());

                        stmt3.setString(5, sqlData_l.toString());

                        java.util.Date data_e = formato_data_entrada.parse(tfPEmissao.getText());

                        java.sql.Date sqlData_e = new java.sql.Date(data_e.getTime());

                        stmt3.setString(6, sqlData_e.toString());

                        java.util.Date data_v = formato_data_entrada.parse(tfPVencimento.getText());

                        java.sql.Date sqlData_v = new java.sql.Date(data_v.getTime());

                        stmt3.setString(7, sqlData_v.toString());

                        stmt3.setString(8, tfPDocumento.getText());

                        stmt3.setString(9, "4.008.006"); // Lançado como Receitas Financeiras - Desconto Obtido

                        tfPDescricao.setText(tfPDescricao.getText() + " -Descto Concedido- " + jLabelNr.getText());

                        stmt3.setString(10, (tfPDescricao.getText()));

                        // Remover todos os pontos, exceto o decimal

                        String valorTexto = tfPDesconto.getText().replaceAll("\\.", "");

                        // Substituir a vírgula decimal por ponto decimal

                        valorTexto = valorTexto.replaceAll(",", ".");

                        // Parse para Double

                        stmt3.setDouble(11, Double.parseDouble("-" + valorTexto));

                        stmt3.setString(12, sqlData_l.toString());

                        stmt3.setString(13, "DC");

                        stmt3.setString(14, "V");

                        stmt3.execute();

                        stmt3.close();

                    } catch (SQLException ex) {

                        Logger.getLogger(Tela_Receber.class.getName()).log(Level.SEVERE, null, ex);

                    } catch (ParseException ex) {

                        Logger.getLogger(Tela_Receber.class.getName()).log(Level.SEVERE, null, ex);

                    } finally {

                        conexao.fecharConexao(); // Fecha a conexão no final

                    }

                }

                //Final de lançamento de Desconto Concedido



                //Início de Lançamento de juros recebidos + tfPJuros

                if (j > 0) {

                    conexao.abrirConexao(); // Abre a conexão

                    Connection con4 = conexao.getConexao(); // Obtém a conexão

                    String sql4 = "INSERT INTO tbmovimento(recurso,vrecurso,clifor,vCliFor,dtlancto,dtEmi,dtVcto,documento,classif,Descr,valor,dtApr,statusMov,Prev) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

                    try (PreparedStatement stmt4 = con4.prepareStatement(sql4)) {

                        stmt4.setString(1, tfPNrRec.getText()); //urso

                        stmt4.setString(2, tfPRec.getText());

                        stmt4.setString(3, tfPNrFav.getText());

                        stmt4.setString(4, tfPFav.getText());

                        // Formato para parsear as datas de entrada

                        SimpleDateFormat formato_data_entrada = new SimpleDateFormat("dd/MM/yyyy");

                        java.util.Date data_l = formato_data_entrada.parse(tfPPagamento.getText());

                        java.sql.Date sqlData_l = new java.sql.Date(data_l.getTime());

                        stmt4.setString(5, sqlData_l.toString());

                        java.util.Date data_e = formato_data_entrada.parse(tfPPagamento.getText());

                        java.sql.Date sqlData_e = new java.sql.Date(data_e.getTime());

                        stmt4.setString(6, sqlData_e.toString());

                        java.util.Date data_v = formato_data_entrada.parse(tfPVencimento.getText());

                        java.sql.Date sqlData_v = new java.sql.Date(data_v.getTime());

                        stmt4.setString(7, sqlData_v.toString());

                        stmt4.setString(8, tfPDocumento.getText());

                        stmt4.setString(9, "3.003.001");//Despesas Financeiras - Juros

                        tfPDescricao.setText(tfPDescricao.getText() + " -Juros Recebidos- " + jLabelNr.getText());

                        stmt4.setString(10, (tfPDescricao.getText()));

                        // Remover todos os pontos, exceto o decimal

                        String valorTexto = tfPJuros.getText().replaceAll("\\.", "");

                        // Substituir a vírgula decimal por ponto decimal

                        valorTexto = valorTexto.replaceAll(",", ".");

                        // Parse para Double

                        stmt4.setDouble(11, Double.parseDouble(valorTexto));

                        stmt4.setString(12, sqlData_l.toString());

                        stmt4.setString(13, "JR");

                        stmt4.setString(14, "V");

                        stmt4.execute();

                        stmt4.close();

                        con4.close();

                    } catch (SQLException | ParseException ex) {

                        Logger.getLogger(Tela_Receber.class.getName()).log(Level.SEVERE, null, ex);

                    } finally {

                        conexao.fecharConexao(); // Fecha a conexão no final

                    }

                }

                //Final de lançamento de juros Recebidos



            } catch (SQLException ex) {

                Logger.getLogger(Tela_Receber.class.getName()).log(Level.SEVERE, null, ex);

            }

        }

        JOptionPane.showMessageDialog(null, "Recebimento efetuado com sucesso!");

        Tela_Mov exibir = null;

        try {

            exibir = new Tela_Mov();

        } catch (SQLException ex) {

            Logger.getLogger(Tela_Receber.class.getName()).log(Level.SEVERE, null, ex);

        }

        exibir.setVisible(true);

        setVisible(false);

    }//GEN-LAST:event_jButtonLancaPgtoActionPerformed

    private void tfPDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPDestinoActionPerformed



    /**

     * @param args the command line arguments

     */

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 

         */

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;

                }

            }

        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(Tela_Receber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(Tela_Receber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(Tela_Receber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(Tela_Receber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>



        /* Create and display the form */

        java.awt.EventQueue.invokeLater(() -> {

            try {

                new Tela_Receber().setVisible(true);

            } catch (SQLException ex) {

                Logger.getLogger(Tela_Receber.class.getName()).log(Level.SEVERE, null, ex);

            }

        });

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechaTelaPagto;
    private javax.swing.JButton jButtonLancaPgto;
    private javax.swing.JComboBox<String> jComboBoxOrigem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNr;
    private javax.swing.JTextField tfPDesconto;
    private javax.swing.JTextField tfPDescricao;
    private javax.swing.JTextField tfPDestino;
    private javax.swing.JTextField tfPDocumento;
    private javax.swing.JFormattedTextField tfPEmissao;
    private javax.swing.JTextField tfPFav;
    private javax.swing.JTextField tfPJuros;
    private javax.swing.JFormattedTextField tfPLanc;
    private javax.swing.JTextField tfPNrFav;
    private javax.swing.JTextField tfPNrRec;
    private javax.swing.JTextField tfPNrRecurso;
    private javax.swing.JFormattedTextField tfPPagamento;
    private javax.swing.JTextField tfPRec;
    private javax.swing.JFormattedTextField tfPVencimento;
    private javax.swing.JTextField tfPVrPago;
    // End of variables declaration//GEN-END:variables

    private static class CarregarCbx {



        //public CarregarCbx() {

        @SuppressWarnings({"empty-statement", "unchecked"})

        public void CarregarCbx(String tabela, String valor, JComboBox combo) throws SQLException {

            String sql = "Select * FROM " + tabela;

            // Cria uma instância da classe Conexao

            Conexao conexao = new Conexao();

            try {

                // Abre a conexão

                conexao.abrirConexao();

                // Obtém a conexão

                Connection con = conexao.getConexao();

                // Prepara e executa a consulta

                PreparedStatement stmt = con.prepareStatement(sql);

                ResultSet rs = stmt.executeQuery();

                while (rs.next()) {

                    combo.addItem(rs.getString(valor) + "-" + (rs.getString("codigo") + "-" + (rs.getString("fk_gpprinc"))));

                }

                rs.close();

                stmt.close();

                con.close();

            } catch (SQLException ex) {

                Logger.getLogger(Tela_Mov.class

                        .getName()).log(Level.SEVERE, null, ex);

            } finally {

                // Fecha a conexão no final

                conexao.fecharConexao();

            }

        }

    }



    private void RcParcial() throws ParseException, SQLException {

        SimpleDateFormat formato_data = new SimpleDateFormat("dd/MM/yyyy");

        Double cheio = Double.parseDouble(tfPVrPago.getText().replaceAll(",", "."));

        Double vparc = Double.parseDouble(JOptionPane.showInputDialog("Informe o valor parcial: "));

        Double Resta = (cheio - vparc);

        Double t = Double.parseDouble(tfPDesconto.getText().replaceAll(",", "."));

        Double j = Double.parseDouble(tfPJuros.getText().replaceAll(",", "."));

        try {

            conexao.abrirConexao(); // Abre a conexão

            Connection con = conexao.getConexao(); // Obtém a conexão

            String sql = "UPDATE tbmovimento SET recurso=?,vrecurso=?,clifor=?,vclifor=?,dtlancto=?,dtEmi=?,dtVcto=?,documento=?,classif=?,Descr=?,valor=?,dtApr=?,statusMov=?,Prev=? WHERE idMov=?";

            PreparedStatement stm = con.prepareStatement(sql);

            stm.setString(1, tfPNrRecurso.getText());

            stm.setString(2, "1.002.001");//Contas à Receber

            stm.setString(3, tfPNrFav.getText());

            stm.setString(4, tfPFav.getText());

            // Formato para parsear as datas de entrada

            SimpleDateFormat formato_data_entrada = new SimpleDateFormat("dd/MM/yyyy");

            java.util.Date data_l = formato_data_entrada.parse(tfPPagamento.getText());

            java.sql.Date sqlData_l = new java.sql.Date(data_l.getTime());

            stm.setString(5, sqlData_l.toString());

            java.util.Date data_e = formato_data_entrada.parse(tfPEmissao.getText());

            java.sql.Date sqlData_e = new java.sql.Date(data_e.getTime());

            stm.setString(6, sqlData_e.toString());

            java.util.Date data_v = formato_data_entrada.parse(tfPVencimento.getText());

            java.sql.Date sqlData_v = new java.sql.Date(data_v.getTime());

            stm.setString(7, sqlData_v.toString());

            stm.setString(8, tfPDocumento.getText());

            stm.setString(9, tfPDestino.getText());

            stm.setString(10, ("1/2-" + tfPDescricao.getText() + jLabelNr.getText()));

            stm.setDouble(11, vparc);

            stm.setString(12, sqlData_l.toString());

            stm.setString(13, "RC");

            stm.setString(14, "V");

            stm.setString(15, jLabelNr.getText());

            stm.execute();

            stm.close();

            con.close();

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "Erro ao fechar a conexão em Atualiza\\u00c3\\u00a7\\u00c3\\u00a3o Parcial! " + ex);

        } finally {

            conexao.fecharConexao(); // Fecha a conexão no final

        }



        try {

            conexao.abrirConexao(); // Abre a conexão

            Connection conp1 = conexao.getConexao(); // Obtém a conexão   

            String sqlp = "INSERT INTO tbmovimento(recurso,vrecurso,clifor,vCliFor,dtlancto,dtEmi,dtVcto,documento,classif,Descr,valor,dtApr,statusMov,Prev) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement stmtp = conp1.prepareStatement(sqlp);

            // Início do Lançamento de Recebimento Parcial +Entrada+ (Fornecedor)

            stmtp.setString(1, tfPNrRecurso.getText());

            stmtp.setString(2, "1.002.001");//Contas à Receber

            stmtp.setString(3, tfPNrFav.getText());

            stmtp.setString(4, tfPFav.getText());

            // Formato para parsear as datas de entrada

            SimpleDateFormat formato_data_entrada = new SimpleDateFormat("dd/MM/yyyy");

            java.util.Date data_l = formato_data_entrada.parse(tfPPagamento.getText());

            java.sql.Date sqlData_l = new java.sql.Date(data_l.getTime());

            stmtp.setString(5, sqlData_l.toString());

            java.util.Date data_e = formato_data_entrada.parse(tfPEmissao.getText());

            java.sql.Date sqlData_e = new java.sql.Date(data_e.getTime());

            stmtp.setString(6, sqlData_e.toString());

            java.util.Date data_v = formato_data_entrada.parse(tfPVencimento.getText());

            java.sql.Date sqlData_v = new java.sql.Date(data_v.getTime());

            stmtp.setString(7, sqlData_v.toString());

            stmtp.setString(8, tfPDocumento.getText());

            stmtp.setString(9, "9.001.003");

            stmtp.setString(10, ("1/2" + tfPDescricao.getText() + jLabelNr.getText()));

            stmtp.setDouble(11, vparc * -1); // Double.parseDouble("-" + tfPVrPago.getText().replaceAll(",", ".")));

            stmtp.setString(12, sqlData_l.toString());

            stmtp.setString(13, "RC");

            stmtp.setString(14, "V");

            stmtp.execute();

            stmtp.close();

            conp1.close();

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "Erro ao fechar a conexão em Recebimento Parcial! " + ex);

        } catch (ParseException ex) {

            Logger.getLogger(Tela_Receber.class.getName()).log(Level.SEVERE, null, ex);

        } finally {

            conexao.fecharConexao(); // Fecha a conexão no final

        }

        //fim recebimento - lançamento 1



        //Inicio recebimento2 - lançamento2 - Entrada -

        try {

            conexao.abrirConexao(); // Abre a conexão

            Connection conp2 = conexao.getConexao(); // Obtém a conexão

            String sqlp2 = "INSERT INTO tbmovimento(recurso,vrecurso,clifor,vCliFor,dtlancto,dtEmi,dtVcto,documento,classif,Descr,valor,dtApr,statusMov,Prev) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

            SimpleDateFormat formato_data2 = new SimpleDateFormat("dd/MM/yyyy");

            try (PreparedStatement stmtp2 = conp2.prepareStatement(sqlp2)) {

                stmtp2.setString(1, tfPNrRec.getText());

                stmtp2.setString(2, tfPRec.getText());

                stmtp2.setString(3, tfPNrFav.getText());

                stmtp2.setString(4, tfPFav.getText());



                // Formato para parsear as datas de entrada

                SimpleDateFormat formato_data_entrada = new SimpleDateFormat("dd/MM/yyyy");



                java.util.Date data_l = formato_data_entrada.parse(tfPPagamento.getText());

                java.sql.Date sqlData_l = new java.sql.Date(data_l.getTime());

                stmtp2.setString(5, sqlData_l.toString());



                java.util.Date data_e = formato_data_entrada.parse(tfPEmissao.getText());

                java.sql.Date sqlData_e = new java.sql.Date(data_e.getTime());

                stmtp2.setString(6, sqlData_e.toString());



                java.util.Date data_v = formato_data_entrada.parse(tfPVencimento.getText());

                java.sql.Date sqlData_v = new java.sql.Date(data_v.getTime());

                stmtp2.setString(7, sqlData_v.toString());



                stmtp2.setString(8, tfPDocumento.getText());

                stmtp2.setString(9, "9.001.003");

                stmtp2.setString(10, ("1/2-" + tfPDescricao.getText() + jLabelNr.getText()));

                stmtp2.setDouble(11, vparc); //Double.parseDouble(tfPVrPago.getText().replaceAll(",", ".")));



                stmtp2.setString(12, sqlData_l.toString());



                stmtp2.setString(13, "RC");

                stmtp2.setString(14, "V");

                stmtp2.execute();

                stmtp2.close();

                conp2.close();

            } catch (SQLException ex) {

                Logger.getLogger(Tela_Receber.class.getName()).log(Level.SEVERE, null, ex);

            } finally {

                conexao.fecharConexao(); // Fecha a conexão no final

            }

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "Erro ao abrir a conexão em Recebimento Parcial recebimento2 Entrada! " + ex);

        }



        //fim recebimento - lançamento 2

        //Inicio do Lançamento de Desdobramento

        try {

            conexao.abrirConexao(); // Abre a conexão

            Connection conpD = conexao.getConexao(); // Obtém a conexão

            String sqlpD = "INSERT INTO tbmovimento(recurso,vrecurso,clifor,vCliFor,dtlancto,dtEmi,dtVcto,documento,classif,Descr,valor,dtApr,statusMov,Prev) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

            try (PreparedStatement stmtpD = conpD.prepareStatement(sqlpD)) {

                stmtpD.setString(1, tfPNrRecurso.getText());

                //stmtpD.setString(2, tfPRec.getText());

                stmtpD.setString(2, "1.002.001");//Contas à Receber

                stmtpD.setString(3, tfPNrFav.getText());

                stmtpD.setString(4, tfPFav.getText());

                // Formato para parsear as datas de entrada

                SimpleDateFormat formato_data_entrada = new SimpleDateFormat("dd/MM/yyyy");

                java.util.Date data_l = formato_data_entrada.parse(tfPPagamento.getText());

                java.sql.Date sqlData_l = new java.sql.Date(data_l.getTime());

                stmtpD.setString(5, sqlData_l.toString());

                java.util.Date data_e = formato_data_entrada.parse(tfPEmissao.getText());

                java.sql.Date sqlData_e = new java.sql.Date(data_e.getTime());

                stmtpD.setString(6, sqlData_e.toString());

                java.util.Date data_v = formato_data_entrada.parse(tfPVencimento.getText());

                java.sql.Date sqlData_v = new java.sql.Date(data_v.getTime());

                stmtpD.setString(7, sqlData_v.toString());

                stmtpD.setString(8, tfPDocumento.getText());

                stmtpD.setString(9, tfPDestino.getText());

                stmtpD.setString(10, "2/2-" + tfPDescricao.getText());

                stmtpD.setDouble(11, Resta);

                stmtpD.setString(12, sqlData_l.toString());

                stmtpD.setString(13, "");

                stmtpD.setString(14, "V");

                stmtpD.execute();

                stmtpD.close();

                conpD.close();

            } catch (SQLException ex) {

                Logger.getLogger(Tela_Receber.class.getName()).log(Level.SEVERE, null, ex);

            } finally {

                conexao.fecharConexao(); // Fecha a conexão no final

            }

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "Erro ao abrir a conexão em Recebimento (desdobramento)! " + ex);

        }



        //Fim do lançamento de desdobramento

        //Inicio de Lançamento de Desconto Concedido - tfPDesconto

        if (t > 0) {

            try {

                conexao.abrirConexao(); // Abre a conexão

                Connection conDs = conexao.getConexao(); // Obtém a conexão

                String sql3 = "INSERT INTO tbmovimento(recurso,vrecurso,clifor,vCliFor,dtlancto,dtEmi,dtVcto,documento,classif,Descr,valor,dtApr,statusMov,Prev) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

                try (PreparedStatement stmt3 = conDs.prepareStatement(sql3)) {

                    stmt3.setString(1, tfPNrRec.getText()); //Banco de Origem do Recurso \\urso

                    stmt3.setString(2, tfPRec.getText()); // Vinculo da Origem Recurso

                    stmt3.setString(3, tfPNrFav.getText()); //Numero do Favorecido 

                    stmt3.setString(4, tfPFav.getText()); // Vinculo do Favorecido

                    // Formato para parsear as datas de entrada

                    SimpleDateFormat formato_data_entrada = new SimpleDateFormat("dd/MM/yyyy");

                    java.util.Date data_l = formato_data_entrada.parse(tfPPagamento.getText());

                    java.sql.Date sqlData_l = new java.sql.Date(data_l.getTime());

                    stmt3.setString(5, sqlData_l.toString());

                    java.util.Date data_e = formato_data_entrada.parse(tfPPagamento.getText());

                    java.sql.Date sqlData_e = new java.sql.Date(data_e.getTime());

                    stmt3.setString(6, sqlData_e.toString());

                    java.util.Date data_v = formato_data_entrada.parse(tfPVencimento.getText());

                    java.sql.Date sqlData_v = new java.sql.Date(data_v.getTime());

                    stmt3.setString(7, sqlData_v.toString());

                    stmt3.setString(8, tfPDocumento.getText());

                    stmt3.setString(9, "4.008.006"); // Lançado como Receitas Financeiras - Desconto Obtido

                    stmt3.setString(10, (tfPDescricao.getText() + "Descto.Concedido " + jLabelNr.getText()));

                    // Remover todos os pontos, exceto o decimal

                    String valorTexto = tfPDesconto.getText().replaceAll("\\.", "");

                    // Substituir a vírgula decimal por ponto decimal

                    valorTexto = valorTexto.replaceAll(",", ".");

                    // Parse para Double

                    stmt3.setDouble(11, Double.parseDouble("-" + valorTexto));

                    stmt3.setString(12, sqlData_l.toString());

                    stmt3.setString(13, "DC");

                    stmt3.setString(14, "V");

                    stmt3.execute();

                    stmt3.close();

                    conDs.close();

                } catch (SQLException | ParseException ex) {

                    Logger.getLogger(Tela_Receber.class.getName()).log(Level.SEVERE, null, ex);

                } finally {

                    conexao.fecharConexao(); // Fecha a conexão no final

                }

            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(null, "Erro ao fechar a conexão em Desconto Obtido! " + ex);

            }

        }

        //Final de lançamento de Desconto Concedido



        //Início de Lançamento de juros recebidos + tfPJuros

        if (j > 0) {



            try {

                conexao.abrirConexao(); // Abre a conexão

                Connection conJs = conexao.getConexao(); // Obtém a conexão

                String sql4 = "INSERT INTO tbmovimento(recurso,vrecurso,clifor,vCliFor,dtlancto,dtEmi,dtVcto,documento,classif,Descr,valor,dtApr,statusMov,Prev) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

                try (PreparedStatement stmt4 = conJs.prepareStatement(sql4)) {

                    stmt4.setString(1, tfPNrRec.getText()); //urso

                    stmt4.setString(2, tfPRec.getText());

                    stmt4.setString(3, tfPNrFav.getText());

                    stmt4.setString(4, tfPFav.getText());



                    // Formato para parsear as datas de entrada

                    SimpleDateFormat formato_data_entrada = new SimpleDateFormat("dd/MM/yyyy");



                    java.util.Date data_l = formato_data_entrada.parse(tfPPagamento.getText());

                    java.sql.Date sqlData_l = new java.sql.Date(data_l.getTime());

                    stmt4.setString(5, sqlData_l.toString());



                    java.util.Date data_e = formato_data_entrada.parse(tfPPagamento.getText());

                    java.sql.Date sqlData_e = new java.sql.Date(data_e.getTime());

                    stmt4.setString(6, sqlData_e.toString());



                    java.util.Date data_v = formato_data_entrada.parse(tfPVencimento.getText());

                    java.sql.Date sqlData_v = new java.sql.Date(data_v.getTime());

                    stmt4.setString(7, sqlData_v.toString());



                    stmt4.setString(8, tfPDocumento.getText());

                    stmt4.setString(9, "3.003.001");//Receitas Financeiras - Juros

                    //tfPDescricao.setText(tfPDescricao.getText() + " -Juros Recebidos- " + jLabelNr.getText());

                    stmt4.setString(10, (tfPDescricao.getText() + "Jrs Recebidos -" + jLabelNr.getText()));

                    //stmt4.setDouble(11, Double.parseDouble(tfPJuros.getText().replaceAll(",", ".")));



                    // Remover todos os pontos, exceto o decimal

                    String valorTexto = tfPJuros.getText().replaceAll("\\.", "");

                    // Substituir a vírgula decimal por ponto decimal

                    valorTexto = valorTexto.replaceAll(",", ".");

                    // Parse para Double

                    stmt4.setDouble(11, Double.parseDouble(valorTexto));



                    stmt4.setString(12, sqlData_l.toString());



                    stmt4.setString(13, "JP");

                    stmt4.setString(14, "V");

                    stmt4.execute();

                    stmt4.close();

                    conJs.close();

                } catch (SQLException | ParseException ex) {

                    Logger.getLogger(Tela_Receber.class.getName()).log(Level.SEVERE, null, ex);

                } finally {

                    conexao.fecharConexao(); // Fecha a conexão no final

                }

            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(null, "Erro ao fechar a conexão em Juros Recebidos! " + ex);

            }

        }

        //Final de lançamento de juros recebidos

        JOptionPane.showMessageDialog(null, "Recebimento parcial efetuado com sucesso!");

        dispose();

    }

}

