package view;


import utilitarios.Conexao;

import java.sql.Connection;

import java.sql.PreparedStatement;

import java.sql.ResultSet;

import java.sql.SQLException;

import java.text.ParseException;

import java.text.SimpleDateFormat;

import java.util.logging.Level;

import java.util.logging.Logger;

import javax.swing.JComboBox;

import javax.swing.JFormattedTextField;

import javax.swing.JOptionPane;



public class Tela_Pagar extends javax.swing.JFrame {



    /**

     * Creates new form Tela_Pagar

     */

    Conexao conexao = new Conexao();



    //Carrega combobox de Favorecidos

    CarregarCbx re = new CarregarCbx();



    public Tela_Pagar() throws SQLException {

        initComponents();

        re.CarregarCbx("tbrecursos", "nomebco", jComboBoxOrigem);

        this.setLocationRelativeTo(null);

        Tela_Mov Lanc = new Tela_Mov();

        jLabelNr.setText(Tela_Mov.textoidMov);

        tfPLanc.setText(Tela_Mov.textoLancto);

        tfPEmissao.setText(Tela_Mov.textoEmissao);

        tfPVencimento.setText(Tela_Mov.textoVencimento);

        tfPPagamento.setText(Tela_Mov.textoApresentacao);

        tfPDocumento.setText(Tela_Mov.textoDocumento);

        tfPDescricao.setText(Tela_Mov.textoDescricao);

        jComboBoxOrigem.setSelectedItem(0);

        tfPDestino.setText(Tela_Mov.textoClass);

        tfPVrPago.setText(Tela_Mov.textoVrPg);

        tfPDesconto.setText("0");

        tfPJuros.setText("0");

        tfPFav.setText(Tela_Mov.textoFav);

        tfPNrFav.setText(Tela_Mov.textoNrFav);

        tfPNrRecurso.setText(Tela_Mov.textoNrRecurso);

        tfPClRecurso.setText(Tela_Mov.textoRecurso);

    }



    /**

     * This method is called from within the constructor to initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is always

     * regenerated by the Form Editor.

     */

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButtonFechaTelaPagto = new javax.swing.JButton();
        jButtonLancaPgto = new javax.swing.JButton();
        tfPDocumento = new javax.swing.JTextField();
        tfPDescricao = new javax.swing.JTextField();
        tfPDestino = new javax.swing.JTextField();
        jComboBoxOrigem = new javax.swing.JComboBox<>();
        tfPVrPago = new javax.swing.JTextField();
        tfPDesconto = new javax.swing.JTextField();
        tfPJuros = new javax.swing.JTextField();
        tfPEmissao = new javax.swing.JFormattedTextField();
        tfPLanc = new javax.swing.JFormattedTextField();
        tfPPagamento = new javax.swing.JFormattedTextField();
        tfPVencimento = new javax.swing.JFormattedTextField();
        jLabelNr = new javax.swing.JLabel();
        tfPFav = new javax.swing.JTextField();
        tfPNrFav = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfPNrRec = new javax.swing.JTextField();
        tfPRec = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfPNrRecurso = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfPClRecurso = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Pagamentos");
        setUndecorated(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Home.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-P A G A M E N T O-");

        jLabel3.setText("Lançamento");

        jLabel4.setText("Emissão");

        jLabel5.setText("Vencimento");

        jLabel6.setText("Pagamento");

        jLabel7.setText("Documento");

        jLabel8.setText("Descrição");

        jLabel9.setText("Origem do Recurso");

        jLabel10.setText("Classificação");

        jLabel11.setText("Valor Pago");

        jLabel12.setText("Desconto Obtido");

        jLabel13.setText("Juros Pagos");

        jButtonFechaTelaPagto.setText("Cancelar");
        jButtonFechaTelaPagto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonFechaTelaPagto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFechaTelaPagtoActionPerformed(evt);
            }
        });

        jButtonLancaPgto.setBackground(new java.awt.Color(255, 0, 0));
        jButtonLancaPgto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonLancaPgto.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLancaPgto.setText("Lançar");
        jButtonLancaPgto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonLancaPgto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLancaPgtoActionPerformed(evt);
            }
        });

        tfPDocumento.setEnabled(false);

        tfPDescricao.setEnabled(false);

        tfPDestino.setEnabled(false);

        jComboBoxOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOrigemActionPerformed(evt);
            }
        });

        tfPVrPago.setEnabled(false);

        tfPEmissao.setEnabled(false);

        tfPLanc.setEnabled(false);

        tfPPagamento.setEnabled(false);

        tfPVencimento.setEnabled(false);

        tfPFav.setEnabled(false);

        tfPNrFav.setEnabled(false);

        jLabel14.setText("Registro");

        tfPNrRec.setEnabled(false);

        tfPRec.setEnabled(false);

        jLabel15.setText("Fornec.");

        jLabel16.setText("V.Forn.");

        jLabel17.setText("  Baixar");

        tfPNrRecurso.setEnabled(false);

        jLabel18.setText("vRecurso");

        tfPClRecurso.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabelNr, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfPLanc, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfPClRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel3)
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel18)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel4)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(tfPVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addGap(48, 48, 48)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(19, 19, 19))))
                            .addComponent(tfPDocumento)
                            .addComponent(tfPDescricao)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfPNrRec, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfPRec, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(tfPNrRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfPNrFav, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfPFav, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(tfPDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPVrPago, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(tfPDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel13))
                            .addComponent(tfPJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLancaPgto)
                .addGap(144, 144, 144)
                .addComponent(jButtonFechaTelaPagto)
                .addGap(213, 213, 213))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(7, 7, 7)
                                .addComponent(jLabelNr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel18))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfPLanc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPClRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)
                        .addComponent(tfPPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(tfPVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPNrRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfPVrPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfPDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfPFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfPNrFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfPNrRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFechaTelaPagto)
                    .addComponent(jButtonLancaPgto))
                .addGap(49, 49, 49))
        );

        jButtonLancaPgto.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void jButtonFechaTelaPagtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFechaTelaPagtoActionPerformed

        // Apenas volta para Tela_Mov sem alterar nada

        Tela_Mov exibir = null;

        try {

            exibir = new Tela_Mov();

            exibir.setVisible(true);

        } catch (SQLException ex) {

            Logger.getLogger(Tela_Pagar.class.getName()).log(Level.SEVERE, null, ex);

        }

        this.dispose(); // Fecha Tela_Pagar

    }//GEN-LAST:event_jButtonFechaTelaPagtoActionPerformed



    private void jComboBoxOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOrigemActionPerformed

        String selectedValue = jComboBoxOrigem.getSelectedItem().toString();//.substring(11);

        var texto = selectedValue.length();

        selectedValue = jComboBoxOrigem.getSelectedItem().toString().substring(texto - 14);

        if (!selectedValue.isEmpty()) {

            selectedValue = jComboBoxOrigem.getSelectedItem().toString().substring(texto - 14);

            String frase1 = selectedValue.substring(0, 4);

            tfPNrRec.setText(frase1);

            String frase2 = selectedValue.substring(5);

            tfPRec.setText(frase2);

        }

    }//GEN-LAST:event_jComboBoxOrigemActionPerformed



    // === ADICIONE ESTE MÉTODO NA CLASSE Tela_Pagar.java ===

    private void log(String mensagem) {

        System.out.println("[LOG Tela_Pagar] " + mensagem);

    }



    private void jButtonLancaPgtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLancaPgtoActionPerformed

        Object[] options = {"Sim", "Não"};

        int i = JOptionPane.showOptionDialog(null, "O Pagamento é parcial?", "Forma de Pagamento", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);



        if (i == JOptionPane.YES_OPTION) {

            try {

                BxParcial();

            } catch (ParseException | SQLException ex) {

                Logger.getLogger(Tela_Pagar.class.getName()).log(Level.SEVERE, null, ex);

            }

            return;

        }



        // === VALORES ===

        double valorPago = Double.parseDouble(tfPVrPago.getText().replaceAll("[^0-9,-]", "").replace(",", "."));

        double desconto = tfPDesconto.getText().isEmpty() ? 0 : Double.parseDouble(tfPDesconto.getText().replace(",", "."));

        double juros = tfPJuros.getText().isEmpty() ? 0 : Double.parseDouble(tfPJuros.getText().replace(",", "."));



        // === DATAS ===

        SimpleDateFormat formatoEntrada = new SimpleDateFormat("dd/MM/yyyy");

        SimpleDateFormat formatoSql = new SimpleDateFormat("yyyy-MM-dd");

        String dataPagtoSql;

        String dataVctoSql;

        try {

            dataPagtoSql = formatoSql.format(formatoEntrada.parse(tfPPagamento.getText()));

            dataVctoSql = formatoSql.format(formatoEntrada.parse(Tela_Mov.textoVencimento));

        } catch (ParseException e) {

            JOptionPane.showMessageDialog(null, "Erro na data.");

            return;

        }



        // === RECURSO ORIGINAL ===

        String vrecursoOrig = Tela_Mov.textoRecurso;

        boolean isEmprestimo = vrecursoOrig != null && (vrecursoOrig.equals("2.001.004") || vrecursoOrig.equals("2.002.001"));



        try {

            conexao.abrirConexao();

            Connection con = conexao.getConexao();

            String sqlInsert = "INSERT INTO tbmovimento(recurso,vrecurso,clifor,vCliFor,dtlancto,dtEmi,dtVcto,documento,classif,Descr,valor,dtApr,statusMov,Prev) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";



            //String sqlUpdate = "UPDATE tbmovimento SET dtVcto = ?, dtApr = ?, statusMov = ? WHERE idMov = ?";

            // === STRING DE UPDATE COM O CAMPO vrecurso ===

            String sqlUpdate = "UPDATE tbmovimento SET dtVcto = ?, dtApr = ?, statusMov = ?, vrecurso = ? WHERE idMov = ?";



            if (isEmprestimo) {

                // ===================================================================

                // EMPRÉSTIMO: 3 LANÇAMENTOS + ATUALIZAÇÃO DOS ORIGINAIS

                // ===================================================================

                // === 1. BAIXA DA DÍVIDA (0079 ? 2.001.004 ===

                try (PreparedStatement stmt = con.prepareStatement(sqlInsert)) {

                    stmt.setString(1, "0079");

                    stmt.setString(2, "2.001.004");

                    stmt.setString(3, tfPNrFav.getText());

                    stmt.setString(4, tfPFav.getText());

                    stmt.setString(5, dataPagtoSql);

                    stmt.setString(6, dataPagtoSql);

                    stmt.setString(7, dataVctoSql);

                    stmt.setString(8, tfPDocumento.getText());

                    stmt.setString(9, "9.001.003");

                    stmt.setString(10, "Pagamento Empréstimo - " + tfPDescricao.getText() + " -PG- " + jLabelNr.getText());

                    stmt.setDouble(11, -valorPago);  //Inverto o sinal para deixar positivo ao lançar

                    stmt.setString(12, dataPagtoSql);

                    stmt.setString(13, "PG");

                    stmt.setString(14, "V");

                    stmt.execute();

                }



                // === 2. SAÍDA DO BANCO (0237) ===

                try (PreparedStatement stmt = con.prepareStatement(sqlInsert)) {

                    stmt.setString(1, tfPNrRec.getText());

                    stmt.setString(2, tfPRec.getText());

                    stmt.setString(3, tfPNrFav.getText());

                    stmt.setString(4, tfPFav.getText());

                    stmt.setString(5, dataPagtoSql);

                    stmt.setString(6, dataPagtoSql);

                    stmt.setString(7, dataPagtoSql);

                    stmt.setString(8, tfPDocumento.getText());

                    stmt.setString(9, "9.001.003");

                    stmt.setString(10, "Saída Pagto Empréstimo - " + tfPDescricao.getText() + " -PG- " + jLabelNr.getText());

                    stmt.setDouble(11, +valorPago);  // Inverto o sinal para deixar negativo para sair da origem do recurso

                    stmt.setString(12, dataPagtoSql);

                    stmt.setString(13, "PG");

                    stmt.setString(14, "V");

                    stmt.execute();

                }



                // === 3. BAIXA DO PASSIVO (0080) ===

                try (PreparedStatement stmt = con.prepareStatement(sqlInsert)) {

                    stmt.setString(1, "0080");

                    stmt.setString(2, vrecursoOrig);

                    stmt.setString(3, tfPNrFav.getText());

                    stmt.setString(4, tfPFav.getText());

                    stmt.setString(5, dataPagtoSql);

                    stmt.setString(6, dataPagtoSql);

                    stmt.setString(7, dataVctoSql);

                    stmt.setString(8, tfPDocumento.getText());

                    stmt.setString(9, "9.001.003");

                    stmt.setString(10, "Baixa Obrig.Empréstimo - " + tfPDescricao.getText() + " -PG- " + jLabelNr.getText());

                    stmt.setDouble(11, -valorPago);  // Inverto o sinal para deix\\u00e1-lo positivo e matar o lançamento do recurso 0080

                    stmt.setString(12, dataPagtoSql);

                    stmt.setString(13, "PG");

                    stmt.setString(14, "V");

                    stmt.execute();

                }



                // === ATUALIZAR REGISTROS ORIGINAIS (0079 e 0080) ===

                String idAPagar = Tela_Mov.textoidMov;  // Ex: "5154"

                String idPassivo = null;



                try {

                    int id0079 = Integer.parseInt(idAPagar);

                    idPassivo = String.valueOf(id0079 - 1);  // 5153



                    // Verifica se é realmente o 0080

                    String sqlCheck = "SELECT recurso FROM tbmovimento WHERE idMov = ? AND recurso = '0080'";

                    try (PreparedStatement check = con.prepareStatement(sqlCheck)) {

                        check.setString(1, idPassivo);

                        ResultSet rs = check.executeQuery();

                        if (!rs.next()) {

                            idPassivo = null;

                        }

                    }

                } catch (NumberFormatException e) {

                    log("Erro: ID inválido: " + idAPagar);

                }



                // Atualiza 0079

                if (idAPagar != null && !idAPagar.isEmpty()) {

                    try (PreparedStatement upd = con.prepareStatement(sqlUpdate)) {

                        upd.setString(1, dataPagtoSql); //dataVctoSql

                        upd.setString(2, dataPagtoSql);

                        upd.setString(3, "PG");

                        upd.setString(4, idAPagar);

                        upd.executeUpdate();

                    }

                }



                // Atualiza 0080

                if (idPassivo != null) {

                    try (PreparedStatement upd = con.prepareStatement(sqlUpdate)) {

                        upd.setString(1, dataPagtoSql); //dataVctoSql

                        upd.setString(2, dataPagtoSql);

                        upd.setString(3, "PG");

                        upd.setString(4, idPassivo);

                        upd.executeUpdate();

                    }

                }



                //log("Empréstimo pago com sucesso: 3 lançamentos + atualização de IDs " + idAPagar + " e " + idPassivo);

                JOptionPane.showMessageDialog(null, "Empréstimo pago com sucesso!!!");



            } else {

                // ===================================================================

                // PAGAMENTO NORMAL (NÃO é EMPRÉSTIMO) - 2 LANÇAMENTOS + ATUALIZAÇÃO DO ORIGINAL

                // ===================================================================



                String idOriginal = Tela_Mov.textoidMov; // ID do registro original (0079)



                // === 1. BAIXA NO CONTAS A PAGAR (0079 ? 2.001.002) ? -valorPago (anula a dívida) ===

                try (PreparedStatement stmt = con.prepareStatement(sqlInsert)) {

                    stmt.setString(1, "0079");

                    if (tfPRec.getText().equals("2.001.003")) {

                        stmt.setString(2, "2.001.003");  // Pagamento com cartão ? baixa no cartão

                    } else {

                        stmt.setString(2, "2.001.002");  // Pagamento normal ? baixa em Contas à Pagar

                    }

                    stmt.setString(3, tfPNrFav.getText());

                    stmt.setString(4, tfPFav.getText());

                    //stmt.setString(5, dataPagtoSql);
                    
                    if (tfPRec.getText().equals("2.001.003")) {

                        stmt.setString(5, formatoSql.format(formatoEntrada.parse(tfPEmissao.getText())));  // Pagamento com cartão ? baixa no cartão

                    } else {

                        stmt.setString(5, dataPagtoSql);  // Pagamento com cartão ? baixa no cartão

                    }

                    stmt.setString(6, formatoSql.format(formatoEntrada.parse(tfPEmissao.getText())));

                    stmt.setString(7, formatoSql.format(formatoEntrada.parse(tfPVencimento.getText())));

                    stmt.setString(8, tfPDocumento.getText());

                    stmt.setString(9, "9.001.003");

                    tfPDescricao.setText(tfPDescricao.getText() + " -PG- " + jLabelNr.getText());

                    stmt.setString(10, tfPDescricao.getText());

                    stmt.setDouble(11, -valorPago);  // NEGATIVO: anula o -valorPago original

                    stmt.setString(12, dataPagtoSql);

                    stmt.setString(13, "PG");

                    stmt.setString(14, "V");

                    stmt.execute();

                }



                // === 2. SAÍDA DO BANCO (recurso de origem) ? +valorPago (sai do banco) ===

                try (PreparedStatement stmt = con.prepareStatement(sqlInsert)) {

                    stmt.setString(1, tfPNrRec.getText());

                    stmt.setString(2, tfPRec.getText());

                    stmt.setString(3, tfPNrFav.getText());

                    stmt.setString(4, tfPFav.getText());

                    //stmt.setString(5, dataPagtoSql);
                    if (tfPRec.getText().equals("2.001.003")) {

                        stmt.setString(5, formatoSql.format(formatoEntrada.parse(tfPEmissao.getText())));  // Pagamento com cartão ? baixa no cartão

                    } else {

                        stmt.setString(5, dataPagtoSql);  // Pagamento com cartão ? baixa no cartão

                    }
                    
                    stmt.setString(6, formatoSql.format(formatoEntrada.parse(tfPEmissao.getText())));

                    stmt.setString(7, formatoSql.format(formatoEntrada.parse(tfPVencimento.getText())));

                    stmt.setString(8, tfPDocumento.getText());

                    stmt.setString(9, "9.001.003");

                    stmt.setString(10, tfPDescricao.getText());

                    stmt.setDouble(11, +valorPago);  // POSITIVO: sai do banco

                    if (tfPRec.getText().equals("2.001.003")) {

                        stmt.setNull(12, java.sql.Types.DATE);

                        stmt.setString(13, "");

                    } else {

                        stmt.setString(12, dataPagtoSql);

                        stmt.setString(13, "PG");

                    }

                    stmt.setString(14, "V");

                    stmt.execute();

                }

                // === ATUALIZA O REGISTRO ORIGINAL (0079) COM dtApr, PG e vrecurso correto ===

                if (idOriginal != null && !idOriginal.isEmpty()) {

                    try (PreparedStatement upd = con.prepareStatement(sqlUpdate)) {

                        upd.setString(1, dataVctoSql);                    // dtVcto (mantém)

                        upd.setString(2, dataPagtoSql);                   // dtApr = data do pagamento

                        upd.setString(3, "PG");                           // statusMov = PG (pago)



                        // === AQUI A MÁGICA: se pagou com cartão, muda o vrecurso para cartão ===

                        if (tfPRec.getText().equals("2.001.003")) {

                            upd.setString(4, "2.001.003");  // vire dívida de cartão

                        } else {

                            upd.setString(4, "2.001.002");  // mantém como Contas à Pagar (pago)

                        }



                        upd.setString(5, idOriginal);                     // WHERE idMov

                        upd.executeUpdate();

                    }

                }



                // === DESCONTO OBTIDO ===

                if (desconto > 0) {

                    try (PreparedStatement stmt = con.prepareStatement(sqlInsert)) {

                        stmt.setString(1, tfPNrRec.getText());

                        stmt.setString(2, tfPRec.getText());

                        stmt.setString(3, tfPNrFav.getText());

                        stmt.setString(4, tfPFav.getText());

                        stmt.setString(5, dataPagtoSql);

                        stmt.setString(6, formatoSql.format(formatoEntrada.parse(tfPEmissao.getText())));

                        stmt.setString(7, formatoSql.format(formatoEntrada.parse(tfPVencimento.getText())));

                        stmt.setString(8, tfPDocumento.getText());

                        stmt.setString(9, "3.003.003");

                        tfPDescricao.setText(tfPDescricao.getText() + " -Descto Obtido- " + jLabelNr.getText());

                        stmt.setString(10, tfPDescricao.getText());

                        stmt.setDouble(11, +desconto);

                        stmt.setString(12, dataPagtoSql);

                        stmt.setString(13, "DO");

                        stmt.setString(14, "V");

                        stmt.execute();

                    }

                }



                // === JUROS PAGOS ===

                if (juros > 0) {

                    try (PreparedStatement stmt = con.prepareStatement(sqlInsert)) {

                        stmt.setString(1, tfPNrRec.getText());

                        stmt.setString(2, tfPRec.getText());

                        stmt.setString(3, tfPNrFav.getText());

                        stmt.setString(4, tfPFav.getText());

                        stmt.setString(5, dataPagtoSql);

                        stmt.setString(6, formatoSql.format(formatoEntrada.parse(tfPEmissao.getText())));

                        stmt.setString(7, formatoSql.format(formatoEntrada.parse(tfPVencimento.getText())));

                        stmt.setString(8, tfPDocumento.getText());

                        stmt.setString(9, "4.008.003");

                        tfPDescricao.setText(tfPDescricao.getText() + " -Juros Pagos- " + jLabelNr.getText());

                        stmt.setString(10, tfPDescricao.getText());

                        stmt.setDouble(11, -juros);

                        stmt.setString(12, dataPagtoSql);

                        stmt.setString(13, "JP");

                        stmt.setString(14, "V");

                        stmt.execute();

                    }

                }



                JOptionPane.showMessageDialog(null, "Pagamento normal efetuado com sucesso!");

            }

            con.close();

        } catch (Exception ex) {

            Logger.getLogger(Tela_Pagar.class.getName()).log(Level.SEVERE, null, ex);

            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());

            return;

        } finally {

            conexao.fecharConexao();

        }



        JOptionPane.showMessageDialog(null, "Pagamento efetuado com sucesso!");

        try {

            new Tela_Mov().setVisible(true);

        } catch (SQLException ex) {

        }

        dispose();

    }//GEN-LAST:event_jButtonLancaPgtoActionPerformed



    /**

     * @param args the command line arguments

     */

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 

         */

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;

                }

            }

        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(Tela_Pagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(Tela_Pagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(Tela_Pagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(Tela_Pagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        //</editor-fold>

        //</editor-fold>



        /* Create and display the form */

        java.awt.EventQueue.invokeLater(() -> {

            try {

                new Tela_Pagar().setVisible(true);

            } catch (SQLException ex) {

                Logger.getLogger(Tela_Pagar.class.getName()).log(Level.SEVERE, null, ex);

            }

        });

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechaTelaPagto;
    private javax.swing.JButton jButtonLancaPgto;
    private javax.swing.JComboBox<String> jComboBoxOrigem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNr;
    private javax.swing.JFormattedTextField tfPClRecurso;
    private javax.swing.JTextField tfPDesconto;
    private javax.swing.JTextField tfPDescricao;
    private javax.swing.JTextField tfPDestino;
    private javax.swing.JTextField tfPDocumento;
    private javax.swing.JFormattedTextField tfPEmissao;
    private javax.swing.JTextField tfPFav;
    private javax.swing.JTextField tfPJuros;
    private javax.swing.JFormattedTextField tfPLanc;
    private javax.swing.JTextField tfPNrFav;
    private javax.swing.JTextField tfPNrRec;
    private javax.swing.JTextField tfPNrRecurso;
    private javax.swing.JFormattedTextField tfPPagamento;
    private javax.swing.JTextField tfPRec;
    private javax.swing.JFormattedTextField tfPVencimento;
    private javax.swing.JTextField tfPVrPago;
    // End of variables declaration//GEN-END:variables



    private static class CarregarCbx {



        @SuppressWarnings({"empty-statement", "unchecked"})

        public void CarregarCbx(String tabela, String valor, JComboBox combo) throws SQLException {

            //String sql = "Select * FROM " + tabela + " ORDER BY apelidoCliFor";

            String sql = "Select * FROM " + tabela;

            // Cria uma instância da classe Conexao

            Conexao conexao = new Conexao();

            try {

                // Abre a conexão

                conexao.abrirConexao();

                // Prepara e executa a consulta

                try ( // Obtém a conexão

                        Connection con = conexao.getConexao()) {

                    // Prepara e executa a consulta

                    PreparedStatement stmt = con.prepareStatement(sql);

                    ResultSet rs = stmt.executeQuery();

                    while (rs.next()) {

                        combo.addItem(rs.getString(valor) + "-" + (rs.getString("codigo") + "-" + (rs.getString("fk_gpprinc"))));

                    }

                    rs.close();

                    stmt.close();

                }

            } catch (SQLException ex) {

                Logger.getLogger(Tela_Mov.class

                        .getName()).log(Level.SEVERE, null, ex);

            } finally {

                // Fecha a conexão no final

                conexao.fecharConexao();

            }

        }

    }



    private void BxParcial() throws ParseException, SQLException {

        //SimpleDateFormat formato_data = new SimpleDateFormat("dd/MM/yyyy");

        Double cheio = Double.parseDouble(tfPVrPago.getText().substring(1).replaceAll(",", "."));

        Double vparc = Double.parseDouble(JOptionPane.showInputDialog("Informe o valor parcial: "));

        Double Resta = (cheio - vparc);

        Resta = Resta * -1;

        Double t = Double.parseDouble(tfPDesconto.getText().replaceAll(",", "."));

        Double j = Double.parseDouble(tfPJuros.getText().replaceAll(",", "."));



        try {

            conexao.abrirConexao(); // Abre a conexão

            Connection con = conexao.getConexao(); // Obtém a conexão

            String sql = "UPDATE tbmovimento SET recurso=?,vrecurso=?,clifor=?,vclifor=?,dtlancto=?,dtEmi=?,dtVcto=?,documento=?,classif=?,Descr=?,valor=?,dtApr=?,statusMov=?,Prev=? WHERE idMov=?";

            PreparedStatement stm = con.prepareStatement(sql);

            stm.setString(1, tfPNrRecurso.getText());

            stm.setString(2, "2.001.002");

            stm.setString(3, tfPNrFav.getText());

            stm.setString(4, tfPFav.getText());

            // Formato para parsear as datas de entrada

            SimpleDateFormat formato_data_entrada = new SimpleDateFormat("dd/MM/yyyy");

            java.util.Date data_l = formato_data_entrada.parse(tfPPagamento.getText());

            java.sql.Date sqlData_l = new java.sql.Date(data_l.getTime());

            stm.setString(5, sqlData_l.toString());

            java.util.Date data_e = formato_data_entrada.parse(tfPEmissao.getText());

            java.sql.Date sqlData_e = new java.sql.Date(data_e.getTime());

            stm.setString(6, sqlData_e.toString());

            java.util.Date data_v = formato_data_entrada.parse(tfPVencimento.getText());

            java.sql.Date sqlData_v = new java.sql.Date(data_v.getTime());

            stm.setString(7, sqlData_v.toString());

            stm.setString(8, tfPDocumento.getText());

            stm.setString(9, tfPDestino.getText());

            stm.setString(10, ("1/2-" + tfPDescricao.getText() + jLabelNr.getText()));

            stm.setDouble(11, vparc * -1);

            stm.setString(12, sqlData_l.toString());

            stm.setString(13, "PG");

            stm.setString(14, "V");

            stm.setString(15, jLabelNr.getText());

            stm.execute();

            stm.close();

            con.close();

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "Erro ao fechar a conexão em Atualização Parcial! " + ex);

        } finally {

            conexao.fecharConexao(); // Fecha a conexão no final

        }



        try {

            conexao.abrirConexao(); // Abre a conexão

            Connection conp1 = conexao.getConexao(); // Obtém a conexão

            //Connection conp1 = Conexao.faz_conexao();

            String sqlp = "INSERT INTO tbmovimento(recurso,vrecurso,clifor,vCliFor,dtlancto,dtEmi,dtVcto,documento,classif,Descr,valor,dtApr,statusMov,Prev) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement stmtp = conp1.prepareStatement(sqlp);

            // Início do Lançamento de Pagamento Parcial +Entrada+ (Fornecedor)

            stmtp.setString(1, tfPNrRecurso.getText());

            stmtp.setString(2, "2.001.002");//Contas à Pagar

            stmtp.setString(3, tfPNrFav.getText());

            stmtp.setString(4, tfPFav.getText());

            // Formato para parsear as datas de entrada

            SimpleDateFormat formato_data_entrada = new SimpleDateFormat("dd/MM/yyyy");

            java.util.Date data_l = formato_data_entrada.parse(tfPPagamento.getText());

            java.sql.Date sqlData_l = new java.sql.Date(data_l.getTime());

            stmtp.setString(5, sqlData_l.toString());

            java.util.Date data_e = formato_data_entrada.parse(tfPEmissao.getText());

            java.sql.Date sqlData_e = new java.sql.Date(data_e.getTime());

            stmtp.setString(6, sqlData_e.toString());

            java.util.Date data_v = formato_data_entrada.parse(tfPVencimento.getText());

            java.sql.Date sqlData_v = new java.sql.Date(data_v.getTime());

            stmtp.setString(7, sqlData_v.toString());

            stmtp.setString(8, tfPDocumento.getText());

            stmtp.setString(9, "9.001.003");

            stmtp.setString(10, ("1/2-" + tfPDescricao.getText() + jLabelNr.getText()));

            stmtp.setDouble(11, vparc);

            stmtp.setString(12, sqlData_l.toString());

            stmtp.setString(13, "PG");

            stmtp.setString(14, "V");

            stmtp.execute();

            stmtp.close();

            conp1.close();

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "Erro ao fechar a conexão em Pagamento Parcial! " + ex);

        } catch (ParseException ex) {

            Logger.getLogger(Tela_Pagar.class.getName()).log(Level.SEVERE, null, ex);

        } finally {

            conexao.fecharConexao(); // Fecha a conexão no final

        }

        //fim pagamento - lançamento 1



        //Inicio pagamento2 - lançamento2 - Saída -

        conexao.abrirConexao(); // Abre a conexão

        Connection conp2 = conexao.getConexao(); // Obtém a conexão

        String sqlp2 = "INSERT INTO tbmovimento(recurso,vrecurso,clifor,vCliFor,dtlancto,dtEmi,dtVcto,documento,classif,Descr,valor,dtApr,statusMov,Prev) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

        SimpleDateFormat formato_data2 = new SimpleDateFormat("yyyy-MM-dd");

        try {

            PreparedStatement stmtp2 = conp2.prepareStatement(sqlp2);

            stmtp2.setString(1, tfPNrRec.getText());

            stmtp2.setString(2, tfPRec.getText());

            stmtp2.setString(3, tfPNrFav.getText());

            stmtp2.setString(4, tfPFav.getText());

            // Formato para parsear as datas de entrada

            SimpleDateFormat formato_data_entrada = new SimpleDateFormat("dd/MM/yyyy");

            java.util.Date data_l = formato_data_entrada.parse(tfPPagamento.getText());

            java.sql.Date sqlData_l = new java.sql.Date(data_l.getTime());

            stmtp2.setString(5, sqlData_l.toString());

            java.util.Date data_e = formato_data_entrada.parse(tfPEmissao.getText());

            java.sql.Date sqlData_e = new java.sql.Date(data_e.getTime());

            stmtp2.setString(6, sqlData_e.toString());

            java.util.Date data_v = formato_data_entrada.parse(tfPVencimento.getText());

            java.sql.Date sqlData_v = new java.sql.Date(data_v.getTime());

            stmtp2.setString(7, sqlData_v.toString());

            stmtp2.setString(8, tfPDocumento.getText());

            stmtp2.setString(9, "9.001.003");

            stmtp2.setString(10, ("1/2-" + tfPDescricao.getText() + jLabelNr.getText()));

            stmtp2.setDouble(11, (vparc * -1));

            stmtp2.setString(12, sqlData_l.toString());

            stmtp2.setString(13, "PG");

            stmtp2.setString(14, "V");

            stmtp2.execute();

            stmtp2.close();

            conp2.close();

        } catch (SQLException ex) {

            Logger.getLogger(Tela_Pagar.class.getName()).log(Level.SEVERE, null, ex);

        } finally {

            conexao.fecharConexao(); // Fecha a conexão no final

        }

        //fim pagamento - lançamento 2



        //Inicio do Lançamento de Desdobramento

        //Connection conpD = null;

        try {

            conexao.abrirConexao(); // Abre a conexão

            Connection conpD = conexao.getConexao(); // Obtém a conexão

            String sqlpD = "INSERT INTO tbmovimento(recurso,vrecurso,clifor,vCliFor,dtlancto,dtEmi,dtVcto,documento,classif,Descr,valor,dtApr,statusMov,Prev) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement stmtpD = conpD.prepareStatement(sqlpD);

            stmtpD.setString(1, tfPNrRecurso.getText());

            stmtpD.setString(2, "2.001.002"); // Contas à Pagar

            stmtpD.setString(3, tfPNrFav.getText());

            stmtpD.setString(4, tfPFav.getText());

            // Formato para parsear as datas de entrada

            SimpleDateFormat formato_data_entrada = new SimpleDateFormat("dd/MM/yyyy");

            java.util.Date data_l = formato_data_entrada.parse(tfPPagamento.getText());

            java.sql.Date sqlData_l = new java.sql.Date(data_l.getTime());

            stmtpD.setString(5, sqlData_l.toString());

            java.util.Date data_e = formato_data_entrada.parse(tfPEmissao.getText());

            java.sql.Date sqlData_e = new java.sql.Date(data_e.getTime());

            stmtpD.setString(6, sqlData_e.toString());

            java.util.Date data_v = formato_data_entrada.parse(tfPVencimento.getText());

            java.sql.Date sqlData_v = new java.sql.Date(data_v.getTime());

            stmtpD.setString(7, sqlData_v.toString());

            stmtpD.setString(8, tfPDocumento.getText());

            stmtpD.setString(9, tfPDestino.getText());

            stmtpD.setString(10, "2/2-" + tfPDescricao.getText());

            stmtpD.setDouble(11, Resta);

            stmtpD.setString(12, null);

            stmtpD.setString(13, "");

            stmtpD.setString(14, "V");

            stmtpD.execute();

            stmtpD.close();

            conpD.close();

        } catch (SQLException ex) {

            Logger.getLogger(Tela_Pagar.class.getName()).log(Level.SEVERE, null, ex);

        } finally {

            conexao.fecharConexao(); // Fecha a conexão no final

        }

        //Fim do lançamento de desdobramento



        //Inicio de Lançamento de Desconto Obtido + tfPDesconto

        if (t > 0) {

            conexao.abrirConexao(); // Abre a conexão

            Connection conDs = conexao.getConexao(); // Obtém a conexão

            String sql3 = "INSERT INTO tbmovimento(recurso,vrecurso,clifor,vCliFor,dtlancto,dtEmi,dtVcto,documento,classif,Descr,valor,dtApr,statusMov,Prev) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

            try (PreparedStatement stmt3 = conDs.prepareStatement(sql3)) {

                stmt3.setString(1, tfPNrRec.getText()); //Banco de Origem do Recurso 

                stmt3.setString(2, tfPRec.getText()); // Vinculo da Origem Recurso

                stmt3.setString(3, tfPNrFav.getText()); //Numero do Favorecido 

                stmt3.setString(4, tfPFav.getText()); // Vinculo do Favorecido

                // Formato para parsear as datas de entrada

                SimpleDateFormat formato_data_entrada = new SimpleDateFormat("dd/MM/yyyy");

                java.util.Date data_l = formato_data_entrada.parse(tfPPagamento.getText());

                java.sql.Date sqlData_l = new java.sql.Date(data_l.getTime());

                stmt3.setString(5, sqlData_l.toString());

                java.util.Date data_e = formato_data_entrada.parse(tfPEmissao.getText());

                java.sql.Date sqlData_e = new java.sql.Date(data_e.getTime());

                stmt3.setString(6, sqlData_e.toString());

                java.util.Date data_v = formato_data_entrada.parse(tfPVencimento.getText());

                java.sql.Date sqlData_v = new java.sql.Date(data_v.getTime());

                stmt3.setString(7, sqlData_v.toString());

                stmt3.setString(8, tfPDocumento.getText());

                stmt3.setString(9, "3.003.003"); // Lançado como Receitas Financeiras - Desconto Obtido

                tfPDescricao.setText(tfPDescricao.getText() + " -Descto Obtido- " + jLabelNr.getText());

                stmt3.setString(10, (tfPDescricao.getText()));

                // Remover todos os pontos, exceto o decimal

                String valorTexto = tfPDesconto.getText().replaceAll("\\.", "");

                // Substituir a vírgula decimal por ponto decimal

                valorTexto = valorTexto.replaceAll(",", ".");

                // Parse para Double

                stmt3.setDouble(11, Double.parseDouble(valorTexto));

                stmt3.setString(12, sqlData_l.toString());

                stmt3.setString(13, "DO");

                stmt3.setString(14, "V");

                stmt3.execute();

                stmt3.close();

                conDs.close();

            } catch (SQLException | ParseException ex) {

                Logger.getLogger(Tela_Pagar.class.getName()).log(Level.SEVERE, null, ex);

            } finally {

                conexao.fecharConexao(); // Fecha a conexão no final

            }

        }

        //Final de lançamento de Desconto Obtido



        //Início de Lançamento de juros pagos - tfPJuros

        if (j > 0) {

            conexao.abrirConexao(); // Abre a conexão

            Connection conJs = conexao.getConexao(); // Obtém a conexão

            String sql4 = "INSERT INTO tbmovimento(recurso,vrecurso,clifor,vCliFor,dtlancto,dtEmi,dtVcto,documento,classif,Descr,valor,dtApr,statusMov,Prev) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

            try (PreparedStatement stmt4 = conJs.prepareStatement(sql4)) {

                stmt4.setString(1, tfPNrRec.getText()); //urso

                stmt4.setString(2, tfPRec.getText());

                stmt4.setString(3, tfPNrFav.getText());

                stmt4.setString(4, tfPFav.getText());

                // Formato para parsear as datas de entrada

                SimpleDateFormat formato_data_entrada = new SimpleDateFormat("dd/MM/yyyy");

                java.util.Date data_l = formato_data_entrada.parse(tfPPagamento.getText());

                java.sql.Date sqlData_l = new java.sql.Date(data_l.getTime());

                stmt4.setString(5, sqlData_l.toString());

                java.util.Date data_e = formato_data_entrada.parse(tfPEmissao.getText());

                java.sql.Date sqlData_e = new java.sql.Date(data_e.getTime());

                stmt4.setString(6, sqlData_e.toString());

                java.util.Date data_v = formato_data_entrada.parse(tfPVencimento.getText());

                java.sql.Date sqlData_v = new java.sql.Date(data_v.getTime());

                stmt4.setString(7, sqlData_v.toString());

                stmt4.setString(8, tfPDocumento.getText());

                stmt4.setString(9, "4.008.003");//Despesas Financeiras - Juros

                tfPDescricao.setText(tfPDescricao.getText() + " -Juros Pagos- " + jLabelNr.getText());

                stmt4.setString(10, (tfPDescricao.getText()));

                // Remover todos os pontos, exceto o decimal

                String valorTexto = tfPJuros.getText().replaceAll("\\.", "");

                // Substituir a vírgula decimal por ponto decimal

                valorTexto = valorTexto.replaceAll(",", ".");

                // Parse para Double

                stmt4.setDouble(11, Double.parseDouble("-" + valorTexto));

                stmt4.setString(12, sqlData_l.toString());

                stmt4.setString(13, "JP");

                stmt4.setString(14, "V");

                stmt4.execute();

                stmt4.close();

                conJs.close();

            } catch (SQLException | ParseException ex) {

                Logger.getLogger(Tela_Pagar.class.getName()).log(Level.SEVERE, null, ex);

            } finally {

                conexao.fecharConexao(); // Fecha a conexão no final

            }

        }

        //Final de lançamento de juros pagos

        JOptionPane.showMessageDialog(null, "Pagamento parcial efetuado com sucesso!");



        Tela_Mov exibir = null;

        try {

            exibir = new Tela_Mov();

            exibir.setVisible(true);

            setVisible(false);

        } catch (SQLException ex) {

            Logger.getLogger(Tela_Pagar.class.getName()).log(Level.SEVERE, null, ex);

        }

        exibir.setVisible(true);

        setVisible(false);

    }

}

