package view;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import modelos.ProjetosEtapasHierarquicoTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.AxisLocation;
import org.jfree.chart.axis.DateAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.title.LegendTitle;
import org.jfree.data.gantt.Task;
import org.jfree.data.gantt.TaskSeries;
import org.jfree.data.gantt.TaskSeriesCollection;
import org.jfree.ui.RectangleEdge;
import javax.swing.table.TableModel;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelos.ProjetoEtapaHierarquico;


public class Tela_Consulta_Projetos extends javax.swing.JFrame {

    /**

     * Creates new form Tela_Cons_Projetos

     */

    public Tela_Consulta_Projetos() {

        initComponents();

        //tabelaProj.setModel(new ProjetosEtapasTableModel(""));

        tabelaProj.setModel(new ProjetosEtapasHierarquicoTableModel(""));

    }



    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {



    }



    /**

     * This method is called from within the constructor to initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is always

     * regenerated by the Form Editor.

     */

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelCorpo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProj = new javax.swing.JTable();
        jPanelBotoes = new javax.swing.JPanel();
        btnConcluidos = new javax.swing.JButton();
        btnNaoConcluidos = new javax.swing.JButton();
        btnGant = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        txt_proj = new javax.swing.JTextField();
        btn_Abrir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Projetos e Etapas");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("- Projetos e Etapas -");

        javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
        jPanelTitulo.setLayout(jPanelTituloLayout);
        jPanelTituloLayout.setHorizontalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTituloLayout.setVerticalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelaProj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PROJETO", "ID ETAPA", "ETAPA", "PRIORIDADE", "INIC_PREV", "INIC_REAL", "FIM_PREV", "FIM_REAL", "STATUS", "OBS", "R$ Previsto", "R$ Realizado", "% Realizado"
            }
        ));
        jScrollPane1.setViewportView(tabelaProj);

        javax.swing.GroupLayout jPanelCorpoLayout = new javax.swing.GroupLayout(jPanelCorpo);
        jPanelCorpo.setLayout(jPanelCorpoLayout);
        jPanelCorpoLayout.setHorizontalGroup(
            jPanelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCorpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanelCorpoLayout.setVerticalGroup(
            jPanelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCorpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnConcluidos.setText("Concluídos");
        btnConcluidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluidosActionPerformed(evt);
            }
        });

        btnNaoConcluidos.setText("Não Concluídos");
        btnNaoConcluidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNaoConcluidosActionPerformed(evt);
            }
        });

        btnGant.setText("Gant");
        btnGant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGantActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btn_Abrir.setText("Abrir Projeto");
        btn_Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AbrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoesLayout = new javax.swing.GroupLayout(jPanelBotoes);
        jPanelBotoes.setLayout(jPanelBotoesLayout);
        jPanelBotoesLayout.setHorizontalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btn_Abrir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_proj, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(btnConcluidos)
                .addGap(18, 18, 18)
                .addComponent(btnNaoConcluidos)
                .addGap(18, 18, 18)
                .addComponent(btnGant)
                .addGap(18, 18, 18)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFechar)
                .addContainerGap(350, Short.MAX_VALUE))
        );
        jPanelBotoesLayout.setVerticalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConcluidos)
                    .addComponent(btnNaoConcluidos)
                    .addComponent(btnGant)
                    .addComponent(btnImprimir)
                    .addComponent(btnFechar)
                    .addComponent(txt_proj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Abrir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelCorpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCorpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void exibirGrafico() throws ParseException {

        try {

            // Criar dataset para o gráfico de Gantt

            TaskSeriesCollection dataset = createDatasetFromTable(tabelaProj.getModel());



            // Criar gráfico

            JFreeChart chart = ChartFactory.createGanttChart(

                    "Gráfico de Gantt",

                    "Projeto/Etapa",

                    "Tempo",

                    dataset,

                    true,

                    true,

                    false

            );



            // Configurar eixo de tempo

            CategoryPlot plot = chart.getCategoryPlot();

            DateAxis rangeAxis = (DateAxis) plot.getRangeAxis();

            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

            rangeAxis.setDateFormatOverride(dateFormat);



            // Definir intervalo do eixo de tempo

            Date minDate = null;

            Date maxDate = null;

            for (int i = 0; i < dataset.getSeriesCount(); i++) {

                TaskSeries series = dataset.getSeries(i);

                for (Object obj : series.getTasks()) {

                    if (obj instanceof Task) {

                        Task task = (Task) obj;

                        Date start = task.getDuration().getStart();

                        Date end = task.getDuration().getEnd();

                        if (minDate == null || start.before(minDate)) {

                            minDate = start;

                        }

                        if (maxDate == null || end.after(maxDate)) {

                            maxDate = end;

                        }

                    }

                }

            }

            if (minDate != null && maxDate != null) {

                // Adicionar margem de 1 dia antes e depois

                long oneDay = 24 * 60 * 60 * 1000L;

                rangeAxis.setRange(new Date(minDate.getTime() - oneDay), new Date(maxDate.getTime() + oneDay));

            }



            // Mover eixo de tempo para a parte inferior

            plot.setRangeAxisLocation(AxisLocation.BOTTOM_OR_RIGHT);



            // Mover legenda para a parte inferior

            LegendTitle legend = chart.getLegend();

            legend.setPosition(RectangleEdge.BOTTOM);



            // Exibir gráfico

            ChartFrame frame = new ChartFrame("Gráfico de Gantt", chart);

            frame.pack();

            frame.setVisible(true);



            // Centralizar a janela

            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

            int x = (screenSize.width - frame.getWidth()) / 2;

            int y = (screenSize.height - frame.getHeight()) / 2;

            frame.setLocation(x, y);



        } catch (ParseException e) {

            e.printStackTrace();

            JOptionPane.showMessageDialog(this, "Erro ao parsear datas: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);

        }

    }



    private TaskSeriesCollection createDatasetFromTable(TableModel model) throws ParseException {

        TaskSeriesCollection dataset = new TaskSeriesCollection();

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        dateFormat.setLenient(false); // Validação rigorosa de datas



        if (model instanceof ProjetosEtapasHierarquicoTableModel) {

            ProjetosEtapasHierarquicoTableModel hierarquicoModel = (ProjetosEtapasHierarquicoTableModel) model;

            List<ProjetoEtapaHierarquico> dados = hierarquicoModel.getDados();



            for (ProjetoEtapaHierarquico projetoEtapa : dados) {

                Object[] projeto = projetoEtapa.getProjeto();

                List<Object[]> etapas = projetoEtapa.getEtapas();



                // Adiciona o projeto

                TaskSeries seriesProjeto = new TaskSeries((String) projeto[1]); // Nome do projeto

                Date projetoInicioPrevisto = null;

                Date projetoFimPrevisto = null;

                Date projetoInicioRealizado = null;

                Date projetoFimRealizado = null;



                // Log para depuração

                //System.out.println("Projeto: " + projeto[1]);

                //System.out.println("Início Previsto: " + projeto[2]);

                //System.out.println("Fim Previsto: " + projeto[3]);

                if (projeto[2] != null && !((String) projeto[2]).isEmpty()) {

                    try {

                        projetoInicioPrevisto = dateFormat.parse((String) projeto[2]);

                        //System.out.println("Início Previsto Parseado: " + projetoInicioPrevisto);

                    } catch (ParseException e) {

                        System.err.println("Erro ao parsear Início Previsto: " + projeto[2]);

                        e.printStackTrace();

                    }

                }

                if (projeto[3] != null && !((String) projeto[3]).isEmpty()) {

                    try {

                        projetoFimPrevisto = dateFormat.parse((String) projeto[3]);

                        //System.out.println("Fim Previsto Parseado: " + projetoFimPrevisto);

                    } catch (ParseException e) {

                        System.err.println("Erro ao parsear Fim Previsto: " + projeto[3]);

                        e.printStackTrace();

                    }

                }

                if (projeto[4] != null && !((String) projeto[4]).isEmpty()) {

                    try {

                        projetoInicioRealizado = dateFormat.parse((String) projeto[4]);

                        //System.out.println("Início Realizado Parseado: " + projetoInicioRealizado);

                    } catch (ParseException e) {

                        System.err.println("Erro ao parsear Início Realizado: " + projeto[4]);

                        e.printStackTrace();

                    }

                }

                if (projeto[5] != null && !((String) projeto[5]).isEmpty()) {

                    try {

                        projetoFimRealizado = dateFormat.parse((String) projeto[5]);

                        //System.out.println("Fim Realizado Parseado: " + projetoFimRealizado);

                    } catch (ParseException e) {

                        System.err.println("Erro ao parsear Fim Realizado: " + projeto[5]);

                        e.printStackTrace();

                    }

                }



                // Ajuste temporário: usar a data final da última etapa como data final do projeto

                Date ultimaEtapaFimPrevisto = null;

                for (Object[] etapa : etapas) {

                    if (etapa[4] != null && !((String) etapa[4]).isEmpty()) {

                        try {

                            Date etapaFimPrevisto = dateFormat.parse((String) etapa[4]);

                            if (ultimaEtapaFimPrevisto == null || etapaFimPrevisto.after(ultimaEtapaFimPrevisto)) {

                                ultimaEtapaFimPrevisto = etapaFimPrevisto;

                            }

                        } catch (ParseException e) {

                            System.err.println("Erro ao parsear Fim Previsto da Etapa: " + etapa[4]);

                            e.printStackTrace();

                        }

                    }

                }

                if (ultimaEtapaFimPrevisto != null && (projetoFimPrevisto == null || ultimaEtapaFimPrevisto.before(projetoFimPrevisto))) {

                    projetoFimPrevisto = ultimaEtapaFimPrevisto;

                    //System.out.println("Ajuste: Fim Previsto do Projeto alterado para: " + projetoFimPrevisto);

                }



                if (projetoInicioPrevisto != null && projetoFimPrevisto != null) {

                    seriesProjeto.add(new Task("Previsto", new org.jfree.data.time.SimpleTimePeriod(projetoInicioPrevisto, projetoFimPrevisto)));

                }

                if (projetoInicioRealizado != null && projetoFimRealizado != null) {

                    seriesProjeto.add(new Task("Realizado", new org.jfree.data.time.SimpleTimePeriod(projetoInicioRealizado, projetoFimRealizado)));

                }

                dataset.add(seriesProjeto);



                // Adiciona as etapas

                for (Object[] etapa : etapas) {

                    TaskSeries seriesEtapa = new TaskSeries("  " + (String) etapa[0]); // Nome da etapa

                    Date etapaInicioPrevisto = null;

                    Date etapaFimPrevisto = null;

                    Date etapaInicioRealizado = null;

                    Date etapaFimRealizado = null;



                    // Log para depuração

                    //System.out.println("Etapa: " + etapa[0]);

                    //System.out.println("Início Previsto: " + etapa[3]);

                    //System.out.println("Fim Previsto: " + etapa[4]);

                    if (etapa[3] != null && !((String) etapa[3]).isEmpty()) {

                        try {

                            etapaInicioPrevisto = dateFormat.parse((String) etapa[3]);

                            //System.out.println("Início Previsto Parseado: " + etapaInicioPrevisto);

                        } catch (ParseException e) {

                            System.err.println("Erro ao parsear Início Previsto: " + etapa[3]);

                            e.printStackTrace();

                        }

                    }

                    if (etapa[4] != null && !((String) etapa[4]).isEmpty()) {

                        try {

                            etapaFimPrevisto = dateFormat.parse((String) etapa[4]);

                            //System.out.println("Fim Previsto Parseado: " + etapaFimPrevisto);

                        } catch (ParseException e) {

                            System.err.println("Erro ao parsear Fim Previsto: " + etapa[4]);

                            e.printStackTrace();

                        }

                    }

                    if (etapa[5] != null && !((String) etapa[5]).isEmpty()) {

                        try {

                            etapaInicioRealizado = dateFormat.parse((String) etapa[5]);

                            //System.out.println("Início Realizado Parseado: " + etapaInicioRealizado);

                        } catch (ParseException e) {

                            System.err.println("Erro ao parsear Início Realizado: " + etapa[5]);

                            e.printStackTrace();

                        }

                    }

                    if (etapa[6] != null && !((String) etapa[6]).isEmpty()) {

                        try {

                            etapaFimRealizado = dateFormat.parse((String) etapa[6]);

                            //System.out.println("Fim Realizado Parseado: " + etapaFimRealizado);

                        } catch (ParseException e) {

                            System.err.println("Erro ao parsear Fim Realizado: " + etapa[6]);

                            e.printStackTrace();

                        }

                    }



                    if (etapaInicioPrevisto != null && etapaFimPrevisto != null) {

                        seriesEtapa.add(new Task("Previsto", new org.jfree.data.time.SimpleTimePeriod(etapaInicioPrevisto, etapaFimPrevisto)));

                    }

                    if (etapaInicioRealizado != null && etapaFimRealizado != null) {

                        seriesEtapa.add(new Task("Realizado", new org.jfree.data.time.SimpleTimePeriod(etapaInicioRealizado, etapaFimRealizado)));

                    }

                    dataset.add(seriesEtapa);

                }

            }

        }

        return dataset;

    }



    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed

        try {

            Tela_Principal exibir;

            exibir = new Tela_Principal();

            exibir.setVisible(true);

            setVisible(false);

        } catch (IOException ex) {

            Logger.getLogger(Tela_Consulta_Projetos.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_btnFecharActionPerformed



    private void btnConcluidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluidosActionPerformed

        //tabelaProj.setModel(new ProjetosEtapasTableModel("Concluído"));

        tabelaProj.setModel(new ProjetosEtapasHierarquicoTableModel("Concluído"));

    }//GEN-LAST:event_btnConcluidosActionPerformed



    private void btnNaoConcluidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaoConcluidosActionPerformed

        //tabelaProj.setModel(new ProjetosEtapasTableModel("Em Andamento"));

        tabelaProj.setModel(new ProjetosEtapasHierarquicoTableModel("Em Andamento"));

    }//GEN-LAST:event_btnNaoConcluidosActionPerformed



    private void btnGantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGantActionPerformed

        try {

            exibirGrafico();

        } catch (ParseException e) {

            e.printStackTrace();

        }

    }//GEN-LAST:event_btnGantActionPerformed



    private void btn_AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AbrirActionPerformed

        String idText = txt_proj.getText().trim();

        try {

            int projetoId = Integer.parseInt(idText);

            ProjetosEtapasHierarquicoTableModel model = new ProjetosEtapasHierarquicoTableModel(projetoId);

            if (model.getRowCount() == 0) {

                JOptionPane.showMessageDialog(this, "Projeto com ID " + projetoId + " não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);

                tabelaProj.setModel(new ProjetosEtapasHierarquicoTableModel("")); // Volta para a exibição padrão

            } else {

                tabelaProj.setModel(model);

            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, "Por favor, insira um ID válido (número inteiro).", "Erro", JOptionPane.ERROR_MESSAGE);

            tabelaProj.setModel(new ProjetosEtapasHierarquicoTableModel("")); // Volta para a exibição padrão

        }        // TODO add your handling code here:

    }//GEN-LAST:event_btn_AbrirActionPerformed



    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed

        // TODO add your handling code here:

        try {

            gerarRelatorioPDF();

            JOptionPane.showMessageDialog(this, "Relatório gerado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Erro ao gerar o relatório: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);

            e.printStackTrace();

        }

    }//GEN-LAST:event_btnImprimirActionPerformed



    private void gerarRelatorioPDF() throws Exception {

//        // Verificar se há dados na tabela

//        TableModel model = tabelaProj.getModel();

//        if (!(model instanceof ProjetosEtapasHierarquicoTableModel)) {

//            throw new Exception("Modelo da tabela inválido.");

//        }

//

//        ProjetosEtapasHierarquicoTableModel hierarquicoModel = (ProjetosEtapasHierarquicoTableModel) model;

//        List<ProjetoEtapaHierarquico> dados = hierarquicoModel.getDados();

//

//        if (dados.isEmpty()) {

//            throw new Exception("Nenhum projeto carregado na tabela.");

//        }

//

//        // Configurar JFileChooser

//        JFileChooser fileChooser = new JFileChooser();

//        fileChooser.setDialogTitle("Salvar Relatório PDF");

//        fileChooser.setFileFilter(new FileNameExtensionFilter("Arquivos PDF", "pdf"));

//        fileChooser.setSelectedFile(new File("relatorio_projeto.pdf"));

//        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home") + "/Desktop"));

//

//        int userSelection = fileChooser.showSaveDialog(this);

//        if (userSelection != JFileChooser.APPROVE_OPTION) {

//            return; // Usuário cancelou

//        }

//

//        File outputFile = fileChooser.getSelectedFile();

//        // Garantir que o arquivo tenha a extensão .pdf

//        String outputPath = outputFile.getAbsolutePath();

//        if (!outputPath.toLowerCase().endsWith(".pdf")) {

//            outputPath += ".pdf";

//            outputFile = new File(outputPath);

//        }

//

//        // Configurar o arquivo PDF

//        Document document = new Document();

//        PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(outputFile));

//

//        // Adicionar evento de página para o rodapé

//        HeaderFooterPageEvent event = new HeaderFooterPageEvent();

//        writer.setPageEvent(event);

//

//        document.open();

//

//        // Definir fontes

//        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, Font.BOLD);

//        Font boldFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, Font.BOLD);

//        Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 12, Font.NORMAL);

//

//        // Iterar sobre os projetos

//        for (ProjetoEtapaHierarquico projetoEtapa : dados) {

//            Object[] projeto = projetoEtapa.getProjeto();

//            String nomeProjeto = (String) projeto[1];

//            String dataInicioPrevista = projeto[2] != null ? (String) projeto[2] : "N/A";

//            String dataFimPrevista = projeto[3] != null ? (String) projeto[3] : "N/A";

//            String dataInicioRealizada = projeto[4] != null ? (String) projeto[4] : "N/A";

//            String dataFimRealizada = projeto[5] != null ? (String) projeto[5] : "N/A";

//

//            List<Object[]> etapas = projetoEtapa.getEtapas();

//            for (int i = 0; i < etapas.size(); i++) {

//                Object[] etapa = etapas.get(i);

//

//                // Título do relatório

//                Paragraph title = new Paragraph("Relatório de Etapa", titleFont);

//                title.setAlignment(Paragraph.ALIGN_CENTER);

//                document.add(title);

//                document.add(new Paragraph(" ", normalFont));

//

//                // Cabeçalho: Informa\\u00e7\\u00f5es do Projeto

//                document.add(new Paragraph("Projeto: " + nomeProjeto, boldFont));

//                document.add(new Paragraph("Data Início Prev.: " + dataInicioPrevista, normalFont));

//                document.add(new Paragraph("Data Fim Prev.: " + dataFimPrevista, normalFont));

//                document.add(new Paragraph("Data Início Realiz.: " + dataInicioRealizada, normalFont));

//                document.add(new Paragraph("Data Fim Realiz.: " + dataFimRealizada, normalFont));

//                document.add(new Paragraph(" ", normalFont));

//

//                // Corpo: Informa\\u00e7\\u00f5es da Etapa

//                String nomeEtapa = (String) etapa[0];

//                String prioridade = etapa[1] != null ? (String) etapa[1] : "N/A";

//                String responsavel = etapa[2] != null ? (String) etapa[2] : "N/A";

//                String etapaInicioPrevista = etapa[3] != null ? (String) etapa[3] : "N/A";

//                String etapaFimPrevista = etapa[4] != null ? (String) etapa[4] : "N/A";

//                String etapaInicioRealizada = etapa[5] != null ? (String) etapa[5] : "N/A";

//                String etapaFimRealizada = etapa[6] != null ? (String) etapa[6] : "N/A";

//                String observacao = etapa[8] != null ? (String) etapa[8] : "N/A";

//

//                document.add(new Paragraph("Etapa: " + nomeEtapa, boldFont));

//                document.add(new Paragraph("Responsável: " + responsavel, normalFont));

//                document.add(new Paragraph("Prioridade: " + prioridade, normalFont));

//                document.add(new Paragraph("Data Início Prev.: " + etapaInicioPrevista, normalFont));

//                document.add(new Paragraph("Data Fim Prev.: " + etapaFimPrevista, normalFont));

//                document.add(new Paragraph("Data Início Realiz.: " + etapaInicioRealizada, normalFont));

//                document.add(new Paragraph("Data Fim Realiz.: " + etapaFimRealizada, normalFont));

//                document.add(new Paragraph("Descrição da Etapa: " + observacao, normalFont));

//

//                // Adicionar uma nova página, exceto para a última etapa

//                if (i < etapas.size() - 1) {

//                    document.newPage();

//                }

//            }

//        }

//

//        // Fechar o documento

//        document.close();

// Configurar JFileChooser

        // Verifica se tem dados na tabela

        TableModel model = tabelaProj.getModel();

        if (!(model instanceof ProjetosEtapasHierarquicoTableModel)) {

            JOptionPane.showMessageDialog(this, "Nenhum dado carregado para gerar relatório.", "Atenção", JOptionPane.WARNING_MESSAGE);

            return;

        }



        ProjetosEtapasHierarquicoTableModel hierarquicoModel = (ProjetosEtapasHierarquicoTableModel) model;

        List<ProjetoEtapaHierarquico> listaProjetos = hierarquicoModel.getDados();



        if (listaProjetos.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Nenhum projeto para gerar relatório.", "Atenção", JOptionPane.WARNING_MESSAGE);

            return;

        }



        // JFileChooser

        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setDialogTitle("Salvar Relatório PDF");

        fileChooser.setFileFilter(new FileNameExtensionFilter("Arquivo PDF", "pdf"));

        fileChooser.setSelectedFile(new File("Relatorio_Projetos_" + LocalDate.now() + ".pdf"));

        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home") + "/Desktop"));



        if (fileChooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {

            return;

        }



        String caminho = fileChooser.getSelectedFile().getAbsolutePath();

        if (!caminho.toLowerCase().endsWith(".pdf")) {

            caminho += ".pdf";

        }



        // PDF

        Document documento = new Document(PageSize.A4.rotate(), 30, 30, 80, 60);

        PdfWriter writer = PdfWriter.getInstance(documento, new FileOutputStream(caminho));

        writer.setPageEvent(new HeaderFooterPageEvent());

        documento.open();



        Font tituloFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, Font.BOLD, BaseColor.DARK_GRAY);

        Font subtituloFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, Font.BOLD);

        Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 10);

        Font negritoFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10);

        Font totalFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, Font.BOLD, new BaseColor(0, 102, 204));



        DecimalFormat df = new DecimalFormat("R$ #,##0.00");

        DecimalFormat pf = new DecimalFormat("0.0%");



        for (int i = 0; i < listaProjetos.size(); i++) {

            ProjetoEtapaHierarquico projetoEtapa = listaProjetos.get(i);

            Object[] projeto = projetoEtapa.getProjeto();

            String nomeProjeto = (String) projeto[1];



            // Cabeçalho

            documento.add(new Paragraph("RELATÓRIO DE PROJETO", tituloFont));

            documento.add(new Paragraph("Projeto: " + nomeProjeto, subtituloFont));

            documento.add(new Paragraph("Gerado em: " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss")), normalFont));

            documento.add(Chunk.NEWLINE);



            // Tabela de etapas

            PdfPTable tabela = new PdfPTable(12);

            tabela.setWidthPercentage(100);

            tabela.setWidths(new float[]{15, 8, 10, 10, 10, 10, 10, 8, 20, 12, 12, 10});



            String[] cabecalho = {"Etapa", "Prioridade", "Responsável", "Início Prev.", "Fim Prev.",

                "Início Real", "Fim Real", "Status", "Observações",

                "R$ Previsto", "$ Realizado", "% Executado"};

            for (String c : cabecalho) {

                PdfPCell cell = new PdfPCell(new Phrase(c, negritoFont));

                cell.setBackgroundColor(new BaseColor(230, 230, 250));

                cell.setHorizontalAlignment(Element.ALIGN_CENTER);

                cell.setPadding(6);

                tabela.addCell(cell);

            }



            BigDecimal totalPrevisto = BigDecimal.ZERO;

            BigDecimal totalRealizado = BigDecimal.ZERO;



            for (Object[] etapa : projetoEtapa.getEtapas()) {

                BigDecimal prev = (BigDecimal) etapa[9];   // valor_previsto

                BigDecimal real = (BigDecimal) etapa[10];  // valor_realizado



                totalPrevisto = totalPrevisto.add(prev);

                totalRealizado = totalRealizado.add(real);



                BigDecimal perc = prev.compareTo(BigDecimal.ZERO) == 0 ? BigDecimal.ZERO

                        : real.divide(prev, 4, RoundingMode.HALF_UP);



                tabela.addCell(new Phrase((String) etapa[0], normalFont));

                tabela.addCell(new Phrase((String) etapa[1], normalFont));

                tabela.addCell(new Phrase((String) etapa[2], normalFont));

                tabela.addCell(new Phrase((String) etapa[3], normalFont));

                tabela.addCell(new Phrase((String) etapa[4], normalFont));

                tabela.addCell(new Phrase((String) etapa[5], normalFont));

                tabela.addCell(new Phrase((String) etapa[6], normalFont));

                tabela.addCell(new Phrase((String) etapa[7], normalFont));

                tabela.addCell(new Phrase((String) etapa[8], normalFont));



                PdfPCell cellPrev = new PdfPCell(new Phrase(df.format(prev), normalFont));

                cellPrev.setHorizontalAlignment(Element.ALIGN_RIGHT);

                tabela.addCell(cellPrev);



                PdfPCell cellReal = new PdfPCell(new Phrase(df.format(real), normalFont));

                cellReal.setHorizontalAlignment(Element.ALIGN_RIGHT);

                tabela.addCell(cellReal);



                PdfPCell cellPerc = new PdfPCell(new Phrase(pf.format(perc), normalFont));

                cellPerc.setHorizontalAlignment(Element.ALIGN_RIGHT);

                tabela.addCell(cellPerc);

            }



            documento.add(tabela);



            // TOTAL DO PROJETO

            PdfPTable totalTable = new PdfPTable(2);

            totalTable.setWidthPercentage(50);

            totalTable.setHorizontalAlignment(Element.ALIGN_RIGHT);

            totalTable.setSpacingBefore(20);



            BigDecimal percentualProjeto = totalPrevisto.compareTo(BigDecimal.ZERO) == 0 ? BigDecimal.ZERO

                    : totalRealizado.divide(totalPrevisto, 4, RoundingMode.HALF_UP);



            addTotalRow(totalTable, "TOTAL ORÇADO:", df.format(totalPrevisto), totalFont);

            addTotalRow(totalTable, "TOTAL REALIZADO:", df.format(totalRealizado), totalFont);

            addTotalRow(totalTable, "PERCENTUAL EXECUTADO:", pf.format(percentualProjeto), totalFont);



            documento.add(totalTable);



            // Nova página se não for o último projeto

            if (i < listaProjetos.size() - 1) {

                documento.newPage();

            }

        }



        documento.close();

        JOptionPane.showMessageDialog(this, "Relatório gerado com sucesso!\n" + caminho, "Sucesso", JOptionPane.INFORMATION_MESSAGE);

    }



    // Método auxiliar para linhas de total

    private void addTotalRow(PdfPTable table, String label, String value, Font font) {

        PdfPCell cell1 = new PdfPCell(new Phrase(label, font));

        cell1.setBorder(Rectangle.NO_BORDER);

        PdfPCell cell2 = new PdfPCell(new Phrase(value, font));

        cell2.setBorder(Rectangle.NO_BORDER);

        cell2.setHorizontalAlignment(Element.ALIGN_RIGHT);

        table.addCell(cell1);

        table.addCell(cell2);

    }



    // Classe interna para gerenciar o rodapé

    private class HeaderFooterPageEvent extends PdfPageEventHelper {

//

//        private PdfTemplate totalPages;

//        private Font footerFont = FontFactory.getFont(FontFactory.HELVETICA, 8, Font.NORMAL);

//

//        @Override

//        public void onOpenDocument(PdfWriter writer, Document document) {

//            totalPages = writer.getDirectContent().createTemplate(30, 16);

//        }

//

//        @Override

//        public void onEndPage(PdfWriter writer, Document document) {

//            PdfPTable footer = new PdfPTable(2);

//            try {

//                footer.setWidths(new int[]{50, 50});

//                footer.setTotalWidth(document.getPageSize().getWidth() - document.leftMargin() - document.rightMargin());

//                footer.setLockedWidth(true);

//

//                // Data e hor\\u00e1rio

//                String dateTime = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));

//                PdfPCell cell = new PdfPCell(new Phrase(dateTime, footerFont));

//                cell.setHorizontalAlignment(Element.ALIGN_LEFT);

//                cell.setBorder(0);

//                footer.addCell(cell);

//

//                // Pagina\\u00e7\\u00e3o

//                cell = new PdfPCell(new Phrase(String.format("Página %d de ", writer.getPageNumber()), footerFont));

//                cell.setHorizontalAlignment(Element.ALIGN_RIGHT);

//                cell.setBorder(0);

//                footer.addCell(cell);

//

//                // Escrever a tabela de rodapé

//                footer.writeSelectedRows(0, -1, document.leftMargin(), document.bottomMargin() - 10, writer.getDirectContent());

//

//                // Adicionar o PdfTemplate diretamente no canvas

//                float templateXPosition = document.leftMargin() + footer.getTotalWidth();// - 20; // Ajuste horizontal

//                float templateYPosition = document.bottomMargin() - 22; //- 12; // Ajuste vertical para alinhar com a baseline

//                writer.getDirectContent().addTemplate(totalPages, templateXPosition, templateYPosition);

//

//            } catch (DocumentException e) {

//                e.printStackTrace();

//            }

//        }

//

//        @Override

//        public void onCloseDocument(PdfWriter writer, Document document) {

//            try {

//                com.itextpdf.text.pdf.ColumnText.showTextAligned(

//                        totalPages,

//                        Element.ALIGN_LEFT,

//                        new Phrase(String.valueOf(writer.getPageNumber() - 1), footerFont),

//                        2, 2,

//                        0

//                );

//            } catch (Exception e) {

//                e.printStackTrace();

//            }

//        }



        Font f = new Font(Font.FontFamily.HELVETICA, 9, Font.ITALIC, BaseColor.GRAY);



        @Override

        public void onEndPage(PdfWriter writer, Document document) {

            PdfContentByte cb = writer.getDirectContent();

            Phrase footer = new Phrase(

                    "Gerado em " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"))

                    + "  ?  Página " + writer.getPageNumber(), f);



            ColumnText.showTextAligned(cb, Element.ALIGN_CENTER, footer,

                    (document.right() - document.left()) / 2 + document.leftMargin(),

                    document.bottom() - 15, 0);

        }

    }



    /**

     * @param args the command line arguments

     */

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 

         */

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;

                }

            }

        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(Tela_Consulta_Projetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(Tela_Consulta_Projetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(Tela_Consulta_Projetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(Tela_Consulta_Projetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        //</editor-fold>

        //</editor-fold>

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;

                }

            }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(Tela_Consulta_Projetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(() -> {

            new Tela_Consulta_Projetos().setVisible(true);

        });

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConcluidos;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGant;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNaoConcluidos;
    private javax.swing.JButton btn_Abrir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelCorpo;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaProj;
    private javax.swing.JTextField txt_proj;
    // End of variables declaration//GEN-END:variables

}

