package view;


import utilitarios.Conexao;

import utilitarios.CustomTableCellRenderer;

import java.awt.Color;

import java.awt.Component;

import java.awt.Font;

import java.io.IOException;

import java.sql.Connection;

import java.sql.PreparedStatement;

import java.sql.ResultSet;

import java.sql.SQLException;

import java.text.DecimalFormat;

import java.text.ParseException;

import java.util.Calendar;

import java.util.Date;

import java.util.Locale;

import java.util.logging.Level;

import java.util.logging.Logger;

import javax.swing.JOptionPane;

import javax.swing.JTable;

import javax.swing.SwingConstants;

import javax.swing.table.DefaultTableCellRenderer;

import javax.swing.table.DefaultTableModel;

import org.jfree.chart.ChartFactory;

import org.jfree.chart.ChartPanel;

import org.jfree.chart.JFreeChart;

import org.jfree.chart.plot.PlotOrientation;

import org.jfree.data.category.DefaultCategoryDataset;

import java.text.SimpleDateFormat;

import javax.swing.JFileChooser;

import javax.swing.JFrame;

import org.jfree.chart.axis.CategoryAxis;

import org.jfree.chart.axis.CategoryLabelPositions;

import org.jfree.chart.plot.CategoryPlot;

import org.jfree.ui.ApplicationFrame;



public class Tela_Consulta_FlxCxD extends javax.swing.JFrame {



    Conexao conexao = new Conexao();



    public Tela_Consulta_FlxCxD() throws SQLException {

        initComponents();

    }



    /**

     * This method is called from within the constructor to initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is always

     * regenerated by the Form Editor.

     */

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldDataIni = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldDataFim = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSaldoAnterior = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonPImprimir = new javax.swing.JButton();
        jButtonPLimpar = new javax.swing.JButton();
        jButtonPFechar = new javax.swing.JButton();
        jButtonGerarGrafico = new javax.swing.JButton();
        jButtonExportar = new javax.swing.JButton();
        jLabelTipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel2.setText("  PERÍODO DE VENCIMENTOS   de");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        try {
            jFormattedTextFieldDataIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("até");

        try {
            jFormattedTextFieldDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reg.", "Recurso", "vRecurso", "Favorecido", "vFavorecido", "Lancto.", "Emissão", "Vencimento", "Semana", "Documento", "Classif.", "Descrição", "Valor", "Apresent.", "Status", "Prev.", "Saldo"
            }
        ));
        jTablePesquisa.setSelectionBackground(new java.awt.Color(255, 255, 204));
        jTablePesquisa.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jTablePesquisa);

        jLabel4.setText("Saldo Anterior:");

        jTextFieldSaldoAnterior.setEditable(false);
        jTextFieldSaldoAnterior.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSaldoAnterior.setEnabled(false);
        jTextFieldSaldoAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSaldoAnteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSaldoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jFormattedTextFieldDataFim, jFormattedTextFieldDataIni});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldSaldoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonPImprimir.setText("Imprimir");
        jButtonPImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonPImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPImprimirActionPerformed(evt);
            }
        });

        jButtonPLimpar.setText("Limpar");
        jButtonPLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonPLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPLimparActionPerformed(evt);
            }
        });

        jButtonPFechar.setText("Fechar");
        jButtonPFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonPFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPFecharActionPerformed(evt);
            }
        });

        jButtonGerarGrafico.setText("Gerar Gráfico");
        jButtonGerarGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarGraficoActionPerformed(evt);
            }
        });

        jButtonExportar.setText("Exportar");
        jButtonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonGerarGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExportar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jButtonPImprimir)
                    .addComponent(jButtonPLimpar)
                    .addComponent(jButtonPFechar)
                    .addComponent(jButtonGerarGrafico)
                    .addComponent(jButtonExportar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTipo.setText("CONSULTA - FLUXO DE CAIXA - DIÁRIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    private void jButtonPFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPFecharActionPerformed



        try {

            Tela_Principal exibir;

            exibir = new Tela_Principal();

            exibir.setVisible(true);

            setVisible(false);

        } catch (IOException ex) {

            Logger.getLogger(Tela_Consulta_FlxCxD.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_jButtonPFecharActionPerformed



    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

        if (jFormattedTextFieldDataIni.getText().trim().length() == 4) {

            JOptionPane.showMessageDialog(null, "Atenção! Favor preencher o campo de data inicial.");

        } else if (jFormattedTextFieldDataFim.getText().trim().length() == 4) {

            JOptionPane.showMessageDialog(null, "Atenção! Favor preencher o campo de data final.");

        } else {

            PegaSaldoAnterior();

            String ssa = jTextFieldSaldoAnterior.getText();

            double sa = Double.parseDouble(ssa);

            DecimalFormat dec = new DecimalFormat("#,##0.00");

            jTextFieldSaldoAnterior.setText(dec.format(sa));



            try {

                SimpleDateFormat formatoBanco = new SimpleDateFormat("yyyy-MM-dd");

                SimpleDateFormat formatoEntrada = new SimpleDateFormat("dd/MM/yyyy");

                DecimalFormat df = new DecimalFormat("#,##0.00");



                conexao.abrirConexao();

                Connection con = conexao.getConexao();



                // --- INÍCIO DA LÓGICA DE CONSULTA ---

                // 1. Pegamos a data inicial e a data de hoje para comparar

                String dataTextoi = jFormattedTextFieldDataIni.getText();

                Date dataInicioRelatorio = formatoEntrada.parse(dataTextoi);



                // Criamos uma data "hoje" sem horas/minutos para uma comparação justa

                Calendar cal = Calendar.getInstance();

                cal.set(Calendar.HOUR_OF_DAY, 0);

                cal.set(Calendar.MINUTE, 0);

                cal.set(Calendar.SECOND, 0);

                cal.set(Calendar.MILLISECOND, 0);

                Date hoje = cal.getTime();



                String sql;



                // Se a data inicial for anterior a hoje, tratamos como Fluxo de Caixa (Realizado)

                if (dataInicioRelatorio.before(hoje)) {

                    // SQL para o PASSADO:

                    sql = "SELECT * FROM tbmovimento WHERE dtApr BETWEEN ? AND ? "

                            + "AND recurso IN ('0079', '0022', '0080') "

                            + "AND classif NOT IN ('9.001.000', '9.001.001', '9.001.002', '9.001.003') "

                            + "ORDER BY dtApr";



                } else {



                    // SQL para o FUTURO (Projeção)

                    sql = "SELECT * FROM tbmovimento WHERE dtVcto BETWEEN ? AND ? "

                            + "AND vrecurso IN('1.001.001', '1.001.002', '1.002.001', '1.003.001', '2.001.002', '2.001.003', '2.001.004') "

                            + "AND statusMov = '' "

                            + "AND recurso <> '0080' "

                            + "ORDER BY dtVcto, recurso, dtEmi";

                }



                PreparedStatement stmt = con.prepareStatement(sql);



                // Setando Data Inicial

                String data_i = formatoBanco.format(dataInicioRelatorio);

                stmt.setString(1, data_i);



                // Setando Data Final

                String dataTextof = jFormattedTextFieldDataFim.getText();

                Date dataf = formatoEntrada.parse(dataTextof);

                String data_f = formatoBanco.format(dataf);

                stmt.setString(2, data_f);



                // --- FIM DA CORREÇÃO DA LÓGICA ---

                ResultSet rs = stmt.executeQuery();



                jLabelTipo.setText(dataInicioRelatorio.before(hoje) ? "CONSULTA - FLUXO DE CAIXA" : "CONSULTA - PROJEÇÃO DE CAIXA");

                jLabelTipo.setForeground(dataInicioRelatorio.before(hoje) ? Color.BLUE : Color.DARK_GRAY);



                DefaultTableModel modelo = (DefaultTableModel) jTablePesquisa.getModel();

                modelo.setNumRows(0);

                jTablePesquisa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(0)).setPreferredWidth(40); //idMov

                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(1)).setPreferredWidth(60); //recurso

                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(2)).setPreferredWidth(0); //70 vrecurso 

                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(3)).setPreferredWidth(70); //50 clifor

                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(4)).setPreferredWidth(0); //75 vCliFor

                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(5)).setPreferredWidth(0); //dtlancto

                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(6)).setPreferredWidth(75); //dtEmi

                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(7)).setPreferredWidth(75); //dtVcto

                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(8)).setPreferredWidth(65); //dia da semana

                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(9)).setPreferredWidth(110); //documento

                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(10)).setPreferredWidth(0);  //classif

                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(11)).setPreferredWidth(280); //Descr

                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(12)).setPreferredWidth(80);  //Valor

                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(13)).setPreferredWidth(0); //dtApr

                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(14)).setPreferredWidth(0); //40 statusMov

                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(15)).setPreferredWidth(40); //30 Prev

                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(16)).setPreferredWidth(80); //Saldo



                DefaultTableCellRenderer tab = new DefaultTableCellRenderer();

                tab.setHorizontalAlignment(SwingConstants.RIGHT); //Alinhando a Direita



                jTablePesquisa.getColumnModel().getColumn(12).setCellRenderer(tab); //Mostrando no Formato Moeda

                jTablePesquisa.getColumnModel().getColumn(16).setCellRenderer(tab); //Mostrando no Formato Moeda



                jTablePesquisa.getColumnModel().getColumn(2).setMinWidth(0); // Ocultando as colunas

                jTablePesquisa.getColumnModel().getColumn(2).setMaxWidth(0); // Ocultando as colunas



                jTablePesquisa.getColumnModel().getColumn(4).setMinWidth(0); // Ocultando as colunas

                jTablePesquisa.getColumnModel().getColumn(4).setMaxWidth(0); // Ocultando as colunas



                jTablePesquisa.getColumnModel().getColumn(5).setMinWidth(0);

                jTablePesquisa.getColumnModel().getColumn(5).setMaxWidth(0);



                jTablePesquisa.getColumnModel().getColumn(10).setMinWidth(0);

                jTablePesquisa.getColumnModel().getColumn(10).setMaxWidth(0);



                jTablePesquisa.getColumnModel().getColumn(13).setMinWidth(0);

                jTablePesquisa.getColumnModel().getColumn(13).setMaxWidth(0);



                jTablePesquisa.getColumnModel().getColumn(14).setMinWidth(0);

                jTablePesquisa.getColumnModel().getColumn(14).setMaxWidth(0);



                SimpleDateFormat sdfSaida = new SimpleDateFormat("dd/MM/yyyy");

                SimpleDateFormat sdfEntrada = new SimpleDateFormat("yyyy-MM-dd");



                String dataAnterior = ""; // Variável para armazenar a data anterior

                int indiceUltimaLinha = -1; // índice da última linha do dia

                double saldoDia = 0.0; // Armazena o saldo acumulado do dia



                try {

                    while (rs.next()) {



                        String lancVcto = formatarData(rs.getString("dtVcto"), sdfSaida, sdfEntrada); // Data de vencimento do registro atual

                        String diaSemana = getDayOfWeek(sdfSaida.format(sdfEntrada.parse(rs.getString("dtVcto")))); // Dia da semana



                        // Incrementa o saldo

                        double valorMovimento = rs.getDouble("Valor");

                        sa = sa + valorMovimento;



                        // Se a data mudar e já houver uma linha anterior, atualiza o saldo da última linha do dia anterior

                        if (!lancVcto.equals(dataAnterior) && indiceUltimaLinha != -1) {

                            modelo.setValueAt(df.format(saldoDia), indiceUltimaLinha, 16); // Atualiza o saldo na última linha do dia anterior

                        }



                        // Atualiza o saldo acumulado do dia atual

                        saldoDia = sa;



                        // Adiciona a linha atual à tabela, sem saldo por enquanto

                        modelo.addRow(new Object[]{

                            rs.getString("idMov"),

                            rs.getString("recurso"),

                            rs.getString("vrecurso"),

                            rs.getString("clifor"),

                            rs.getString("vCliFor"),

                            formatarData(rs.getString("dtlancto"), sdfSaida, sdfEntrada),

                            formatarData(rs.getString("dtEmi"), sdfSaida, sdfEntrada),

                            lancVcto,

                            diaSemana,

                            rs.getString("documento"),

                            rs.getString("classif"),

                            rs.getString("Descr"),

                            df.format(valorMovimento),

                            formatarData(rs.getString("dtApr"), sdfSaida, sdfEntrada),

                            rs.getString("statusMov"),

                            rs.getString("Prev"),

                            "" // O saldo será inserido apenas na última linha do dia

                        });



                        // Atualiza o índice da última linha do dia atual

                        indiceUltimaLinha = modelo.getRowCount() - 1;



                        // Atualiza a data anterior

                        dataAnterior = lancVcto;

                    }



                    // Após sair do loop, insira o saldo na última linha do último dia, se houver

                    if (indiceUltimaLinha != -1) {

                        modelo.setValueAt(df.format(saldoDia), indiceUltimaLinha, 16); // Atualiza o saldo na última linha do último dia

                    }



                    jTablePesquisa.getColumnModel().getColumn(8).setCellRenderer(new ColoreDSem());



                    //Parâmetros Coluna da jTable, Tamanho da Fonte, se é data (true ou false).

                    jTablePesquisa.getColumnModel().getColumn(12).setCellRenderer(new CustomTableCellRenderer(12, 11, false));

                    jTablePesquisa.getColumnModel().getColumn(16).setCellRenderer(new CustomTableCellRenderer(16, 11, false));



                    // Fechar ResultSet e conexão

                    rs.close();

                    con.close();



                } catch (SQLException | ParseException ex) {

                    Logger.getLogger(Tela_Consulta_FlxCxD.class.getName()).log(Level.SEVERE, null, ex);

                }

            } catch (SQLException | ParseException ex) {

                Logger.getLogger(Tela_Consulta_FlxCxD.class.getName()).log(Level.SEVERE, null, ex);

            } finally {

                conexao.fecharConexao(); // Fecha a conexão no final

            }

        }



    }//GEN-LAST:event_jButtonPesquisarActionPerformed



    private String formatarData(String dataString, SimpleDateFormat sdfSaida, SimpleDateFormat sdfEntrada) {

        // Verifica se é nulo, vazio ou se contém a string "null" (comum em alguns drivers JDBC)

        if (dataString == null || dataString.trim().isEmpty() || dataString.equalsIgnoreCase("null")) {

            return "";

        }

        try {

            Date dataUtil = sdfEntrada.parse(dataString);

            return sdfSaida.format(dataUtil);

        } catch (ParseException e) {

            // Em relatórios, às vezes é melhor retornar vazio do que "Data inválida" 

            // para não poluir o visual, mas manter o log para o desenvolvedor.

            return "";

        }

    }



    private void jButtonPLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPLimparActionPerformed

        ((DefaultTableModel) jTablePesquisa.getModel()).setRowCount(0);

        jFormattedTextFieldDataIni.setText("");

        jFormattedTextFieldDataFim.setText("");

        jTextFieldSaldoAnterior.setText("0");

    }//GEN-LAST:event_jButtonPLimparActionPerformed



    private void jButtonPImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPImprimirActionPerformed



        java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm");

        String infDt = dateFormat.format(new java.util.Date());

        String dIni = jFormattedTextFieldDataIni.getText();

        String dFim = jFormattedTextFieldDataFim.getText();

        String txt1 = jLabelTipo.getText() + " - Período: " + dIni + " a " + dFim;

        String txt2 = "Saldo Anterior: " + jTextFieldSaldoAnterior.getText();



        java.awt.print.PrinterJob job = java.awt.print.PrinterJob.getPrinterJob();

        javax.print.attribute.PrintRequestAttributeSet set = new javax.print.attribute.HashPrintRequestAttributeSet();

        set.add(javax.print.attribute.standard.OrientationRequested.LANDSCAPE);



        final java.awt.print.Printable tabelaOriginal = jTablePesquisa.getPrintable(javax.swing.JTable.PrintMode.FIT_WIDTH, null, new java.text.MessageFormat("Pág. {0,number,integer} - " + infDt));



        java.awt.print.Printable meuLayout = (graphics, pageFormat, pageIndex) -> {

            java.awt.Graphics2D g2d = (java.awt.Graphics2D) graphics;



            // 1. Desenha o seu cabeçalho manualmente na página 0

            if (pageIndex == 0) {

                g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

                g2d.setColor(java.awt.Color.BLACK);

                g2d.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 10));

                g2d.drawString(txt1, 0, 15);



                java.awt.FontMetrics fm = g2d.getFontMetrics();

                int xDireita = (int) pageFormat.getImageableWidth() - fm.stringWidth(txt2) - 5;

                g2d.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 10));

                g2d.drawString(txt2, xDireita, 30);

                g2d.drawLine(0, 35, (int) pageFormat.getImageableWidth(), 35);



                // Volta o translate para não afetar a criação da cópia abaixo

                g2d.translate(-pageFormat.getImageableX(), -pageFormat.getImageableY());

            }



            // 2. O SEGREDO: Criamos uma cópia para a tabela

            java.awt.Graphics2D g2dTabela = (java.awt.Graphics2D) g2d.create();



            // Se for a página 0, empurramos APENAS a cópia da tabela para baixo

            if (pageIndex == 0) {

                g2dTabela.translate(0, 35);

            }



            // 3. Mandamos a tabela imprimir usando a cópia deslocada

            int resultado = tabelaOriginal.print(g2dTabela, pageFormat, pageIndex);



            // 4. Jogamos a cópia fora (libera memória)

            g2dTabela.dispose();



            // 5. Retornamos o resultado usando o g2d original (que está com o rodapé no lugar certo)

            return resultado;

        };



        job.setPrintable(meuLayout);

        if (job.printDialog(set)) {

            try {

                job.print(set);

            } catch (java.awt.print.PrinterException e) {

                System.out.println(e.getMessage());

            }

        }



    }//GEN-LAST:event_jButtonPImprimirActionPerformed



    private void jTextFieldSaldoAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSaldoAnteriorActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldSaldoAnteriorActionPerformed



    private void jButtonGerarGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarGraficoActionPerformed

        DefaultTableModel modelo = (DefaultTableModel) jTablePesquisa.getModel();



        GraficoDeLinha grafico = new GraficoDeLinha("Gráfico de Saldo");

        grafico.criarGrafico(modelo); // Passa o modelo da tabela como parâmetro

    }//GEN-LAST:event_jButtonGerarGraficoActionPerformed



    private void jButtonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportarActionPerformed

        // Verifica se a tabela tem dados

        if (jTablePesquisa.getRowCount() == 0) {

            JOptionPane.showMessageDialog(null, "Não há dados na tabela para exportar.");

            return;

        }



        JFileChooser chooser = new JFileChooser();

        chooser.setDialogTitle("Salvar Relatório");

        // Define um nome padrão para o arquivo

        chooser.setSelectedFile(new java.io.File("Relatorio_Fluxo_Caixa.csv"));



        int userSelection = chooser.showSaveDialog(this);



        if (userSelection == JFileChooser.APPROVE_OPTION) {

            java.io.File arquivoParaSalvar = chooser.getSelectedFile();



            try (java.io.FileWriter fw = new java.io.FileWriter(arquivoParaSalvar)) {

                DefaultTableModel modelo = (DefaultTableModel) jTablePesquisa.getModel();

                int colCount = modelo.getColumnCount();



                // 1. Escreve os Cabeçalhos (ignorando colunas ocultas se desejar)

                for (int i = 0; i < colCount; i++) {

                    fw.write(modelo.getColumnName(i) + (i == colCount - 1 ? "" : ";"));

                }

                fw.write("\n");



                // 2. Escreve as Linhas

                for (int i = 0; i < modelo.getRowCount(); i++) {

                    for (int j = 0; j < colCount; j++) {

                        Object valor = modelo.getValueAt(i, j);

                        String texto = (valor == null) ? "" : valor.toString();



                        // Limpa pontos/vírgulas se necessário ou apenas remove quebras de linha

                        texto = texto.replace("\n", " ").replace(";", ",");



                        fw.write(texto + (j == colCount - 1 ? "" : ";"));

                    }

                    fw.write("\n");

                }



                JOptionPane.showMessageDialog(null, "Arquivo exportado com sucesso para:\n" + arquivoParaSalvar.getAbsolutePath());



            } catch (java.io.IOException ex) {

                JOptionPane.showMessageDialog(null, "Erro ao salvar o arquivo: " + ex.getMessage());

                Logger.getLogger(Tela_Consulta_FlxCxD.class.getName()).log(Level.SEVERE, null, ex);

            }

        }

    }//GEN-LAST:event_jButtonExportarActionPerformed



    /**

     * @param args the command line arguments

     */

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 

         */

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;

                }

            }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(Tela_Consulta_FlxCxD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>



        /* Create and display the form */

        java.awt.EventQueue.invokeLater(() -> {

            try {

                new Tela_Consulta_FlxCxD().setVisible(true);

            } catch (SQLException ex) {

                Logger.getLogger(Tela_Consulta_FlxCxD.class.getName()).log(Level.SEVERE, null, ex);

            }

        });

    }



    private void PegaSaldoAnterior() {

        //String sql = "SELECT SUM(Valor) FROM tbmovimento WHERE dtlancto <= ? AND vrecurso in ('1.001.001','1.001.002', '1.003.001') AND recurso not in('0079','0022')";
        String sql = "SELECT SUM(Valor) FROM tbmovimento WHERE dtlancto <= ? AND vrecurso in ('1.001.001','1.001.002') AND recurso not in('0079','0022')";
        try {

            conexao.abrirConexao(); // Abre a conexão

            try (Connection con = conexao.getConexao(); // Obtém a conexão

                PreparedStatement stt = con.prepareStatement(sql)            ) {

                String dataTexto = jFormattedTextFieldDataIni.getText();

                SimpleDateFormat formatoEntrada = new SimpleDateFormat("dd/MM/yyyy");

                Date data = formatoEntrada.parse(dataTexto);

                SimpleDateFormat formatoBanco = new SimpleDateFormat("yyyy-MM-dd");

                String dataFormatada = formatoBanco.format(data);

                stt.setString(1, dataFormatada);

                try (ResultSet rsoma = stt.executeQuery()) {

                    double somaval = 0;

                    while (rsoma.next()) {

                        somaval = rsoma.getDouble(1);

                    }

                    jTextFieldSaldoAnterior.setText(String.valueOf(somaval));

                }

            }

        } catch (SQLException | ParseException ex) {

            Logger.getLogger(Tela_Consulta_FlxCxD.class.getName()).log(Level.SEVERE, null, ex);

        } finally {

            conexao.fecharConexao(); // Fecha a conexão no final

        }

    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExportar;
    private javax.swing.JButton jButtonGerarGrafico;
    private javax.swing.JButton jButtonPFechar;
    private javax.swing.JButton jButtonPImprimir;
    private javax.swing.JButton jButtonPLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataFim;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataIni;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisa;
    private javax.swing.JTextField jTextFieldSaldoAnterior;
    // End of variables declaration//GEN-END:variables



    private static final String[] WEEKDAYS = {"Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"};



    public static String getDayOfWeek(String data) {



        try {

            SimpleDateFormat parser = new SimpleDateFormat("dd/MM/yyyy");

            parser.setLenient(false);

            Calendar cal = Calendar.getInstance();

            cal.setTime(parser.parse(data));

            @SuppressWarnings("deprecation")

            SimpleDateFormat dayFormat = new SimpleDateFormat("EEE", new Locale("pt", "BR")); // Formato abreviado do dia da semana

            String dayOfWeek = dayFormat.format(cal.getTime());

            return dayOfWeek.replace(".", ""); // Remover ponto final

        } catch (ParseException e) {

        }

        return "---";

    }



    public class ColoreDSem extends DefaultTableCellRenderer {



        //private Component componente;



        @Override

        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            Component componente = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            Font font = new Font("Tahoma", Font.PLAIN, 11);

            String confere = table.getValueAt(row, column).toString(); // Obter o valor diretamente da coluna 8 (dia da semana)

            this.setHorizontalAlignment(CENTER);

            if ("sáb".equals(confere) || "dom".equals(confere)) {

                this.setForeground(Color.RED);

                componente.setFont(font);

            } else {

                this.setForeground(Color.BLACK);

            }

            return this;

        }

    }



    public class GraficoDeLinha extends ApplicationFrame {



        public GraficoDeLinha(String title) {

            super(title);

        }



        public void criarGrafico(DefaultTableModel tableModel) {

            DefaultCategoryDataset dataset = new DefaultCategoryDataset();



            // Percorre as linhas da tabela para pegar as datas e os saldos

            for (int i = 0; i < tableModel.getRowCount(); i++) {

                String data = (String) tableModel.getValueAt(i, 7); // Coluna de data

                String saldoStr = (String) tableModel.getValueAt(i, 16); // Coluna de saldo



                // Verifica se o saldo é vazio, nulo ou contém apenas espaços em branco

                if (saldoStr != null && !saldoStr.trim().isEmpty()) {

                    try {

                        // Remove os separadores de milhar (pontos) e substitui a vírgula decimal por ponto

                        double saldo = Double.parseDouble(saldoStr.replace(".", "").replace(",", "."));

                        dataset.addValue(saldo, "Saldo", data); // Adiciona o saldo no dataset

                    } catch (NumberFormatException e) {

                        System.err.println("Erro ao converter o saldo: " + saldoStr);

                    }

                } else {

                    //System.err.println("Saldo vazio ou nulo na linha: " + i + " - data: " + data);

                }

            }



            // Cria o gráfico de linha

            JFreeChart lineChart = ChartFactory.createLineChart(

                    "Evolução do Saldo no Período",

                    "Data", // Eixo X

                    "Saldo", // Eixo Y

                    dataset,

                    PlotOrientation.VERTICAL,

                    true, true, false);



            // Personalizar o gráfico (ajustar a aparência das datas no eixo X)

            CategoryPlot plot = lineChart.getCategoryPlot();

            CategoryAxis domainAxis = plot.getDomainAxis();



            // Rotacionar os rótulos para melhorar a legibilidade

            domainAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_45);



            // Reduzir o tamanho da fonte das labels no eixo X

            domainAxis.setTickLabelFont(new Font("Tahoma", Font.PLAIN, 10));



            // Exibe o gráfico em um JFrame no centro da tela

            ChartPanel chartPanel = new ChartPanel(lineChart);

            chartPanel.setPreferredSize(new java.awt.Dimension(800, 600));



            // Exibe o gráfico em uma janela

            JFrame frame = new JFrame("Gráfico de Saldo");

            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Alterado de EXIT_ON_CLOSE para DISPOSE_ON_CLOSE

            frame.getContentPane().add(chartPanel);

            frame.pack();

            frame.setLocationRelativeTo(null); // Centraliza a janela

            frame.setVisible(true);

        }

    }

}

