package view;

import utilitarios.Conexao;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfWriter;
import dao.ItensComprasDAO;
import dao.ComprasDAO;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import model.ItensCompras;
import model.Compras;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.ZoneId;
import javax.swing.JFileChooser;

/**
 *
 * @author CARLOS
 */
public class Form_HistoricoCompras extends javax.swing.JDialog {

    /**
     * Creates new form FormularioHistorico
     */
    private Conexao conexao;
    private ComprasDAO comprasDAO; // Mantenha a referência do DAO

    public Form_HistoricoCompras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Histórico de Compras");
        setLocationRelativeTo(null);

        // Data inicial = primeiro dia do mês atual
        LocalDate hoje = LocalDate.now();
        txtInicio.setText(hoje.withDayOfMonth(1).format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        txtFim.setText(hoje.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));

        // Carrega todas as compras ao abrir
        try {
            carregarCompras();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar histórico.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtInicio = new javax.swing.JFormattedTextField();
        txtFim = new javax.swing.JFormattedTextField();
        btnPesquisarCompra = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btn_GerarComprasNoPeriodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Histórico de Compras");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Histórico de Compras");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta por data"));

        jLabel2.setText("Data Inicial");

        jLabel3.setText("Data Final");

        try {
            txtInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/20##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/20##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnPesquisarCompra.setText("Pesquisar");
        btnPesquisarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtFim, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(btnPesquisarCompra)
                .addGap(25, 25, 25))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtFim, txtInicio});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarCompra))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Fornecedor", "Data da Compra", "Total da Compra", "Total Acumulado", "Observações"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(tabela);

        btn_GerarComprasNoPeriodo.setText("Imprime Compras no Período");
        btn_GerarComprasNoPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GerarComprasNoPeriodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_GerarComprasNoPeriodo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_GerarComprasNoPeriodo))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCompraActionPerformed
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        // VALIDA CAMPOS VAZIOS
        if (txtInicio.getText().trim().isEmpty() || txtFim.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Preencha as duas datas para pesquisar!",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            LocalDate inicio = LocalDate.parse(txtInicio.getText().trim(), fmt);
            LocalDate fim = LocalDate.parse(txtFim.getText().trim(), fmt);

            // VALIDA SE A DATA FINAL É MAIOR QUE A INICIAL
            if (fim.isBefore(inicio)) {
                JOptionPane.showMessageDialog(this,
                        "Data final não pode ser menor que a data inicial!",
                        "Erro de Período", JOptionPane.WARNING_MESSAGE);
                return;
            }

            ComprasDAO dao = new ComprasDAO();
            List<Compras> lista = dao.historicoCompras(inicio, fim); // ? seu método com filtro por data

            DefaultTableModel model = (DefaultTableModel) tabela.getModel();
            model.setRowCount(0);

            NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.of("pt", "BR"));
            double acumulado = 0;

            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Nenhuma compra encontrada no período informado.",
                        "Resultado", JOptionPane.INFORMATION_MESSAGE);
            } else {
                for (Compras c : lista) {
                    acumulado += c.getTotalCompra();

                    String dataFormatada = "Sem data";
                    if (c.getDataCompra() != null) {
                        dataFormatada = c.getDataCompra()
                                .toInstant()
                                .atZone(ZoneId.systemDefault())
                                .toLocalDate()
                                .format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                    }

                    model.addRow(new Object[]{
                        c.getId(),
                        c.getFornecedor() != null ? c.getFornecedor().getNomeCliFor() : "SEM FORNECEDOR",
                        dataFormatada,
                        nf.format(c.getTotalCompra()),
                        nf.format(acumulado),
                        c.getObservacoes() != null && !c.getObservacoes().isEmpty() ? c.getObservacoes() : "Sem obs"
                    });
                }

                JOptionPane.showMessageDialog(this,
                        "Pesquisa concluída!\n" + lista.size() + " compra(s) encontrada(s).\nTotal no período: " + nf.format(acumulado),
                        "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this,
                    "Data inválida!\nUse o formato: dd/MM/yyyy\nExemplo: 01/10/2025",
                    "Formato Inválido", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Erro ao buscar compras:\n" + ex.getMessage(),
                    "Erro no Banco", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisarCompraActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        if (tabela.getSelectedRow() == -1) {
            return;
        }

        int idCompra = (int) tabela.getValueAt(tabela.getSelectedRow(), 0);

        try (Connection con = Conexao.faz_conexao()) {
            Form_DetalheCompras fdc = new Form_DetalheCompras(this, true);
            fdc.txtIdCompra.setText(String.valueOf(idCompra));
            fdc.txtFornecedor.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
            fdc.txtDataCompra.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
            fdc.txtTotalCompra.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
            fdc.txtObs.setText(tabela.getValueAt(tabela.getSelectedRow(), 5).toString());

            ItensComprasDAO dao = new ItensComprasDAO();
            List<ItensCompras> itens = dao.listarPorCompra(idCompra);  // ? MÉTODO CORRETO

            DefaultTableModel model = (DefaultTableModel) fdc.Carrinho.getModel();
            model.setRowCount(0);

            NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.of("pt", "BR"));
            for (ItensCompras i : itens) {
                model.addRow(new Object[]{
                    i.getProdutoId(),
                    i.getDescricao(),
                    String.format("%.3f", i.getQtd()),
                    nf.format(i.getPrecoCompra()),
                    nf.format(i.getSubtotal())
                });
            }

            fdc.setVisible(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar itens: " + ex.getMessage());
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void btn_GerarComprasNoPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GerarComprasNoPeriodoActionPerformed
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        try {

            // Parse das datas de início e fim
            LocalDate dataInicio = LocalDate.parse(txtInicio.getText(), formato);
            LocalDate dataFim = LocalDate.parse(txtFim.getText(), formato);

            // Cria a conexão com o banco de dados
            Connection con = new Conexao().faz_conexao();

            // Recupera o histórico de compras no intervalo de datas
            ComprasDAO dao = new ComprasDAO(con);
            List<Compras> lista = dao.historicoCompras(dataInicio, dataFim);

            // Atualiza a tabela com os dados do histórico
            DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
            modelo.setRowCount(0); // Limpa a tabela antes de preencher

            @SuppressWarnings("deprecation")
            NumberFormat nf = NumberFormat.getNumberInstance(new Locale("pt", "BR"));
            nf.setMaximumFractionDigits(2);
            nf.setMinimumFractionDigits(2); // Para garantir 2 casas decimais sempre
            nf.setGroupingUsed(true); // Para habilitar separadores de milhar
            double comprasAcumulado = 0.0;

            for (Compras c : lista) {
                String totalCompraFormatado = nf.format(c.getTotalCompra());
                comprasAcumulado += c.getTotalCompra();
                String comprasAcumuladoFormatado = nf.format(comprasAcumulado);

                // Formata a data
                String dataFormatada = "";

                if (c.getDataCompra() != null) {
                    LocalDate data = c.getDataCompra().toInstant()
                            .atZone(ZoneId.systemDefault())
                            .toLocalDate();
                    dataFormatada = data.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                }

                modelo.addRow(new Object[]{
                    c.getId(),
                    c.getFornecedor().getNomeCliFor(),
                    dataFormatada,
                    totalCompraFormatado,
                    comprasAcumuladoFormatado,
                    c.getObservacoes()
                });
            }

            // Chama o método para gerar o relatório PDF
            String caminhoArquivo = "relatorio_compras.pdf";
            gerarRelatorioComprasPDF(lista, caminhoArquivo);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao gerar o histórico de compras: " + e.getMessage());
        } catch (BadElementException | IOException ex) {
            Logger.getLogger(Form_HistoricoCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_GerarComprasNoPeriodoActionPerformed

    private void gerarRelatorioComprasPDF(List<Compras> listaCompras, String caminhoArquivo) throws BadElementException, IOException {
        try {
            // Obtém o caminho para a Área de Trabalho
            String desktopPath = javax.swing.filechooser.FileSystemView.getFileSystemView().getHomeDirectory().getAbsolutePath();

            // Configuração do JFileChooser
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Salvar Relatório");
            fileChooser.setCurrentDirectory(new File(desktopPath)); // Define a Área de Trabalho como diretório inicial

            // Exibe a janela para o usuário escolher o local e nome do arquivo
            int escolha = fileChooser.showSaveDialog(null);
            if (escolha != JFileChooser.APPROVE_OPTION) {
                return; // Sai do método se o usuário cancelar a operação
            }

            // Recupera o arquivo selecionado e garante a extensão .pdf
            File arquivo = fileChooser.getSelectedFile();
            if (!arquivo.getName().endsWith(".pdf")) {
                arquivo = new File(arquivo.getAbsolutePath() + ".pdf");
            }

            // Criação do documento PDF
            Document document = new Document();
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(arquivo));
            document.open();

            // Adiciona o logo (caso exista)
            Image imagem = null;
            try {
                imagem = Image.getInstance("src/Imagens/Home.png"); // Caminho da imagem
                imagem.scaleAbsolute(45f, 50f);
                imagem.setAlignment(Element.ALIGN_LEFT);
                document.add(imagem);
            } catch (DocumentException | IOException e) {
                JOptionPane.showMessageDialog(null, "Imagem não encontrada: " + e.getMessage());
            }

            // Adiciona o título com o período
            Font fonteTitulo = new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD);

            // Adiciona o título
            Paragraph titulo = new Paragraph(
                    "Relatório de Compras",
                    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14)
            );
            titulo.setAlignment(Element.ALIGN_CENTER);
            titulo.setSpacingAfter(10f); // Adiciona espaçamento abaixo do título
            document.add(titulo);

            // Converte as strings para LocalDate
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate inicioDate = LocalDate.parse(txtInicio.getText(), formatter);
            LocalDate fimDate = LocalDate.parse(txtFim.getText(), formatter);

            // Adiciona o período abaixo do título
            Paragraph periodo = new Paragraph(
                    "Referente ao período de: "
                    + inicioDate.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")) + " até "
                    + fimDate.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12)
            );
            periodo.setAlignment(Element.ALIGN_CENTER);
            periodo.setSpacingAfter(20f); // Espaçamento após o período
            document.add(periodo);

            // Tabela do relatório
            PdfPTable tabela = new PdfPTable(5); // Número de colunas
            tabela.setWidths(new float[]{1, 3, 2, 2, 3}); // Proporções das colunas
            tabela.setWidthPercentage(100);

            // Cabeçalho da tabela
            Font fonteCabecalho = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
            tabela.addCell(new PdfPCell(new Phrase("ID", fonteCabecalho)));
            tabela.addCell(new PdfPCell(new Phrase("Fornecedor", fonteCabecalho)));
            tabela.addCell(new PdfPCell(new Phrase("Data", fonteCabecalho)));
            tabela.addCell(new PdfPCell(new Phrase("Valor", fonteCabecalho)));
            tabela.addCell(new PdfPCell(new Phrase("Observações", fonteCabecalho)));

            // Conteúdo da tabela
            Font fonteConteudo = new Font(Font.FontFamily.HELVETICA, 11);

            // Formatação para valores monetários
            @SuppressWarnings("deprecation")
            NumberFormat nf = NumberFormat.getNumberInstance(new Locale("pt", "BR"));
            nf.setMinimumFractionDigits(2);
            nf.setMaximumFractionDigits(2);

            double somaTotal = 0.0; // Variável para acumular os totais

            if (listaCompras != null && !listaCompras.isEmpty()) {
                for (Compras c : listaCompras) {
                    // Adiciona o ID
                    tabela.addCell(new PdfPCell(new Phrase(String.valueOf(c.getId()), fonteConteudo)));

                    // Adiciona o nome do fornecedor
                    tabela.addCell(new PdfPCell(new Phrase(c.getFornecedor().getNomeCliFor(), fonteConteudo)));

                    // Formata a data
                    String dataFormatada = "";
                    if (c.getDataCompra() != null) {
                        LocalDate dataCompra = c.getDataCompra().toInstant()
                                .atZone(ZoneId.systemDefault())
                                .toLocalDate();
                        dataFormatada = dataCompra.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                    }
                    tabela.addCell(new PdfPCell(new Phrase(dataFormatada, fonteConteudo)));

                    // Formata o total da compra
                    double totalCompra = c.getTotalCompra();
                    somaTotal += totalCompra; // Acumula o total
                    String totalCompraFormatado = nf.format(totalCompra);
                    tabela.addCell(new PdfPCell(new Phrase(totalCompraFormatado, fonteConteudo)));

                    // Adiciona observações
                    tabela.addCell(new PdfPCell(new Phrase(c.getObservacoes(), fonteConteudo)));
                }

                // Adiciona a linha com a soma total
                Font fonteSoma = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
                PdfPCell celulaVazia = new PdfPCell(new Phrase("")); // Células vazias
                celulaVazia.setBorder(PdfPCell.NO_BORDER);

                tabela.addCell(celulaVazia); // Para a coluna ID
                tabela.addCell(celulaVazia); // Para a coluna Fornecedor
                tabela.addCell(new PdfPCell(new Phrase("TOTAL COMPRAS", fonteSoma))); // Rótulo
                tabela.addCell(new PdfPCell(new Phrase(nf.format(somaTotal), fonteSoma))); // Soma total formatada
                tabela.addCell(celulaVazia); // Para a coluna Observações
            } else {
                System.out.println("A lista de compras está vazia.");
            }

            // Adiciona rodapé no PDF
            writer.setPageEvent(new PdfPageEventHelper() {
                @Override
                public void onEndPage(PdfWriter writer, Document document) {
                    String footerText = "Gerado em " + LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))
                            + " - Pág. " + writer.getPageNumber();
                    ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_RIGHT, new Phrase(footerText),
                            document.right() - 30, document.bottom() - 10, 0); // Ajusta o rodapé à direita
                }
            });

            // Adiciona a tabela no documento
            document.add(tabela);

            // Fecha o documento
            document.close();
            JOptionPane.showMessageDialog(null, "Relatório gerado com sucesso em: " + arquivo.getAbsolutePath());

            // Abre o PDF para visualização
            Desktop.getDesktop().open(arquivo);

        } catch (DocumentException | HeadlessException | FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Erro ao gerar o relatório: " + e.getMessage());
        }
    }

    // Método para carregar as compras na tabela
    public void carregarCompras() throws ParseException {

        try {
            ComprasDAO dao = new ComprasDAO();
            List<Compras> lista = dao.listarCompras();

            DefaultTableModel model = (DefaultTableModel) tabela.getModel();
            model.setRowCount(0);

            NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.of("pt", "BR"));
            double acumulado = 0;

            for (Compras c : lista) {
                acumulado += c.getTotalCompra();

                // CONVERSÃO PERFEITA DE TIMESTAMP ? String dd/MM/yyyy
                String dataFormatada = "Data inválida";
                if (c.getDataCompra() != null) {
                    LocalDate data = c.getDataCompra()
                            .toInstant()
                            .atZone(ZoneId.systemDefault())
                            .toLocalDate();
                    dataFormatada = data.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                }

                model.addRow(new Object[]{
                    c.getId(),
                    c.getFornecedor().getNomeCliFor(),
                    dataFormatada,
                    nf.format(c.getTotalCompra()),
                    nf.format(acumulado),
                    c.getObservacoes() != null ? c.getObservacoes() : ""
                });
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar histórico de compras:\n" + ex.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisarCompra;
    private javax.swing.JButton btn_GerarComprasNoPeriodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable tabela;
    private javax.swing.JFormattedTextField txtFim;
    private javax.swing.JFormattedTextField txtInicio;
    // End of variables declaration//GEN-END:variables
}
