package view;

import utilitarios.Conexao;
import classes.CustomTableCellRenderer;
import classes.ImprimirJTable;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import static javax.swing.SwingConstants.CENTER;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.ApplicationFrame;

/**
 *
 * @author CARLOS
 */
public class VConsFlxCxDiario extends javax.swing.JInternalFrame {

    /**
     * Creates new form VConsFlxCxDiario
     */
    public VConsFlxCxDiario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTipo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldDataIni = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldDataFim = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSaldoAnterior = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonPImprimir = new javax.swing.JButton();
        jButtonPLimpar = new javax.swing.JButton();
        jButtonPFechar = new javax.swing.JButton();
        jButtonGerarGrafico = new javax.swing.JButton();
        jButtonExportar = new javax.swing.JButton();

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTipo.setText("CONSULTA - FLUXO DE CAIXA - DIÁRIO");

        jLabel2.setText("   PERÍODO DE VENCIMENTOS   de");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        try {
            jFormattedTextFieldDataIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("até");

        try {
            jFormattedTextFieldDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Saldo Anterior:");

        jTextFieldSaldoAnterior.setEditable(false);
        jTextFieldSaldoAnterior.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSaldoAnterior.setEnabled(false);
        jTextFieldSaldoAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSaldoAnteriorActionPerformed(evt);
            }
        });

        jTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reg.", "Recurso", "vRecurso", "Favorecido", "vFavorecido", "Lancto.", "Emissão", "Vencimento", "Semana", "Documento", "Classif.", "Descrição", "Valor", "Apresent.", "Status", "Prev.", "Saldo"
            }
        ));
        jTablePesquisa.setSelectionBackground(new java.awt.Color(255, 255, 204));
        jScrollPane1.setViewportView(jTablePesquisa);

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonPImprimir.setText("Imprimir");
        jButtonPImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPImprimirActionPerformed(evt);
            }
        });

        jButtonPLimpar.setText("Limpar");
        jButtonPLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPLimparActionPerformed(evt);
            }
        });

        jButtonPFechar.setText("Fechar");
        jButtonPFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPFecharActionPerformed(evt);
            }
        });

        jButtonGerarGrafico.setText("Gerar Gráfico");
        jButtonGerarGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarGraficoActionPerformed(evt);
            }
        });

        jButtonExportar.setText("Exportar");
        jButtonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonGerarGrafico)
                .addGap(18, 18, 18)
                .addComponent(jButtonExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonExportar, jButtonGerarGrafico, jButtonPFechar, jButtonPImprimir, jButtonPLimpar, jButtonPesquisar});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jButtonPImprimir)
                    .addComponent(jButtonPLimpar)
                    .addComponent(jButtonGerarGrafico)
                    .addComponent(jButtonExportar)
                    .addComponent(jButtonPFechar))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonExportar, jButtonGerarGrafico, jButtonPFechar, jButtonPImprimir, jButtonPLimpar, jButtonPesquisar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(428, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSaldoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabelTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldSaldoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        setBounds(30, 35, 1280, 663);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSaldoAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSaldoAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSaldoAnteriorActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

        if (jFormattedTextFieldDataIni.getText().trim().length() != 10) {
            JOptionPane.showMessageDialog(null, "Atenção! Favor preencher corretamente a data inicial (dd/MM/yyyy).");
            return;
        }
        if (jFormattedTextFieldDataFim.getText().trim().length() != 10) {
            JOptionPane.showMessageDialog(null, "Atenção! Favor preencher corretamente a data final (dd/MM/yyyy).");
            return;
        }

        PegaSaldoAnterior();
        double sa = Double.parseDouble(jTextFieldSaldoAnterior.getText().replace(".", "").replace(",", "."));
        DecimalFormat dec = new DecimalFormat("#,##0.00");
        jTextFieldSaldoAnterior.setText(dec.format(sa));

        try {
            SimpleDateFormat formatoEntrada = new SimpleDateFormat("dd/MM/yyyy");

            Date dataInicioRelatorio = formatoEntrada.parse(jFormattedTextFieldDataIni.getText());
            Date dataFimRelatorio = formatoEntrada.parse(jFormattedTextFieldDataFim.getText());

            // Data de hoje zerada (sem hora) para comparação
            Calendar calHoje = Calendar.getInstance();
            calHoje.set(Calendar.HOUR_OF_DAY, 0);
            calHoje.set(Calendar.MINUTE, 0);
            calHoje.set(Calendar.SECOND, 0);
            calHoje.set(Calendar.MILLISECOND, 0);
            Date hoje = calHoje.getTime();

            // Determina se é Fluxo Realizado (passado ou hoje) ou Projeção (futuro)
            boolean isRealizado = dataInicioRelatorio.before(hoje); // ontem ou antes ? realizado

            String sql;
            
            String campoDataOrdenacao; // para ORDER BY e para calcular dia da semana
            
            if (isRealizado) {
                sql = "SELECT * FROM tbmovimento WHERE dtApr BETWEEN ? AND ? "
                        + "AND recurso IN ('0079', '0022', '0080') "
                        + "AND classif NOT IN ('9.001.000', '9.001.001', '9.001.002', '9.001.003') "
                        + "ORDER BY dtApr";
                campoDataOrdenacao = "dtApr";
            } else {

            // PROJEÇÃO - volta ao filtro ORIGINAL que funcionava perfeitamente
                sql = "SELECT * FROM tbmovimento WHERE dtVcto BETWEEN ? AND ? "
                        + "AND vrecurso IN ('1.002.001', '2.001.002', '2.001.003', '2.001.004') "
                        + "AND recurso <> '0080' "
                        + "AND statusMov = '' "
                        + "ORDER BY dtVcto, recurso, dtEmi";
                campoDataOrdenacao = "dtVcto";
            }

            Connection con = Conexao.faz_conexao();
            PreparedStatement stmt = con.prepareStatement(sql);

            // Usa java.sql.Date para compatibilidade perfeita com MySQL
            stmt.setDate(1, new java.sql.Date(dataInicioRelatorio.getTime()));
            stmt.setDate(2, new java.sql.Date(dataFimRelatorio.getTime()));

            ResultSet rs = stmt.executeQuery();

            // Atualiza o label de tipo de consulta
            if (jLabelTipo != null) {
                jLabelTipo.setText(isRealizado ? "CONSULTA - FLUXO DE CAIXA" : "CONSULTA - PROJEÇÃO DE CAIXA");
                jLabelTipo.setForeground(isRealizado ? Color.BLUE : Color.DARK_GRAY);
            }

            DefaultTableModel modelo = (DefaultTableModel) jTablePesquisa.getModel();
            modelo.setNumRows(0);

            // Configuração das colunas (mantendo seu layout original)
            jTablePesquisa.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(0)).setPreferredWidth(40);   // idMov
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(1)).setPreferredWidth(60);   // recurso
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(2)).setPreferredWidth(0);    // vrecurso
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(3)).setPreferredWidth(70);   // clifor
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(4)).setPreferredWidth(0);    // vCliFor
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(5)).setPreferredWidth(0);    // dtlancto
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(6)).setPreferredWidth(75);   // dtEmi
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(7)).setPreferredWidth(75);   // dtVcto/dtApr
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(8)).setPreferredWidth(65);   // dia semana
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(9)).setPreferredWidth(200);  // documento
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(10)).setPreferredWidth(0);   // classif
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(11)).setPreferredWidth(430); // Descr
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(12)).setPreferredWidth(90);  // Valor
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(13)).setPreferredWidth(0);   // dtApr
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(14)).setPreferredWidth(0);   // statusMov
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(15)).setPreferredWidth(40);  // Prev
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(16)).setPreferredWidth(105); // Saldo

            // Renderizadores
            DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
            rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

            jTablePesquisa.getColumnModel().getColumn(12).setCellRenderer(rightRenderer);
            jTablePesquisa.getColumnModel().getColumn(16).setCellRenderer(rightRenderer);
            jTablePesquisa.getColumnModel().getColumn(15).setCellRenderer(centerRenderer);

            // Ocultar colunas
            int[] colunasOcultas = {2, 4, 5, 10, 13, 14};
            for (int i : colunasOcultas) {
                jTablePesquisa.getColumnModel().getColumn(i).setMinWidth(0);
                jTablePesquisa.getColumnModel().getColumn(i).setMaxWidth(0);
            }

            DecimalFormat df = new DecimalFormat("#,##0.00");
            SimpleDateFormat sdfSaida = new SimpleDateFormat("dd/MM/yyyy");

            String dataAnterior = "";
            int indiceUltimaLinha = -1;
            double saldoAcumulado = sa;

            while (rs.next()) {
                // Pega a data correta conforme o tipo de consulta
                java.sql.Date dataSql = rs.getDate(campoDataOrdenacao);
                //String dataFormatada = (dataSql != null) ? sdfSaida.format(dataSql) : "";
                // Data principal (dtApr ou dtVcto) - já tratada antes
                String dataFormatada = (dataSql != null) ? sdfSaida.format(dataSql) : "";

                String diaSemana = getDayOfWeek(dataFormatada);

                String dtLancto = rs.getDate("dtlancto") != null ? sdfSaida.format(rs.getDate("dtlancto")) : "";
                String dtEmi = rs.getDate("dtEmi") != null ? sdfSaida.format(rs.getDate("dtEmi")) : "";
                String dtApr = rs.getDate("dtApr") != null ? sdfSaida.format(rs.getDate("dtApr")) : "";

                double valorMovimento = rs.getDouble("Valor");
                saldoAcumulado += valorMovimento;

                // Se mudou o dia, atualiza o saldo na última linha do dia anterior
                if (!dataFormatada.equals(dataAnterior) && indiceUltimaLinha != -1) {
                    modelo.setValueAt(df.format(saldoAcumulado - valorMovimento), indiceUltimaLinha, 16);
                }

                modelo.addRow(new Object[]{
                    rs.getString("idMov"),
                    rs.getString("recurso"),
                    rs.getString("vrecurso"),
                    rs.getString("clifor"),
                    rs.getString("vCliFor"),
                    dtLancto,
                    dtEmi,
                    dataFormatada,
                    diaSemana,
                    rs.getString("documento"),
                    rs.getString("classif"),
                    rs.getString("Descr"),
                    df.format(valorMovimento),
                    dtApr,
                    rs.getString("statusMov"),
                    rs.getString("Prev"),
                    ""
                });

                indiceUltimaLinha = modelo.getRowCount() - 1;
                dataAnterior = dataFormatada;
            }

            // Preenche o saldo final na última linha
            if (indiceUltimaLinha != -1) {
                modelo.setValueAt(df.format(saldoAcumulado), indiceUltimaLinha, 16);
            }

            // Renderizadores personalizados finais
            jTablePesquisa.getColumnModel().getColumn(8).setCellRenderer(new ColoreDSem());
            jTablePesquisa.getColumnModel().getColumn(12).setCellRenderer(new CustomTableCellRenderer(12, 11, false));
            jTablePesquisa.getColumnModel().getColumn(16).setCellRenderer(new CustomTableCellRenderer(16, 11, false));

            rs.close();
            stmt.close();
            con.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro na consulta: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private String formatarData(String dataString, SimpleDateFormat sdfSaida, SimpleDateFormat sdfEntrada) {
        if (dataString == null) {
            return "";
        }
        try {
            Date dataUtil = sdfEntrada.parse(dataString);
            return sdfSaida.format(dataUtil);
        } catch (ParseException e) {
            return "Data inválida";
        }
    }


    private void jButtonPImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPImprimirActionPerformed

        java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm");
        String infDt = dateFormat.format(new java.util.Date());
        String dIni = jFormattedTextFieldDataIni.getText();
        String dFim = jFormattedTextFieldDataFim.getText();
        String txt1 = jLabelTipo.getText() + " - Período: " + dIni + " a " + dFim;
        String txt2 = "Saldo Anterior: " + jTextFieldSaldoAnterior.getText();

        java.awt.print.PrinterJob job = java.awt.print.PrinterJob.getPrinterJob();
        javax.print.attribute.PrintRequestAttributeSet set = new javax.print.attribute.HashPrintRequestAttributeSet();
        set.add(javax.print.attribute.standard.OrientationRequested.LANDSCAPE);

        final java.awt.print.Printable tabelaOriginal = jTablePesquisa.getPrintable(javax.swing.JTable.PrintMode.FIT_WIDTH, null, new java.text.MessageFormat("Pág. {0,number,integer} - " + infDt));

        java.awt.print.Printable meuLayout = (graphics, pageFormat, pageIndex) -> {
            java.awt.Graphics2D g2d = (java.awt.Graphics2D) graphics;

            // 1. Desenha o seu cabeçalho manualmente na página 0
            if (pageIndex == 0) {
                g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
                g2d.setColor(java.awt.Color.BLACK);
                g2d.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 10));
                g2d.drawString(txt1, 0, 15);

                java.awt.FontMetrics fm = g2d.getFontMetrics();
                int xDireita = (int) pageFormat.getImageableWidth() - fm.stringWidth(txt2) - 5;
                g2d.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 10));
                g2d.drawString(txt2, xDireita, 30);
                g2d.drawLine(0, 35, (int) pageFormat.getImageableWidth(), 35);

                // Volta o translate para não afetar a criação da cópia abaixo
                g2d.translate(-pageFormat.getImageableX(), -pageFormat.getImageableY());
            }

            // 2. O SEGREDO: Criamos uma cópia para a tabela
            java.awt.Graphics2D g2dTabela = (java.awt.Graphics2D) g2d.create();

            // Se for a página 0, empurramos APENAS a cópia da tabela para baixo
            if (pageIndex == 0) {
                g2dTabela.translate(0, 35);
            }

            // 3. Mandamos a tabela imprimir usando a cópia deslocada
            int resultado = tabelaOriginal.print(g2dTabela, pageFormat, pageIndex);

            // 4. Jogamos a cópia fora (libera memória)
            g2dTabela.dispose();

            // 5. Retornamos o resultado usando o g2d original (que está com o rodapé no lugar certo)
            return resultado;
        };

        job.setPrintable(meuLayout);
        if (job.printDialog(set)) {
            try {
                job.print(set);
            } catch (java.awt.print.PrinterException e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonPImprimirActionPerformed

    private void jButtonPLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPLimparActionPerformed
        ((DefaultTableModel) jTablePesquisa.getModel()).setRowCount(0);
        jFormattedTextFieldDataIni.setText("");
        jFormattedTextFieldDataFim.setText("");
        jTextFieldSaldoAnterior.setText("0");
    }//GEN-LAST:event_jButtonPLimparActionPerformed

    private void jButtonPFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonPFecharActionPerformed

    private void jButtonGerarGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarGraficoActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTablePesquisa.getModel();

        GraficoDeLinha grafico = new GraficoDeLinha("Gráfico de Saldo");
        grafico.criarGrafico(modelo); // Passa o modelo da tabela como parâmetro
    }//GEN-LAST:event_jButtonGerarGraficoActionPerformed

    private void jButtonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportarActionPerformed
        // Verifica se a tabela tem dados
        if (jTablePesquisa.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Não há dados na tabela para exportar.");
            return;
        }

        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Salvar Relatório");
        // Define um nome padrão para o arquivo
        chooser.setSelectedFile(new java.io.File("Relatorio_Fluxo_Caixa.csv"));

        int userSelection = chooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            java.io.File arquivoParaSalvar = chooser.getSelectedFile();

            try (java.io.FileWriter fw = new java.io.FileWriter(arquivoParaSalvar)) {
                DefaultTableModel modelo = (DefaultTableModel) jTablePesquisa.getModel();
                int colCount = modelo.getColumnCount();

                // 1. Escreve os Cabeçalhos (ignorando colunas ocultas se desejar)
                for (int i = 0; i < colCount; i++) {
                    fw.write(modelo.getColumnName(i) + (i == colCount - 1 ? "" : ";"));
                }
                fw.write("\n");

                // 2. Escreve as Linhas
                for (int i = 0; i < modelo.getRowCount(); i++) {
                    for (int j = 0; j < colCount; j++) {
                        Object valor = modelo.getValueAt(i, j);
                        String texto = (valor == null) ? "" : valor.toString();

                        // Limpa pontos/vírgulas se necessário ou apenas remove quebras de linha
                        texto = texto.replace("\n", " ").replace(";", ",");

                        fw.write(texto + (j == colCount - 1 ? "" : ";"));
                    }
                    fw.write("\n");
                }

                JOptionPane.showMessageDialog(null, "Arquivo exportado com sucesso para:\n" + arquivoParaSalvar.getAbsolutePath());

            } catch (java.io.IOException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao salvar o arquivo: " + ex.getMessage());
                Logger.getLogger(VConsFlxCxDiario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonExportarActionPerformed

    private void PegaSaldoAnterior() {
        try {
            SimpleDateFormat formatoEntrada = new SimpleDateFormat("dd/MM/yyyy");

            Date dataInicio = formatoEntrada.parse(jFormattedTextFieldDataIni.getText());

            Connection con = Conexao.faz_conexao();

            // SQL exatamente como no SQLite: usa dtlancto e os vrecurso corretos
            String sql = "SELECT COALESCE(SUM(Valor), 0) AS saldo_anterior "
                    + "FROM tbmovimento "
                    + "WHERE dtlancto <= ? "
                    + "AND vrecurso IN ('1.001.001', '1.001.002') "
                    + "AND recurso NOT IN ('0079', '0022')";
            //+ "AND vrecurso IN ('1.001.001', '1.001.002', '1.003.001') "
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setDate(1, new java.sql.Date(dataInicio.getTime()));

            ResultSet rs = stmt.executeQuery();

            double saldoAnterior = 0.0;
            if (rs.next()) {
                saldoAnterior = rs.getDouble("saldo_anterior");
            }

            // Formata como moeda brasileira
            DecimalFormat df = new DecimalFormat("#,##0.00");
            jTextFieldSaldoAnterior.setText(df.format(saldoAnterior));

            rs.close();
            stmt.close();
            con.close();

        } catch (Exception ex) {
            jTextFieldSaldoAnterior.setText("0,00");
            Logger.getLogger(VConsFlxCxDiario.class.getName()).log(Level.SEVERE, "Erro ao calcular saldo anterior", ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExportar;
    private javax.swing.JButton jButtonGerarGrafico;
    private javax.swing.JButton jButtonPFechar;
    private javax.swing.JButton jButtonPImprimir;
    private javax.swing.JButton jButtonPLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataFim;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataIni;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisa;
    private javax.swing.JTextField jTextFieldSaldoAnterior;
    // End of variables declaration//GEN-END:variables

    public static String[] WEEKDAYS = {"Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sab"};

    public static String getDayOfWeek(String data) {
        try {
            SimpleDateFormat parser = new SimpleDateFormat("dd/MM/yyyy");
            parser.setLenient(false);
            Calendar cal = Calendar.getInstance();
            cal.setTime(parser.parse(data));
            return WEEKDAYS[cal.get(Calendar.DAY_OF_WEEK) - 1];
        } catch (ParseException e) {
            e.printStackTrace();
        }
        return "---";
    }

    public class ColoreDSem extends DefaultTableCellRenderer {

        private Component componente;

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            componente = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            Font font = new Font("Tahoma", Font.PLAIN, 11);
            String confere;
            confere = table.getValueAt(row, 7).toString();
            confere = getDayOfWeek(confere);
            this.setHorizontalAlignment(CENTER);
            switch (confere) {
                case "Sab" -> {
                    this.setForeground(Color.RED);
                    componente.setFont(font);
                }
                case "Dom" -> {
                    this.setForeground(Color.RED);
                    componente.setFont(font);
                }
                default ->
                    this.setForeground(Color.black);
            }
            return this;
        }
    }

    public class GraficoDeLinha extends ApplicationFrame {

        public GraficoDeLinha(String title) {
            super(title);
        }

        public void criarGrafico(DefaultTableModel tableModel) {
            DefaultCategoryDataset dataset = new DefaultCategoryDataset();

            // Percorre as linhas da tabela para pegar as datas e os saldos
            for (int i = 0; i < tableModel.getRowCount(); i++) {
                String data = (String) tableModel.getValueAt(i, 7); // Coluna de data
                String saldoStr = (String) tableModel.getValueAt(i, 16); // Coluna de saldo

                // Verifica se o saldo é vazio, nulo ou contém apenas espaços em branco
                if (saldoStr != null && !saldoStr.trim().isEmpty()) {
                    try {
                        // Remove os separadores de milhar (pontos) e substitui a vírgula decimal por ponto
                        double saldo = Double.parseDouble(saldoStr.replace(".", "").replace(",", "."));
                        dataset.addValue(saldo, "Saldo", data); // Adiciona o saldo no dataset
                    } catch (NumberFormatException e) {
                        System.err.println("Erro ao converter o saldo: " + saldoStr);
                    }
                } else {
                    //System.err.println("Saldo vazio ou nulo na linha: " + i + " - data: " + data);
                }
            }

            // Cria o gráfico de linha
            JFreeChart lineChart = ChartFactory.createLineChart(
                    "Evolução do Saldo no Período",
                    "Data", // Eixo X
                    "Saldo", // Eixo Y
                    dataset,
                    PlotOrientation.VERTICAL,
                    true, true, false);

            // Personalizar o gráfico (ajustar a aparência das datas no eixo X)
            CategoryPlot plot = lineChart.getCategoryPlot();
            CategoryAxis domainAxis = plot.getDomainAxis();

            // Rotacionar os rótulos para melhorar a legibilidade
            domainAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_45);

            // Reduzir o tamanho da fonte das labels no eixo X
            domainAxis.setTickLabelFont(new Font("Tahoma", Font.PLAIN, 10));

            // Exibe o gráfico em um JFrame no centro da tela
            ChartPanel chartPanel = new ChartPanel(lineChart);
            chartPanel.setPreferredSize(new java.awt.Dimension(800, 600));

            // Exibe o gráfico em uma janela
            JFrame frame = new JFrame("Gráfico de Saldo");
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Alterado de EXIT_ON_CLOSE para DISPOSE_ON_CLOSE
            frame.getContentPane().add(chartPanel);
            frame.pack();
            frame.setLocationRelativeTo(null); // Centraliza a janela
            frame.setVisible(true);
        }
    }
}
