package view;

import utilitarios.Conexao;
import classes.CustomTableCellRenderer;
import classes.ExportToExcel;
import classes.ImprimirJTable;
import classes.PercentualRenderer;
import java.awt.Color;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author CARLOS
 */
public class VConsRD extends javax.swing.JInternalFrame {

    /**
     * Creates new form VConsRD
     */
    public VConsRD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRegime = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldDataIni = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldDataFim = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonPImprimir = new javax.swing.JButton();
        jButtonPLimpar = new javax.swing.JButton();
        jButtonPFechar = new javax.swing.JButton();
        jButtonGraficoDesp = new javax.swing.JButton();
        jButtonGraficoRec = new javax.swing.JButton();
        jButtonExportar = new javax.swing.JButton();
        jPanelRegime = new javax.swing.JPanel();
        rbCaixa = new javax.swing.JRadioButton();
        rbCompetencia = new javax.swing.JRadioButton();
        rbVcto = new javax.swing.JRadioButton();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CONSULTA - RECEITAS X DESPESAS");

        jLabel2.setText("   PERÍODO DE VENCIMENTOS  de");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        try {
            jFormattedTextFieldDataIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("até");

        try {
            jFormattedTextFieldDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRINCIPAL", "GRUPO", "CONTA", "TOTAL CONTA", "ACUMULADO", "PERCENTUAL", "MEDIA HISTORICA(%)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePesquisa.setSelectionBackground(new java.awt.Color(255, 255, 204));
        jScrollPane1.setViewportView(jTablePesquisa);

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonPImprimir.setText("Imprimir");
        jButtonPImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPImprimirActionPerformed(evt);
            }
        });

        jButtonPLimpar.setText("Limpar");
        jButtonPLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPLimparActionPerformed(evt);
            }
        });

        jButtonPFechar.setText("Fechar");
        jButtonPFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPFecharActionPerformed(evt);
            }
        });

        jButtonGraficoDesp.setText("Gráfico Despesas");
        jButtonGraficoDesp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGraficoDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGraficoDespActionPerformed(evt);
            }
        });

        jButtonGraficoRec.setText("Gráfico Receitas");
        jButtonGraficoRec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGraficoRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGraficoRecActionPerformed(evt);
            }
        });

        jButtonExportar.setText("Exportar para Excel");
        jButtonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGraficoDesp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGraficoRec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExportar, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jButtonPImprimir)
                    .addComponent(jButtonPLimpar)
                    .addComponent(jButtonPFechar)
                    .addComponent(jButtonGraficoDesp)
                    .addComponent(jButtonGraficoRec)
                    .addComponent(jButtonExportar))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        grupoRegime.add(rbCaixa);
        rbCaixa.setText("Regime de Caixa");

        grupoRegime.add(rbCompetencia);
        rbCompetencia.setText("Regime de Competência");

        grupoRegime.add(rbVcto);
        rbVcto.setText("Vencimento");

        javax.swing.GroupLayout jPanelRegimeLayout = new javax.swing.GroupLayout(jPanelRegime);
        jPanelRegime.setLayout(jPanelRegimeLayout);
        jPanelRegimeLayout.setHorizontalGroup(
            jPanelRegimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbVcto)
                .addGap(35, 35, 35)
                .addComponent(rbCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(rbCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelRegimeLayout.setVerticalGroup(
            jPanelRegimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegimeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRegimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCompetencia)
                    .addComponent(rbCaixa)
                    .addComponent(rbVcto))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRegime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRegime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBounds(110, 35, 1120, 656);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

    if (jFormattedTextFieldDataIni.getText().trim().length() == 4) {
            JOptionPane.showMessageDialog(null, "Atenção! Favor preencher o campo de data inicial.");
            return;
        } else if (jFormattedTextFieldDataFim.getText().trim().length() == 4) {
            JOptionPane.showMessageDialog(null, "Atenção! Favor preencher o campo de data final.");
            return;
        }

        // Variáveis para armazenar os valores das categorias
        double receitasOperacionais = 0.0;
        double receitasNaoOperacionais = 0.0;
        double despesasOperacionais = 0.0;
        double despesasNaoOperacionais = 0.0;
        double totalReceitas = 0.0;
        double totalDespesas = 0.0;

        // Declarações de variáveis de data no escopo do método
        SimpleDateFormat formato_data = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat formatoBanco = new SimpleDateFormat("yyyy-MM-dd");
        String dataTextoi = jFormattedTextFieldDataIni.getText();
        String dataTextof = jFormattedTextFieldDataFim.getText();
        java.util.Date data_i2;
        java.util.Date data_f2;
        try {
            data_i2 = formato_data.parse(dataTextoi);
            data_f2 = formato_data.parse(dataTextof);
        } catch (ParseException ex) {
            Logger.getLogger(VConsRD.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao processar datas: " + ex.getMessage());
            return;
        }
        String data_i = formatoBanco.format(data_i2);
        String data_f = formatoBanco.format(data_f2);

        // Determinar o campo de data com base na seleção do usuário
        String campoData;
        if (rbVcto.isSelected()) {
            campoData = "dtVcto";
        } else if (rbCompetencia.isSelected()) {
            campoData = "dtEmi";
        } else {
            campoData = "dtApr";
        }

        // Consulta para totais do período selecionado
        Connection con2 = null;
        PreparedStatement stmt2 = null;
        ResultSet rs2 = null;
        try {
            con2 = Conexao.faz_conexao();

            String sql2
                    = "SELECT nome_S, SUM(Valor) AS Total "
                    + "FROM viewmovrd "
                    + "WHERE " + campoData + " BETWEEN ? AND ? "
                    + "AND nome_P <> 'NULO' "
                    + "AND classif NOT IN ('3.003.005', '4.008.011') "
                    + "GROUP BY nome_S;";
            stmt2 = con2.prepareStatement(sql2);
            stmt2.setString(1, data_i);
            stmt2.setString(2, data_f);
            rs2 = stmt2.executeQuery();

            while (rs2.next()) {
                String nomeS = rs2.getString("nome_S");
                double total = rs2.getDouble("Total");
                if ("RECEITAS OPERACIONAIS".equalsIgnoreCase(nomeS)) {
                    receitasOperacionais += total;
                    totalReceitas += total;
                } else if ("RECEITAS NÃO OPERACIONAIS".equalsIgnoreCase(nomeS) || "RECEITAS NAO OPERACIONAIS".equalsIgnoreCase(nomeS)) {
                    receitasNaoOperacionais += total;
                    totalReceitas += total;
                } else if ("DESPESAS OPERACIONAIS".equalsIgnoreCase(nomeS)) {
                    despesasOperacionais += total;
                    totalDespesas += total;
                } else if ("DESPESAS NÃO OPERACIONAIS".equalsIgnoreCase(nomeS) || "DESPESAS NAO OPERACIONAIS".equalsIgnoreCase(nomeS)) {
                    despesasNaoOperacionais += total;
                    totalDespesas += total;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(VConsRD.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao consultar totais: " + ex.getMessage());
            return;
        } finally {
            try {
                if (rs2 != null) {
                    rs2.close();
                }
                if (stmt2 != null) {
                    stmt2.close();
                }
                // Não fechar con2 aqui para evitar "database closed"
            } catch (SQLException ex) {
                Logger.getLogger(VConsRD.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        // Mapa para armazenar os percentuais históricos por nome_C
        Map<String, Double> percentuaisHistoricos = new HashMap<>();
        Connection conHist = null;
        PreparedStatement stmtHist = null;
        ResultSet rsHist = null;
        try {
            conHist = Conexao.faz_conexao();
            
            // Calcular data inicial como 24 meses antes da data final
            java.time.LocalDate dataFim = data_f2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            java.time.LocalDate dataInicioHist = dataFim.minusMonths(24);
            String dataInicioHistStr = formatoBanco.format(java.util.Date.from(dataInicioHist.atStartOfDay(ZoneId.systemDefault()).toInstant()));

            // Consulta para totais históricos por nome_S (últimos 24 meses)
            String sqlHistTotais = "SELECT nome_S, SUM(Valor) AS Total FROM viewmovrd WHERE nome_P <> 'NULO' AND " + campoData + " >= ? GROUP BY nome_S";
            stmtHist = conHist.prepareStatement(sqlHistTotais);
            stmtHist.setString(1, dataInicioHistStr);
            rsHist = stmtHist.executeQuery();

            double totalReceitasHist = 0.0;
            double totalDespesasHist = 0.0;

            while (rsHist.next()) {
                String nomeS = rsHist.getString("nome_S");
                double total = rsHist.getDouble("Total");
                if (nomeS != null && nomeS.contains("RECEITAS")) {
                    totalReceitasHist += total;
                } else if (nomeS != null && nomeS.contains("DESPESAS")) {
                    totalDespesasHist += total;
                }
            }
            rsHist.close();
            stmtHist.close();

            // Consulta para totais históricos por nome_C (últimos 24 meses)
            String sqlHist = "SELECT nome_C, nome_S, SUM(Valor) AS Total FROM viewmovrd WHERE nome_P <> 'NULO' AND " + campoData + " >= ? GROUP BY nome_C, nome_S";
            stmtHist = conHist.prepareStatement(sqlHist);
            stmtHist.setString(1, dataInicioHistStr);
            rsHist = stmtHist.executeQuery();

            while (rsHist.next()) {
                String nomeC = rsHist.getString("nome_C");
                String nomeS = rsHist.getString("nome_S");
                double total = rsHist.getDouble("Total");
                double percentHist = 0.0;
                if (total > 0 && totalReceitasHist != 0) {
                    percentHist = (total / totalReceitasHist) * 100;
                } else if (total < 0 && totalDespesasHist != 0) {
                    percentHist = (total / totalDespesasHist) * 100;
                }
                percentuaisHistoricos.put(nomeC, percentHist);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VConsRD.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao consultar históricos: " + ex.getMessage());
            return;
        } finally {
            try {
                if (rsHist != null) {
                    rsHist.close();
                }
                if (stmtHist != null) {
                    stmtHist.close();
                }
                // Não fechar conHist aqui para evitar "database closed"
            } catch (SQLException ex) {
                Logger.getLogger(VConsRD.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        // Consulta principal para preencher a tabela
        Connection con = null;
        PreparedStatement stmt = null;
        ResultSet rs = null;
        try {
            con = Conexao.faz_conexao();
            String sql = "SELECT nome_P, nome_S, nome_C, SUM(Valor) AS Total"
                    + " FROM viewmovrd "
                    + "WHERE " + campoData + " BETWEEN ? AND ? "
                    + "AND nome_P <> 'NULO' "
                    + "AND classif NOT IN ('3.003.005','4.008.011') "
                    + "GROUP BY nome_P, nome_S, nome_C "
                    + "ORDER BY classif;";
    
            stmt = con.prepareStatement(sql);
            stmt.setString(1, data_i);
            stmt.setString(2, data_f);
            rs = stmt.executeQuery();

            DefaultTableModel modelo = new DefaultTableModel(
                    new Object[]{"PRINCIPAL", "GRUPO", "CONTA", "TOTAL", "ACUMULADO", "PERCENTUAL", "MÉDIA HISTÓRICA (%)"},
                    0
            );
            jTablePesquisa.setModel(modelo);
            double sa = 0.00;
            jTablePesquisa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(0)).setPreferredWidth(90);
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(1)).setPreferredWidth(210);
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(2)).setPreferredWidth(365);
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(3)).setPreferredWidth(130);
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(4)).setPreferredWidth(100);
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(5)).setPreferredWidth(80);
            jTablePesquisa.getColumn(jTablePesquisa.getColumnName(6)).setPreferredWidth(90);
            DefaultTableCellRenderer tab = new DefaultTableCellRenderer();
            tab.setHorizontalAlignment(SwingConstants.RIGHT);
            jTablePesquisa.getColumnModel().getColumn(3).setCellRenderer(tab);
            jTablePesquisa.getColumnModel().getColumn(4).setCellRenderer(tab);
            String prin = "";
            String sub = "";
            String lastPrin = "";
            DecimalFormat df = new DecimalFormat("#,##0.00");
            DecimalFormat dp = new DecimalFormat("0.0000");

            while (rs.next()) {
                double percent = 0.0000;
                String nomeC = rs.getString("nome_C");
                double total = rs.getDouble("Total");
                if (total > 0) {
                    percent = totalReceitas != 0 ? (total / totalReceitas) * 100 : 0.0;
                } else if (total < 0) {
                    percent = totalDespesas != 0 ? (total / totalDespesas) * 100 : 0.0;
                }
                sa += total;
                if (!lastPrin.isEmpty() && !lastPrin.equals(rs.getString("nome_P"))) {
                    modelo.addRow(new Object[]{"", "", "", "", "", "", ""});
                }
                if (prin.equals(rs.getString("nome_P"))) {
                    prin = " ";
                } else {
                    prin = rs.getString("nome_P");
                }
                if (sub.equals(rs.getString("nome_S"))) {
                    sub = " ";
                } else {
                    sub = rs.getString("nome_S");
                }
                double percentHist = percentuaisHistoricos.getOrDefault(nomeC, 0.0);
                modelo.addRow(new Object[]{
                    prin,
                    sub,
                    nomeC,
                    df.format(total),
                    df.format(sa),
                    dp.format(percent),
                    dp.format(percentHist)
                });
                lastPrin = rs.getString("nome_P");
                prin = rs.getString("nome_P");
                sub = rs.getString("nome_S");
            }

            modelo.addRow(new Object[]{"", "", "", "", "", "", ""});
            String taxaConsumo = totalReceitas != 0 ? dp.format((-totalDespesas / totalReceitas) * 100) : "N/A";
            modelo.addRow(new Object[]{"", "", "TAXA DE CONSUMO", "", "", taxaConsumo, ""});

            long diasDoPeriodo = ChronoUnit.DAYS.between(
                    data_i2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate(),
                    data_f2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate()
            ) + 1;

            double receitaPorDia = totalReceitas != 0 ? totalReceitas / diasDoPeriodo : 0.0;
            int receitaDias = (int) Math.round(receitaPorDia);
            String textoReceitaDias = receitaDias + " dias";

            double diasConsumidos = receitaPorDia != 0 ? totalDespesas / receitaPorDia : 0.0;
            int despesaDias = (int) Math.round(diasConsumidos);
            String textoDespesaDias = -despesaDias + " dias";

            modelo.addRow(new Object[]{"", "", "", "", "", "", ""});
            modelo.addRow(new Object[]{"", "", "TOTAL DIAS NO PERÍODO: " + diasDoPeriodo + " dias", "", "", "", ""});
            modelo.addRow(new Object[]{"", "", "DIAS EQUIVALENTES CONSUMIDOS: " + textoDespesaDias, "", "", "", ""});
            modelo.addRow(new Object[]{"", "", "", "", "", "", ""});
            modelo.addRow(new Object[]{"", "", "RECEITAS OPERACIONAIS", "", df.format(receitasOperacionais), "", ""});
            modelo.addRow(new Object[]{"", "", "DESPESAS OPERACIONAIS", "", df.format(despesasOperacionais), "", ""});
            modelo.addRow(new Object[]{"", "", "RESULTADO OPERACIONAL (RECEITAS-DESPESAS)", "", df.format(receitasOperacionais + despesasOperacionais), "", ""});
            modelo.addRow(new Object[]{"", "", "", "", "", "", ""});
            modelo.addRow(new Object[]{"", "", "RECEITAS NÃO OPERACIONAIS", "", df.format(receitasNaoOperacionais), "", ""});
            modelo.addRow(new Object[]{"", "", "DESPESAS NÃO OPERACIONAIS", "", df.format(despesasNaoOperacionais), "", ""});
            modelo.addRow(new Object[]{"", "", "RESULTADO NÃO OPERACIONAL", "", df.format(receitasNaoOperacionais + despesasNaoOperacionais), "", ""});
            modelo.addRow(new Object[]{"", "", "", "", "", "", ""});
            modelo.addRow(new Object[]{"", "", "RESULTADO FINAL DO PERÍODO:", "", df.format(receitasOperacionais + despesasOperacionais + receitasNaoOperacionais + despesasNaoOperacionais), "", ""});

            jTablePesquisa.getColumnModel().getColumn(3).setCellRenderer(new CustomTableCellRenderer(3, 11, false));
            jTablePesquisa.getColumnModel().getColumn(4).setCellRenderer(new CustomTableCellRenderer(4, 11, false));
            PercentualRenderer percentualRenderer = new PercentualRenderer();
            jTablePesquisa.getColumnModel().getColumn(5).setCellRenderer(percentualRenderer);
            jTablePesquisa.getColumnModel().getColumn(6).setCellRenderer(percentualRenderer);
        
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Consulta_Inflacao.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao preencher tabela: " + ex.getMessage());
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (stmt != null) {
                    stmt.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException ex) {
                Logger.getLogger(VConsRD.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonPImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPImprimirActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        Date date = new Date();
        String infDt = dateFormat.format(date);
        
        // Pegar as datas dos campos
        String dataInicial = jFormattedTextFieldDataIni.getText();
        String dataFinal = jFormattedTextFieldDataFim.getText();
        
        PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
        set.add(OrientationRequested.LANDSCAPE);
        
        // Cabeçalho com as datas do período
        MessageFormat cabecalho = new MessageFormat(
                "Receitas X Despesas - Período: " + dataInicial + " a " + dataFinal );
        
        MessageFormat rodape = new MessageFormat(
                "Página {0,number,integer}" + " - Impressão: " + infDt );
        
        try {
            jTablePesquisa.print(JTable.PrintMode.FIT_WIDTH, cabecalho, rodape, false, set, false);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Erro ao imprimir!!! %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jButtonPImprimirActionPerformed

    private void jButtonPLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPLimparActionPerformed
        ((DefaultTableModel) jTablePesquisa.getModel()).setRowCount(0);
        jFormattedTextFieldDataIni.setText("");
        jFormattedTextFieldDataFim.setText("");
    }//GEN-LAST:event_jButtonPLimparActionPerformed

    private void jButtonPFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonPFecharActionPerformed

    private void jButtonGraficoDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGraficoDespActionPerformed
        try {
            PieChartDesp desp = new PieChartDesp();
        } catch (ParseException ex) {
            Logger.getLogger(VConsRD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonGraficoDespActionPerformed

    private void jButtonGraficoRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGraficoRecActionPerformed
        // TODO add your handling code here:
        try {
            PieChartRec rec = new PieChartRec();
        } catch (ParseException ex) {
            Logger.getLogger(VConsRD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonGraficoRecActionPerformed

    private void jButtonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Salvar como...");
        int userSelection = fileChooser.showSaveDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String path = fileChooser.getSelectedFile().getAbsolutePath();
            if (!path.endsWith(".xlsx")) {
                path += ".xlsx";
            }
            try {
                ExportToExcel exporter = new ExportToExcel();
                exporter.exportTable(jTablePesquisa, path);
                JOptionPane.showMessageDialog(null, "Arquivo Excel " + path + " foi gerado com sucesso!");
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao exportar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonExportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoRegime;
    private javax.swing.JButton jButtonExportar;
    private javax.swing.JButton jButtonGraficoDesp;
    private javax.swing.JButton jButtonGraficoRec;
    private javax.swing.JButton jButtonPFechar;
    private javax.swing.JButton jButtonPImprimir;
    private javax.swing.JButton jButtonPLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataFim;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataIni;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelRegime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisa;
    private javax.swing.JRadioButton rbCaixa;
    private javax.swing.JRadioButton rbCompetencia;
    private javax.swing.JRadioButton rbVcto;
    // End of variables declaration//GEN-END:variables

    public class PieChartDesp extends JFrame {

        JFreeChart chart;

        public PieChartDesp() throws ParseException {
            super("Gráfico Despesas no Período");
            setSize(1000, 800);
            setLayout(null);
            setResizable(false);
            setLocationRelativeTo(null);
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            crearGraficoD();
            ChartPanel panel = new ChartPanel(chart, false);
            panel.setBounds(10, 20, 960, 720);
            add(panel);
            setVisible(true);
        }

        public void crearGraficoD() throws ParseException {
            ArrayList<String> labels = new ArrayList<>();
            DecimalFormat df = new DecimalFormat("#,###.00");
            ArrayList<Double> values = new ArrayList<>();
            for (int i = 0; i < jTablePesquisa.getRowCount(); i++) {
                String value = (String) jTablePesquisa.getValueAt(i, 3);
                if (value != null && !value.trim().isEmpty()) {
                    labels.add((String) jTablePesquisa.getValueAt(i, 2));
                    values.add(df.parse(value).doubleValue() * -1);
                }
            }
            DefaultPieDataset dataset = new DefaultPieDataset();
            for (int i = 0; i < labels.size(); i++) {
                dataset.setValue(labels.get(i), values.get(i));
            }
            chart = ChartFactory.createPieChart(
                    "Gráfico de Despesas por Período", //Titulo do grafico
                    dataset, //data
                    true, //Legenda
                    true,
                    false);
            //pintura
            chart.setBackgroundPaint(Color.ORANGE);//Cor do funde da janela
            chart.getTitle().setPaint(Color.blue); //Dar cor ao titulo
            PiePlot plot = (PiePlot) chart.getPlot();
            plot.setLabelBackgroundPaint(Color.ORANGE);//Cor das etiquetas
            plot.setBackgroundPaint(Color.WHITE); //Cor do fundo do grafico        
            this.dispose();
        }
    }

    public class PieChartRec extends JFrame {

        JFreeChart chart;

        public PieChartRec() throws ParseException {
            super("Gráfico Receitas no Período");
            setSize(1000, 800);
            setLayout(null);
            setResizable(false);
            setLocationRelativeTo(null);
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            crearGraficoR();
            ChartPanel panel = new ChartPanel(chart, false);
            panel.setBounds(10, 20, 960, 720);
            add(panel);
            setVisible(true);
        }

        public void crearGraficoR() throws ParseException {
            ArrayList<String> labels = new ArrayList<>();
            DecimalFormat df = new DecimalFormat("#,###.00");
            ArrayList<Double> values = new ArrayList<>();
            for (int i = 0; i < jTablePesquisa.getRowCount(); i++) {
                String value = (String) jTablePesquisa.getValueAt(i, 3);
                if (value != null && !value.trim().isEmpty()) {
                    labels.add((String) jTablePesquisa.getValueAt(i, 2));
                    values.add(df.parse(value).doubleValue());
                }
            }
            DefaultPieDataset dataset = new DefaultPieDataset();
            for (int i = 0; i < labels.size(); i++) {
                dataset.setValue(labels.get(i), values.get(i));
            }
            chart = ChartFactory.createPieChart(
                    "Gráfico de Receitas por Período", //Título do Gráfico
                    dataset, //data
                    true, //Legenda
                    true,
                    false);
            //pintura
            chart.setBackgroundPaint(Color.ORANGE);//Cor de fundo da janela
            chart.getTitle().setPaint(Color.blue); //Dar cor ao título
            PiePlot plot = (PiePlot) chart.getPlot();
            plot.setLabelBackgroundPaint(Color.ORANGE);//Cor das etiquetas
            plot.setBackgroundPaint(Color.WHITE); //Cor de fundo do gráfico        
            this.dispose();
        }
    }

}
