package view;

import utilitarios.Conexao;
import classes.CustomTableCellRenderer;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author CARLOS
 */
public class VConsClientes extends javax.swing.JInternalFrame {
     CarregarCbx re = new CarregarCbx(); //Carrega combobox de Favorecidos
    /**
     * Creates new form VConsClientes
     * @throws java.sql.SQLException
     */
    public VConsClientes() throws SQLException {
        initComponents();
        re.CarregarCbx("tbclifor", "apelidoCliFor", jComboBoxPesq);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPesq = new javax.swing.JComboBox<>();
        tfNrFav = new javax.swing.JTextField();
        tfFavorecidos = new javax.swing.JTextField();
        tfNoCli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldDataIni = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldDataFim = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSaldoAnterior = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonPImprimir = new javax.swing.JButton();
        jButtonPLimpar = new javax.swing.JButton();
        jButtonPFechar = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CONSULTA - FAVORECIDOS (Clientes)");

        jLabel1.setText("Conta para pesquisa:");

        jComboBoxPesq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jComboBoxPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPesqActionPerformed(evt);
            }
        });

        tfNrFav.setEnabled(false);

        tfFavorecidos.setEnabled(false);
        tfFavorecidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFavorecidosActionPerformed(evt);
            }
        });

        tfNoCli.setEnabled(false);
        tfNoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoCliActionPerformed(evt);
            }
        });

        jLabel2.setText("Período Vcto.à pesquisar");

        try {
            jFormattedTextFieldDataIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("até");

        try {
            jFormattedTextFieldDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Saldo Anterior:");

        jTextFieldSaldoAnterior.setEnabled(false);

        jTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reg.", "Recurso", "vRecurso", "Favorecido", "vFavorecido", "Lancto.", "Emissão", "Vencimento", "Documento", "Classif.", "Descrição", "Valor", "Apresent.", "Status", "Prev.", "Saldo"
            }
        ));
        jTablePesquisa.setSelectionBackground(new java.awt.Color(255, 255, 204));
        jScrollPane1.setViewportView(jTablePesquisa);

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonPImprimir.setText("Imprimir");
        jButtonPImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPImprimirActionPerformed(evt);
            }
        });

        jButtonPLimpar.setText("Limpar");
        jButtonPLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPLimparActionPerformed(evt);
            }
        });

        jButtonPFechar.setText("Fechar");
        jButtonPFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(348, 348, 348))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jButtonPImprimir)
                    .addComponent(jButtonPLimpar)
                    .addComponent(jButtonPFechar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPesq, 0, 323, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNrFav, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFavorecidos, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfNoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSaldoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldSaldoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFavorecidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNrFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfNoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        setBounds(30, 45, 1293, 634);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPesqActionPerformed
        if (jComboBoxPesq.getSelectedIndex() > 0) {
            String selectedValue = jComboBoxPesq.getSelectedItem().toString();
            var texto = selectedValue.length();
            String completo = selectedValue;
            selectedValue = jComboBoxPesq.getSelectedItem().toString().substring(texto - 14);
            if (!selectedValue.isEmpty()) {
                String frase1 = selectedValue.substring(0, 4);
                tfNrFav.setText(frase1);
                String frase2 = selectedValue.substring(5);
                tfFavorecidos.setText(frase2);
                String frase3 = completo.substring(0, (texto - 15));
                tfNoCli.setText(frase3);
            }
        }
    }//GEN-LAST:event_jComboBoxPesqActionPerformed

    private void tfFavorecidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFavorecidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFavorecidosActionPerformed

    private void tfNoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoCliActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        if (jFormattedTextFieldDataIni.getText().trim().length() == 4) {
            JOptionPane.showMessageDialog(null, "Atenção! Favor preencher o campo de data inicial.");
        } else if (jFormattedTextFieldDataFim.getText().trim().length() == 4) {
            JOptionPane.showMessageDialog(null, "Atenção! Favor preencher o campo de data final.");
        } else {
            PegaSaldoAnterior();
            String ssa = jTextFieldSaldoAnterior.getText();
            double sa = Double.valueOf(ssa).doubleValue();
            DecimalFormat dec = new DecimalFormat("#,##0.00");
            jTextFieldSaldoAnterior.setText(dec.format(sa));

            try {
                SimpleDateFormat formato_data = new SimpleDateFormat("dd/MM/yyyy");
                DecimalFormat df = new DecimalFormat("#,##0.00");
                Connection con;
                con = Conexao.faz_conexao();
                String sql = "SELECT * FROM tbmovimento WHERE dtVcto BETWEEN ? AND ? AND clifor = ? AND recurso='0022' ORDER BY dtVcto";
                PreparedStatement stmt = con.prepareStatement(sql);
                java.util.Date data_i = null;
                try {
                    data_i = formato_data.parse(jFormattedTextFieldDataIni.getText());
                } catch (ParseException ex) {
                    System.out.println("Problema ao pegar data inicial: " + ex);
                }
                stmt.setDate(1, new java.sql.Date(data_i.getTime()));
                java.util.Date data_f = null;
                try {
                    data_f = formato_data.parse(jFormattedTextFieldDataFim.getText());
                } catch (ParseException ex) {
                    System.out.println("Problema ao pegar data Final: " + ex);
                }
                stmt.setDate(2, new java.sql.Date(data_f.getTime()));
                stmt.setString(3, tfNrFav.getText());
                try (ResultSet rs = stmt.executeQuery()) {
                    DefaultTableModel modelo = (DefaultTableModel) jTablePesquisa.getModel();
                    modelo.setNumRows(0);
                    //jTablePesquisa.setRowSorter(new TableRowSorter(modelo)); // Organiza tabela clicando no título da coluna
                    jTablePesquisa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
                    jTablePesquisa.getColumn(jTablePesquisa.getColumnName(0)).setPreferredWidth(40); //idMov
                    jTablePesquisa.getColumn(jTablePesquisa.getColumnName(1)).setPreferredWidth(60); //recurso
                    jTablePesquisa.getColumn(jTablePesquisa.getColumnName(2)).setPreferredWidth(0); //70 vrecurso
                    jTablePesquisa.getColumn(jTablePesquisa.getColumnName(3)).setPreferredWidth(50); //50 clifor
                    jTablePesquisa.getColumn(jTablePesquisa.getColumnName(4)).setPreferredWidth(0); //75 vCliFor
                    jTablePesquisa.getColumn(jTablePesquisa.getColumnName(5)).setPreferredWidth(75); //dtlancto
                    jTablePesquisa.getColumn(jTablePesquisa.getColumnName(6)).setPreferredWidth(75); //dtEmi
                    jTablePesquisa.getColumn(jTablePesquisa.getColumnName(7)).setPreferredWidth(75); //dtVcto
                    jTablePesquisa.getColumn(jTablePesquisa.getColumnName(8)).setPreferredWidth(110); //documento
                    jTablePesquisa.getColumn(jTablePesquisa.getColumnName(9)).setPreferredWidth(70);  //classif
                    jTablePesquisa.getColumn(jTablePesquisa.getColumnName(10)).setPreferredWidth(378); //Descr
                    jTablePesquisa.getColumn(jTablePesquisa.getColumnName(11)).setPreferredWidth(80);  //Valor
                    jTablePesquisa.getColumn(jTablePesquisa.getColumnName(12)).setPreferredWidth(75); //dtApr
                    jTablePesquisa.getColumn(jTablePesquisa.getColumnName(13)).setPreferredWidth(60); //statusMov
                    jTablePesquisa.getColumn(jTablePesquisa.getColumnName(14)).setPreferredWidth(30); //Prev
                    jTablePesquisa.getColumn(jTablePesquisa.getColumnName(15)).setPreferredWidth(80); //Saldo
                    DefaultTableCellRenderer tab = new DefaultTableCellRenderer();
                    tab.setHorizontalAlignment(SwingConstants.RIGHT);
                    jTablePesquisa.getColumnModel().getColumn(11).setCellRenderer(tab);
                    jTablePesquisa.getColumnModel().getColumn(15).setCellRenderer(tab);
                    
                    jTablePesquisa.getColumnModel().getColumn(2).setMinWidth(0); // Ocultando as colunas
                    jTablePesquisa.getColumnModel().getColumn(2).setMaxWidth(0); // Ocultando as colunas
                    
                    jTablePesquisa.getColumnModel().getColumn(4).setMinWidth(0); // Ocultando as colunas
                    jTablePesquisa.getColumnModel().getColumn(4).setMaxWidth(0); // Ocultando as colunas
                    
                    while (rs.next()) {
                        sa = sa + rs.getDouble("Valor");
                        Date Apre = rs.getDate("dtApr");
                        String AprFormatada;
                        if (Apre == null && !"".equals(Apre)) {
                            AprFormatada = null;
                        } else if (Apre.equals("  /  /    ")) {
                            AprFormatada = null;
                        } else if (Apre.equals("")) {
                            AprFormatada = null;
                        } else {
                            AprFormatada = formato_data.format(Apre);
                        }
                        modelo.addRow(new Object[]{rs.getString("idMov"),
                            rs.getString("recurso"),
                            rs.getString("vrecurso"),
                            rs.getString("clifor"),
                            rs.getString("vCliFor"),
                            formato_data.format(rs.getDate("dtlancto")),
                            formato_data.format(rs.getDate("dtEmi")),
                            formato_data.format(rs.getDate("dtVcto")),
                            rs.getString("documento"),
                            rs.getString("classif"),
                            rs.getString("Descr"),
                            df.format(rs.getDouble("Valor")),
                            AprFormatada,
                            rs.getString("statusMov"),
                            rs.getString("Prev"),
                            df.format(sa),});
                    }
                    //Parâmetros Coluna da jTable, Tamanho da Fonte, se é data (true ou false).
                    jTablePesquisa.getColumnModel().getColumn(11).setCellRenderer(new CustomTableCellRenderer(11, 11, false));
                    jTablePesquisa.getColumnModel().getColumn(15).setCellRenderer(new CustomTableCellRenderer(15, 11, false));
                }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(VConsClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonPImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPImprimirActionPerformed
        String nomeCli = tfNoCli.getText();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        Date date = new Date();
        String infDt = dateFormat.format(date);
        MessageFormat cabecalho = new MessageFormat("Consulta - Clientes - " + nomeCli + " - " + infDt);
        MessageFormat rodape = new MessageFormat("Página {0,number,integer}");
        PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
        set.add(OrientationRequested.LANDSCAPE);
        try {
            //jTablePesquisa.print(JTable.PrintMode.FIT_WIDTH, cabecalho, rodape);
            jTablePesquisa.print(JTable.PrintMode.FIT_WIDTH, cabecalho, rodape, false, set, false);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Erro ao imprimir!!! %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jButtonPImprimirActionPerformed

    private void jButtonPLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPLimparActionPerformed
        ((DefaultTableModel) jTablePesquisa.getModel()).setRowCount(0);
        tfNrFav.setText("");
        tfFavorecidos.setText("");
        jFormattedTextFieldDataIni.setText("");
        jFormattedTextFieldDataFim.setText("");
        jTextFieldSaldoAnterior.setText("");
        jComboBoxPesq.setSelectedIndex(0);
        tfNoCli.setText("");
    }//GEN-LAST:event_jButtonPLimparActionPerformed

    private void jButtonPFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonPFecharActionPerformed
    
    private void PegaSaldoAnterior() {
        //DecimalFormat dec = new DecimalFormat("#,##0.00");
        String sql = "SELECT SUM(Valor) FROM tbmovimento WHERE dtVcto < ? AND clifor = ? AND recurso = '0022' ";
        Connection con;
        try {
            con = Conexao.faz_conexao();
            ResultSet rsoma;
            try (PreparedStatement stt = con.prepareStatement(sql)) {
                SimpleDateFormat formato_data = new SimpleDateFormat("dd/MM/yyyy");
                java.util.Date data_c = formato_data.parse(jFormattedTextFieldDataIni.getText());
                stt.setDate(1, new java.sql.Date(data_c.getTime()));
                stt.setString(2, tfNrFav.getText());
                rsoma = stt.executeQuery();
                double somaval = 0;
                while (rsoma.next()) {
                    somaval = rsoma.getDouble(1);
                }   jTextFieldSaldoAnterior.setText(String.valueOf(somaval));
            }
            rsoma.close();
            con.close();
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(VConsClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPFechar;
    private javax.swing.JButton jButtonPImprimir;
    private javax.swing.JButton jButtonPLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JComboBox<String> jComboBoxPesq;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataFim;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataIni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisa;
    private javax.swing.JTextField jTextFieldSaldoAnterior;
    private javax.swing.JTextField tfFavorecidos;
    private javax.swing.JTextField tfNoCli;
    private javax.swing.JTextField tfNrFav;
    // End of variables declaration//GEN-END:variables
    
    private static class CarregarCbx {

        @SuppressWarnings({"empty-statement", "unchecked"})
        public void CarregarCbx(String tabela, String valor, JComboBox combo) throws SQLException {
            //String sql = "Select * FROM " + tabela;
            String sql = "Select * FROM " + tabela + " WHERE codCliFor > '0999' " + " ORDER BY apelidoCliFor";
            Connection con = Conexao.faz_conexao();
            try {
                PreparedStatement stmt = con.prepareStatement(sql);
                ResultSet rs = stmt.executeQuery();
                while (rs.next()) {
                    combo.addItem(rs.getString(valor) + "-" + (rs.getString("codCliFor") + "-" + rs.getString("fkCliForGp")));
                }
                rs.close();
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(VConsClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
