package view;

import utilitarios.Conexao;
import utilitarios.CustomTableCellRendererFat;
import com.itextpdf.text.Chunk;
import dao.ItensVendasDAO;
import dao.VendasDAO;
import model.ItensVendas;
import model.Vendas;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.time.format.DateTimeParseException;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import javax.swing.JFileChooser;

/**
 *
 * @author CARLOS
 */
public class Form_HistoricoVendas extends javax.swing.JDialog {

    // Declarações no início da classe
    Conexao conexao = new Conexao();
    private VendasDAO vendasDAO;

    /**
     * Creates new form FormularioHistorico
     */
    public Form_HistoricoVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Histórico de Vendas");
        setLocationRelativeTo(parent);

        // Datas padrão: hoje e 7 dias atrás
        txtFim.setText(java.time.LocalDate.now()
                .format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        txtInicio.setText(java.time.LocalDate.now().minusDays(7)
                .format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy")));

        // Render bonito na tabela
        tabela.setDefaultRenderer(Object.class, new CustomTableCellRendererFat());

        // === DESABILITA EDIÇÃO DA TABELA PARA O DUPLO CLIQUE FUNCIONAR ===
        tabela.setDefaultEditor(Object.class, null);  // Impede edição de qualquer célula
        tabela.setCellSelectionEnabled(false);
        tabela.setRowSelectionAllowed(true);
        tabela.setColumnSelectionAllowed(false);
        // =============================================
    }

    public Form_HistoricoVendas() {
        this(null, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtInicio = new javax.swing.JFormattedTextField();
        txtFim = new javax.swing.JFormattedTextField();
        btnPesquisarVenda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnGerarRelatorio = new javax.swing.JButton();
        btnApurarLucro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Histórico de Vendas");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Histórico de Vendas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta por data"));

        jLabel2.setText("Data Inicial");

        jLabel3.setText("Data Final");

        try {
            txtInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/20##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/20##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnPesquisarVenda.setText("Pesquisar");
        btnPesquisarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtFim, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btnPesquisarVenda)
                .addGap(61, 61, 61))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtFim, txtInicio});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarVenda))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cliente", "Data da Venda", "Total da Venda", "Total Acumulado", "Observações"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        btnGerarRelatorio.setText("Gerar Relatório  de Faturamento");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        btnApurarLucro.setText("Apurar Lucro no Período");
        btnApurarLucro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApurarLucroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnApurarLucro)
                .addGap(54, 54, 54)
                .addComponent(btnGerarRelatorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGerarRelatorio)
                    .addComponent(btnApurarLucro)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarVendaActionPerformed
        try {
            LocalDate inicio = LocalDate.parse(txtInicio.getText().trim(),
                    DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            LocalDate fim = LocalDate.parse(txtFim.getText().trim(),
                    DateTimeFormatter.ofPattern("dd/MM/yyyy"));

            List<Vendas> lista = new VendasDAO().historicoVendas(inicio, fim);

            DefaultTableModel model = (DefaultTableModel) tabela.getModel();
            model.setRowCount(0);

            NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.of("pt", "BR"));
            double acumulado = 0.0;

            for (Vendas v : lista) {
                acumulado += v.getTotal_venda();

                // Formata a data do Timestamp
                String dataFormatada = v.getData_venda() != null
                        ? v.getData_venda().toLocalDateTime()
                                .format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")) : "";

                model.addRow(new Object[]{
                    v.getId(),
                    v.getClientes() != null ? v.getClientes().getNomeCliFor() : "AVULSO",
                    dataFormatada,
                    nf.format(v.getTotal_venda()),
                    nf.format(acumulado),
                    v.getObservacoes() != null ? v.getObservacoes() : ""
                });
            }

            tabela.setDefaultRenderer(Object.class, new CustomTableCellRendererFat());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnPesquisarVendaActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        if (evt.getClickCount() == 2) { // duplo clique
            int row = tabela.getSelectedRow();
            if (row != -1) { // verifica se tem linha selecionada
                int idVenda = (int) tabela.getValueAt(row, 0);
                new Form_DetalheVenda(this, true, idVenda).setVisible(true);
            }
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
        try {
            LocalDate inicio = LocalDate.parse(txtInicio.getText().trim(),
                    DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            LocalDate fim = LocalDate.parse(txtFim.getText().trim(),
                    DateTimeFormatter.ofPattern("dd/MM/yyyy"));

            List<Vendas> lista = new VendasDAO().historicoVendas(inicio, fim);

            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nenhuma venda encontrada no período!");
                return;
            }

            gerarPDFVendas(lista, inicio, fim);

            JOptionPane.showMessageDialog(this, "Relatório gerado com sucesso na Área de Trabalho!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao gerar relatório: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGerarRelatorioActionPerformed

    private void btnApurarLucroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApurarLucroActionPerformed
        try {
            LocalDate inicio = LocalDate.parse(txtInicio.getText().trim(),
                    DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            LocalDate fim = LocalDate.parse(txtFim.getText().trim(),
                    DateTimeFormatter.ofPattern("dd/MM/yyyy"));

            try (Connection con = Conexao.faz_conexao()) {
                String sql = """
                SELECT 
                    DATE(v.data_venda) AS data,
                    SUM(iv.subtotal) AS faturado,
                    SUM(p.precoMedioCusto * iv.qtd) AS custo,
                    SUM(iv.subtotal - (p.precoMedioCusto * iv.qtd)) AS lucro
                FROM tb_vendas v
                INNER JOIN tb_itensvendas iv ON v.id = iv.venda_id
                INNER JOIN tb_produtos p ON iv.produto_id = p.id
                WHERE DATE(v.data_venda) BETWEEN ? AND ?
                GROUP BY DATE(v.data_venda)
                ORDER BY data
                """;

                try (PreparedStatement ps = con.prepareStatement(sql)) {
                    ps.setString(1, inicio.toString());
                    ps.setString(2, fim.toString());
                    try (ResultSet rs = ps.executeQuery()) {
                        gerarRelatorioLucro(rs, inicio, fim);
                    }
                }
            }
            JOptionPane.showMessageDialog(this, "Relatório de lucro gerado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnApurarLucroActionPerformed

    private void gerarPDFVendas(List<Vendas> lista, LocalDate inicio, LocalDate fim) throws Exception {
        String caminho = System.getProperty("user.home") + "/Desktop/Relatorio_Vendas_"
                + inicio.format(DateTimeFormatter.ofPattern("dd-MM-yyyy")) + "_a_"
                + fim.format(DateTimeFormatter.ofPattern("dd-MM-yyyy")) + ".pdf";

        Document doc = new Document();
        PdfWriter.getInstance(doc, new FileOutputStream(caminho));
        doc.open();

        // Título
        Paragraph titulo = new Paragraph("RELATÓRIO DE VENDAS",
                FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16));
        titulo.setAlignment(Element.ALIGN_CENTER);
        doc.add(titulo);

        doc.add(new Paragraph("Período: " + inicio.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))
                + " a " + fim.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))));
        doc.add(new Paragraph("Gerado em: " + LocalDateTime.now().format(
                DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"))));
        doc.add(new Paragraph(" "));

        // Tabela
        PdfPTable table = new PdfPTable(5);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{10, 30, 15, 15, 30});

        table.addCell("ID");
        table.addCell("Cliente");
        table.addCell("Data");
        table.addCell("Valor");
        table.addCell("Obs");

        NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.of("pt", "BR"));
        double total = 0;

        for (Vendas v : lista) {
            total += v.getTotal_venda();
            String data = v.getData_venda() != null
                    ? v.getData_venda().toLocalDateTime().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")) : "";

            table.addCell(String.valueOf(v.getId()));
            table.addCell(v.getClientes() != null ? v.getClientes().getNomeCliFor() : "AVULSO");
            table.addCell(data);
            table.addCell(nf.format(v.getTotal_venda()));
            table.addCell(v.getObservacoes() != null ? v.getObservacoes() : "");
        }

        // Total
        PdfPCell cellTotal = new PdfPCell(new Phrase("TOTAL GERAL: " + nf.format(total)));
        cellTotal.setColspan(5);
        cellTotal.setHorizontalAlignment(Element.ALIGN_RIGHT);
        cellTotal.setBackgroundColor(new com.itextpdf.text.BaseColor(200, 200, 255));
        table.addCell(cellTotal);

        doc.add(table);
        doc.close();

        Desktop.getDesktop().open(new File(caminho));
    }

    private void gerarRelatorioLucro(ResultSet rs, LocalDate inicio, LocalDate fim) throws Exception {
        String caminho = System.getProperty("user.home") + "/Desktop/Lucro_"
                + inicio.format(DateTimeFormatter.ofPattern("dd-MM")) + "_a_"
                + fim.format(DateTimeFormatter.ofPattern("dd-MM-yyyy")) + ".pdf";

        Document doc = new Document();
        PdfWriter.getInstance(doc, new FileOutputStream(caminho));
        doc.open();

        doc.add(new Paragraph("APURAÇÃO DE LUCRO",
                FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16)));
        doc.add(new Paragraph("Período: " + inicio.format(DateTimeFormatter.ofPattern("dd-MM-yyyy")) + " a " + fim.format(DateTimeFormatter.ofPattern("dd-MM-yyyy"))));
        doc.add(new Paragraph("Gerado em: " + LocalDateTime.now().format(
                DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"))));
        doc.add(new Paragraph(" "));

        PdfPTable table = new PdfPTable(4);
        table.setWidthPercentage(100);
        table.addCell("Data");
        table.addCell("Faturado");
        table.addCell("Custo");
        table.addCell("Lucro");

        NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.of("pt", "BR"));
        double totalFaturado = 0, totalCusto = 0, totalLucro = 0;

        while (rs.next()) {
            String data = rs.getDate("data").toLocalDate()
                    .format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            double faturado = rs.getDouble("faturado");
            double custo = rs.getDouble("custo");
            double lucro = rs.getDouble("lucro");

            totalFaturado += faturado;
            totalCusto += custo;
            totalLucro += lucro;

            table.addCell(data);
            table.addCell(nf.format(faturado));
            table.addCell(nf.format(custo));
            table.addCell(nf.format(lucro));
        }

        // Total
        table.addCell("TOTAL");
        table.addCell(nf.format(totalFaturado));
        table.addCell(nf.format(totalCusto));
        table.addCell(nf.format(totalLucro));

        doc.add(table);
        doc.close();

        Desktop.getDesktop().open(new File(caminho));
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApurarLucro;
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JButton btnPesquisarVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JFormattedTextField txtFim;
    private javax.swing.JFormattedTextField txtInicio;
    // End of variables declaration//GEN-END:variables
}
