package view;

import utilitarios.Conexao;
import classes.CustomTableCellRenderer;
import classes.ExportToExcel;
import classes.ImprimirJTable;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

public class Tela_de_Consulta_Balance extends javax.swing.JFrame {

    public Tela_de_Consulta_Balance() throws SQLException {
        initComponents();
        // Só desabilita o X, mantém a barra normal
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRegime = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldDataFim = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldDataIni = new javax.swing.JFormattedTextField();
        jRadioButtonVcto = new javax.swing.JRadioButton();
        jRadioButtonEmissao = new javax.swing.JRadioButton();
        jRadioButtonApresent = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonPImprimir = new javax.swing.JButton();
        jButtonPLimpar = new javax.swing.JButton();
        jButtonPFechar = new javax.swing.JButton();
        jButtonExportar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Data Final");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        try {
            jFormattedTextFieldDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Principal", "Grupo", "Conta", "Nome", "Total", "Acumulado"
            }
        ));
        jTablePesquisa.setSelectionBackground(new java.awt.Color(255, 255, 204));
        jTablePesquisa.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jTablePesquisa);

        jLabel3.setText("Data Inicial");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        try {
            jFormattedTextFieldDataIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        buttonGroupRegime.add(jRadioButtonVcto);
        jRadioButtonVcto.setText("Vencimento");
        jRadioButtonVcto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVctoActionPerformed(evt);
            }
        });

        buttonGroupRegime.add(jRadioButtonEmissao);
        jRadioButtonEmissao.setText("Emissão");

        buttonGroupRegime.add(jRadioButtonApresent);
        jRadioButtonApresent.setText("Apresentação");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1282, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(457, 457, 457)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(483, 483, 483)
                        .addComponent(jRadioButtonVcto)
                        .addGap(26, 26, 26)
                        .addComponent(jRadioButtonEmissao)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonApresent)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonVcto)
                    .addComponent(jRadioButtonEmissao)
                    .addComponent(jRadioButtonApresent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonPImprimir.setText("Imprimir");
        jButtonPImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonPImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPImprimirActionPerformed(evt);
            }
        });

        jButtonPLimpar.setText("Limpar");
        jButtonPLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonPLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPLimparActionPerformed(evt);
            }
        });

        jButtonPFechar.setText("Fechar");
        jButtonPFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonPFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPFecharActionPerformed(evt);
            }
        });

        jButtonExportar.setText("Exportar para Excel");
        jButtonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonPesquisar)
                .addComponent(jButtonPImprimir)
                .addComponent(jButtonPLimpar)
                .addComponent(jButtonPFechar)
                .addComponent(jButtonExportar))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CONSULTA  -  BALANÇO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPFecharActionPerformed

        try {
            TelaPrincipal exibir;
            exibir = new TelaPrincipal();
            exibir.setVisible(true);
            setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(Tela_de_Consulta_Balance.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonPFecharActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

        if (jFormattedTextFieldDataIni.getText().trim().length() == 4) {
            JOptionPane.showMessageDialog(null, "Atenção! Favor preencher o campo de data inicial.");
        } else if (jFormattedTextFieldDataFim.getText().trim().length() == 4) {
            JOptionPane.showMessageDialog(null, "Atenção! Favor preencher o campo de data final.");
        } else {

            PreparedStatement stmt = null, stmt2 = null, stmtCP = null;
            ResultSet rs = null, rs2 = null, rsCP = null;
            Connection con = null;

            try {
                SimpleDateFormat formatoEntrada = new SimpleDateFormat("dd/MM/yyyy");
                DecimalFormat df = new DecimalFormat("#,##0.00");
                DecimalFormat dp = new DecimalFormat("0.0000%");
                DecimalFormat di = new DecimalFormat("0.0000");
                DecimalFormat d = new DecimalFormat("00");

                String dataIniStr = jFormattedTextFieldDataIni.getText().trim();
                String dataFimStr = jFormattedTextFieldDataFim.getText().trim();

                // Validação básica das datas (evita ParseException inesperado)
                if (dataIniStr.length() != 10 || dataFimStr.length() != 10) {
                    JOptionPane.showMessageDialog(null, "Datas devem estar no formato dd/MM/yyyy");
                    return;
                }

                Date dataIniUtil = formatoEntrada.parse(dataIniStr);
                Date dataFimUtil = formatoEntrada.parse(dataFimStr);

                // Converte para java.sql.Date ? o mais correto para MySQL
                java.sql.Date sqlDataIni = new java.sql.Date(dataIniUtil.getTime());
                java.sql.Date sqlDataFim = new java.sql.Date(dataFimUtil.getTime());

                Double Ativo = 0.00;
                Double Passivo = 0.00;
                Double SubPassivo = 0.00;
                Double PatrLiq = 0.00;
                Double Resultado = 0.00;

                con = Conexao.faz_conexao();

                // === CONSULTA PRINCIPAL DO BALANÇO (MYSQL/MARIADB) ===
                String sql = """
                    SELECT
                        nome_P AS Princ,
                        nome_S AS Sub,
                        CASE
                            WHEN UPPER(TRIM(nome_C)) LIKE '%CONTAS À RECEBER%' THEN 'Contas à Receber'
                            WHEN UPPER(TRIM(nomebco)) = 'CONTAS À RECEBER' AND UPPER(TRIM(nome_C)) = 'BANCOS' THEN 'Contas à Receber'
                            ELSE nome_C
                        END AS Conta,
                        CASE
                            WHEN UPPER(TRIM(nomebco)) = 'CONTAS À RECEBER' THEN 'CONTAS À RECEBER'
                            WHEN UPPER(TRIM(nome_C)) LIKE '%CONTAS À RECEBER%' THEN 'CONTAS À RECEBER'
                            ELSE nomebco
                        END AS Nome,
                        CASE
                            WHEN UPPER(TRIM(nome_C)) LIKE '%CONTAS À RECEBER%' THEN '1.002.001'
                            WHEN UPPER(TRIM(nomebco)) = 'CONTAS À RECEBER' AND UPPER(TRIM(nome_C)) = 'BANCOS' THEN '1.002.001'
                            ELSE vrecurso
                        END AS vrecurso,
                        recurso,
                        SUM(Valor) AS Total
                    FROM view_movimento
                    WHERE COALESCE(Prev, '') <> 'F'
                      AND dtlancto <= ?
                      -- ALTERAÇÃO AQUI: Excluímos a lógica complexa de datas e forçamos a saída da conta
                      AND TRIM(nome_C) <> 'Contas à Pagar'
                      AND NOT (nomebco = 'CONTAS À PAGAR' AND nome_C NOT IN ('Contas à Pagar'))
                    GROUP BY
                        1, 2, 3, 4, 5, 6
                    ORDER BY
                        CAST(SUBSTRING(
                            CASE WHEN UPPER(TRIM(nome_C)) LIKE '%CONTAS À RECEBER%' THEN '1.002.001'
                                 WHEN UPPER(TRIM(nomebco)) = 'CONTAS À RECEBER' AND UPPER(TRIM(nome_C)) = 'BANCOS' THEN '1.002.001'
                                 ELSE vrecurso END, 1, 1) AS UNSIGNED),
                        CASE WHEN UPPER(TRIM(nome_C)) LIKE '%CONTAS À RECEBER%' THEN '1.002.001'
                             WHEN UPPER(TRIM(nomebco)) = 'CONTAS À RECEBER' AND UPPER(TRIM(nome_C)) = 'BANCOS' THEN '1.002.001'
                             ELSE vrecurso END
                    """;

                stmt = con.prepareStatement(sql);
                stmt.setDate(1, sqlDataFim);
                rs = stmt.executeQuery();

                DefaultTableModel modelo = (DefaultTableModel) jTablePesquisa.getModel();
                modelo.setNumRows(0);

                jTablePesquisa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(0)).setPreferredWidth(80); // Princ
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(1)).setPreferredWidth(295); // Sub
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(2)).setPreferredWidth(280); // Conta
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(3)).setPreferredWidth(405); // Nome
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(4)).setPreferredWidth(100); // Total
                jTablePesquisa.getColumn(jTablePesquisa.getColumnName(5)).setPreferredWidth(100); // Acumulado

                DefaultTableCellRenderer right = new DefaultTableCellRenderer();
                right.setHorizontalAlignment(SwingConstants.RIGHT);
                jTablePesquisa.getColumnModel().getColumn(4).setCellRenderer(right);
                jTablePesquisa.getColumnModel().getColumn(5).setCellRenderer(right);

                String prin = "a", sub = " ", cta = " ", titulo = "s";
                double totalPrincipal = 0, totalGrupo = 0, totalConta = 0, sa = 0, subPrincipal = 0.0;
                double saNoFinalDoAtivo = 0.0;
                HashMap<String, Double> contaTotais = new HashMap<>();

                while (rs.next()) {
                    String currentPrincipal = rs.getString("Princ");
                    String currentSub = rs.getString("Sub");
                    String currentConta = rs.getString("Conta");
                    double valor = rs.getDouble("Total");

                    if (titulo.equals("s")) {
                        modelo.addRow(new Object[]{"", "", "", "", "", ""});
                        modelo.addRow(new Object[]{"", " -- BALANÇO PATRIMONIAL -- ", "Realizado em - " + dataFimStr, "", 0, 0});
                        modelo.addRow(new Object[]{"", "", "", "", "", ""});
                        titulo = "n";
                    }

                    if (!cta.equals(currentConta) && !cta.equals(" ")) {
                        modelo.addRow(new Object[]{"", "", "", "TOTAL DA CONTA " + cta, df.format(totalConta), df.format(sa)});
                        modelo.addRow(new Object[]{"", "", "", "", "", ""});
                        contaTotais.put(cta.replace(" ", "_").toUpperCase(), Math.round(totalConta * 100.0) / 100.0);
                        totalConta = 0.0;
                    }

                    if (!sub.equals(currentSub)) {
                        if (!sub.equals(" ")) {
                            modelo.addRow(new Object[]{"", "", "", "TOTAL DO GRUPO " + sub, df.format(totalGrupo), df.format(sa)});
                            subPrincipal = totalGrupo;
                            modelo.addRow(new Object[]{"", "", "", "", "", ""});
                        }
                        totalGrupo = 0.0;
                    }

                    if (!prin.equals(currentPrincipal)) {
                        if (!prin.equals("a")) {
                            if (prin.equals("ATIVO")) {
                                saNoFinalDoAtivo = sa;
                                Ativo = sa;
                            }
                            modelo.addRow(new Object[]{"", "", "", "TOTAL DO " + prin, "", df.format(sa)});
                            modelo.addRow(new Object[]{"", "", "", "", "", ""});
                        }
                        totalPrincipal = 0.0;
                        subPrincipal = 0.0;
                    }

                    sa += valor;
                    totalPrincipal += valor;
                    totalGrupo += valor;
                    totalConta += valor;

                    modelo.addRow(new Object[]{
                        prin.equals(currentPrincipal) ? "" : currentPrincipal,
                        sub.equals(currentSub) ? "" : currentSub,
                        cta.equals(currentConta) ? "" : currentConta,
                        rs.getString("Nome"), df.format(valor), df.format(sa)
                    });

                    prin = currentPrincipal;
                    sub = currentSub;
                    cta = currentConta;
                }

                // Isso garante que a última conta vinda do SQL (como Empréstimos) seja totalizada
                if (!cta.equals(" ") && !cta.equals("Contas à Pagar")) {
                    modelo.addRow(new Object[]{"", "", "", "TOTAL DA CONTA " + cta, df.format(totalConta), df.format(sa)});
                    modelo.addRow(new Object[]{"", "", "", "", "", ""});

                    // Salva o total dessa última conta no HashMap (importante para as análises)
                    contaTotais.put(cta.replace(" ", "_").toUpperCase(), Math.round(totalConta * 100.0) / 100.0);

                    // Zera o totalConta para não somar lixo no próximo passo
                    totalConta = 0.0;
                }

                // === SUA CONSULTA ESPECIAL CONTAS À PAGAR ===
                String sqlCP = "SELECT COALESCE(SUM(Valor), 0) AS TotalCP FROM view_movimento WHERE recurso = '0079' AND vrecurso = '2.001.002' AND Prev <> 'F' AND dtlancto <= ? AND (dtApr IS NULL OR dtApr >= ?)";
                stmtCP = con.prepareStatement(sqlCP);
                stmtCP.setDate(1, sqlDataFim);
                stmtCP.setDate(2, sqlDataIni);
                rsCP = stmtCP.executeQuery();
                double saldoContasPagarCorreto = 0.0;

                contaTotais.put("CONTAS_À_PAGAR", saldoContasPagarCorreto);
                if (rsCP.next()) {
                    saldoContasPagarCorreto = Math.round(rsCP.getDouble("TotalCP") * 100.0) / 100.0;
                }

                // 2. ATUALIZA OS ACUMULADOS (Crucial para o balanço bater)
                sa += saldoContasPagarCorreto;
                totalGrupo += saldoContasPagarCorreto;
                totalPrincipal += saldoContasPagarCorreto;

                // 3. Adiciona a linha visual do Contas à Pagar
                //modelo.addRow(new Object[]{"", "", "", "", "", ""});
                modelo.addRow(new Object[]{
                    "",
                    "",
                    "Contas à Pagar",
                    "CONTAS À PAGAR",
                    df.format(saldoContasPagarCorreto),
                    df.format(sa)
                });

                // === MOSTRAR O TOTAL DA CONTA ===
                modelo.addRow(new Object[]{"", "", "", "TOTAL DA CONTA Contas à Pagar", df.format(saldoContasPagarCorreto), df.format(sa)});
                //modelo.addRow(new Object[]{"", "", "", "", "", ""}); // Linha em branco para separar

                // 4. Salva no HashMap para as Análises (Fleuriet/ROE/ROA)
                contaTotais.put("CONTAS_À_PAGAR", saldoContasPagarCorreto);

                // 5. FECHAMENTOS DE GRUPO (Agora com os valores somados corretamente)
                // Fechamento do Grupo (PASSIVO CIRCULANTE)
                modelo.addRow(new Object[]{"", "", "", "", "", ""});
                modelo.addRow(new Object[]{"", "", "", "TOTAL DO GRUPO " + sub, df.format(totalGrupo), df.format(sa)});
                modelo.addRow(new Object[]{"", "", "", "", "", ""});

                // Fechamento do Principal (PASSIVO)
                modelo.addRow(new Object[]{"", "", "", "SUB DO " + prin, "", df.format(sa)});
                //modelo.addRow(new Object[]{"", "", "", "", "", ""});

                // 6. Atualiza a variável global do Passivo para os cálculos de ROE/ROA
                Passivo = totalPrincipal;

                // === RECEITAS E DESPESAS ===
                String campoData = jRadioButtonVcto.isSelected() ? "dtvcto" : jRadioButtonEmissao.isSelected() ? "dtemi" : "dtapr";
                String sql2 = "SELECT SUM(CASE WHEN nome_P = 'RECEITAS' THEN Valor ELSE 0 END) AS TotalReceitas, SUM(CASE WHEN nome_P = 'DESPESAS' THEN Valor ELSE 0 END) AS TotalDespesas FROM viewmovrd WHERE " + campoData + " BETWEEN ? AND ? AND nome_P <> 'NULO' AND vRecurso NOT IN ('2.001.004')";
                stmt2 = con.prepareStatement(sql2);
                stmt2.setDate(1, sqlDataIni);
                stmt2.setDate(2, sqlDataFim);
                rs2 = stmt2.executeQuery();
                double Receitas = 0, Despesas = 0;
                if (rs2.next()) {
                    Receitas = rs2.getDouble("TotalReceitas");
                    Despesas = rs2.getDouble("TotalDespesas");
                }

                // Cálculos Finais usando suas variáveis
                Resultado = -(Receitas + Despesas);
                SubPassivo = -Ativo;
                PatrLiq = -(sa);

                // Exibição Final (PL e Resultados)
                modelo.addRow(new Object[]{"", "", "", "", "", ""});
                modelo.addRow(new Object[]{"", "PATRIMÔNIO_LÍQUIDO", "Patrimônio_Acumulado", "", df.format(PatrLiq), ""});
                modelo.addRow(new Object[]{"", "", "", "", "", ""});
                modelo.addRow(new Object[]{"", "", "", "RECEITAS NO PERÍODO", df.format(Receitas), ""});
                modelo.addRow(new Object[]{"", "", "", "DESPESAS NO PERÍODO", df.format(Despesas), ""});
                modelo.addRow(new Object[]{"", "", "", "RESULTADO DO PERÍODO", df.format(-Resultado), ""});
                modelo.addRow(new Object[]{"", "", "", "", "", ""});
                modelo.addRow(new Object[]{"", "", "", "TOTAL DO PASSIVO", "", df.format(SubPassivo)});
                modelo.addRow(new Object[]{"", "", "", "", "", ""});

                // === ANÁLISE FLEURIET (IGUAL AO MYSQL) ===
                double atCirculante = contaTotais.getOrDefault("BANCOS", 0.0)
                        + contaTotais.getOrDefault("CAIXA", 0.0)
                        + contaTotais.getOrDefault("CONTAS_À_RECEBER", 0.0)
                        + contaTotais.getOrDefault("CONTA_POUPANÇA", 0.0);

                double pasNaoCiclico = contaTotais.getOrDefault("EMPREST.DE_LONGO_PRAZO_(+_DE_1_ANO)", 0.0);

                double anCiclico = contaTotais.getOrDefault("IMOBILIZADO", 0.0);
                double pnCiclico = PatrLiq;
                double paErratico = contaTotais.getOrDefault("EMPR.OBTIDOS_CURTO_PRAZO", 0.0);

                // Bloco de Análises (Usando os nomes que você já tinha)
                double atCiclico = contaTotais.getOrDefault("CONTAS_À_RECEBER", 0.0);
                double atErratico = contaTotais.getOrDefault("BANCOS", 0.0) + contaTotais.getOrDefault("CAIXA", 0.0) + contaTotais.getOrDefault("CONTA_POUPANÇA", 0.0);
                double pasCiclico = contaTotais.getOrDefault("CONTAS_À_PAGAR", 0.0) + contaTotais.getOrDefault("CARTÕES_DE_CRÉDITO", 0.0);
                double passivoTotalCirculanteENaoCirculante = pasCiclico;
                double passivoTotal = pasCiclico + pasNaoCiclico;

                double CDG = -PatrLiq - contaTotais.getOrDefault("IMOBILIZADO", 0.0);
                double NCG = atCiclico + pasCiclico;
                double ST = atErratico;

                String sinalCDG = CDG >= 0 ? "+" : "-";
                String sinalNCG = NCG >= 0 ? "+" : "-";
                String sinalST = ST >= 0 ? "+" : "-";
                String situacaoFinanceira = getSituacaoFinanceira(sinalCDG, sinalNCG, sinalST);

                String roe = PatrLiq != 0 ? dp.format(-Resultado / -PatrLiq) : "N/A";
                String roa = (sa - SubPassivo + PatrLiq) != 0 ? dp.format(-Resultado / (-(sa - SubPassivo + PatrLiq))) : "N/A";
                String consumo = Receitas != 0 ? dp.format(-Despesas / Receitas) : "N/A";
                String pct = SubPassivo != 0 ? dp.format(-passivoTotalCirculanteENaoCirculante / Ativo) : "N/A";
                String liquidez = (-pasCiclico - paErratico) != 0 ? di.format((atCiclico + atErratico) / (-pasCiclico - paErratico)) : "N/A";
                String cobertura = Despesas != 0 ? di.format((atErratico + atCiclico) / -Despesas) + " meses" : "N/A";
                String coberturaDias = Despesas != 0 ? d.format(((atErratico + atCiclico) / -Despesas) * 30) + " dias" : "N/A";
                String endividamento = SubPassivo != 0 ? di.format(pasCiclico / SubPassivo) : "N/A";
                String poupanca = Receitas != 0 ? dp.format(-Resultado / Receitas) : "N/A";

                modelo.addRow(new Object[]{"", " A N Á L I S E S ", "", "", "", ""});
                modelo.addRow(new Object[]{"", " ========== ", "", "", "", ""});
                modelo.addRow(new Object[]{"", "ROE(Return on Common Equity)", "RETORNO SOBRE CAPITAL PRÓPRIO", "Resultado(Lucro ou Prejuízo)/Patrimônio Liq.", "", dp.format((Resultado / PatrLiq))});
                modelo.addRow(new Object[]{"", "ROA(Rentab.Op.do Ativo ou TIR))", "RETORNO SOBRE O ATIVO", "Resultado/Ativo Total", "", dp.format((Resultado / (SubPassivo + subPrincipal)))});
                modelo.addRow(new Object[]{"", "CONSUMO SOBRE A RECEITA", "TAXA DE CONSUMO", "Despesas/Receitas", "", consumo});
                modelo.addRow(new Object[]{"", "USO DO CAPITAL DE TERCEIROS", "PCT-PARTICIPAÇÃO DO CAPITAL DE TERCEIROS", "Passivo Circulante e não Circulante/Passivo Total", "", pct});
                modelo.addRow(new Object[]{"", "", "", "", "", ""});
                modelo.addRow(new Object[]{"", "ATIVO E PASSIVO CÍCLICO", "AC - ATIVO CÍCLICO", "Ctas.à Receber + Empréstimos C.Prazo", "", df.format(atCiclico)});
                modelo.addRow(new Object[]{"", "", "PC - PASSIVO CÍCLICO", "Ctas.à Pagar + Cartões + Fornecedores", "", df.format(-pasCiclico)});
                modelo.addRow(new Object[]{"", "", "", "", "", ""});
                modelo.addRow(new Object[]{"", "ATIVO E PASSIVO NÃO CÍCLICOS", "ANC - ATIVO NÃO CÍCLICO", "Realiz. Longo Prazo + Imobilizado", "", df.format(anCiclico)});
                modelo.addRow(new Object[]{"", "", "PNC - PASSIVO NÃO CÍCLICO", "Financ.Longo Prazo + Capital Social", "", df.format(-pnCiclico)});
                modelo.addRow(new Object[]{"", "", "", "", "", ""});
                modelo.addRow(new Object[]{"", "ATIVO E PASSIVO ERRÁTICOS", "AE - ATIVO ERRÁTICO", "Caixa + Equiv. de caixa", "", df.format(atErratico)});
                modelo.addRow(new Object[]{"", "", "PE - PASSIVO ERRÁTICO", "Outros Financiamentos de Curto Prazo", "", df.format(-paErratico)});
                modelo.addRow(new Object[]{"", "", "", "", "", ""});
                modelo.addRow(new Object[]{"", "ANÁLISE FINANCEIRA (Fleuriet)", "CDG", "PNC - ANC", "", df.format(CDG)});
                modelo.addRow(new Object[]{"", "", "NCG", "AC - PC", "", df.format(NCG)});
                modelo.addRow(new Object[]{"", "", "ST -Situação de Tesouraria", "AE - PE", "", df.format(atErratico + paErratico)});
                modelo.addRow(new Object[]{"", "", "Situação Financeira", sinalCDG + " " + sinalNCG + " " + sinalST, "", situacaoFinanceira});
                modelo.addRow(new Object[]{"", "", "", "", "", ""});
                modelo.addRow(new Object[]{"", "Í N D I C E S", "", "", "", ""});
                modelo.addRow(new Object[]{"", "------------------", "", "", "", ""});
                modelo.addRow(new Object[]{"", "ÍNDICE DE LIQUIDEZ", "Ideal > 1", "Ativo C.Prazo/Passivo C.Prazo", liquidez, ""});
                modelo.addRow(new Object[]{"", "ÍNDICE DE COBERTURA DESPESAS", "Ideal > 6", "Ativo C.Prazo/Despesas Mensais", cobertura, coberturaDias});
                modelo.addRow(new Object[]{"", "ÍNDICE DE ENDIVIDAMENTO", "Ideal próximo a 0", "Passivo Exigível/Ativo Total", di.format(-pasCiclico / -(SubPassivo + subPrincipal)), ""});
                modelo.addRow(new Object[]{"", "ÍNDICE DE POUPANÇA", "Ideal > 10%", "Resultado Disponível p/Investir/Receitas", poupanca, ""});
                modelo.addRow(new Object[]{"", "", "", "", "", ""});
                modelo.addRow(new Object[]{"", "PLANEJAMENTO FINANCEIRO", "", "", "", " %Atingido "});
                modelo.addRow(new Object[]{"", "-----------------------------------------", "", "", "", "-------------"});
                modelo.addRow(new Object[]{"", "PMS", "Patrimônio Mínimo de Sobrevivência", "6 x Valor Desp.Mensais", df.format(-Despesas * 6), Despesas != 0 ? dp.format(atCirculante / (-Despesas * 6)) : "N/A"});
                modelo.addRow(new Object[]{"", "PMR", "Patrimônio Mínimo Recomendado", "20 x Valor Desp.Mensais", df.format(-Despesas * 20), Despesas != 0 ? dp.format(atCirculante / (-Despesas * 20)) : "N/A"});
                modelo.addRow(new Object[]{"", "PI", "Patrimônio Ideal", "12 x Vr.Desp.Mensais x 10% x Idade", df.format((-Despesas * 12 * 0.1 * 60)), Despesas != 0 ? dp.format(atCirculante / ((-Despesas * 12 * 0.1) * 60)) : "N/A"});
                modelo.addRow(new Object[]{"", "PNIF", "Patrim.Nec.p/Indep.Financeira", "12 x Desp.Mensais / Menor % Rentabilidade a.a.", df.format(-Despesas * 12 / 0.06), Despesas != 0 ? dp.format(atCirculante / (-Despesas * 12 / 0.06)) : "N/A"});

                // Renderização
                jTablePesquisa.getColumnModel().getColumn(0).setCellRenderer(new CustomTableCellRenderer(0, 16, false));
                jTablePesquisa.getColumnModel().getColumn(1).setCellRenderer(new CustomTableCellRenderer(1, 14, false));
                jTablePesquisa.getColumnModel().getColumn(2).setCellRenderer(new CustomTableCellRenderer(2, 12, false));
                jTablePesquisa.getColumnModel().getColumn(3).setCellRenderer(new CustomTableCellRenderer(3, 10, false));
                jTablePesquisa.getColumnModel().getColumn(4).setCellRenderer(new CustomTableCellRenderer(4, 11, false));
                jTablePesquisa.getColumnModel().getColumn(5).setCellRenderer(new CustomTableCellRenderer(5, 11, false));
                jTablePesquisa.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                    @Override
                    public void mouseMoved(java.awt.event.MouseEvent e) {
                        int row = jTablePesquisa.rowAtPoint(e.getPoint());
                        int col = jTablePesquisa.columnAtPoint(e.getPoint());
                        if (row > -1 && col > -1) {
                            Object value = jTablePesquisa.getValueAt(row, col);
                            if (value != null && !value.toString().isEmpty()) {
                                jTablePesquisa.setToolTipText(value.toString());
                            }
                        }
                    }
                });

                // === QUADRO DE DIAGNÓSTICO E CONSULTORIA FINANCEIRA ===
                modelo.addRow(new Object[]{"", "", "", "", "", ""});
                modelo.addRow(new Object[]{"", " D I A G N Ó S T I C O   D O   S I S T E M A ", "", "", "", ""});
                modelo.addRow(new Object[]{"", "-----------------------------------------", "", "", "", ""});
                modelo.addRow(new Object[]{"", "", "--- Análise Consultiva ---", "", "", ""});

                // 1. Diagnóstico de Liquidez (já está bom, só ajustei ordem das colunas para ficar consistente)
                double liqValor = 0; // ? substitua pelo cálculo real
                String labelLiq = "";
                String descLiq = "";
                if (liqValor > 1.5) {
                    labelLiq = "EXCELENTE:";
                    descLiq = "Você tem forte folga financeira para honrar compromissos.";
                } else if (liqValor >= 1.0) {
                    labelLiq = "BOM:";
                    descLiq = "Seus recursos cobrem suas dívidas, mas sem grande margem.";
                } else {
                    labelLiq = "CRÍTICO:";
                    descLiq = "Você pode precisar de crédito para pagar contas imediatas.";
                }
                modelo.addRow(new Object[]{"", "SAÚDE FINANCEIRA:", labelLiq, descLiq, "", ""});

                // 2. Diagnóstico de Capital de Giro (Fleuriet) ? agora separado
                String labelCG = "";
                String descCG = "";
                if (CDG >= 0 && ST >= 0) {
                    labelCG = "ESTRATÉGIA:";
                    descCG = "Posição sólida. Momento ideal para investimentos ou novos aportes.";
                } else if (ST < 0) {
                    labelCG = "ATENÇÃO:";
                    descCG = "Sua tesouraria está negativa. Cuidado com juros de cheque especial/cartão.";
                } else {
                    labelCG = "REVISÃO:";
                    descCG = "Verifique se seus prazos de pagamento estão muito curtos em relação aos recebimentos.";
                }
                modelo.addRow(new Object[]{"", "CAPITAL DE GIRO:", labelCG, descCG, "", ""});

                // 3. Diagnóstico de Poupança (Rentabilidade)
                double poupValor = 0;
                try {
                    poupValor = Double.parseDouble(poupanca.replace("%", "").replace(",", "."));
                } catch (Exception e) {
                    // já está vazio, continua com 0
                }
                String labelPoup = "";
                String descPoup = "";
                if (poupValor > 20) {
                    labelPoup = "ALTA PERFORMANCE:";
                    descPoup = "Você retém uma excelente fatia da sua receita.";
                } else if (poupValor >= 10) {
                    labelPoup = "DENTRO DA META:";
                    descPoup = "Sua taxa de poupança está saudável (acima de 10%).";
                } else {
                    labelPoup = "RISCO:";
                    descPoup = "Margem de sobra muito baixa. Qualquer imprevisto pode gerar endividamento.";
                }
                modelo.addRow(new Object[]{"", "CAPACIDADE DE ACÚMULO:", labelPoup, descPoup, "", ""});

                // 4. Dica de Gestão (Baseado no Endividamento)
                // Aqui tem só duas situações, então fica mais simples
                double endivValor = 0;
                try {
                    endivValor = Double.parseDouble(endividamento.replace(",", "."));
                } catch (Exception e) {
                    // continua 0
                }
                String labelDica = (endivValor < 0.3) ? "OPORTUNIDADE:" : "PRIORIDADE:";
                String descDica = (endivValor < 0.3)
                        ? "Baixo endividamento. Tem espaço para alavancar projetos com capital de terceiros."
                        : "Foque na redução de custos fixos e quitação de dívidas de curto prazo.";

                modelo.addRow(new Object[]{"", "DICA DO CONSULTOR:", labelDica, descDica, "", ""});

                // Linha separadora (pode manter ou usar borda na tabela)
                modelo.addRow(new Object[]{"", "-----------------------------------------", "", "", "", ""});

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
                ex.printStackTrace();
            } finally {
                try {
                    if (rs != null) {
                        rs.close();
                    }
                } catch (Exception e) {
                }
                try {
                    if (stmt != null) {
                        stmt.close();
                    }
                } catch (Exception e) {
                }
                try {
                    if (rs2 != null) {
                        rs2.close();
                    }
                } catch (Exception e) {
                }
                try {
                    if (stmt2 != null) {
                        stmt2.close();
                    }
                } catch (Exception e) {
                }
                try {
                    if (con != null) {
                        con.close();
                    }
                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    // === MÉTODO AUXILIAR ===
    private String getSituacaoFinanceira(String cdg, String ncg, String st) {
        if (cdg.equals("+") && ncg.equals("-") && st.equals("+")) {
            return "Excelente";
        }
        if (cdg.equals("+") && ncg.equals("+") && st.equals("+")) {
            return "Sólida";
        }
        if (cdg.equals("+") && ncg.equals("+") && st.equals("-")) {
            return "Insatisfatória";
        }
        if (cdg.equals("-") && ncg.equals("+") && st.equals("-")) {
            return "Péssima";
        }
        if (cdg.equals("-") && ncg.equals("-") && st.equals("-")) {
            return "Muito Ruim";
        }
        if (cdg.equals("-") && ncg.equals("-") && st.equals("+")) {
            return "Alto Risco";
        }
        return "Não Classificada";
    }

    private void jButtonPLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPLimparActionPerformed
        ((DefaultTableModel) jTablePesquisa.getModel()).setRowCount(0);
        jFormattedTextFieldDataIni.setText("");
        jFormattedTextFieldDataFim.setText("");
    }//GEN-LAST:event_jButtonPLimparActionPerformed

    private void jButtonPImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPImprimirActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy_HH-mm");
        Date date = new Date();
        String infDt = dateFormat.format(date);
        
        // Pegar as datas dos campos
        String dataInicial = jFormattedTextFieldDataIni.getText();
        String dataFinal = jFormattedTextFieldDataFim.getText();

        // Título padrão para o arquivo
        String tituloPadrao = "Balanço Patrimonial";

         // Cabeçalho com as datas do período
        MessageFormat cabecalho = new MessageFormat(
                tituloPadrao + " - Período: " + dataInicial + " a " + dataFinal
        );

        MessageFormat rodape = new MessageFormat("Página {0,number,integer}" + " - Impressão: " + infDt
        );
        
        // Formatando o cabeçalho com o título padrão e a data/hora
        //MessageFormat cabecalho = new MessageFormat(tituloPadrao + " - " + infDt);
        //MessageFormat rodape = new MessageFormat("Página {0,number,integer}");

        PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
        set.add(OrientationRequested.LANDSCAPE);

        try {
            jTablePesquisa.print(JTable.PrintMode.FIT_WIDTH, cabecalho, rodape, false, set, false);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Erro ao imprimir!!! %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jButtonPImprimirActionPerformed

    private void jButtonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Salvar como...");
        int userSelection = fileChooser.showSaveDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String path = fileChooser.getSelectedFile().getAbsolutePath();
            if (!path.endsWith(".xlsx")) {
                path += ".xlsx";
            }
            try {
                ExportToExcel exporter = new ExportToExcel();
                exporter.exportTable(jTablePesquisa, path);
                JOptionPane.showMessageDialog(null, "Arquivo Excel " + path + " foi gerado com sucesso!");
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao exportar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonExportarActionPerformed

    private void jRadioButtonVctoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVctoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonVctoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Consulta_Balance.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Consulta_Balance.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Consulta_Balance.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_de_Consulta_Balance.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Tela_de_Consulta_Balance().setVisible(true);

                } catch (SQLException ex) {
                    Logger.getLogger(Tela_de_Consulta_Balance.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupRegime;
    private javax.swing.JButton jButtonExportar;
    private javax.swing.JButton jButtonPFechar;
    private javax.swing.JButton jButtonPImprimir;
    private javax.swing.JButton jButtonPLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataFim;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataIni;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonApresent;
    private javax.swing.JRadioButton jRadioButtonEmissao;
    private javax.swing.JRadioButton jRadioButtonVcto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisa;
    // End of variables declaration//GEN-END:variables
}
