package view;

import utilitarios.Conexao;
import dao.CliForDAO;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JComboBox;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.TableRowSorter;
import model.CliFor;
import model.Placon;
import relatorios.RelCliFor;
import utilitarios.LimpaTela;

public class Tela_de_CliFor extends javax.swing.JFrame {

    private final CliForDAO dao = new CliForDAO();
    private String editingCodCliFor = null;

    public Tela_de_CliFor() {
        initComponents();
        setTitle("Cadastro de Clientes/Fornecedores");
        carregarComboGrupoPrincipal();
        configurarTabela();
        adicionarListeners();
        listar();
    }

    private void configurarTabela() {
        tbDadosCliFor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbDadosCliFor.getColumnModel().getColumn(0).setPreferredWidth(50);   // cod
        tbDadosCliFor.getColumnModel().getColumn(1).setPreferredWidth(50);   // tipo
        tbDadosCliFor.getColumnModel().getColumn(2).setPreferredWidth(300);  // nome
        tbDadosCliFor.getColumnModel().getColumn(3).setPreferredWidth(200);  // apelido
        tbDadosCliFor.getColumnModel().getColumn(4).setPreferredWidth(180);  // email
        tbDadosCliFor.getColumnModel().getColumn(5).setPreferredWidth(120);  // celular
        tbDadosCliFor.getColumnModel().getColumn(12).setPreferredWidth(150); // cidade
        tbDadosCliFor.getColumnModel().getColumn(18).setPreferredWidth(100); // grupo

        // Ocultar colunas
        int[] colunasOcultas = {4, 6, 7, 8, 9, 10, 11, 14, 15, 17};
        for (int col : colunasOcultas) {
            tbDadosCliFor.getColumnModel().getColumn(col).setMinWidth(0);
            tbDadosCliFor.getColumnModel().getColumn(col).setMaxWidth(0);
            tbDadosCliFor.getColumnModel().getColumn(col).setWidth(0);
        }

        tbDadosCliFor.setRowSorter(new TableRowSorter<>(tbDadosCliFor.getModel()));
    }

    private void carregarComboGrupoPrincipal() {
        try {
            new CarregarCbx().CarregarCbx("gpprincipal", "nome_C", cbxConta);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar grupos: " + ex.getMessage());
        }
    }

    private void adicionarListeners() {
        // Sugere código automático ao mudar tipo (só quando Não está editando)
        jCbxTipo.addItemListener(e -> {
            if (e.getStateChange() == 1 && editingCodCliFor == null) {
                String tipo = (String) jCbxTipo.getSelectedItem();
                String novoCod = tipo.equals("CLI") ? dao.suggestClienteCode() : dao.suggestFornecedorCode();
                tfCodCliFor.setText(novoCod);
            }
        });

        // Preenche campos ao clicar na tabela
        tbDadosCliFor.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (!e.getValueIsAdjusting() && tbDadosCliFor.getSelectedRow() != -1) {
                int row = tbDadosCliFor.getSelectedRow();
                tfCodCliFor.setText(getValue(row, 0));
                jCbxTipo.setSelectedItem(getValue(row, 1));
                tfNomeCliFor.setText(getValue(row, 2));
                tfNomeFant.setText(getValue(row, 3));
                txtEmail.setText(getValue(row, 4));
                txtCelular.setText(getValue(row, 5));
                txtTelefone.setText(getValue(row, 6));
                txtCep.setText(getValue(row, 7));
                txtEndereco.setText(getValue(row, 8));
                txtNumero.setText(getValue(row, 9));
                txtComplemento.setText(getValue(row, 10));
                txtBairro.setText(getValue(row, 11));
                txtCidade.setText(getValue(row, 12));
                cbUF.setSelectedItem(getValue(row, 13));
                txtRG.setText(getValue(row, 14));
                txtCpf.setText(getValue(row, 15));
                tfContato.setText(getValue(row, 16));
                tfObs.setText(getValue(row, 17));
                tfConta.setText(getValue(row, 18));

                editingCodCliFor = tfCodCliFor.getText();
                btSalvar.setEnabled(false);
            }
        });
    }

    private String getValue(int row, int col) {
        Object val = tbDadosCliFor.getValueAt(row, col);
        return val == null ? "" : val.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelCadFav = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfCodCliFor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jCbxTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tfNomeCliFor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfNomeFant = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfContato = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfObs = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxConta = new javax.swing.JComboBox<>();
        tfConta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        cbUF = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txtRG = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDadosCliFor = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btAbrir = new javax.swing.JButton();
        tfBusca = new javax.swing.JTextField();
        btnListarDados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("       Cadastro de Clientes e Fornecedores");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        btSalvar.setText("Salvar");
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonImprimir)
                .addGap(18, 18, 18)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btSalvar, btnAtualizar, btnExcluir, btnFechar, jButtonImprimir});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnExcluir)
                    .addComponent(btnFechar)
                    .addComponent(jButtonImprimir))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE FAVORECIDOS");

        jLabel2.setText("Cod");

        jLabel11.setText("Tipo");

        jCbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "CLI", "FOR", "BCO", "CAR", "PER" }));

        jLabel3.setText("Nome");

        jLabel5.setText("Nome Fantasia");

        jLabel6.setText("Contato");

        jLabel7.setText("Observação:");

        jLabel4.setText("Vinculo");

        cbxConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbxConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxContaActionPerformed(evt);
            }
        });

        tfConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContaActionPerformed(evt);
            }
        });

        jLabel8.setText("E-mail:");

        jLabel9.setText("Celular:");

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)# ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setText("Telefone:");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setText("CEP");

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel13.setText("Endereço:");

        jLabel14.setText("Número:");

        jLabel15.setText("Bairro :");

        jLabel16.setText("Complemento:");

        jLabel17.setText("Cidade:");

        cbUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel18.setText("RG/IE :");

        jLabel19.setText("CPF/CNPJ :");

        jLabel20.setText("UF:");

        javax.swing.GroupLayout jPanelCadFavLayout = new javax.swing.GroupLayout(jPanelCadFav);
        jPanelCadFav.setLayout(jPanelCadFavLayout);
        jPanelCadFavLayout.setHorizontalGroup(
            jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadFavLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadFavLayout.createSequentialGroup()
                        .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addComponent(jLabel8)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadFavLayout.createSequentialGroup()
                                .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNomeCliFor, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCodCliFor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCadFavLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanelCadFavLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)))
                                .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCadFavLayout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jCbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelCadFavLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelCadFavLayout.createSequentialGroup()
                                                .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel10)
                                                .addGap(45, 45, 45)
                                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(tfNomeFant, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanelCadFavLayout.createSequentialGroup()
                                .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtRG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                        .addComponent(txtBairro, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(134, 134, 134)
                                .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanelCadFavLayout.createSequentialGroup()
                                        .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanelCadFavLayout.createSequentialGroup()
                                                .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(jPanelCadFavLayout.createSequentialGroup()
                                                        .addComponent(jLabel19)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanelCadFavLayout.createSequentialGroup()
                                                        .addComponent(jLabel16)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtCidade))
                                            .addGroup(jPanelCadFavLayout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(34, 34, 34)
                                                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanelCadFavLayout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanelCadFavLayout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanelCadFavLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfConta, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfObs, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(tfContato, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxConta, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel18))
                .addGap(129, 130, Short.MAX_VALUE))
        );
        jPanelCadFavLayout.setVerticalGroup(
            jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadFavLayout.createSequentialGroup()
                .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodCliFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jCbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeCliFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(tfNomeFant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadFavLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanelCadFavLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20))
                            .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16)
                                .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelCadFavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelCadFavLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbUF, cbxConta, jCbxTipo, tfCodCliFor, tfConta, tfContato, tfNomeCliFor, tfNomeFant, tfObs, txtBairro, txtCelular, txtCep, txtCidade, txtComplemento, txtCpf, txtEmail, txtEndereco, txtNumero, txtRG, txtTelefone});

        tbDadosCliFor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Tipo", "Razão Social", "Nome Fantasia", "E-mail", "Celular", "Telefone", "CEP", "Endereço", "Numero", "Bairro", "Complemento", "Cidade", "UF", "RG/IE", "CPF/CNPJ", "Contato", "Observação", "Vinculo"
            }
        ));
        tbDadosCliFor.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tbDadosCliFor.setSelectionForeground(new java.awt.Color(255, 255, 0));
        jScrollPane1.setViewportView(tbDadosCliFor);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Abrir Dados"));

        btAbrir.setText("Abrir");
        btAbrir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirActionPerformed(evt);
            }
        });

        btnListarDados.setText("Listar Dados");
        btnListarDados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btAbrir)
                .addComponent(tfBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnListarDados))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCadFav, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCadFav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (tfCodCliFor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Código obrigatório!");
            return;
        }

        CliFor c = montarObjeto();
        Placon gp = buscarGrupoPrincipal(tfConta.getText().trim());
        if (gp == null && !tfConta.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Grupo Principal inválido!");
            return;
        }
        c.setFkCliForGp(gp);

        try {
            dao.salvar(c);
            JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
            limparCampos();
            listar();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar: " + ex.getMessage());
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirActionPerformed
        String cod = tfBusca.getText().trim();
        if (cod.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um código para buscar.");
            return;
        }
        try {
            CliFor c = dao.buscarPorCodigo(cod);
            if (c != null) {
                preencherCampos(c);
                editingCodCliFor = c.getCodCliFor();
                btSalvar.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "Registro não encontrado!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro na busca: " + ex.getMessage());
        }
    }//GEN-LAST:event_btAbrirActionPerformed

    @SuppressWarnings("unchecked")
    private void btnListarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarDadosActionPerformed
        listar();
    }//GEN-LAST:event_btnListarDadosActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        if (editingCodCliFor == null) {
            JOptionPane.showMessageDialog(this, "Selecione um registro para editar.");
            return;
        }

        CliFor c = montarObjeto();
        c.setCodCliFor(editingCodCliFor);
        Placon gp = buscarGrupoPrincipal(tfConta.getText().trim());
        if (gp == null && !tfConta.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Grupo Principal inválido!");
            return;
        }
        c.setFkCliForGp(gp);

        try {
            dao.atualizar(c);
            JOptionPane.showMessageDialog(this, "Atualizado com sucesso!");
            limparCampos();
            listar();
            editingCodCliFor = null;
            btSalvar.setEnabled(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (editingCodCliFor == null) {
            JOptionPane.showMessageDialog(this, "Selecione um registro para excluir.");
            return;
        }

        int resp = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            try {
                dao.excluir(editingCodCliFor);
                JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
                limparCampos();
                listar();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        try {
            TelaPrincipal exibir;
            exibir = new TelaPrincipal();
            exibir.setVisible(true);
            setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(Tela_de_CliFor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFecharActionPerformed

    private void cbxContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxContaActionPerformed
        if (cbxConta.getSelectedItem() != null) {
            String item = cbxConta.getSelectedItem().toString();
            if (item.length() > 9) {
                tfConta.setText(item.substring(item.length() - 9));
            }
        }
    }//GEN-LAST:event_cbxContaActionPerformed

    private void tfContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContaActionPerformed

    // ===================== MÉTODOS AUXILIARES =====================
    private CliFor montarObjeto() {
        CliFor c = new CliFor();
        c.setCodCliFor(tfCodCliFor.getText().trim());
        c.setTipo((String) jCbxTipo.getSelectedItem());
        c.setNomeCliFor(tfNomeCliFor.getText().trim());
        c.setApelidoCliFor(tfNomeFant.getText().trim().isEmpty() ? null : tfNomeFant.getText().trim());
        c.setEmail(txtEmail.getText().trim().isEmpty() ? null : txtEmail.getText().trim());
        c.setCelular(txtCelular.getText().trim().isEmpty() ? null : txtCelular.getText().trim());
        c.setTelefone(txtTelefone.getText().trim().isEmpty() ? null : txtTelefone.getText().trim());
        c.setCep(txtCep.getText().trim().isEmpty() ? null : txtCep.getText().trim());
        c.setEndereco(txtEndereco.getText().trim().isEmpty() ? null : txtEndereco.getText().trim());
        c.setNumero(txtNumero.getText().trim().isEmpty() ? 0 : Integer.parseInt(txtNumero.getText().trim()));
        c.setComplemento(txtComplemento.getText().trim().isEmpty() ? null : txtComplemento.getText().trim());
        c.setBairro(txtBairro.getText().trim().isEmpty() ? null : txtBairro.getText().trim());
        c.setCidade(txtCidade.getText().trim().isEmpty() ? null : txtCidade.getText().trim());
        c.setEstado(cbUF.getSelectedItem() != null ? cbUF.getSelectedItem().toString() : null);
        c.setRg(txtRG.getText().trim().isEmpty() ? null : txtRG.getText().trim());
        c.setCpf(txtCpf.getText().trim().isEmpty() ? null : txtCpf.getText().trim());
        c.setContatoCliFor(tfContato.getText().trim().isEmpty() ? null : tfContato.getText().trim());
        c.setObs(tfObs.getText().trim().isEmpty() ? null : tfObs.getText().trim());
        return c;
    }

    private void preencherCampos(CliFor c) {
        tfCodCliFor.setText(c.getCodCliFor() != null ? c.getCodCliFor() : "");
        jCbxTipo.setSelectedItem(c.getTipo() != null ? c.getTipo() : "CLI");
        tfNomeCliFor.setText(c.getNomeCliFor() != null ? c.getNomeCliFor() : "");
        tfNomeFant.setText(c.getApelidoCliFor() != null ? c.getApelidoCliFor() : "");
        txtEmail.setText(c.getEmail() != null ? c.getEmail() : "");
        txtCelular.setText(c.getCelular() != null ? c.getCelular() : "");
        txtTelefone.setText(c.getTelefone() != null ? c.getTelefone() : "");
        txtCep.setText(c.getCep() != null ? c.getCep() : "");
        txtEndereco.setText(c.getEndereco() != null ? c.getEndereco() : "");
        txtNumero.setText(c.getNumero() > 0 ? String.valueOf(c.getNumero()) : "");
        txtComplemento.setText(c.getComplemento() != null ? c.getComplemento() : "");
        txtBairro.setText(c.getBairro() != null ? c.getBairro() : "");
        txtCidade.setText(c.getCidade() != null ? c.getCidade() : "");
        cbUF.setSelectedItem(c.getEstado() != null ? c.getEstado() : "SP");
        txtRG.setText(c.getRg() != null ? c.getRg() : "");
        txtCpf.setText(c.getCpf() != null ? c.getCpf() : "");
        tfContato.setText(c.getContatoCliFor() != null ? c.getContatoCliFor() : "");
        tfObs.setText(c.getObs() != null ? c.getObs() : "");
        tfConta.setText(c.getFkCliForGp() != null ? c.getFkCliForGp().getCod_Geral() : "");
    }

    private void limparCampos() {
        new LimpaTela().LimpaTela(jPanelCadFav);
        editingCodCliFor = null;
        btSalvar.setEnabled(true);
        tbDadosCliFor.clearSelection();
    }

    private Placon buscarGrupoPrincipal(String cod) {
        if (cod == null || cod.trim().isEmpty()) {
            return null;
        }
        try {
            return dao.buscarGrupoPrincipal(cod.trim());
        } catch (SQLException ex) {
            Logger.getLogger(Tela_de_CliFor.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }


    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
    }//GEN-LAST:event_formWindowActivated

    public void listar() {
        try {
            // 1. DESATIVA O SORTER ANTES DE MEXER NO MODEL
            tbDadosCliFor.setRowSorter(null);

            List<CliFor> lista = dao.listarTodos();
            DefaultTableModel model = (DefaultTableModel) tbDadosCliFor.getModel();
            model.setRowCount(0);

            for (CliFor c : lista) {
                model.addRow(new Object[]{
                    c.getCodCliFor(),
                    c.getTipo(),
                    c.getNomeCliFor(),
                    c.getApelidoCliFor() != null ? c.getApelidoCliFor() : "",
                    c.getEmail() != null ? c.getEmail() : "",
                    c.getCelular() != null ? c.getCelular() : "",
                    c.getTelefone() != null ? c.getTelefone() : "",
                    c.getCep() != null ? c.getCep() : "",
                    c.getEndereco() != null ? c.getEndereco() : "",
                    c.getNumero(),
                    c.getComplemento() != null ? c.getComplemento() : "",
                    c.getBairro() != null ? c.getBairro() : "",
                    c.getCidade() != null ? c.getCidade() : "",
                    c.getEstado() != null ? c.getEstado() : "",
                    c.getRg() != null ? c.getRg() : "",
                    c.getCpf() != null ? c.getCpf() : "",
                    c.getContatoCliFor() != null ? c.getContatoCliFor() : "",
                    c.getObs() != null ? c.getObs() : "",
                    c.getFkCliForGp() != null ? c.getFkCliForGp().getCod_Geral() : ""
                });
            }

            // 2. Só REATIVA O SORTER DEPOIS DE TERMINAR TUDO
            tbDadosCliFor.setRowSorter(new TableRowSorter<>(model));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar lista: " + ex.getMessage());
        }
    }

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        try {
            RelCliFor CliFor = new RelCliFor();
            JOptionPane.showMessageDialog(null, "Relatório de Favorecidos gerado com sucesso!");
            dispose();
            //new Tela_de_CliFor().setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Tela_de_CliFor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_de_CliFor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnListarDados;
    private javax.swing.JComboBox<String> cbUF;
    private javax.swing.JComboBox<String> cbxConta;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JComboBox<String> jCbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCadFav;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDadosCliFor;
    private javax.swing.JTextField tfBusca;
    private javax.swing.JTextField tfCodCliFor;
    private javax.swing.JTextField tfConta;
    private javax.swing.JTextField tfContato;
    private javax.swing.JTextField tfNomeCliFor;
    private javax.swing.JTextField tfNomeFant;
    private javax.swing.JTextField tfObs;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRG;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private static class CarregarCbx {

        @SuppressWarnings({"empty-statement", "unchecked"})
        public void CarregarCbx(String tabela, String valor, JComboBox combo) throws SQLException {
            String sql = "Select * FROM " + tabela;
            Connection con = Conexao.faz_conexao();
            try {
                PreparedStatement stmt = con.prepareStatement(sql);
                try (ResultSet rs = stmt.executeQuery()) {
                    while (rs.next()) {
                        //combo.addItem(rs.getString(valor) + "-" + (rs.getString("codCliFor") + "-" + rs.getString("fkCliForGp")));
                        combo.addItem(rs.getString(valor) + "-" + rs.getString("cod_Geral"));
                    }
                }
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(Tela_de_CliFor.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
