package view;

import utilitarios.Conexao;
import utilitarios.ImprimirJTable;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.MessageFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JFrame;
import javax.swing.JTable;
import view.TelaPrincipal;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilitarios.ExportToExcel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;

public class Tela_Consulta_Inflacao extends javax.swing.JFrame {

    Conexao conexao = new Conexao();

    /**
     * Creates new form Tela_Consulta_Inflacao
     */
    public Tela_Consulta_Inflacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldDataIni = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldDataFim = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaInflacao = new javax.swing.JTable();
        jPanelRegime = new javax.swing.JPanel();
        rbCaixa = new javax.swing.JRadioButton();
        rbCompetencia = new javax.swing.JRadioButton();
        rbVcto = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        calcularInflacaoPessoal = new javax.swing.JButton();
        jButtonPImprimir = new javax.swing.JButton();
        jButtonPLimpar = new javax.swing.JButton();
        jButtonPFechar = new javax.swing.JButton();
        jButtonGrafico = new javax.swing.JButton();
        jButtonExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("CONSULTA - INFLAÇÃO NO PERÍODO");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("   PERÍODO DE PESQUISA - de :  ");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        try {
            jFormattedTextFieldDataIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataIniActionPerformed(evt);
            }
        });

        jLabel3.setText("até");

        try {
            jFormattedTextFieldDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tabelaInflacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CATEGORIA", "GRUPO", "GASTO ANTERIOR", "GASTO ATUAL", "PESO (%)", "VARIAÇÃO (%)", "CONTRIBUIÇÃO P/ INFLAÇÃO (%)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaInflacao.setSelectionBackground(new java.awt.Color(255, 255, 204));
        tabelaInflacao.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(tabelaInflacao);

        rbCaixa.setText("Regime de Caixa");

        rbCompetencia.setText("Regime de Competência");

        rbVcto.setText("Vencimento");

        javax.swing.GroupLayout jPanelRegimeLayout = new javax.swing.GroupLayout(jPanelRegime);
        jPanelRegime.setLayout(jPanelRegimeLayout);
        jPanelRegimeLayout.setHorizontalGroup(
            jPanelRegimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbVcto)
                .addGap(35, 35, 35)
                .addComponent(rbCaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(rbCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelRegimeLayout.setVerticalGroup(
            jPanelRegimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegimeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRegimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCompetencia)
                    .addComponent(rbCaixa)
                    .addComponent(rbVcto))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(jPanelRegime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(433, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelRegime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        calcularInflacaoPessoal.setText("Pesquisar");
        calcularInflacaoPessoal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calcularInflacaoPessoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularInflacaoPessoalActionPerformed(evt);
            }
        });

        jButtonPImprimir.setText("Imprimir");
        jButtonPImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPImprimirActionPerformed(evt);
            }
        });

        jButtonPLimpar.setText("Limpar");
        jButtonPLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPLimparActionPerformed(evt);
            }
        });

        jButtonPFechar.setText("Fechar");
        jButtonPFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPFecharActionPerformed(evt);
            }
        });

        jButtonGrafico.setText("Gráfico Inflação");
        jButtonGrafico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGraficoActionPerformed(evt);
            }
        });

        jButtonExportar.setText("Exportar para Excel");
        jButtonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(calcularInflacaoPessoal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGrafico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(calcularInflacaoPessoal)
                    .addComponent(jButtonPImprimir)
                    .addComponent(jButtonPLimpar)
                    .addComponent(jButtonGrafico)
                    .addComponent(jButtonExportar)
                    .addComponent(jButtonPFechar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 634, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void calcularInflacaoPessoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularInflacaoPessoalActionPerformed
        if (jFormattedTextFieldDataIni.getText().trim().length() == 4) {
            JOptionPane.showMessageDialog(null, "Atenção! Favor preencher o campo de data inicial.");
            return;
        } else if (jFormattedTextFieldDataFim.getText().trim().length() == 4) {
            JOptionPane.showMessageDialog(null, "Atenção! Favor preencher o campo de data final.");
            return;
        }

        SimpleDateFormat formato_data = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat formatoBanco = new SimpleDateFormat("yyyy-MM-dd");

        String dataTextoi = jFormattedTextFieldDataIni.getText();
        String dataTextof = jFormattedTextFieldDataFim.getText();

        java.util.Date data_i_atual, data_f_atual;
        try {
            data_i_atual = formato_data.parse(dataTextoi);
            data_f_atual = formato_data.parse(dataTextof);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao processar datas: " + ex.getMessage());
            return;
        }

        // Calcular período anterior: MESMO PERÍODO DO ANO ANTERIOR (subtrai 1 ano)
        java.time.LocalDate dataIniAtual = data_i_atual.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        java.time.LocalDate dataFimAtual = data_f_atual.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        java.time.LocalDate dataIniAnterior = dataIniAtual.minusYears(1);
        java.time.LocalDate dataFimAnterior = dataFimAtual.minusYears(1);

        String data_i_atual_str = formatoBanco.format(data_i_atual);
        String data_f_atual_str = formatoBanco.format(data_f_atual);
        String data_i_anterior_str = formatoBanco.format(
                java.util.Date.from(dataIniAnterior.atStartOfDay(ZoneId.systemDefault()).toInstant())
        );
        String data_f_anterior_str = formatoBanco.format(
                java.util.Date.from(dataFimAnterior.atStartOfDay(ZoneId.systemDefault()).toInstant())
        );

        // Determinar campo de data
        String campoData = rbVcto.isSelected() ? "dtVcto"
                : rbCompetencia.isSelected() ? "dtEmi" : "dtApr";

        Connection con = null;
        PreparedStatement stmt = null;
        ResultSet rs = null;

        try {
            con = Conexao.faz_conexao();

            // MySQL/MariaDB: CAST(? AS DATE) + LEFT JOIN + UNION (sem FULL OUTER JOIN)
            String sql
                    = "SELECT * FROM ( "
                    + "WITH PeriodoAtual AS ( "
                    + "    SELECT nome_C, nome_S, SUM(ABS(Valor)) AS totalatual "
                    + "    FROM viewmovrd "
                    + "    WHERE " + campoData + " BETWEEN CAST(? AS DATE) AND CAST(? AS DATE) "
                    + "      AND nome_P <> 'NULO' "
                    + "      AND classif NOT IN ('3.003.005', '4.008.011') "
                    + "      AND Valor < 0 "
                    + "    GROUP BY nome_C, nome_S "
                    + "), "
                    + "PeriodoAnterior AS ( "
                    + "    SELECT nome_C, nome_S, SUM(ABS(Valor)) AS totalanterior "
                    + "    FROM viewmovrd "
                    + "    WHERE " + campoData + " BETWEEN CAST(? AS DATE) AND CAST(? AS DATE) "
                    + "      AND nome_P <> 'NULO' "
                    + "      AND classif NOT IN ('3.003.005', '4.008.011') "
                    + "      AND Valor < 0 "
                    + "    GROUP BY nome_C, nome_S "
                    + "), "
                    + "TotaisPeriodos AS ( "
                    + "    SELECT "
                    + "        (SELECT SUM(ABS(Valor)) FROM viewmovrd "
                    + "         WHERE " + campoData + " BETWEEN CAST(? AS DATE) AND CAST(? AS DATE) "
                    + "           AND nome_P <> 'NULO' "
                    + "           AND classif NOT IN ('3.003.005', '4.008.011') "
                    + "           AND Valor < 0) AS totaldespesasatual, "
                    + "        (SELECT SUM(ABS(Valor)) FROM viewmovrd "
                    + "         WHERE " + campoData + " BETWEEN CAST(? AS DATE) AND CAST(? AS DATE) "
                    + "           AND nome_P <> 'NULO' "
                    + "           AND classif NOT IN ('3.003.005', '4.008.011') "
                    + "           AND Valor < 0) AS totaldespesasanterior "
                    + ") "
                    + "SELECT "
                    + "    COALESCE(pa.nome_C, pp.nome_C) AS categoria, "
                    + "    COALESCE(pa.nome_S, pp.nome_S) AS grupo, "
                    + "    COALESCE(pp.totalanterior, 0) AS gastoanterior, "
                    + "    COALESCE(pa.totalatual, 0) AS gastoatual, "
                    + "    CASE WHEN t.totaldespesasanterior > 0 "
                    + "         THEN (COALESCE(pp.totalanterior, 0) / t.totaldespesasanterior * 100) "
                    + "         ELSE 0 END AS pesocategoria, "
                    + "    CASE WHEN COALESCE(pp.totalanterior, 0) > 0 "
                    + "         THEN ((COALESCE(pa.totalatual, 0) - COALESCE(pp.totalanterior, 0)) / COALESCE(pp.totalanterior, 0) * 100) "
                    + "         WHEN COALESCE(pa.totalatual, 0) > 0 THEN 100 "
                    + "         ELSE 0 END AS variacaopercent, "
                    + "    CASE WHEN t.totaldespesasanterior > 0 AND COALESCE(pp.totalanterior, 0) > 0 "
                    + "         THEN (((COALESCE(pa.totalatual, 0) - COALESCE(pp.totalanterior, 0)) / COALESCE(pp.totalanterior, 0) * 100) "
                    + "               * (COALESCE(pp.totalanterior, 0) / t.totaldespesasanterior * 100) / 100) "
                    + "         ELSE 0 END AS contribuicaoinflacao "
                    + "FROM PeriodoAtual pa "
                    + "LEFT JOIN PeriodoAnterior pp ON pa.nome_C = pp.nome_C "
                    + "CROSS JOIN TotaisPeriodos t "
                    + "UNION "
                    + "SELECT "
                    + "    COALESCE(pa.nome_C, pp.nome_C) AS categoria, "
                    + "    COALESCE(pa.nome_S, pp.nome_S) AS grupo, "
                    + "    COALESCE(pp.totalanterior, 0) AS gastoanterior, "
                    + "    COALESCE(pa.totalatual, 0) AS gastoatual, "
                    + "    CASE WHEN t.totaldespesasanterior > 0 "
                    + "         THEN (COALESCE(pp.totalanterior, 0) / t.totaldespesasanterior * 100) "
                    + "         ELSE 0 END AS pesocategoria, "
                    + "    CASE WHEN COALESCE(pp.totalanterior, 0) > 0 "
                    + "         THEN ((COALESCE(pa.totalatual, 0) - COALESCE(pp.totalanterior, 0)) / COALESCE(pp.totalanterior, 0) * 100) "
                    + "         WHEN COALESCE(pa.totalatual, 0) > 0 THEN 100 "
                    + "         ELSE 0 END AS variacaopercent, "
                    + "    CASE WHEN t.totaldespesasanterior > 0 AND COALESCE(pp.totalanterior, 0) > 0 "
                    + "         THEN (((COALESCE(pa.totalatual, 0) - COALESCE(pp.totalanterior, 0)) / COALESCE(pp.totalanterior, 0) * 100) "
                    + "               * (COALESCE(pp.totalanterior, 0) / t.totaldespesasanterior * 100) / 100) "
                    + "         ELSE 0 END AS contribuicaoinflacao "
                    + "FROM PeriodoAnterior pp "
                    + "LEFT JOIN PeriodoAtual pa ON pa.nome_C = pp.nome_C "
                    + "CROSS JOIN TotaisPeriodos t "
                    + "WHERE pa.nome_C IS NULL "
                    + ") AS resultado "
                    + "ORDER BY ABS(contribuicaoinflacao) DESC";

            stmt = con.prepareStatement(sql);
            stmt.setString(1, data_i_atual_str);
            stmt.setString(2, data_f_atual_str);
            stmt.setString(3, data_i_anterior_str);
            stmt.setString(4, data_f_anterior_str);
            stmt.setString(5, data_i_atual_str);
            stmt.setString(6, data_f_atual_str);
            stmt.setString(7, data_i_anterior_str);
            stmt.setString(8, data_f_anterior_str);

            rs = stmt.executeQuery();

            DefaultTableModel modelo = new DefaultTableModel(
                    new Object[]{"CATEGORIA", "GRUPO", "GASTO ANTERIOR", "GASTO ATUAL",
                        "PESO (%)", "VARIAÇÃO (%)", "CONTRIBUIÇÃO (%)"},
                    0
            );
            tabelaInflacao.setModel(modelo);

            DecimalFormat df = new DecimalFormat("#,##0.00");
            DecimalFormat dp = new DecimalFormat("0.0000");

            double inflacaoTotal = 0.0;

            while (rs.next()) {
                double contribuicao = rs.getDouble("contribuicaoinflacao");
                inflacaoTotal += contribuicao;

                modelo.addRow(new Object[]{
                    rs.getString("categoria"),
                    rs.getString("grupo"),
                    df.format(rs.getDouble("gastoanterior")),
                    df.format(rs.getDouble("gastoatual")),
                    dp.format(rs.getDouble("pesocategoria")),
                    dp.format(rs.getDouble("variacaopercent")),
                    dp.format(contribuicao)
                });
            }

            // Adicionar linha de resumo
            modelo.addRow(new Object[]{"", "", "", "", "", "", ""});
            modelo.addRow(new Object[]{"", "", "", "", "",
                "INFLAÇÃO:", dp.format(inflacaoTotal) + "%"});

            // Configurar largura das colunas
            tabelaInflacao.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            tabelaInflacao.getColumn("CATEGORIA").setPreferredWidth(370);
            tabelaInflacao.getColumn("GRUPO").setPreferredWidth(210);
            tabelaInflacao.getColumn("GASTO ANTERIOR").setPreferredWidth(130);
            tabelaInflacao.getColumn("GASTO ATUAL").setPreferredWidth(130);
            tabelaInflacao.getColumn("PESO (%)").setPreferredWidth(80);
            tabelaInflacao.getColumn("VARIAÇÃO (%)").setPreferredWidth(100);
            tabelaInflacao.getColumn("CONTRIBUIÇÃO (%)").setPreferredWidth(130);

            JOptionPane.showMessageDialog(null,
                    "Sua inflação pessoal no período foi de: " + dp.format(inflacaoTotal) + "%\n\n"
                    + "Período atual: " + dataTextoi + " a " + dataTextof + "\n"
                    + "Período anterior (ano passado): "
                    + formato_data.format(java.util.Date.from(dataIniAnterior.atStartOfDay(ZoneId.systemDefault()).toInstant()))
                    + " a " + formato_data.format(java.util.Date.from(dataFimAnterior.atStartOfDay(ZoneId.systemDefault()).toInstant())),
                    "Inflação Pessoal",
                    JOptionPane.INFORMATION_MESSAGE
            );

        } catch (SQLException ex) {
            Logger.getLogger(Tela_Consulta_Inflacao.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao calcular inflação: " + ex.getMessage());
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (stmt != null) {
                    stmt.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Tela_Consulta_Inflacao.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_calcularInflacaoPessoalActionPerformed

    private void jButtonPImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPImprimirActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        Date date = new Date();
        String infDt = dateFormat.format(date);

        // Pegar as datas dos campos
        String dataInicial = jFormattedTextFieldDataIni.getText();
        String dataFinal = jFormattedTextFieldDataFim.getText();

        PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
        set.add(OrientationRequested.LANDSCAPE);

        // Cabeçalho com as datas do período
        MessageFormat cabecalho = new MessageFormat(
                "Inflação Pessoal - Período: " + dataInicial + " a " + dataFinal
        );

        MessageFormat rodape = new MessageFormat("Página {0,number,integer}" + " - Impressão: " + infDt
        );

        try {
            tabelaInflacao.print(JTable.PrintMode.FIT_WIDTH, cabecalho, rodape, false, set, false);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Erro ao imprimir!!! %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jButtonPImprimirActionPerformed

    private void jButtonPLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPLimparActionPerformed
        ((DefaultTableModel) tabelaInflacao.getModel()).setRowCount(0);
        jFormattedTextFieldDataIni.setText("");
        jFormattedTextFieldDataFim.setText("");
    }//GEN-LAST:event_jButtonPLimparActionPerformed

    private void jButtonPFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPFecharActionPerformed
        try {
            TelaPrincipal exibir;
            exibir = new TelaPrincipal();
            exibir.setVisible(true);
            setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(Tela_Consulta_Inflacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPFecharActionPerformed

    private void jButtonGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGraficoActionPerformed
        try {
            // Verificar se há dados na tabela antes de gerar o gráfico
            if (tabelaInflacao.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null,
                        "Atenção! Execute a consulta de inflação antes de gerar o gráfico.",
                        "Aviso",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            BarChartInflacao grafico = new BarChartInflacao();
        } catch (Exception ex) {
            Logger.getLogger(Tela_Consulta_Inflacao.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,
                    "Erro ao gerar gráfico: " + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGraficoActionPerformed

    private void jButtonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Salvar como...");
        int userSelection = fileChooser.showSaveDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String path = fileChooser.getSelectedFile().getAbsolutePath();
            if (!path.endsWith(".xlsx")) {
                path += ".xlsx";
            }
            try {
                ExportToExcel exporter = new ExportToExcel();
                exporter.exportTable(tabelaInflacao, path);
                JOptionPane.showMessageDialog(null, "Arquivo Excel " + path + " foi gerado com sucesso!");
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro ao exportar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonExportarActionPerformed

    public class BarChartInflacao extends JFrame {

        JFreeChart chart;

        public BarChartInflacao() throws ParseException {
            super("Gráfico de Inflação Pessoal - Comparativo por Categoria");
            setSize(1200, 800);
            setLayout(null);
            setResizable(false);
            setLocationRelativeTo(null);
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            criarGraficoInflacao();
            ChartPanel panel = new ChartPanel(chart, false);
            panel.setBounds(10, 20, 1160, 720);
            add(panel);
            setVisible(true);
        }

        public void criarGraficoInflacao() throws ParseException {
            DecimalFormat df = new DecimalFormat("#,###.00");

            // Dataset para barras agrupadas
            DefaultCategoryDataset dataset = new DefaultCategoryDataset();

            // Pegar apenas as top 15 categorias com maior contribuição absoluta
            ArrayList<String> categorias = new ArrayList<>();
            ArrayList<Double> gastosAnteriores = new ArrayList<>();
            ArrayList<Double> gastosAtuais = new ArrayList<>();
            ArrayList<Double> contribuicoes = new ArrayList<>();

            // Coletar dados da tabela (pular as linhas de resumo no final)
            int ultimaLinha = tabelaInflacao.getRowCount();
            for (int i = 0; i < ultimaLinha; i++) {
                Object catObj = tabelaInflacao.getValueAt(i, 0); // Categoria
                Object gastoAntObj = tabelaInflacao.getValueAt(i, 2); // Gasto Anterior
                Object gastoAtualObj = tabelaInflacao.getValueAt(i, 3); // Gasto Atual
                Object contribObj = tabelaInflacao.getValueAt(i, 6); // Contribuição

                // Parar quando chegar nas linhas vazias/resumo
                if (catObj == null || catObj.toString().trim().isEmpty()) {
                    break;
                }

                String categoria = catObj.toString();
                String gastoAntStr = gastoAntObj.toString();
                String gastoAtualStr = gastoAtualObj.toString();
                String contribStr = contribObj.toString();

                if (!categoria.isEmpty() && !gastoAntStr.isEmpty() && !gastoAtualStr.isEmpty()) {
                    categorias.add(categoria);
                    gastosAnteriores.add(df.parse(gastoAntStr).doubleValue());
                    gastosAtuais.add(df.parse(gastoAtualStr).doubleValue());

                    // Pegar contribuição em valor absoluto para ordenar
                    double contrib = Math.abs(df.parse(contribStr).doubleValue());
                    contribuicoes.add(contrib);
                }
            }

            // Ordenar por contribuição (pegar as 15 mais relevantes)
            ArrayList<Integer> indices = new ArrayList<>();
            for (int i = 0; i < contribuicoes.size(); i++) {
                indices.add(i);
            }

            // Ordenar índices por contribuição decrescente
            indices.sort((i1, i2) -> Double.compare(contribuicoes.get(i2), contribuicoes.get(i1)));

            // Pegar apenas top 15 (ou menos se não houver 15)
            int limite = Math.min(15, indices.size());

            for (int i = 0; i < limite; i++) {
                int idx = indices.get(i);
                String cat = categorias.get(idx);

                // Limitar tamanho do nome da categoria para caber no gráfico
                if (cat.length() > 25) {
                    cat = cat.substring(0, 22) + "...";
                }

                dataset.addValue(gastosAnteriores.get(idx), "Período Anterior", cat);
                dataset.addValue(gastosAtuais.get(idx), "Período Atual", cat);
            }

            // Criar gráfico de barras
            chart = ChartFactory.createBarChart(
                    "Comparativo de Gastos - Top 15 Categorias", // Título
                    "Categorias", // Eixo X
                    "Valor (R$)", // Eixo Y
                    dataset, // Dados
                    PlotOrientation.VERTICAL, // Orientação
                    true, // Legenda
                    true, // Tooltips
                    false // URLs
            );

            // Personalização visual
            chart.setBackgroundPaint(new Color(245, 245, 245));
            chart.getTitle().setPaint(new Color(0, 51, 102));
            chart.getTitle().setFont(new Font("Arial", Font.BOLD, 18));

            CategoryPlot plot = chart.getCategoryPlot();
            plot.setBackgroundPaint(Color.WHITE);
            plot.setDomainGridlinePaint(Color.LIGHT_GRAY);
            plot.setRangeGridlinePaint(Color.LIGHT_GRAY);

            // Cores das barras
            BarRenderer renderer = (BarRenderer) plot.getRenderer();
            renderer.setSeriesPaint(0, new Color(70, 130, 180)); // Azul para período anterior
            renderer.setSeriesPaint(1, new Color(220, 20, 60)); // Vermelho para período atual

            // Rotacionar labels do eixo X para caber melhor
            CategoryAxis domainAxis = plot.getDomainAxis();
            domainAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_45);
            domainAxis.setLabelFont(new Font("Arial", Font.PLAIN, 12));

            // Formatar eixo Y com valores monetários
            NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
            rangeAxis.setNumberFormatOverride(new DecimalFormat("R$ #,##0.00"));
            rangeAxis.setLabelFont(new Font("Arial", Font.PLAIN, 12));
        }
    }


    private void jFormattedTextFieldDataIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataIniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataIniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Consulta_Inflacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Consulta_Inflacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Consulta_Inflacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Consulta_Inflacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Consulta_Inflacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcularInflacaoPessoal;
    private javax.swing.JButton jButtonExportar;
    private javax.swing.JButton jButtonGrafico;
    private javax.swing.JButton jButtonPFechar;
    private javax.swing.JButton jButtonPImprimir;
    private javax.swing.JButton jButtonPLimpar;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataFim;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataIni;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelRegime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbCaixa;
    private javax.swing.JRadioButton rbCompetencia;
    private javax.swing.JRadioButton rbVcto;
    private javax.swing.JTable tabelaInflacao;
    // End of variables declaration//GEN-END:variables
}
